### ISSUE TITLE
Store gitcoin passport score in user table 

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1000]
Maybe we will want to user the score for other things in the future, related to GIVbacks or other products.

I'm creating this issue by request after the QF call!

**Comment by laurenluz** [comment]
@mohammadranjbarz @CarlosQ96 I think this is done, right? we can close it?

**Comment by CarlosQ96** [comment]
yes @laurenluz  done like 2 months ago!

**Comment by laurenluz** [comment]
I thought so!
