### ISSUE TITLE
Data Collection for Sybil Analysis

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1002]
After each round of QF, we will need to collect the donation data, make a table/spreadsheet/dashboard for it, and then analyze it to remove possible sybil attacks.

I hope @mohammadranjbarz can help me to set everything up in the backend for QF so that this data is easy to grab & organize.

This, for example, is the data set that QF round organizers get from gitcoin in the beta round:
![image.png](https://images.zenhubusercontent.com/5fdfac16a58523a866ddb68d/c26c5bec-fd4f-4e70-a5c4-8076053b40aa)

Info we need:
- donor address
- "to" project id
- amount sent
- timestamp
- which chain
- passport score
- passport score threshold 

We might need more information for this, but I'll leave a comment in this issue once I figure it out. Also open to suggestions on things I missed. cc @moenick @griffgreen

@mohammadranjbarz - can you keep this in mind and keep an eye on this issue?

FYI @aminlatifi @MohammadPCh

**Comment by MoeNick** [comment]
Do you prefer to have this feature in AdminJs? there's a csv export feature there. 
OR
we may add an endpoint like GIVbacks and set kinda OPS for each round. 
@laurenluz

**Comment by laurenluz** [comment]
ahh man @MoeNick I don't understand the options you're proposing really. maybe you can explain it to me?

From my last meeting with Trustalabs "with whom, we are thinking about doing the sybil analysis work", they said... all they will need is a simple list of address that donated during the QF round.

I still need to talk with them more to get clarification and finalize that that is true.

**Comment by MoeNick** [comment]
yeah if we know the manual operation process you and they may want to do, we may get more clear, I'd better not propose things actually. If you only need the data, it's fine. we can have it whenever you want, but if you need a feature, we have to make it clear. 

So this issue tmk is just a query.

**Comment by laurenluz** [comment]
Hey @MoeNick @mohammadranjbarz @CarlosQ96 

yesterday I spoke w/ the crew at Trustalabs, and this is the information they will need from us to do the analysis... For all donations in our QF round to QF-eligible projects, we'll need:
- Donor Wallet address
- USD value of donation
- project they donated to - (I think link + wallet address + chain)
- Transaction hash

Will we need to set up anything special to get this info? or can we just get it from querying our database?

**Comment by CarlosQ96** [comment]
We can use the Adminjs, Ill check the filters are working. And we could filter by qfround and get those donations info. Im just curious on the passport score not being asked. Maybe they do it on their side?

**Comment by laurenluz** [comment]
Oh yes, let's include passport score as well! because if the user doesn't had passport score, we should not even send the data to trustalabs I think.

passport score is like our 1st check.

**Comment by divine-comedian** [comment]
Related to:
https://github.com/Giveth/giveth-dapps-v2/issues/2757

**Comment by laurenluz** [comment]
@CarlosQ96 - are you working on the bug on exporting donation data? We should test to make sure we can easily get:

- Donor Wallet address
- Passport score (or at least eligible Y / N)
- USD value of donation
- project they donated to - (I think link + wallet address + chain)
- Transaction hash

**Comment by laurenluz** [comment]
FYI @CarlosQ96 - we got this from Trustalabs as a sample of what they need:

![telegram-cloud-photo-size-5-6158778765556169432-y](https://github.com/Giveth/impact-graph/assets/75490971/33b50237-881f-449b-a1bc-9ae78ee63bdf)

They will also need the chainID (name) because we'll be looking at donations on multiple chains.

**Comment by CarlosQ96** [comment]
Its on production and staging you can test by filtering in the donation tab by qfround Id and then clicking the export to csv option. 
CHeck the spreadsheed @WhyldWanderer has access to

**Comment by maryjaf** [comment]
Is it possible to add name/id of round in drop down menu for this field?

**Comment by laurenluz** [comment]
we the qfroundid now!

and we exported & sent the data to Trustalabs for the alpha round

**Comment by MoeNick** [comment]
@laurenluz I've left it open for your QA, if you feels ok, let's close it.
