### ISSUE TITLE
'Export to csv' not working in Adminbro

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1008]
When I choose export filter to csv in the Admin bro it doesnt apply the filter.

Here was my filter:
![image](https://github.com/Giveth/impact-graph/assets/74267818/3f46d410-876b-496b-833a-088695b96463)

Here is the data i received:
https://docs.google.com/spreadsheets/d/1uqw40RxtxhhsVBq5_QwnBJ1V40z6I8Pfe2q8nxdHejM/edit#gid=975693035

I renamed the sheet to "Ashley Issue Sheet" so that you can easily find it.

**Comment by MoeNick** [comment]
Shall I move it to test column @CarlosQ96 ?
