### ISSUE TITLE
Donations from logged in users are being saved but not assigned to them

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#101]
The issue happens on mutation 'saveDonation'

This shows on staging while reproducing this

![image](https://user-images.githubusercontent.com/18689480/123484949-c9c45a80-d5ce-11eb-9a0b-18ef0e350c0f.png)

Nevermind this image^^ that's because my domain isn't being whitelisted from our node

**Comment by divine-comedian** [comment]
testing on next.giveth
brave browser clean cache and cookies

no issues making a donation, they show up correctly on the UI..
![image](https://user-images.githubusercontent.com/67759413/124391486-d592d980-dcbe-11eb-9d58-c2680250c44b.png)
 
and it shows up in the backend on staging...
![image](https://user-images.githubusercontent.com/67759413/124391675-cf512d00-dcbf-11eb-8833-8b738da0a91f.png)
