### ISSUE TITLE
QF| AdminJs: Showing Add/Remove QF round in edit page of projects

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1015]
Now it is possible to add/ remove QF round only from list of project and this option doesn't exist in edit page
@MoeNick

**Comment by laurenluz** [comment]
@mohammadranjbarz @CarlosQ96 - can you help?

**Comment by mohammadranjbarz** [comment]
@maryjaf 
It's on develop, you can test now

<img width="1440" alt="Screen Shot 1402-03-23 at 12 13 50" src="https://github.com/Giveth/impact-graph/assets/9850545/f7222bdf-ba57-405e-8d0d-5b42ba592eeb">

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz 
Plz check this case
https://dev.serve.giveth.io/admin/resources/Project/records/28/show
1- for this project when I tap on "remove project from QF round " the QF round 34 is not removed from the page 
<img width="1402" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/0032d9f5-88b1-4cb5-9a4e-a1fda1e1699e">
2- the message that it shown by taping on add/ remove should be changed
