### ISSUE TITLE
Support load balancer or db replica (read only nodes)

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1016]
Postgres and typeorm ([here](https://typeorm.io/multiple-data-sources#replication)) both support db replicas, one primary read/write node and multiple read nodes.
This can improve our performance (we must see) as we have heavy write queries like refreshing materialized views.
@mhmdksh has created a replica node for impact-graph db (both staging and production). 
Let's first try this feature  on the staging and then apply on the production

**Comment by aminlatifi** [comment]
#1014

**Comment by mhmdksh** [comment]
As mentioned, the read replica for our DBs is created. Please send a DM for connection info

**Comment by aminlatifi** [comment]
DEVs: It must be noted, we won't get the best out of this upgrade completely since some of our read calls are done with query which will hit the master node

> All simple queries performed by find methods or select query builders are using a random slave instance. All queries performed by query method are performed using the master instance.

So we need to modify our queries (e.g. in resolvers) to use the read node instead.

**Comment by MoeNick** [comment]
who wants to take this? 
@CarlosQ96 @aminlatifi

**Comment by MoeNick** [comment]
I added thi to technical debts, is it still valid?

**Comment by aminlatifi** [comment]
> I added thi to technical debts, is it still valid?

Yes

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up once superfluid is done "modify our queries (e.g. in resolvers) to use the read node instead" as amin mentioned above.

**Comment by aminlatifi** [comment]
https://typeorm.io/multiple-data-sources#using-multiple-data-sources
Above shows how we can use replicas and also has a default mode in querying the slave (read only mode in our case)

**Comment by mhmdksh** [comment]
@jainkrati This is a long running issue, that is very important to follow up on since it is mainly responsible for the performance of our DB queries

**Comment by maryjaf** [comment]
This issue should be tested ? how can I test it ? @aminlatifi @CarlosQ96

**Comment by aminlatifi** [comment]
@maryjaf It's working and most of the read queries are hitting read-only replica. From the user side, there is no way to find it out, you must look at the database monitoring in the digital ocean and we did it.

**Comment by maryjaf** [comment]
> @maryjaf It's working and most of the read queries are hitting read-only replica. From the user side, there is no way to find it out, you must look at the database monitoring in the digital ocean and we did it.

Thanks @aminlatifi 
So this issue could be moved to "close"?

**Comment by aminlatifi** [comment]
> > @maryjaf It's working and most of the read queries are hitting read-only replica. From the user side, there is no way to find it out, you must look at the database monitoring in the digital ocean and we did it.
> 
> Thanks @aminlatifi So this issue could be moved to "close"?

Yes

**Comment by aminlatifi** [comment]
Typeorm allows us to define `defaultMode` as the default replica of read queries. We can set it to `master` and then manually create queries against read replica using 
```ts
const slaveQueryRunner = dataSource.createQueryRunner("slave")
```
It is a way around which allows us to put some loads on read-only replicas manually. We can implement it faster  to fix performance issue.

The other way is one @CarlosQ96 mentioned to change all write/save queries to be sure they are executed to read-write replica.

**Comment by jainkrati** [comment]
@RamRamez please continue working on this along with @CarlosQ96

**Comment by aminlatifi** [comment]
> Typeorm allows us to define `defaultMode` as the default replica of read queries. We can set it to `master` and then manually create queries against read replica using
> 
> ```ts
> const slaveQueryRunner = dataSource.createQueryRunner("slave")
> ```
> 
> It is a way around which allows us to put some loads on read-only replicas manually. We can implement it faster to fix performance issue.
> 
> The other way is one @CarlosQ96 mentioned to change all write/save queries to be sure they are executed to read-write replica.

@CarlosQ96 @RamRamez 
https://github.com/Giveth/impact-graph/issues/1016#issuecomment-2100197365

**Comment by aminlatifi** [comment]
> Typeorm allows us to define `defaultMode` as the default replica of read queries. We can set it to `master` and then manually create queries against read replica using
> 
> ```ts
> const slaveQueryRunner = dataSource.createQueryRunner("slave")
> ```
> 
> It is a way around which allows us to put some loads on read-only replicas manually. We can implement it faster to fix performance issue.
> 
> The other way is one @CarlosQ96 mentioned to change all write/save queries to be sure they are executed to read-write replica.

@CarlosQ96 @RamRamez 
https://typeorm.io/multiple-data-sources#adjusting-the-default-destination-for-reads

<img width="485" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/12646940-c2da-493f-8a38-0c84487c4fb3">

**Comment by RamRamez** [comment]
By default all read connections with be routed to slave and write connections will go to master. By adding `defaultMode: master`, all read connections will be routed to master, then we have to manually define all read queries one by one to use slave, that's very time consuming, besides that TypeORM doesn't fully support defining read DB manually for all methods that we use like .find and .findOne
So I think adding defaultMode is not a good option.
Since TypeORM doesn't fully support DB replica for all repo methods, I suggest we use load balancing for DB instead of replica with a proxy server to balance DB connections.
cc @jainkrati

**Comment by jainkrati** [comment]
@mhmdksh @RamRamez @CarlosQ96 could you pls coordinate for setting up load balancer

**Comment by mhmdksh** [comment]
> @mhmdksh @RamRamez @CarlosQ96 could you pls coordinate for setting up load balancer

Thanks @jainkrati , I've created this issue to explore this and make a setup ready for testing: https://github.com/Giveth/devops/issues/238

Will update you on the same

**Comment by jainkrati** [comment]
whats the progress here @RamRamez @MohammadPCh

**Comment by RamRamez** [comment]
@maryjaf I will DM you about testing this issue

**Comment by maryjaf** [comment]
I haven't seen any problem in verification flow or changing the status from admin bro @RamRamez
