### ISSUE TITLE
Displaying the projects related to each QF round in the admin

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1029]
Since we can see only the list of current round's projects in the dApp, It is necessary to see the list of projects of each  QF round in the admin panel 

We can also display the amount of donation  and estimated matching

**Comment by MoeNick** [comment]
is it p1 or p2? @laurenluz 
you can use labels

**Comment by laurenluz** [comment]
added

**Comment by laurenluz** [comment]
@maryjaf can you give a little more of an idea of where this informatino would be ideally & why we might want to view it in admin bro?

**Comment by maryjaf** [comment]
Qf round history menu could cover this requirement approximately( after a round), 

But it would be good if admin users could see all projects of a round in a page and be able to  add or remove some projects to  the round 
 like below now video we could see QF round's project  and it would be great if :
 - There is pagination for a round that it has many project
 - Adding or removing could be done on this page or a new page on admin
 

https://github.com/Giveth/impact-graph/assets/111529185/163473ad-a173-47b1-a0fd-4aac9839b4be

**Comment by laurenluz** [comment]
sounds great yeah. I think this is a good p2. Thanks @maryjaf !

**Comment by jainkrati** [comment]
@RamRamez pls pick this post your p0 and p1 issues.

**Comment by jainkrati** [comment]
@RamRamez pls guide @Meriem-BM on this

**Comment by Meriem-BM** [comment]
Hey @maryjaf from what I understood this is already implemented (we can see projects list on QF round Tab) but what's missing is the pagination, right?

For adding/removing projects we already have an issue #1125 it will be reviewed then merged.

**Comment by Meriem-BM** [comment]
@maryjaf can you check the comment before this one.

**Comment by maryjaf** [comment]
> * There is pagination for a round that it has many project
> * Adding or removing could be done on this page or a new page on admin

Yeah I had  mentioned the problem of previous view of qf round in admin in this comment 
and now the issue related to  adding/removing project has been solved 
and the only thing that it would be good to have is this :
-There is pagination for a round that it has many project
@Meriem-BM

**Comment by Meriem-BM** [comment]
Hey @maryjaf, you can test this now

**Comment by maryjaf** [comment]
Thanks @Meriem-BM it has been fixed
