### ISSUE TITLE
Webservice for return qf round funding history

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1034]
Frontend needs to show unique contributors, raisedFund in value USD and the send matching txLink ( or maybe amount, I remember we talked about it but I'm not sure about the conclusion), for other data of active qf round we use materialized views because they change and we need refresh them , .., but for previous rounds I think the best ways is having a new table (**qfRoundHistory**) with this structure:

| name                   | type    | required | description |
|------------------------|---------|----------|-------------|
| qfRoundId              | integer | yes      |             |
| projectId              | integer | yes      |             |
| raisedFund             | float   | no       |             |
| uniqueContributors     | integer | no       |             |
| sendMatchingFundTxLink | string  | no       |             |
| matchingFund           | float   | no       |             |
| createdAt              | Date    | yes      |             |

So we just need to implement a graphql query , then frontend can call it with sending `qfRoundId` and `projectId` .

but still I'm not sure about when and how we should fill **qfRoundHistory** table

@MohammadPCh  @CarlosQ96  @aminlatifi  @laurenluz  Any thought?

![history](https://github.com/Giveth/impact-graph/assets/9850545/667b0fa8-b160-47fd-b074-fc51ef15e36c)

**Comment by MoeNick** [comment]
Hey @mohammadranjbarz 
Can I assign it to @CarlosQ96 ? 
to remove Cherik's blocker while you are busy with Cannon

**Comment by mohammadranjbarz** [comment]
> Hey @mohammadranjbarz Can I assign it to @CarlosQ96 ? to remove Cherik's blocker while you are busy with Cannon

I already started it, and I believe @CarlosQ96  is busy with debugging Chainvine and Optimism issue

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  
Now the webservice is ready
You can call it  with this query
```
    query (
      $projectId: Int!
      $qfRoundId: Int!
    ) {
      getQfRoundHistory(
        projectId: $projectId
        qfRoundId: $qfRoundId
      ) {
        uniqueDonors
        raisedFundInUsd
        donationsCount
        matchingFund
        distributedFundNetwork
        distributedFundTxHash
      }
    }
```

We fill that table when someone update it from adminBro or when endDate of an active qfRound passes

<img width="1142" alt="Screen Shot 1402-03-31 at 14 47 17" src="https://github.com/Giveth/impact-graph/assets/9850545/812d785f-b412-4eee-9d4d-57fdb6b07ad6">

We fill this table with these conditions:
1. `qfRound` should not be active
2. qfRound's `endDate` should be passed
3. donations should be `verified`
4. donor's `passportScore` should be more that `qfRound.minimumPassportScore`

@maryjaf  You can test adminjs panel too, for instance when you delete some records and update it again they should be added again or something like that

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @CarlosQ96  @laurenluz 
I dont have any idea how we should fill real matching fund's of these records so it's empty for now

**Comment by MohammadPCh** [comment]
Thanks @mohammadranjbarz

**Comment by laurenluz** [comment]
> @aminlatifi @CarlosQ96 @laurenluz
> I dont have any idea how we should fill real matching fund's of these records so it's empty for now

I think @CarlosQ96 will work on that in https://github.com/Giveth/giveth-dapps-v2/issues/2757

**Comment by CarlosQ96** [comment]
Ill take this last bit if required, I know mohammad left a field for it in the db
