### ISSUE TITLE
Adding Goerli OP as supported network to staging

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1036]
it includes all subgraphs requests plus:

- defining the network as a supported network
- donation verification
- supported network in verification process
- adding new address in edit project
- editing address in edit project

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapps-v2/issues/2774_

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
Looking at this PR can help 
https://github.com/Giveth/impact-graph/pull/894/

(It might not be completed but most of the things are similar to changes of this PR)

**Comment by CarlosQ96** [comment]
Thanks @mohammadranjbarz

**Comment by laurenluz** [comment]
@CarlosQ96 - are you working on this this week? we need the backend before cherik can start work on it

**Comment by CarlosQ96** [comment]
@laurenluz yes I started working on it yesterday! will try to have a PR for today

**Comment by laurenluz** [comment]
yippie!!

**Comment by maryjaf** [comment]
My donation on OP Goerli is pending and I can't check the Givback scenarios plz check @CarlosQ96 
https://serve.giveth.io/admin/resources/Donation/records/16666/show

cc @MoeNick

**Comment by mohammadranjbarz** [comment]
> My donation on OP Goerli is pending and I can't check the Givback scenarios plz check @CarlosQ96 https://serve.giveth.io/admin/resources/Donation/records/16666/show
> 
> cc @MoeNick

@CarlosQ96  We get this error, can you check the infura key to see if there is ok ?
I will send the infura key for you in DM

```

    syncDonationStatusWithBlockchainNetwork() error {
      error: Error: processing response error (body="{\"jsonrpc\":\"2.0\",\"id\":44,\"error\":{\"code\":-32603,\"message\":\"request failed or timed out\"}}", error={"code":-32603}, requestBody="{\"method\":\"eth_getTransactionCount\",\"params\":[\"0xf577ae8b97d839b9c0522a620299dc08792c738c\",\"latest\"],\"id\":44,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="https://optimism-goerli.infura.io/v3/{I deleted apiKey from logs to put it in issue}", code=SERVER_ERROR, version=web/5.7.1)
          at Logger.makeError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:238:21)
          at Logger.throwError (/usr/src/app/node_modules/@ethersproject/logger/lib/index.js:247:20)
          at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:313:32
          at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
          at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
          at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (node:internal/process/task_queues:96:5) {
        reason: 'processing response error',
        code: 'SERVER_ERROR',
        body: '{"jsonrpc":"2.0","id":44,"error":{"code":-32603,"message":"request failed or timed out"}}',
        error: Error: request failed or timed out
            at getResult (/usr/src/app/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:191:21)
            at processJsonFunc (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:356:22)
            at /usr/src/app/node_modules/@ethersproject/web/lib/index.js:288:46
            at step (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:33:23)
            at Object.next (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:14:53)
            at fulfilled (/usr/src/app/node_modules/@ethersproject/web/lib/index.js:5:58)
            at runMicrotasks (<anonymous>)
            at processTicksAndRejections (node:internal/process/task_queues:96:5) {
          code: -32603,
          data: undefined
        },
        requestBody: '{"method":"eth_getTransactionCount","params":["{I deleted apiKey from logs to put it in issue}","latest"],"id":44,"jsonrpc":"2.0"}',
        requestMethod: 'POST',
        url: 'https://optimism-goerli.infura.io/v3/{I deleted apiKey from logs to put it in issue}'
      },
      donationId: 16666,
      txHash: '0x982da9e1ff0a4f14094308b173c65c8b6cc26b4755d9446ef3dfe8a35539b0f4'
    }
```

**Comment by CarlosQ96** [comment]
@maryjaf can you please test again 
![image](https://github.com/Giveth/impact-graph/assets/92376054/d15b7a6c-72f0-4eb5-aecb-2fc7a47b24ec)


Seems our infura api keys were having issues but its been resolved for optimism apis.

**Comment by CarlosQ96** [comment]
the donation is in fact verified now.

**Comment by maryjaf** [comment]
Thanks
Yeah the problem has been resolved and now we have a verified donation on OP Goerli
but when I call the /eligible-donations and set the **optimism**, there is no result in response and when set the **all other chain** in request this response with unknown network is shown, plz check @CarlosQ96 @mohammadranjbarz 

[
  {
    "amount": 0.000001,
    "currency": "ETH",
    "createdAt": "2023-08-03-08:24:29",
    "valueUsd": 0.00183578,
    "bottomRankInRound": 1,
    "givbacksRound": 20855,
    "projectRank": 1,
    "givbackFactor": 0.75,
    "valueUsdAfterGivbackFactor": 0,
    "giverAddress": "0xf577ae8b97d839b9c0522a620299dc08792c738c",
    "txHash": "0xcc196d6a9ba1c7bb473a04bd415cf39340f6afefc387c656f79ea4ab47a3a10b",
    "network": "unknown network",
    "source": "giveth.io",
    "giverName": null,
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/test-project-op1",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  }
]

**Comment by maryjaf** [comment]
> Thanks Yeah the problem has been resolved and now we have a verified donation on OP Goerli but when I call the /eligible-donations and set the **optimism**, there is no result in response and when set the **all other chain** in request this response with unknown network is shown, plz check @CarlosQ96 @mohammadranjbarz
> 
> [ { "amount": 0.000001, "currency": "ETH", "createdAt": "2023-08-03-08:24:29", "valueUsd": 0.00183578, "bottomRankInRound": 1, "givbacksRound": 20855, "projectRank": 1, "givbackFactor": 0.75, "valueUsdAfterGivbackFactor": 0, "giverAddress": "0xf577ae8b97d839b9c0522a620299dc08792c738c", "txHash": "0xcc196d6a9ba1c7bb473a04bd415cf39340f6afefc387c656f79ea4ab47a3a10b", "network": "unknown network", "source": "giveth.io", "giverName": null, "giverEmail": null, "projectLink": "https://giveth.io/project/test-project-op1", "isReferrerGivbackEligible": false, "referrerWallet": null } ]

This problem hasn't been resolved yet, plz take a look @CarlosQ96

**Comment by maryjaf** [comment]
> but when I call the /eligible-donations and set the **optimism**, there is no result in response and when set the **all other chain** in request this response with unknown network is shown, plz check @CarlosQ96 @mohammadranjbarz
> 
> [ { "amount": 0.000001, "currency": "ETH", "createdAt": "2023-08-03-08:24:29", "valueUsd": 0.00183578, "bottomRankInRound": 1, "givbacksRound": 20855, "projectRank": 1, "givbackFactor": 0.75, "valueUsdAfterGivbackFactor": 0, "giverAddress": "0xf577ae8b97d839b9c0522a620299dc08792c738c", "txHash": "0xcc196d6a9ba1c7bb473a04bd415cf39340f6afefc387c656f79ea4ab47a3a10b", "network": "unknown network", "source": "giveth.io", "giverName": null, "giverEmail": null, "projectLink": "https://giveth.io/project/test-project-op1", "isReferrerGivbackEligible": false, "referrerWallet": null } ]

This problem hasn't been resolved yet, plz take a look @CarlosQ96

**Comment by mohammadranjbarz** [comment]
@maryjaf   I haven't set OP Goerli to be returned in the response as OP donations, if you want that please tell me I can implement it

**Comment by maryjaf** [comment]
In order to test the Givback and it's calculation , we need to have the amount of givback allocated after the donation on OP Goerli
What do you think @laurenluz @MoeNick ?

**Comment by MoeNick** [comment]
> @maryjaf I haven't set OP Goerli to be returned in the response as OP donations, if you want that please tell me I can implement it

@mohammadranjbarz If we want to test it,  we need it, we can't jump into OP production without testing it on Goerli, but only if @laurenluz approve we can dismiss it for now.

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's deployed on both staging and production, now if you choose `Optimism` you will see the optimism-goerli donations as well

**Comment by maryjaf** [comment]
> @maryjaf It's deployed on both staging and production, now if you choose `Optimism` you will see the optimism-goerli donations as well

ُThanks @mohammadranjbarz This issue has been resolved and now  I can see the donation on OP Goerli  in the response of  giveback eligible  by setting chain on optimism

{
    "amount": 0.000003,
    "currency": "ETH",
    "createdAt": "2023-08-06-09:30:22",
    "valueUsd": 0.00550035,
    "bottomRankInRound": 36,
    "givbacksRound": 21074,
    "projectRank": 36,
    "givbackFactor": 0.5,
    "valueUsdAfterGivbackFactor": 0.0027502,
    "giverAddress": "0xf577ae8b97d839b9c0522a620299dc08792c738c",
    "txHash": "0x847ed1036b8d157d0ec26c8f7d3716cad04d92c621aef2a11c2f763a4e1e72b8",
    "network": "optimism-goerli",
    "source": "giveth.io",
    "giverName": null,
    "giverEmail": null,
    "projectLink": "https://giveth.io/project/test-project-op1",
    "isReferrerGivbackEligible": false,
    "referrerWallet": null
  },
