### ISSUE TITLE
When I create a new QF round but do not check "is active" in admin bro, after tapping "save" the round is activated

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1043]
When I create a new QF round and the "is active" not checked , after taping on save in the list this round is shown activated @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e52c6946-64ad-404a-ab00-ffcc40cfcc60)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6cc7329b-cf35-4d33-82c4-ceeb2914980b)

_Originally posted by @maryjaf in https://github.com/Giveth/impact-graph/issues/998#issuecomment-1607647335_

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's deployed on Staging you can test it
