### ISSUE TITLE
Show related projects of qfround in qfRound tab

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1044]
Now we just can edit/see related qfround of projects in project page we should can do from qfRound page as well

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick  @laurenluz 
I show the related projects of a qf round like below, and you can click on the related project and remove it from current active round, and for adding projects to the round from this page it's kind of complicated because of adminjs limitations I think we can skip it for MVP WDYT?

<img width="1731" alt="Screen Shot 1402-04-14 at 16 54 58" src="https://github.com/Giveth/impact-graph/assets/9850545/3077740d-7c43-4fd4-89fd-383c424d3535">

٬وش

**Comment by laurenluz** [comment]
yeah I think that's fine! as long as we can add them elsewhere.

**Comment by MoeNick** [comment]
@maryjaf fyi

**Comment by maryjaf** [comment]
I checked and it was ok
