### ISSUE TITLE
Use I18N library for QF translations

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1047]

**Comment by MoeNick** [comment]
How can test it @MohammadPCh ?

**Comment by laurenluz** [comment]
I think @Zeptimus and @mateodaza are working on catalan & spanish - maybe you can give an update? or should we close this issue? is there another? 👀

**Comment by laurenluz** [comment]
https://github.com/Giveth/giveth-dapps-v2/pull/2881#issuecomment-1634532421
