### ISSUE TITLE
Support subgraph studio subgraphs (backend)

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/impact-graph#1050]
In order to keep the DApp running, we should need to our studio-deployed subgraph as soon as possible. The hosted version that we are using now will not be supported indefinitely and is actually past its announced date of support.

We also need this on the frontend - the relevant issue is being created. Please notify devops once the changes can be merged, so we can have a seamless transition!

Link to issue for frontend: [issue #2836 in different repo](https://github.com/Giveth/giveth-dapps-v2/issues/2836)

**Comment by MoeNick** [comment]
@CarlosQ96 @aminlatifi 
what happened to this, I remembered we rolled it back, is it safe we test one more time?

**Comment by aminlatifi** [comment]
> @CarlosQ96 @aminlatifi what happened to this, I remembered we rolled it back, is it safe we test one more time?

It has been rolled back, you are right.
we must coordinate with devops team for it to provide us the studio links. Though, by integrating givpower balance aggregator we won't need subgraph link in impact-graph AFAIK

**Comment by MoeNick** [comment]
@aminlatifi what happened to their bug,  did they respond?

**Comment by aminlatifi** [comment]
> @aminlatifi what happened to their bug, did they respond?

Our last message to them is unresponded!
https://discord.com/channels/438038660412342282/1142798258364747898/1144262860525015181

**Comment by divine-comedian** [comment]
@CarlosQ96 @aminlatifi is this issue still relevant?

**Comment by aminlatifi** [comment]
> @CarlosQ96 @aminlatifi is this issue still relevant?

yes, it can be closed.
