### ISSUE TITLE
Return list of campaigns of a project in projectBySlug webservice

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1051]
https://github.com/Giveth/giveth-dapps-v2/issues/2544

**Comment by MoeNick** [comment]
If you'r ok I can plan for this one this week.

**Comment by mohammadranjbarz** [comment]
> If you'r ok I can plan for this one this week.

Yeah it's ok, we can do it

**Comment by MoeNick** [comment]
@CarlosQ96 we planned this one from last week, is there any progress?

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  @MohammadPCh  @MoeNick 

Now we return list of active campaigns of a project in `projectBySlug` web service.

sample:

‍‍
‍‍‍```

export const fetchProjectsBySlugQuery = `
  query (
    $slug: String!
  ) {
    projectBySlug(
      slug: $slug
    ) {
      id
      title
      balance
      image
      slug
      creationDate
      updatedAt
      admin
      description
      walletAddress
      impactLocation
      qualityScore
      verified
      traceCampaignId
      listed
      reviewStatus
      givingBlocksId
      campaigns {
        id
        title
        description
        type
        photo
        video
        videoPreview
        slug
        isActive
        order
        landingLink
        filterFields
        sortingField
        createdAt
        updatedAt
      
      }
      ......
    }
  }
`;

```

**Comment by maryjaf** [comment]
Are frontend changes required to see the campaign name as a tag in project page? @alireza-sharifpour

**Comment by alireza-sharifpour** [comment]
> Are frontend changes required to see the campaign name as a tag in project page? @alireza-sharifpour

Yes we need to update the frontend. @maryjaf

**Comment by maryjaf** [comment]
> > Are frontend changes required to see the campaign name as a tag in project page? @alireza-sharifpour
> 
> Yes we need to update the frontend. @maryjaf

Plz let me know when it's ready to test

**Comment by MoeNick** [comment]
We have another issue for front end this one was only for backed. can you test by API @maryjaf ?

**Comment by maryjaf** [comment]
Sample response:

{
    "data": {
        "projectBySlug": {
            "id": "223639",
            "campaigns": [
                **{
                    "id": "13",
                    "title": "testi"
                }**
            ],
            "slug": "testpfp010",
            "givingBlocksId": null,
            "changeId": null,
            "slugHistory": [],
            "updatedAt": "2023-07-17T06:21:33.227Z",
            "listed": true,
            "walletAddress": null,
            "title": "testpfp010",
            "traceCampaignId": null,
            "totalReactions": 0,
            "totalDonations": 0.0036744,
            "image": "/images/defaultProjectImages/3.png",
            "totalTraceDonations": 0,
            "status": {
                "id": "5",
                "name": "activate"
            }
        }
    }
}

**Comment by maryjaf** [comment]
I'm going to move this issue to in-progress because of this comment
https://github.com/Giveth/giveth-dapps-v2/issues/2544#issuecomment-1733194475

**Comment by MoeNick** [comment]
@mohammadranjbarz told me it's working but has some performance issues as Carlos commented so he created another issue for his one https://github.com/Giveth/impact-graph/pull/1136
waiting for him to let us know what to do with finalizing the frontend.

**Comment by maryjaf** [comment]
plz check this project: https://staging.giveth.io/project/giveth-tour-bridge-the-world?tab=givpower
this project is belong to a "GIVpower is here " campaign but no tag is shown in project page @mohammadranjbarz

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz This problem has been resolved and now the all campaign tags are shown correctly

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz This problem has been resolved and now the all campaign tags are shown correctly
