### ISSUE TITLE
Add projects to nonactive QF rounds in admin bro

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1056]
We'd like to be able to set up ronuds in advance... so set the start & end dates in the future... and set which projects will be part of the round.

Currently we can only add projects to active QF rounds, but we'd like to expand this (post MVP launch) to add projects to inactive QF rounds in the future.

**Comment by divine-comedian** [comment]
Good to implement this for the next round

Would like to add projects before activating the round.

**Comment by divine-comedian** [comment]
@mohammadranjbarz can we add this one to the sprint backlog?

**Comment by laurenluz** [comment]
@mohammadranjbarz - do you have time for this one before the end of the week?
