### ISSUE TITLE
Allow unlisted projects to still be part of QF rounds (listing status should be independent from QF eligibility)

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1058]
If a project is unlisted, it should be hidden from the list of projects on giveth.io/qf
but if someone were to get to the project through its direct link and donate, their donation can still be include in QF

I'm imagining a scenario where the project owner edits their project... and it gets unlisted for a period of time before our admins can review... they should not be removed from the QF round for doing that

**Comment by mohammadranjbarz** [comment]
@laurenluz  I think now we do the way you want, @maryjaf  can you test and verify it?

**Comment by maryjaf** [comment]
I edited one project and change it's status to unlisted ,when I try to donate to this project
https://staging.giveth.io/project/teach-music-to-children?tab=donations

1- the estimated matching isn't shown in donate page

<img width="1433" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/d099ac06-52f8-4cbb-96ec-5d17747767b5">

2- after donation I can see this donation only in all donation tab not in qf-round tab and the amount of donation /estimated matching and number of contributor weren't changed for a round

<img width="1440" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/0813c1c5-04d4-4069-b180-12782c9fdcd0">
<img width="1407" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/cd1acd43-c81d-43c4-8255-cca3ffc11abc">

**Comment by mohammadranjbarz** [comment]
@maryjaf  @laurenluz  
We had some condition somewhere that was making problem for `non-verified` and `unlisted` projects, I fixed that, now can you test it again?

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I've tested and now for the project (unlisted and unverified ) the donation is shown correctly but it take more time to update the list compared to before, I checked with @mohammadranjbarz ,another issue is created to check this later

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz I've tested and now for the project (unlisted and unverified ) the donation is shown correctly but it take more time to update the list compared to before, I checked with @mohammadranjbarz ,another issue is created to check this later

@maryjaf The problem is that our RPC node that we are using in Staging ENV has some delay with chain so we verify it few minutes later.
@mhmdksh  @geleeroyale  I used a public node RPC if you can change it to another one it might fix this delay during verifying donation in Staging ( I'm talking about this `XDAI_NODE_HTTP_URL` in .env)
