### ISSUE TITLE
The logic of rounding number is different in donation tab and project view

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1061]
<img width="1439" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/e919bd12-a3f0-454e-8a6f-f5e8d14eb02d">
@MohammadPCh @alireza-sharifpour

**Comment by laurenluz** [comment]
We should round to two decimals on both if we are showing a $ value

**Comment by MohammadPCh** [comment]
@laurenluz @maryjaf please test it again :sweat_smile:

**Comment by maryjaf** [comment]
Thanks @MohammadPCh it's ok
