### ISSUE TITLE
Improve performance of query - getPowerBoostingSnapshotWithoutBalance

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1067]
This query takes more than one minutes to run.
```sql
select "userId", "powerSnapshotId", "blockNumber","walletAddress"
        from (select DISTINCT "powerSnapshotId", "userId" from power_boosting_snapshot) as boosting
        inner join public."user" as "user" on  "userId"= "user".id
        inner join power_snapshot as "snapshot" on boosting."powerSnapshotId" = snapshot.id
        where snapshot."blockNumber" is not NULL
        and not exists (
          select
          from power_balance_snapshot as "balance"
          where balance."powerSnapshotId" = boosting."powerSnapshotId" and
          balance."userId" = boosting."userId"
        )
        order by "blockNumber" ASC
        LIMIT $1
        OFFSET $2
```

**Comment by divine-comedian** [comment]
Need to change how we have designed back-end, putting a heavy load on the back-end, we probably cannot optimize this since it is a complex query. 

Will need a few weeks to work on technical debts like this

**Comment by maryjaf** [comment]
How can I test this issue?
should we check all scenarios related to Givpower and ranking calculation  to sure every thing works as before on STG or sth more should be tested?
@aminlatifi

**Comment by aminlatifi** [comment]
> How can I test this issue? should we check all scenarios related to Givpower and ranking calculation to sure every thing works as before on STG or sth more should be tested? @aminlatifi

@maryjaf Yes, GIVpower sorting (not instant boosting) must be tested. We must be sure the balance snapshotting and calculating the balance based on average of periodic snapshots is working as before

**Comment by maryjaf** [comment]
On stg:
Start Date :Sun Aug 6 2023 8:00 PM
End Date: Sun Aug 20 2023 8:00 PM
Can you decrease the round time on stg ?

**Comment by maryjaf** [comment]
Some times by modifying the percentage of Givpower, my Givpower is changed to 0 and after that by refreshing has been resolved

<img width="1397" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/fbef99b4-cdcc-4de0-9c1a-d7823873b134">

<img width="1125" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/70d07bd2-2129-46f5-a6ad-ca8b5fe52df0">

@aminlatifi

**Comment by aminlatifi** [comment]
> Some times by modifying the percentage of Givpower, my Givpower is changed to 0 and after that by refreshing has been resolved
> 
> <img alt="image" width="1397" src="https://user-images.githubusercontent.com/111529185/260406539-fbef99b4-cdcc-4de0-9c1a-d7823873b134.png"> <img alt="image" width="1125" src="https://user-images.githubusercontent.com/111529185/260418099-70d07bd2-2129-46f5-a6ad-ca8b5fe52df0.png">
> @aminlatifi

it would be a frontend issue, though subgraph had issue this morning
@MohammadPCh

**Comment by MohammadPCh** [comment]
we get data from the subgraph, maybe it has a problem when you check it. Besides that, we refactored this part completely on GIVeconomy. and will fix on new release.

**Comment by maryjaf** [comment]
> Some times by modifying the percentage of Givpower, my Givpower is changed to 0 and after that by refreshing has been resolved


Thanks @MohammadPCh I didn't see this problem on GIVeconomy and it seems it has been resolved
