### ISSUE TITLE
Editting project from project view page in admin panel causes removing recipient addresses!!!!

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1073]

**Comment by mohammadranjbarz** [comment]
@maryjaf It's deployed on Staging, if you tested and it was ok, tell me to merge the hotfix PR on production
https://github.com/Giveth/impact-graph/pull/1075

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz,  I'v checked on stg and this problem has been resolved

**Comment by mohammadranjbarz** [comment]
@maryjaf  Now It's on the production can you test it?

@laurenluz  @WhyldWanderer 
I also ran below query to see what projects don't have  addresses to see maybe their projects got affected by this bug

```
SELECT p.slug, p.title, p.id
FROM project p
LEFT JOIN project_address pa ON p.id = pa."projectId"
WHERE pa."projectId" IS NULL;
```

So these are the result of the query

|slug                                            |title                                             |id  |
|------------------------------------------------|--------------------------------------------------|----|
|All-for-Climate-DAO-0                           |All for Climate DAO                               |1241|
|Music-Hive-Community-0                          |Music Hive Community                              |1417|
|internal-testing                                |Internal Testing                                  |1648|
|testfilter                                      |testfilter                                        |2132|
|testemail                                       |testemail                                         |2222|
|maryam                                          |maryam                                            |2238|
|testfinal001                                    |testfinal001                                      |2289|
|pay-the-pizza-forward-at-ethdenver              |Pay the Pizza Forward at ETHDenver!               |2345|
|the-river-giver-for-creators                    |The River Giver for Creators                      |2361|
|testy                                           |testy                                             |2366|
|rrr                                             |RRR                                               |2370|
|her-dao-latam                                   |HER DAO LATAM                                     |2508|
|needs-map                                       |NeedsMap                                          |2518|
|needs-map-0                                     |Needs Map                                         |2519|
|cvf                                             |CVF                                               |2526|
|community-volunteers-foundation                 |Community Volunteers Foundation                   |2527|
|support-to-life                                 |Support To Life                                   |2539|
|afad-disaster-and-emergency-management-authority|AFAD - Disaster and Emergency Management Authority|2543|
|tider-basic-needs-association                   |TIDER - Basic Needs Association                   |2544|
|turkish-red-crescent                            |Turkish Red Crescent                              |2546|
|akut-search-and-rescue                          |AKUT Search and Rescue                            |2548|
|nef-foundation                                  |Nef Foundation                                    |2549|
|unicef-in-turkiye                               |UNICEF in Turkiye                                 |2552|

Some of them are test projects, but for others we can if they have donations we can find addresses from there and fill it ourselves or @WhyldWanderer  can reach them out and ask them then we can set it ourselves
@laurenluz  WDYT?

**Comment by maryjaf** [comment]
We can ignore the test projects like:
internal-testing | Internal Testing | 1648
testfilter | testfilter | 2132
testemail | testemail | 2222
maryam | maryam | 2238
testy | testy | 2366
rrr | RRR | 2370

**Comment by laurenluz** [comment]
@mohammadranjbarz 

Spoke with Ashley about it, and we think your plan is good.
- if they have donations, we should just add that address as the project recipient address.... be sure that you only add that address on the appropriate chains (maybe they are multisigs, so we can't just set the same address for every chain if we don't know it worked before).
- if they are projects with no donations, maybe you can send me their names & emails and we can reach out to them to add it.
