### ISSUE TITLE
Docker image publish problem

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1083]
We have a problem, impact-graph images is not created or published correctly!
The version is registered as staging doesn't hold the latest version of branch
Comparing src/repositories/powerSnapshotRepository.ts file content in repo and published docker

**Comment by mhmdksh** [comment]
Thanks @aminlatifi working on it...

**Comment by mhmdksh** [comment]
Pushed some changes to the pipelines, I'm assuming the builds should work now as expected here are the commits for reference:

- https://github.com/Giveth/impact-graph/commit/fa6c83bc209f10fa00c322e573fb7da848616372
- https://github.com/Giveth/impact-graph/commit/f419419e3defc0d1469a159c6506adbff68ae86e
- https://github.com/Giveth/impact-graph/commit/d71eaf226fbcc80770e99f34e58881c0c56a5e68

**Comment by mhmdksh** [comment]
@MoeNick This is done, we can close it...
