### ISSUE TITLE
Slow query 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1086]
This query is run often staging and takes long time to be executed
```sql
SELECT pu.id, pu."projectId"
      FROM project_update as pu
      WHERE pu.id = (
        SELECT puu.id
        FROM project_update as puu
        WHERE puu."isMain" = $1 AND pu."projectId" = puu."projectId"
        ORDER BY puu."createdAt" DESC
        LIMIT $2
      )
      ORDER BY pu."createdAt" DESC
      LIMIT $3
      OFFSET $4
```

The last one!
<img width="1577" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/9eb5fabe-693b-459c-8c41-d0e2f0ae9d41">

**Comment by mhmdksh** [comment]
@aminlatifi @CarlosQ96 Check out this: https://github.com/hydradatabase/hydra

The numbers look impressive...

**Comment by MoeNick** [comment]
Waiting for @CarlosQ96 fix.
