### ISSUE TITLE
Integrate GIVpower balance aggregator

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1094]
GIVpower aggregator for staging env is ready and is accessible on https://dev.serve.giveth.io/givpower-balance-aggregator URL.

The API doc is available on https://dev.serve.giveth.io/givpower-balance-aggregator/api
Repo: https://github.com/Giveth/giveconomy-balance-aggregator

We must integrate this service for to GIVpower boosting services: **Balance Snapshot** and **Instant Power Balance**

### Fetching GIVPower Balance Snapshot
To fill GIVpower balance snapshots we must take these actions:
1. Use `/fetch-state/least-indexed-block-timestamp` API to check the balance aggregator service has reached to snapshot time on indexing. On impact-graph, we want to fill user balance at snapshot times regularly every 4 hours. The balance aggregator service must have processed all changes to at least that point to deliver valid user power at that the snapshot time.
2. Use `/power-balance/by-timestamp` API to fetch every user balance at the snapshot time.

#### New User Instant Power

We can use the balance aggregator service to fetch a new user instant power by `/power-balance` API

#### Update Instant Powers

The balance aggregator service has `/fetch-state/least-indexed-block-timestamp` API which allows fetching user balances updated after a specific date. 

**Note:**  It's recommended to fetch balances in batches of 1000 (take: 1000) and don't use pagination because of issues may happen on edge cases. Suppose a use balance gets updated during paginating, its place will be changed!

**Note:** On the impact-graph we must keep the `update_at` value of the last record fetched by calling this API and on the next call set `date` value
- If 1000 items has been returned, one millisecond before `updated_at` because there would be more balanes updated at `update_at`
- same value of `update_at` if less than 1000 has returned

**Comment by aminlatifi** [comment]
@MoeNick @laurenluz It's the next step on supporting multichain givpower on givpower boosting. Must be planned.

**Comment by maryjaf** [comment]
Project's rank for all projects is shown "--" plz check @aminlatifi @mohammadranjbarz

**Comment by maryjaf** [comment]
Project's rank for all projects is shown "--" plz check @aminlatifi @mohammadranjbarz
