### ISSUE TITLE
Add "AcceptFundOnGoerli" and "AcceptFundOnAlfajores" to projects filters

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#1098]
Filtering projects by Mainnet and Celo are not working on staging.

![image](https://github.com/Giveth/impact-graph/assets/73441857/edf96bb3-6574-475f-bac5-1e3252e10b26)

![image](https://github.com/Giveth/impact-graph/assets/73441857/9c03c639-862f-4f7c-a662-7540388b92b5)

Supported queries are:
"\"AcceptFundOnGnosis\", \"AcceptFundOnMainnet\", \"AcceptFundOnCelo\", \"AcceptFundOnPolygon\", or \"AcceptFundOnOptimism\"

So, "AcceptFundOnGoerli" and "AcceptFundOnAlfajores" should be added to projects filters

I think it's nice to have a rule for future namings, I did this on front-end:
`AcceptFundOn + chainName.split(' ')[0].toUpperCase()`

e.g. for Alfajores Testnet the filter will be `AcceptFundOnAlfajores`

@mohammadranjbarz @CarlosQ96 Do you agree?

**Comment by RamRamez** [comment]
FYI @maryjaf

**Comment by CarlosQ96** [comment]
ill take it

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 this issue has been resolved on stg
