### ISSUE TITLE
Allow user to specify multisig  session & jwt token expiration

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1117]
To expand on this we need to make a session handler on the backend, we're thinking on using redis to cache these values, essentially we also have to

**Comment by divine-comedian** [comment]
> To expand on this we need to make a session handler on the backend, we're thinking on using redis to cache these values, essentially we also have to

Repurposing this issue 

From our chats related to https://github.com/Giveth/giveth-dapps-v2/issues/3375
When a multisig message is generated we give the multisig 1 week to sign the message. after that they need to restart the process. If they successfully sign in and then a signer from the multisig logs into Giveth we then issue a jwt token for that user. 

On first issue of this jwt token to a user we should extend the duration of the multisig session to match the expiration of the jwt token. 
We should be able to receive a response from the front-end where the user has specified how long they would like their session to last - options will be 3 days, 1 week, 1 month

Subsequent jwt tokens issued to users who are also signers on the given multisig should not extend the duration of the multisig session. 

If possible the jwt tokens issued after the 1st should match the expiration date of the multisig session.

**Comment by CarlosQ96** [comment]
Backend Merged @divine-comedian
