### ISSUE TITLE
Save message hash for every multisig session

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1118]

**Comment by CarlosQ96** [comment]
Using the SDK search for the state of the transaction, this info will be fetched by frontend. When all signatures are done. Create JWT. 

Endpoint Get Transaction: getTransaction
https://docs.safe.global/reference/api-kit

**Comment by maryjaf** [comment]
How can I test issues related to multisig in Unit Testing column ? 
On which branch? @CarlosQ96 @mateodaza
