### ISSUE TITLE
Unify projects count in projectsByUserId and userByAddress

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1123]
In `userByAddress` web service we return all projects count but in `projectsByUserId` we return `active` and `listed` projects. 
After I talked with @RamRamez , it's better to return `active` and `listed` project, unless if user who requests is the owner of that wallet address then we should return all projects count.

@RamRamez  is it ok?
@CarlosQ96  can you take this?

![userByAddress](https://github.com/Giveth/impact-graph/assets/9850545/307f2158-29ab-4be6-8d06-c89e7ddf1a8f)

![projectsByUserId](https://github.com/Giveth/impact-graph/assets/9850545/16e4282c-9315-4d4b-a191-63117a6b987c)

**Comment by maryjaf** [comment]
Do you have any Idea when this issue will be ready to test?  @mohammadranjbarz @CarlosQ96

**Comment by maryjaf** [comment]
Related to: https://github.com/Giveth/giveth-dapps-v2/issues/3060#issuecomment-1708299008

**Comment by maryjaf** [comment]
> Do you have any Idea when this issue will be ready to test? @mohammadranjbarz @CarlosQ96

Kindly reminder @CarlosQ96

**Comment by CarlosQ96** [comment]
I'll work on it between today and tomorrow

**Comment by CarlosQ96** [comment]
Finished Pr ill merge tomorrow early so we can test. @maryjaf

**Comment by maryjaf** [comment]
I tested and by this changes  the project count in public profile view for the owner has been affected and it isn't correct 
@CarlosQ96 & @mateodaza   checked and raised this issue https://github.com/Giveth/giveth-dapps-v2/issues/3203

**Comment by CarlosQ96** [comment]
Backend done but need frontend to finalize it. Will leave it here in QA column. @maryjaf 
https://github.com/Giveth/giveth-dapps-v2/issues/3203
