### ISSUE TITLE
Adding projects to a round in a simple way from admin bro

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1125]
Now for adding a project to a active round the admin user should pass this step

1. In project page tap on filter
2. Enter the project title or slug in filter section
3. Tap on apply change
4. After showing project , tap on add project to QF round
these steps for adding a lot of project take more time and it is so boring

It's better that a  simple way should be designed  for adding lots of projects to a specific round 
cc: @laurenluz @mohammadranjbarz

**Comment by laurenluz** [comment]
@WhyldWanderer or @maryjaf - do you have a suggestion on how we could improve this?

Do we have backend bandwidth to improve this in the next week before we launch the Optimism QF round? I expect we'll be adding about 100-125 projects in that round. @CarlosQ96 @mohammadranjbarz

**Comment by maryjaf** [comment]
Now on the stage with the cooperation of Mohammad, the projects that have a polygon or op  address , were added to a specific round with the  database Query 
we can use this solution on production or design a more better flow to add in admin bro that  admin users could add  many projects to a round

**Comment by laurenluz** [comment]
this is really interesting! @CarlosQ96 @mohammadranjbarz - does this mean that we (comms/community) can just give you a list of the projects... and you can make a query to add them to the round? should we do that for the Optimism round?

we are currently keeping track of projects in here (the green ones have met all requirements): 
https://docs.google.com/spreadsheets/d/128pT6L4cVbZtmFAsUloDG238Xt4c3v7BxJTes5J_Yk0/edit#gid=0

**Comment by laurenluz** [comment]
@MoeNick - how come this is in icebox?

**Comment by mohammadranjbarz** [comment]
> this is really interesting! @CarlosQ96 @mohammadranjbarz - does this mean that we (comms/community) can just give you a list of the projects... and you can make a query to add them to the round? should we do that for the Optimism round?
> 
> we are currently keeping track of projects in here (the green ones have met all requirements): https://docs.google.com/spreadsheets/d/128pT6L4cVbZtmFAsUloDG238Xt4c3v7BxJTes5J_Yk0/edit#gid=0

Yeah sure, exactly

**Comment by laurenluz** [comment]
@WhyldWanderer @NikolaCreatrix - can you guys chime in here on how you think that we can improve admin bro to make it easier to add project to the round?

trying to decide if we should prioritize this issue.

**Comment by laurenluz** [comment]
@maryjaf do you still think we should work on this issue? do you have ideas on how we should improve admin bro so that it doesn't require a dev to add the projects in bulk?

**Comment by maryjaf** [comment]
> @maryjaf do you still think we should work on this issue? do you have ideas on how we should improve admin bro so that it doesn't require a dev to add the projects in bulk?

I think the opinion of owner of adding projects to the round could be more useful for this issue
Now adding huge number of projects to a round by current admin behavior is very difficult and it is needed to add these project manually  from database 

I left a comment on the below issue, it seems these two issues are related 

https://github.com/Giveth/impact-graph/issues/1029#issuecomment-1918534525

**Comment by MoeNick** [comment]
I put p2 to this, correct me @laurenluz if Im wrong.

**Comment by WhyldWanderer** [comment]
> can you guys chime in here on how you think that we can improve admin bro to make it easier to add project to the round?

I am curious if there is a way to do it via csv? I know we can export csv's from the adminbro.. is it also possible to import a csv list of all the slugs of the projects, or IDs?

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 
I've tested this issue and now by adding project ids  in this new field "Add Project Ids List" in Qf page, the projects are added to the round correctly 
But when I tap on "edit" button for this qf round, these field are empty although these project ids are added correctly to this round
https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/90/edit
<img width="1440" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWR3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--762eb3d27569decbf666e0b8b6f700bb40da2747/image.png" alt="image.png" />

**Comment by CarlosQ96** [comment]
@maryjaf yeah the field is just for adding the projects. But not for displaying. Should I add some field to display those ids?

**Comment by jainkrati** [comment]
Yes lets do it. @maryjaf confirmed we will benefit from showing project IDs

**Comment by jainkrati** [comment]
@CarlosQ96 pls guide @Meriem-BM to take this up.

**Comment by CarlosQ96** [comment]
@Meriem-BM I think we can add another virtual field for removing projects using the same logic. 

Also @maryjaf wants to know which projects are added. I remember there is a adminBRO / adminJs property called like prefill or like a placeholder. So that the ids are visible in the textArea, or you can make a custom component for that textArea prefilling the ids. 

Can fill in the textArea that is for adding new projects to the qfround as there is logic that prevents adding them twice, so its safe.

**Comment by jainkrati** [comment]
@Meriem-BM pls take this up with guidance from @CarlosQ96

**Comment by maryjaf** [comment]
> But when I tap on "edit" button for this qf round, these field are empty although these project ids are added correctly to this round
> https://impact-graph.serve.giveth.io/admin/resources/QfRound/records/90/edit

Thanks @Meriem-BM this problem has been resolved
 

- [ ] I have one suggestion for next improvements on this, if you agree @jainkrati @Meriem-BM we could create a separate issue for next phase
Now If an Id is set by user that it isn't in our db and actually this projectId not be correct,   this message is shown:
"There was an error updating record, Check out console to see more information."

It would be helpful  if the incorrect ids be mentioned in the message

**Comment by maryjaf** [comment]
- [x] I couldn't remove a project by using this new field, please take a look @Meriem-BM 
-select one Qf round
-tap on edit
-Remove one or more project ids
-tap on save
-tap on edit again
-the removing ids are also shown  

https://github.com/Giveth/impact-graph/assets/111529185/8157b1df-89d1-43ea-8f7a-7e7718e3dc46

**Comment by maryjaf** [comment]
> * [ ]  I couldn't remove a project by using this new field, please take a look @Meriem-BM
>   -select one Qf round
>   -tap on edit
>   -Remove one or more project ids
>   -tap on save
>   -tap on edit again
>   -the removing ids are also shown
> 
>  Screen.Recording.2024-05-20.at.9.13.22.PM.mov

Kindly reminder @Meriem-BM

**Comment by maryjaf** [comment]
> * [ ]  I have one suggestion for next improvements on this, if you agree @jainkrati @Meriem-BM we could create a separate issue for next phase
>   Now If an Id is set by user that it isn't in our db and actually this projectId not be correct,   this message is shown:
>   "There was an error updating record, Check out console to see more information."
> 
> It would be helpful if the incorrect ids be mentioned in the message

What do you think about this ? Do you think it would be helpful for admin user or we can ignore this ? @laurenluz

**Comment by Meriem-BM** [comment]
Hey @maryjaf, sorry for the delay, you can test this now

**Comment by laurenluz** [comment]
> > * I have one suggestion for next improvements on this, if you agree @jainkrati @Meriem-BM we could create a separate issue for next phase
> >   Now If an Id is set by user that it isn't in our db and actually this projectId not be correct,   this message is shown:
> >   "There was an error updating record, Check out console to see more information."
> > 
> > It would be helpful if the incorrect ids be mentioned in the message
> 
> What do you think about this ? Do you think it would be helpful for admin user or we can ignore this ? @laurenluz

Hey @maryjaf! I think this is a good suggestion but perhaps not worth the extra work. there are very few people using admin bro, so as long as we know.... like *some issue* happened and it wasn't added, I Think the admin can trouble shoot and double check the id perhaps.

But I won't say know if it's super easy 😅  just trying to be conscious about our full dev pipeline.

**Comment by maryjaf** [comment]
> Hey @maryjaf, sorry for the delay, you can test this now

Thanks @Meriem-BM 
I'v tested again and it has been fixed.
