### ISSUE TITLE
Check for new Projects who have added an OP address - September 2023

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1127]
We should do another query and find the list of projects that have added OP address to do another distribution. Related to https://github.com/Giveth/giveth-dapps-v2/issues/2637

**Comment by MoeNick** [comment]
is it urgent?

**Comment by divine-comedian** [comment]
> is it urgent?

No not, urgent  - mohammad knows how to do it and can handle it when he's returnd from vacay

**Comment by oyealmond** [comment]
hey team! Im gathering the metrics of our progress on this, could you tell me how many projects with an OP address we have? (I assume only verified projects right?)

**Comment by MoeNick** [comment]
If its urgent we can ask @CarlosQ96 to take a look. Mohammad is on vacay

**Comment by oyealmond** [comment]
I think we can wait for @mohammadranjbarz! And actually would be great to have both categories: 

number of Giveth Projects with an OP address (verified and not verified). 
number Verified Projects with an OP address

Thanks!

**Comment by mohammadranjbarz** [comment]
@oyealmond  @divine-comedian 
Non verified projects that have OP addresses ( **170**)
[non_verified_projects_with_OP_address_2023-09-25.csv](https://github.com/Giveth/impact-graph/files/12712955/non_verified_projects_with_OP_address_2023-09-25.csv)


Verified projects that have OP addresses ( **114**)
[verified_projects_with_OP_address_2023-09-25.csv](https://github.com/Giveth/impact-graph/files/12712956/verified_projects_with_OP_address_2023-09-25.csv)

**Comment by divine-comedian** [comment]
Updated a new entry into the spreadsheet and used a formula to detect projects we already distributed to -
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

**Comment by divine-comedian** [comment]
awaiting multisig tx to pass this
https://app.onchainden.com/safes/oeth:0x4d9339dd97db55e3b9bcbe65de39ff9c04d1c2cd/transactions/0xc0eabbeac359e8aeb51fead70875c1b0db85beed85311c66b701a3a8dd52aee6

**Comment by laurenluz** [comment]
how ofter will we be doing these checks? I expect we'll get a bunch more in the next week or so because we're doing a big comms/outreach push to try to get projects to add their OP address to enter the QF round.

I think we should do a check next week again.

**Comment by divine-comedian** [comment]
> how ofter will we be doing these checks? I expect we'll get a bunch more in the next week or so because we're doing a big comms/outreach push to try to get projects to add their OP address to enter the QF round.
> 
> I think we should do a check next week again.

@mohammadranjbarz does them manually - you can check the original issue referenced
