### ISSUE TITLE
Improve Error Logging for adding duplicate token

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1130]
When trying to add a token to the list when the same token has already been added we should show a more explicit error message to not confuse the administrator attempting to make the change

![Screenshot from 2023-09-20 13-18-48](https://github.com/Giveth/impact-graph/assets/67759413/9de94910-c59e-485d-b3ea-95fc4f39501f)

**Comment by jainkrati** [comment]
@RamRamez pls take a look at this.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
when I set the fields just like a existing token,  by tapping on "save " for the first time I got this error 
"there was an error updating record, checkout console to see more information"

and by tpping again on "save" button, I got this error
duplicate key value violates unique constraint "IDX_4e29282c925a82d9e50480c2af"

**Comment by RamRamez** [comment]
@maryjaf Yes, I fixed it to return the DB error, and for a duplicate record DB returns something like "duplicate key value violates unique constraint"

**Comment by maryjaf** [comment]
> when I set the fields just like a existing token, by tapping on "save " for the first time I got this error
> "there was an error updating record, checkout console to see more information"

but by tapping on "save" for the first time, the previous error is shown 
Is this accepted ?

**Comment by RamRamez** [comment]
I checked multiple times, you should be able to see this error for the first time
![image](https://github.com/Giveth/impact-graph/assets/73441857/ee8b188a-1379-4626-a9eb-3d07405a61c4)

**Comment by maryjaf** [comment]
I've checked again and it was ok 
This message is shown in duplicate token scenario :
duplicate key value violates unique constraint "IDX_4e29282c925a82d9e50480c2af"

**Comment by MoeNick** [comment]
Seems it's not merged on Prod, right? @RamRamez ?

**Comment by RamRamez** [comment]
> Seems it's not merged on Prod, right? @RamRamez ?

No, it's on staging
