### ISSUE TITLE
Implement new web service to check if someone donated to a project in an specific qfRound or not

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1138]
* Suggested webServie name:
**doesDonatedToProjectInQfRound**
* Inputs
  * `projectId`
  * `qfRoundId`
  * `userId` @MohammadPCh  or you prefer `walletAddress` ?
* Response  
Should return just a boolean
@MohammadPCh  @MoeNick  Please let me know if you need something more for this webservie
related to https://github.com/Giveth/giveth-dapps-v2/issues/2958

**Comment by MoeNick** [comment]
It's all fine. thank you

**Comment by mohammadranjbarz** [comment]
@MoeNick  The backend part is merged now

@MohammadPCh  You can call it in this way

```
query (
   $projectId: Int!,
   $qfRoundId: Int!,
   $userId: Int!
  ) {
    doesDonatedToProjectInQfRound(
      projectId: $projectId
      qfRoundId: $qfRoundId
      userId: $userId
    )
  }
  ```
  and it would return a boolean

**Comment by laurenluz** [comment]
@mohammadranjbarz - you are great!!
