### ISSUE TITLE
Save user's DID from ceramic and add a verification relationship on database

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#114]
We want to verify user's identity on different web 2 social networks using services like 3box or self.id through idx/ceramic

For this we would like to save the DID and where did the user verified its identity

A new table for the users is needed, to relate the DID, platform, protocol, claim and attestation for example:

user: 1
did: did:3:kjz123...456
protocol: 3box
platform: "twitter"
claim: "https://twitter.com/mateodazab/status/1267200723177148418"
attestation: "eyJ0eXA....8UgNZ79bw" (JWT)

To finalize we need to add this information to user's resolver so it can be accessible from all queries that is needed

**Comment by MoeNick** [comment]
Can I test it?  any ideas ?
btw, It was an old requests that we decide to postpone it. we may ask @cquinterom096 to sync more about priorities if he's still participating in project.

**Comment by mateodaza** [comment]
This needs frontend integration, it was delayed because of priorities
