### ISSUE TITLE
Add pyUSD and GLO dollar to GIVbacks token list

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1140]
Following up on this suggestion from @GriffGreen 
https://forum.giveth.io/t/givbacks-token-list/253/41

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBakg5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--22cbbdea70aa98947e3b3c5ec3fb146712ee4610/image.png)

We should add these two to our token list and find a way to set the prices.

We should after that add them to our GIVbacks eligible list - which can be done simply from the admin dashboard/

GLO - https://www.coingecko.com/en/coins/glo-dollar
(this doesn't meet our usual liquidity requirements, Griff says we can fix the price to $1 always)

pyUSD - https://www.coingecko.com/en/coins/paypal-usd

**Comment by maryjaf** [comment]
I set "is stable coin: true" for DrGIV3 on goerli on stg and the result was expected
![image](https://github.com/Giveth/impact-graph/assets/111529185/0de61544-4fe8-45ca-be92-2abd0e02b59f)


I need GLO and pyUSD  for test on prod, if possible plz send to this my account @divine-comedian 
0xcd192b61a8Dd586A97592555c1f5709e032F2505

**Comment by divine-comedian** [comment]
## GLO Dollar
Here's the address on polygon https://polygonscan.com/address/0x4f604735c1cf31399c6e711d5962b2b3e0225ad3

bought a little on uniswap and sent it to you 
https://polygonscan.com/tx/0xea314c4096554dfe043ffaca63c9e08f7ae99c5895f0635a34fc603f7a5b66c5

-- 

pyUSD is only on mainnet so a bit outta my budget for testing :( - I think it's okay though if we don't test on prod, unless @GriffGreen has some to test with

**Comment by gglucass** [comment]
@divine-comedian @maryjaf wanted to let you know of https://github.com/Giveth/impact-graph/issues/1168 - would be cool if this can be updated soon :-)
