### ISSUE TITLE
Distribute OP to new verified projects with optimism addresses - October 2023

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1155]
From https://github.com/Giveth/giveth-dapps-v2/issues/2637

We'll need to fetch the list of verified projects that have added an OP address @mohammadranjbarz 

Once we have that I can run it against the list of projects we have already have distributed to. 

Keeping you in the loop @oyealmond so you know for comms.

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @oyealmond 

# Query
```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```
# Result
[project_with_op_addresses_2023_10_15.csv](https://github.com/Giveth/impact-graph/files/12909089/project_with_op_addresses_2023_10_15.csv)

**Comment by divine-comedian** [comment]
This tx will distribute 25 OP each to 93 projects who added an OP address in the last month :exploding_head: 

You can check out the spreadsheet work here. (Please check my work!)
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing


You can sign the transaction here: :black_nib: 
https://app.onchainden.com/safes/oeth:0x4D9339dd97db55e3B9bCBE65dE39fF9c04d1C2cd/transactions/0x40156bb192f1720a61a8b04cc9b7cb9e5f8d458fb6d3094de9783c133c0950fc

**Comment by divine-comedian** [comment]
Looks like this was distributed on Oct. 17

Here's the tx if we choose to show them on the front-end
https://optimistic.etherscan.io/tx/0xae94e3d4f6959aa42be25b6b9ff7b048bb08dd85c7863433792d318f99a7fa47

**Comment by oyealmond** [comment]
Thanks @mohammadranjbarz @divine-comedian! 
I scheduled a tweet announcing this for tomorrow.
