### ISSUE TITLE
Change Glo Dollar's naming on Giveth from `GLO` to `Glo Dollar` and `USDGLO`

### ISSUE THREAD

**Issue by gglucass** [Giveth/impact-graph#1168]
We standardize our naming scheme to `Glo Dollar` for the name and `USDGLO` for the symbol. See https://coinmarketcap.com/currencies/glo-dollar/ for an example. 

Would be great if the Giveth platform can use this naming scheme too instead of the current "GLO" for both the name and the ticker :-)

_Originally posted by @gglucass in https://github.com/Giveth/impact-graph/pull/1152#discussion_r1360375928_

**Comment by divine-comedian** [comment]
the name, symbol and image should be fixed on mainnet & polygon
![Screenshot from 2023-11-03 13-58-17](https://github.com/Giveth/impact-graph/assets/67759413/b9cc5c81-1aa7-4bf9-8847-5f6c2d3e7e02)

you can check it out on giveth.io

**Comment by gglucass** [comment]
Terrific, thank you @divine-comedian!
