### ISSUE TITLE
Optimize Analytics Tracking Calls

### ISSUE THREAD

**Issue by cquinterom096** [Giveth/impact-graph#117]
This is a Quality of Life change. 
Right now Analytics tracking methods are being called in the main code/mutations, this is an issue because it slows down the backend from answering the frontend and if the tracking break, it breaks the whole code.

Solutions: 
1. Refactor Tracking calls into it's own module / methods / classes so it's not spread out through the whole code base.
2. Move tracking calls to a background Job that it's executed after the backend answers the frontend.

**Comment by MoeNick** [comment]
@divine-comedian @cquinterom096 shall we start this? 
is it needed to be more clarified?
