### ISSUE TITLE
[solana-v2]Hash SPL addresses for projects with Solana addresses & add to project information

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1172]
In Solana token transfers work differently than in EVM 

Each wallet has separate "token accounts" for every token 

When a token is transferred from wallet A -> wallet B it is transferred from the corresponding token account of wallet A to the token account associated with wallet B

A wallet owner needs to manually create their token accounts to view & manage tokens they've received

However we are able to know what their given token account address is/will be by hashing together their main account address with the address of the token contract.. 

@jainkrati - can also clarify if I missed or misunderstood any points

**Comment by jainkrati** [comment]
Here is the reference link : https://spl.solana.com/token#example-transferring-tokens-to-another-user

**Comment by divine-comedian** [comment]
I think we also need this:
https://spl.solana.com/associated-token-account

**Comment by divine-comedian** [comment]
- SOL (native token)
- mSOL `mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So`
- USDC `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`
- USDT `Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB`
- RAY `4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R`
- bSOL `bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1`
- AUDIO `9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM`
- MANGO `MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac`
- Coin98 `0xaec945e04baf28b135fa7c640f624f8d90f1c3a6`

**Comment by jainkrati** [comment]
For now we are only supporting donation with SOL token in v1. This is what we agreed @divine-comedian 

In v2 when more tokens are involved, we can use JS implementation given here https://spl.solana.com/token#example-transferring-tokens-to-another-user to calculate the Associated Token Accounts before transfer.

**Comment by divine-comedian** [comment]
@jainkrati Yes that is correct! We can focus on just making SOL donations happen and work on SPL tokens in a later iteration of this feature

**Comment by MoeNick** [comment]
According to our timeline, we have to start v1, I would appreciate assigning it to the backend guys or starting it yourself. @aminlatifi 
CC: @jainkrati

**Comment by aminlatifi** [comment]
The expected finish time is by the end of Tuesday Jan 9

**Comment by MoeNick** [comment]
I can see its' merged, can we put it in QA?

**Comment by aminlatifi** [comment]
@MoeNick the backend is merged. The FE must be integrated as well.

**Comment by MoeNick** [comment]
@alireza-sharifpour will test with token before 
please test with new SOL recipient address.
