### ISSUE TITLE
Add Solana information to user profiles 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1174]
Users who add their Solana addresses to their existing profiles will need the information appended to their user information in the database 

Also vice versa for users who have solana and add an ethereum adresses

**Comment by jainkrati** [comment]
We would build on the DB change discussed here https://app.zenhub.com/workspaces/all-devs-61644589b92edf0016f6999c/issues/gh/giveth/impact-graph/1173, but Frontend ofcourse needs to show relevant information.

**Comment by divine-comedian** [comment]
@jainkrati - Is there something missing from the issue specification? Or more details myself or @MoeNick can provide? 

If not please assign this issue if you have sufficient clarity.

**Comment by aminlatifi** [comment]
It would be implemented for the Solana V2 support
  - The user is signed in with his Ethereum Wallet
  - He wants to add his Solana Address
  - He clicks on "Add Solana Address"
  - Should ask connect your solana wallet!
  - He connects his solana wallet
  - We ask sign a random message (where to fetch it?! authentication service?!)
  - The user passes us the wallet address and signature
  - We verify the signature and if it's valid we add the solana address to the user

**Comment by MoeNick** [comment]
I think this is a bad idea to do it in 2 different phases:

- We got in trouble with data, we gonna have lots of duplicate users in ETH and in Solana. sorting these users to map to the other account is going to be frustrating 

- We won;t get the money for only newly added users, cause it don;t work, if I sign in with solana as a new user, I could not donate cause there is no projects to be able to ad their addresses! 

cc: @divine-comedian @jainkrati

**Comment by divine-comedian** [comment]
## Project Owners Adding Solana Address
To clarify @MoeNick 's point 

Since a project owner is aliased by their eth address in order for them to add a solana address for their existing project they would need to log in with their eth address (since we can't alias the two together... yet) 

This is okay for now, unless @aminlatifi thinks it will cause lots of problems later. 

We should absolutely make sure a user can sign in w/ solana and make a project w/ a solana address as part of MVP since we are required to onboard solana native projects and have them receive donations as part of the final grant milestone. 

## Sign In with Solana 
I think it's okay for now if v1 is only sign in w/ Solana and we can't handle having joined sol/eth profiles. 

@aminlatifi If you think it won't be a major headache to join existing separated solana and ethereum profiles then I'm okay, as long as you keep it in mind for post-MVP it is a requirement that users can have 1 profile with a joined solana/ethereum address

---

In general since our deadlines are VERY tight we should **cut scope as much as possible** and meet the minimum requirements of the grant. 

While development is in process @MoeNick can do the necessary planning & research for post MVP follow up.

**Comment by CarlosQ96** [comment]
This is the most complex part. And can easily take **3-4 days (24-32 hours of work)** if NO big side effects arise.
As the user is tightly coupled with the eth wallet and called in many places.

Also changes in logic in the frontend might occur, since interacting with the backend depends on the schema.

Ideal solution would be to abstract the user from the wallet and add a linking functionality (to eth wallet/user) + what Amin said in this comment.

**Comment by aminlatifi** [comment]
It's better to go for merging accounts at the last step.
Currently, we have an authentication issue with the Solana wallet. If we resolve it, we can complete the flow of donating in Solana and Creating projects with the Solana address. I hope we can have them implemented by next week, then aim for supporting both ETH and Solana address for single user.

**Comment by MoeNick** [comment]
I think we will get in trouble if we go live and we going to have duplicate users. 

if you have a clear solution for it @divine-comedian  I'm down that we have it in 2 separate version, unless I not sure. 

@mosaeedi is working on this 'link your eth account' thing, but if we lunch v1, the flow will change, we should customize it again for solana-native users who already joined.

**Comment by MoeNick** [comment]
@aminlatifi @CarlosQ96 
This one should be in QA, right?

**Comment by aminlatifi** [comment]
> @aminlatifi @CarlosQ96 This one should be in QA, right?

Yes

**Comment by MoeNick** [comment]
@maryjaf FYI

**Comment by MoeNick** [comment]
We excluded the merging account feature from this issue and made another [EPIC ](https://github.com/Giveth/giveth-dapps-v2/issues/3392)here, which that epic is out of scope. 

But the acceptance criteria for this story is I can complete my SOL profile, as a new user. @maryjaf
