### ISSUE TITLE
Fetch prices of SOL & Solana tokens 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1175]
Tokens will be 

- SOL (native token)
- mSOL `mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So`
- USDC `EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v`
- USDT `Es9vMFrzaCERmJfrF4H2FYD4KCoNkY11McCe8BenwNYB`
- RAY `4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R`
- bSOL `bSo13r4TkiE4KumL71LsHTPpL2euBYLFx6h9HP3piy1`
- AUDIO `9LzCMqDgTKYz9Drzqnpgee3SGa89up3a247ypMj2xrqM`
- MANGO `MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac`
- Coin98 `0xaec945e04baf28b135fa7c640f624f8d90f1c3a6`

WDYT @jainkrati ?

We should figure out if we are getting these from APIs (which could be expensive) or if we want to use a solution similar to what we have with the monoswap repo pricing @mateodaza and @mohammadranjbarz handles most of this.

Here's the repo
https://github.com/Giveth/monoswap

**Comment by jainkrati** [comment]
Fetching latest token prices https://www.quicknode.com/guides/solana-development/3rd-party-integrations/pyth-price-feeds

**Comment by divine-comedian** [comment]
> Fetching latest token prices https://www.quicknode.com/guides/solana-development/3rd-party-integrations/pyth-price-feeds

I see this protocol requires some development in Rust.. Is this the only option or is there easier options for our team that are available in JS?

**Comment by jainkrati** [comment]
Thanks @divine-comedian . Some options in Typescript APIs are https://coinmarketcap.com/api/documentation/v1/#operation/getV2CryptocurrencyQuotesLatest, https://docs.moralis.io/web3-data-api/solana/reference/get-sol-token-price?network=mainnet&address=SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt, https://docs.birdeye.so/reference/get_public-price,

**Comment by mohammadranjbarz** [comment]
@jainkrati  @aminlatifi  @MoeNick  @divine-comedian 
We have the codebase for coingecko, if the plans are ok we can use it for Solana tokens prices
https://www.coingecko.com/en/api

<img width="1209" alt="Screen Shot 1402-09-13 at 15 47 01" src="https://github.com/Giveth/impact-graph/assets/9850545/52a0a555-52d0-4c56-9740-b828f3545afa">

**Comment by aminlatifi** [comment]
> @jainkrati @aminlatifi @MoeNick @divine-comedian We have the codebase for coingecko, if the plans are ok we can use it for Solana tokens prices https://www.coingecko.com/en/api
> 
> <img alt="Screen Shot 1402-09-13 at 15 47 01" width="1209" src="https://private-user-images.githubusercontent.com/9850545/287694587-52a0a555-52d0-4c56-9740-b828f3545afa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTI2MjIsIm5iZiI6MTcwMTY5MjMyMiwicGF0aCI6Ii85ODUwNTQ1LzI4NzY5NDU4Ny01MmEwYTU1NS01MmQwLTRjNTYtOTc0MC1iODI4ZjM1NDVhZmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDRUMTIxODQyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZWQ5ZGJmNjU5ZTYxMzQ1Nzc4MGM2YWU4YmJhOWZkYmFjNTQ1MmNkZGE5ZTI5OTAwOGEwNDUzYjBlN2M5ODU1YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aZMoDZ7Hy9e_1cpPGQbsDkmFBfkf7XSqw6UPFptx-NU">

We only use coingecko for ETC and Solana in the future, so a free plan would be enough for us!

**Comment by MoeNick** [comment]
@mohammadranjbarz @aminlatifi 
Is there any progress here on prices and donation verification? is that the issue I should track?

**Comment by aminlatifi** [comment]
> @mohammadranjbarz @aminlatifi Is there any progress here on prices and donation verification? is that the issue I should track?

@mohammadranjbarz Is working on donation verification and @CarlosQ96 takes care of donation saving and price fetching.

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @MoeNick 

Can you give me a simple token transfer for each token we want to support ( I looked in block explorer but all of them that I checked were batch transfer not a single transfer) I need it to write test cases

**Comment by MoeNick** [comment]
I put this in progress.

**Comment by MoeNick** [comment]
> @divine-comedian @MoeNick
> 
> Can you give me a simple token transfer for each token we want to support ( I looked in block explorer but all of them that I checked were batch transfer not a single transfer) I need it to write test cases

I think this is related @mohammadranjbarz 
https://github.com/Giveth/impact-graph/issues/1172

**Comment by CarlosQ96** [comment]
I did the price fetch for Solana token and updating the price with a function. This works with a coingeckoId, we should be good now. 


Not sure it requires a more robust implementation. Ill move to QA

**Comment by CarlosQ96** [comment]
Should we make a migration to add the rest of the tokens or is that in another phase? @mohammadranjbarz @MoeNick

**Comment by mohammadranjbarz** [comment]
> Should we make a migration to add the rest of the tokens or is that in another phase? @mohammadranjbarz @MoeNick

Yeah I agree with you

**Comment by MoeNick** [comment]
Can you provide the estimatios? @CarlosQ96

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 You can add all the tokens in your migration, because now we can verify **spl-token** transfer on solana (It's almost done, but I'm refactoring to push after that)

**Comment by CarlosQ96** [comment]
Half a day, I'll continue on it today.

**Comment by CarlosQ96** [comment]
Added the tokens from mainnet migration to Mohammads PR as they touched similar changes. Coingecko returns all those tokens easily as they are supported in their API

**Comment by aminlatifi** [comment]
> * 0xaec945e04baf28b135fa7c640f624f8d90f1c3a6

@divine-comedian The address you had entered for coin98 is an evm one, we used this address instead C98A4nkJXhpVZNAZdHUA95RpTF3T4whtQubL3YobiUX9
