### ISSUE TITLE
Two projects with same slug and recipient address

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1176]
These two projects have the same slug and recipient address. 
Shouldn't this be impossible?

https://giveth.io/project/women-economic-empowerment

Project IDs are 2881 and 2882

Maybe we can delete the one that is not verified?

**Comment by jainkrati** [comment]
@mohammadranjbarz pls guide @RamRamez to take this up. Just trying to onboard him to solve these kind of product heavy issues

**Comment by RamRamez** [comment]
@WhyldWanderer I checked and we have only one project with the slug "women-economic-empowerment" that is id = 2881.

**Comment by WhyldWanderer** [comment]
Yes.. I believe the 2882 one got deleted in the end. However it doesn't solve the issue as Giveth shouldn't allow for this use case. 

Maybe it's still worth doing some testing to create some projects with the same title to see what happens on the backend?

**Comment by RamRamez** [comment]
@WhyldWanderer of course, I did some testing, it's impossible to add duplicate projects with UI, but by sending multiple direct requests to backend at the same time, I could create different projects with same title and wallet address.
To solve this, I added a unique index for slug field in Project entity. Also, we had some projects with duplicate slug on staging and production that I solved them all.
I've sent the PR and it's waiting for review.

**Comment by RamRamez** [comment]
The PR for this issue is ready. I'll merge it on staging after SuperFluid release.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
It has been resolved and know there is no way to create one project with same name and address
