### ISSUE TITLE
Add Solana Address for donations

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1188]
Supporting donations in Solana in the backend, so far only donations in Solana.
The donation creation endpoint must support donation made on Solana.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Is working on Solana donation validation. I suppose he won't need to touch the database/schema at this stage but @CarlosQ96 it would be better to sync with him on this.

**Comment by CarlosQ96** [comment]
I think this can be done in about **8 hours. (buffer max 2 day time: 16 hours)**

Need to make some tests donations and test projects, and try with solana addresses with the graphql api. To get the prices coingecko might be the best option to be fast. (we have an adapter)

Note: Here im talking strictly about the action of donating with solana and getting prices, minimal user logic or mocked. As it's related to authentication service + issue https://github.com/Giveth/impact-graph/issues/1174

**Comment by aminlatifi** [comment]
> I think this can be done in about **8 hours. (buffer max 2 day time: 16 hours)**
> 
> Need to make some tests donations and test projects, and try with solana addresses with the graphql api. To get the prices coingecko might be the best option to be fast. (we have an adapter)
> 
> Note: Here im talking strictly about the action of donating with solana and getting prices, minimal user logic or mocked. As it's related to authentication service + issue #1174

The same expectation, would finish till tomorrow Dec 13

**Comment by aminlatifi** [comment]
@CarlosQ96 Please do anything you want to do on top of #1196

**Comment by MoeNick** [comment]
Shall I close this one?
