### ISSUE TITLE
Upgrade node.js version

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1192]
Currently, the authentication service is based on node version 16.14.2, which is deprecated.
The goal would be to migrate to v20 lts

**Comment by MoeNick** [comment]
is it p1 or p2? @aminlatifi

**Comment by aminlatifi** [comment]
> is it p1 or p2? @aminlatifi
Labeled to p2

**Comment by jainkrati** [comment]
@MohammadPCh can you complete this by 1st Feb?

**Comment by aminlatifi** [comment]
It's done by https://github.com/Giveth/impact-graph/pull/1271

**Comment by jainkrati** [comment]
Thanks for taking this up @mohammadranjbarz .
