### ISSUE TITLE
Add CORS switch in config

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1217]
CORS checking cannot be disabled, let's add a config entry to don't/do load cors middleware based on that.

**Comment by mohammadranjbarz** [comment]
@aminlatifi 
We have it already

https://github.com/Giveth/impact-graph/blob/89181dfa4c773025d06f5009904bbe2fba0f62ea/src/server/bootstrap.ts#L200-L230

**Comment by aminlatifi** [comment]
> @aminlatifi We have it already
> 
> https://github.com/Giveth/impact-graph/blob/89181dfa4c773025d06f5009904bbe2fba0f62ea/src/server/bootstrap.ts#L200-L230

I meant this line
https://github.com/Giveth/impact-graph/blob/89181dfa4c773025d06f5009904bbe2fba0f62ea/src/server/bootstrap.ts#L235
CORS is enabled whole the time

**Comment by aminlatifi** [comment]
It's already merge to the staging. Devops can test it

**Comment by aminlatifi** [comment]
@mhmdksh let's close this one if you confirm it's done.

**Comment by mhmdksh** [comment]
Yes, I can confirm that it's working. We can close this issue now. Thanks @aminlatifi
