### ISSUE TITLE
impact-graph errors on sentry

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1228]
Not all impact-graph errors are saved on the sentry corresponding project. 
1. First we must be sure sentry dashboard is configured well and for every impact-graph instant a project with meaningful name is created e.g. impact-graph-production, impact-graph-develop
2. Then configure impact-graph instance with correct sentry credentials and urls
3. Be sure all impact-graph errors are sent to sentry

**Comment by aminlatifi** [comment]
@geleeroyale @mhmdksh We have a single impact-graph project in sentry, is it for production? or staging? 
Maybe it's better to have separate projects per ENVs

**Comment by geleeroyale** [comment]
Done! We have set up keys for two different projects now

**Comment by jainkrati** [comment]
@aminlatifi are there any updates here? Please also involve @RamRamez for dividing the work load. I am setting up a call for the same.

**Comment by aminlatifi** [comment]
@jainkrati The Devops team has sorted it out.
