### ISSUE TITLE
Verifying solana donations

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1231]
On staging we have made solana donations which are not verified yet

<img width="1612" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/d6c1c27e-4b85-4c64-a338-7c155cf4ae6d">

**Comment by mohammadranjbarz** [comment]
<img width="1156" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkNVQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--52c85bb4a89db6e186c451ec8d8155b9568f623f/Screenshot%201402-10-13%20at%2011.45.14%20in%20the%20morning.png" alt="Screenshot 1402-10-13 at 11.45.14 in the morning.png" />

They are verified now
