### ISSUE TITLE
P0 - Donation failing in the UI

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1233]
After donating on Optimism, I received this error.
Chrome browser

![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/77085b2f-d760-431b-b588-1f03e8f4aa7a)

https://optimistic.etherscan.io/tx/0xec8349aef06c97bf1e26fe97de2d05c33243bcc8d78703f37ee2fbb5a85ce6ec

**Comment by RamRamez** [comment]
Mentioning @mohammadranjbarz @CarlosQ96 to keep them in the loop.
I haven't found the problem yet, I'm working on it.
I will ask backend guys to check it too.

**Comment by WhyldWanderer** [comment]
It happened again on this transaction:
https://optimistic.etherscan.io/tx/0x0cbc732797ab1f9caeb14b113a2962fc2c4d569ee41a4300029be0260d31b614


This time I was able to capture a screenshot of the console
![image](https://github.com/Giveth/giveth-dapps-v2/assets/74267818/c0b9b21d-570e-4a60-8b24-24e692436b40)

**Comment by WhyldWanderer** [comment]
And another:
https://optimistic.etherscan.io/tx/0xcfc02cf1d3f2249d6551ffca8f2b9cba75b40d3841efd3f031164327a10c2e5b

**Comment by WhyldWanderer** [comment]
It may sound weird but it seems to have something to do with the amount of the donation. Smaller donations (500 GIV) seem to work fine but if i donate a larger amount (1500 GIV) it does not save.

**Comment by WhyldWanderer** [comment]
Nevermind... this one for 500 GIV also did not save
https://optimistic.etherscan.io/tx/0xc34714b9fc44e5a1afcd611b168c65b980d6ed14b5b4381401c250acf09fa589

**Comment by RamRamez** [comment]
I'm mentioning @aminlatifi to keep him in the loop

**Comment by Rolazo** [comment]
@RamRamez @aminlatifi 
Guys my bad, I was checking the status (Old version), cheking the CPU/RAM , redis looks fine, It went just at 60%.
![image](https://github.com/Giveth/giveth-dapps-v2/assets/38561963/e268a1fb-8ab8-4b38-a0ca-b1a0b4cb2807)

**Comment by divine-comedian** [comment]
@mohammadranjbarz 

Can you add these transactions manually to the DB? This is including all of the ones @WhyldWanderer reported above and the ones I gathered from support requests in Discord.

- [x] https://optimistic.etherscan.io/tx/0x0cbc732797ab1f9caeb14b113a2962fc2c4d569ee41a4300029be0260d31b614
- [x] https://optimistic.etherscan.io/tx/0xec8349aef06c97bf1e26fe97de2d05c33243bcc8d78703f37ee2fbb5a85ce6ec
- [x] https://optimistic.etherscan.io/tx/0xc34714b9fc44e5a1afcd611b168c65b980d6ed14b5b4381401c250acf09fa589
- [x] https://optimistic.etherscan.io/tx/0x3367ba1fa95a672030a6b70ba1649551f7ae38271834066d6bcd9a120567c393
- [x] https://optimistic.etherscan.io/tx/0x8838d5be728ac29110340aacd883e9ede19048146e1c28842e4f4e28e4ba4761
- [x] https://optimistic.etherscan.io/tx/0x519eba6cb2cd23629a190dec600faa025f485dac8e6b331d299e87cea837d18a
- [x] https://optimistic.etherscan.io/tx/0xc047f19d1b5f868fbc8e9db0c226a006e62fd59975375118b54718b0ea27bba0
- [x] https://optimistic.etherscan.io/tx/0x4c68af6ee296fe43ba205816e05e34ac6d84190d8ca793fa217f416cf8835429
- [x] https://optimistic.etherscan.io/tx/0xcfc02cf1d3f2249d6551ffca8f2b9cba75b40d3841efd3f031164327a10c2e5b

**Comment by MoeNick** [comment]
Adding more here based on the Saturday support channel:

- [x] https://optimistic.etherscan.io/tx/0x9ad5a37b1c71a940862f152e9d0d557755f4f7ddb5cc1327174a1ede90bceb64
- [x] https://optimistic.etherscan.io/tx/0x2e410bf8b53bbefe6025a6409fc9cee4f29e79b7f3025f260d85fd7555496e46

**Comment by MoeNick** [comment]
Adding one more based on Sun support channel:

- [ ] https://optimistic.etherscan.io/tx/0xead36175c01203d5ed31a056f69d5a10e97084267bab746c1f71e09b6921eeda

**Comment by laurenluz** [comment]
Do we know when the Dapp was down? @WhyldWanderer ? Can we make an estimated start & finish time and then widen the range, so we can check all donations within that time & start adding them?

**Comment by laurenluz** [comment]
- [ ] https://optimistic.etherscan.io/tx/0x5de5ca5e5c05a25f249c2251c043c727ca327619d15d78814d92e312a7205711


mine just failed.

We need to fix this issue ASAP!

**Comment by laurenluz** [comment]
- [ ] https://optimistic.etherscan.io/tx/0xdbfbc5631b4f2a9272dba86a3dfd1f504e7e894111652dc0e27327e55def150f

**Comment by RamRamez** [comment]
When user starts a tx, we call an endpoint called "createDonation" that saves the donation on DB. For some reason, when front-end calls this endpoint, it fails and donations will be lost.
I sent a PR that will try to call "createDonation" endpoint multiple times (in case it fails), not only once. This way we will have less lost donations.
@laurenluz If you think it's urgent, we can have a hotfix.

**Comment by laurenluz** [comment]
@RamRamez this is totally urgent. The longer the issue persists, the more manual work we will need to do.

If we call "create donation" multiple times, will that lead to more issues from overloading our backend?

Do we know why it has been failing?

**Comment by mohammadranjbarz** [comment]
@maryjaf 
Can you check the projects to see if all this donations are in our DB with correct data now?
And if they are correct check the item of that tx in this issue

You can see these donation details and projects here ( if you had any question to have to test it please ping me)
https://github.com/Giveth/impact-graph/blob/master/migration/1703398409668-add_missed_op_donations_to_db.ts

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz 
These transaction have been added into "all donation" and "Giving season"
but I don't know how could we be sure that estimated matching is calculated correctly ?

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz These transaction have been added into "all donation" and "Giving season" but I don't know how could we be sure that estimated matching is calculated correctly ?

@mohammadranjbarz 
If it's in the donations and the QfRound Donations the estimated matching would be correct for sure

**Comment by RamRamez** [comment]
> @RamRamez this is totally urgent. The longer the issue persists, the more manual work we will need to do.
> 
> If we call "create donation" multiple times, will that lead to more issues from overloading our backend?
> 
> Do we know why it has been failing?

@laurenluz I haven't found the root cause yet, I did different donations on OP but all of them were successful. I need to see network tab to investigate further.

I don't think it will overload the backend because it only sends the second request when the first one has been failed. And it sends the third request only if the second one has been failed (to max of 5 requests). I think it helps losing less donations.

**Comment by laurenluz** [comment]
I think it's a good idea. I heard we found one possible cause of the issue on USDC donations, but I also had issues w other donation tokens.

So this would help.

Maybe @mohammadranjbarz or @aminlatifi can confirm so we're all on the same page?

**Comment by aminlatifi** [comment]
> I think it's a good idea. I heard we found one possible cause of the issue on USDC donations, but I also had issues w other donation tokens.
> 
> So this would help.
> 
> Maybe @mohammadranjbarz or @aminlatifi can confirm so we're all on the same page?

Confirm it's a good idea.

**Comment by jainkrati** [comment]
@maryjaf can you pls test and close it given that @aminlatifi has deployed a fix for failing donations.

**Comment by maryjaf** [comment]
Yeah I had tested the scenarios for checking draf donation on prod  and it worked correctly
