### ISSUE TITLE
Reduce notification centre

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#1239]
In an effort to limit load on our backend, it would be great to reduce the notification centre

Imo, we should:
- Don't send notifications for received donations less than $1 (neither emails nor in the dapp)
- Don't send notifications for sent donations (neither emails or in the dapp)
- Remove: My project activity -  Project published
- Remove: My project activity - Project updated or edited

**Comment by laurenluz** [comment]
@divine-comedian @WhyldWanderer @NikolaCreatrix please feel free to add other suggestions of not useful notifications

cc @jainkrati FYI - when we did load testing on the dapp, 35% of the resources were being used up by the notificaiton centre. This is a not very useful service that is impacting important things... like recording donations.

**Comment by divine-comedian** [comment]
These are great! I would also add:

Project you liked is listed
![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/1394440c-c722-4bf7-b851-fe9defee7124)


@jainkrati - who has bandwidth to take this on? This will reduce the load significantly ahead of the polygon round 

## Checklist 
Remove these **notifications**:
- [x] Donor: Made Donation
- [x] Project Owner: Received Donation (**If donation USD value is > $1**)
- [x] Project Owner: My project activity - Project published
- [x] Project Owner: My project activity - Project updated or edited
- [x] General User: Project user liked: Project is now listed

Remove these **emails**
- [x] Project Owner: Received Donation (**If donation USD value is > $1**)
- [x] Donor: Made Donation

**Comment by aminlatifi** [comment]
@CarlosQ96 Do you think you will have bandwidth to take it?

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up as a p0. Let me know if you have any other p0 items on plate. I will help you reprioritize.

**Comment by CarlosQ96** [comment]
Thanks, I can take it soon. Finishing p0 about importing the missing donations, currently a draft pr, im cleaning up and will leave it for review in a few hours.

**Comment by divine-comedian** [comment]
@CarlosQ96 - We should find a way to test to know if this is the root cause of our issues. 

In the meantime, for expediency we should turn off the notification center while we work on these issues defined above. 

We should remember to turn on the notification center in time for GIVbacks distribution so users are notified of those. 

cc @WhyldWanderer

**Comment by CarlosQ96** [comment]
@RamRamez there is a small part that must be done in the frontend, the notification settings are handled directly by your side. Maybe we can disable that view for now.

**Comment by aminlatifi** [comment]
> @CarlosQ96 - We should find a way to test to know if this is the root cause of our issues.
> 
> In the meantime, for expediency we should turn off the notification center while we work on these issues defined above.
> 
> We should remember to turn on the notification center in time for GIVbacks distribution so users are notified of those.
> 
> cc @WhyldWanderer

GIVBack notifications are sent by giveconomy-notificaiton-service, independent of impact-graph.

**Comment by aminlatifi** [comment]
There is an important question here! should we ignore all notifications that used to be sent during this off time? or do we have to send them suspended notifications after it's enabled?

**Comment by laurenluz** [comment]
I feel like the most important ones not to miss are GIVbacks are out...

I honestly don't think it is an issue to just ignore & never send the ones during this time, but curious to hear what @whyldwanderer or @divine-comedian think

**Comment by divine-comedian** [comment]
Yes, we can ignore the notifications

**Comment by WhyldWanderer** [comment]
Yeah.. I think we can ignore them as well.. how long is the projected period of time for it to be completely down?

**Comment by maryjaf** [comment]
my project received a 11 USD donation but no notification and email has been sent for project owner

https://explorer.solana.com/tx/7599siBRhzt6W39Mom3VS9eqJkMzSJNHkKcbDKRdDZRU3tsUSLMqV3r74WRUnEHJM1BkfiPs58gg7Ldbtj7PDVh?cluster=devnet

<img width="1316" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/45e04d61-6328-4219-bca7-402dd6c23404">

**Comment by divine-comedian** [comment]
@maryjaf  - Are you sure this service is working for Solana donations? This issue was made with EVM donations in mind (it should eventually work for Solana too)

**Comment by maryjaf** [comment]
> my project received a 11 USD donation but no notification and email has been sent for project owner

ّI reported this problem on issue about solana notification (# 3559), and Amin said it seems it's related to this issue

**Comment by divine-comedian** [comment]
@CarlosQ96 - what is the update for this issue?

**Comment by laurenluz** [comment]
but what if....

![image](https://github.com/Giveth/impact-graph/assets/75490971/125d856f-9eb6-4d48-be9b-d1f72886c9f9)

**Comment by CarlosQ96** [comment]
The notifications from the checklist have been disabled. I thought Maryjaf late confirmed the issue were fixed. Can you reconfirm @maryjaf ?

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 Yeah the problem related to solana donation notification has been resolved, I had commented on (# 3559)
