### ISSUE TITLE
Update recurring donation status

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1243]
Recurring Donations can be ended either by user action or automatically when the user's super token balance reaches a critical low point (almost zero). 

We should handle when this happens. When a user triggers this action by ending their stream (possible from my donations UI)
https://github.com/Giveth/giveth-dapps-v2/issues/3092

We should update the status of the recurring donation so we know its no longer active. 

When it is triggered outside of the UI, either on another UI, directly on the blockchain by a user or by the super token running out of balance we need to capture that and also update the status - we can follow this in https://github.com/Giveth/impact-graph/issues/1148

**Comment by divine-comedian** [comment]
## Open Questions on Saving the extra data 
- Where do we keep track of the total amount donated and it's USD value? At what point is that info saved & how?
- How do we handle showing the total amount donated on the single project page to reflect new recurring donations?

**Comment by jainkrati** [comment]
We can use Subgraph to query latest value of amount donated and use Chainlink or QuickNode API to find USD value. @MohammadPCh @mohammadranjbarz please share your thoughts here.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 This is the issue related to get recurring donation info from blockchain

**Comment by divine-comedian** [comment]
Closing this issue - follow up in #1148
