### ISSUE TITLE
Save networkId for Solana donations and addresses

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1244]
As the frontend is accustomed to using value zero as network ID for Solana Addresses and Donations, let's update our mutations endpoint logic to save `networkId` to a configured value based on the environment. e.g. on production 101 (Mainnet) and on staging 103 (Devnet)

**Comment by divine-comedian** [comment]
@mohammadranjbarz @aminlatifi is this issue complete? I see the PR is merged.

**Comment by divine-comedian** [comment]
@mohammadranjbarz @aminlatifi what is the update on this issue? is it done?

**Comment by aminlatifi** [comment]
> @mohammadranjbarz @aminlatifi what is the update on this issue? is it done?

I think @mohammadranjbarz has done it, right?

**Comment by mohammadranjbarz** [comment]
> > @mohammadranjbarz @aminlatifi what is the update on this issue? is it done?
> 
> I think @mohammadranjbarz has done it, right?

@divine-comedian  Amin is right, it's done
