### ISSUE TITLE
Bug in "Share and Get rewarded" modal on solana

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1256]
1- 
-user is signed out
-Tap on "share and get rewarded" button 
-Tap on "connect wallet"

https://github.com/Giveth/impact-graph/assets/111529185/a6cb4f4f-fdcd-4c4a-ab55-85c79ebb10b5

2-
-Connect wallet is done from user menu
-Tap on "share and get rewarded" button 
-Tap on "sign in"
- an empty modal is shown

https://github.com/Giveth/impact-graph/assets/111529185/693bbd4c-cff7-4803-8e85-899e35fb0858

**Comment by MoeNick** [comment]
@alireza-sharifpour 

if a user is on SOL, I guess we should skip requesting for referral code and make it a simple sharing, on these views:

- projects
- single project page
- donation page
- project card.

Please make sure is there any part of the DApp is affected by this integration or not.

Thanks.

**Comment by MoeNick** [comment]
After a call we had, we decided to let the user switch network to use referral feature as the chain-vine is not evm compatible.

The copy for these views: 

``Currently this feature is only available on EVM chains. 
``Switch Network

Thanks @alireza-sharifpour 
FYI @maryjaf

**Comment by CarlosQ96** [comment]
Yeah definitely, Solana is not supported by them. So I'm sure their api will not work. As we would probably need to ask them to add the integration too. I will double check tomorrow the exact error, but it's my guess looking and the code and how it works.

**Comment by MoeNick** [comment]
@alireza-sharifpour @aminlatifi 
Would you pls help me finalize the attached pr, I guess review is still pending

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour @aminlatifi Would you pls help me finalize the attached pr, I guess review is still pending

This is under review, if anyone can review it, it will be great.

**Comment by maryjaf** [comment]
Thanks @alireza 
This issue has been fixed
