### ISSUE TITLE
Add up totalDonations and totalHearts column when values are updated

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#126]

**Comment by MoeNick** [comment]
@divine-comedian ping to test

**Comment by mohammadranjbarz** [comment]
> @divine-comedian ping to test

For `totalHearts` I believe it's not needed anymore because we use `reactions` relation and it works (https://github.com/Giveth/giveth-next/issues/228)
but for `totalDonations` I have no idea

**Comment by divine-comedian** [comment]
sorry there's no context in this issue besides the description so I have no idea how/where to test this. @MoeNick
