### ISSUE TITLE
Changing the sorting of SOL Token (on prod) 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1278]
As a user, I want to see the specific sorting of tokens on the donation page when Im on Solana so I can have better visibility on well-known tokens. 

This is the currant sorting on production
<img width="482" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGtQQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11ad58f629ee07bd085d573180ad91d3d988e5bc/image.png" alt="image.png" />

I want to have this sorting:

1. SOL
2. USDC
3. RAY
4. BSOL
5. and the rest does not matter

**Comment by MoeNick** [comment]
Would you pls assign it to someone?

**Comment by MoeNick** [comment]
a gentle reminder on this @jainkrati

**Comment by jainkrati** [comment]
@alireza-sharifpour could you take this up. Let me know if you need more than a few hours to finish this. I am hoping we can do tthis by tomoror wmorning.

**Comment by alireza-sharifpour** [comment]
I think this sort should be done in the backend because we take this list from backend.
And not only for Solana but also for all other networks this is the way we handle this.
@jainkrati @MoeNick

**Comment by MoeNick** [comment]
Yes, it's a backend issue, I usually do it in admin for other chains. But for Solana I could not manage it, I remember for release I asked Mohammad to add tokens .

**Comment by jainkrati** [comment]
@mohammadranjbarz pls take this up.

**Comment by jainkrati** [comment]
@RamRamez pls work on this with minmal guidance from @mohammadranjbarz

**Comment by RamRamez** [comment]
I fixed it on production.
@maryjaf to test and verify

**Comment by maryjaf** [comment]
<img width="892" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3NxQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06e4ddb0d16569af0a6a650ee9d241b29e019726/image.png" alt="image.png" />
