### ISSUE TITLE
Arb | Adding Price for ARB tokens in Monoswap 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1281]
The list of tokens we need the price : 

NAME | Symbol | Address

1. Arbiterum ETH - ETH
2. Tether USDt -USDT - 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
3. USDC -  USDC - 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
4. Chainlink - LINK - 0xf97f4df75117a78c1A5a0DBb814Af92458539FB4
5. Dai - DAI - 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
6. Uniswap - UNI - 0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0
7. Lido - DAO LDO - 0x13Ad51ed4F1B7e9Dc168d8a00cB3f4dDD85EfA60
8. Arbitrum - ARB - 0x912CE59144191C1204E64559FE8253a0e49E6548
9. Brigded ISDC - USDC.e - 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
10. TrueUSD - TUSD - 0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07
11. The Graph - GRT - 0x9623063377AD1B27544C965cCd7342f7EA7e88C7
12. Frax Share - FXS - 0x9d2f299715d94d8a7e6f5eaa8e654e8c74a988a7
13. USDD - USDD - 0x680447595e8b7b3Aa1B43beB9f6098C79ac2Ab3f
14. WOO - WOO - 0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b
15. Gnosis - GNO - 0xa0b862f60edef4452f25b4160f177db44deb6cf1
16. Curve DAO Token- CRV - 0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978
17. Compound - COMP - 0x354A6dA3fcde098F8389cad84b0182725c6C91dE
18. GMX - GMX - 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a
19. Loopring - LRC - 0x46d0cE7de6247b0A95f67b43B589b4041BaE7fbE
20. Treasure - MAGIC - 0x539bdE0d7Dbd336b79148AA742883198BBF60342
21. SushiSwap - SUSHI - 0xd4d42f0b6def4ce0383636770ef773390d85c61a
22. yearn.finance - YFI - 0x82e3A8F066a6989666b031d916c43672085b1582
23. Xai - XAI - 0x4Cb9a7AE498CEDcBb5EAe9f25736aE7d428C9D66
24. XLivepeer - LPT - 0x289ba1701C2F088cf0faf8B3705246331cB8A839
25. XWrapped Bitcoin - WBTC - 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f
26. Cartesi - CTSI - 0x319f865b287fCC10b30d8cE6144e8b6D1b476999

**Comment by aminlatifi** [comment]
I am not sure monoswap is still the best price-fetching option, @mohammadranjbarz @CarlosQ96 I would like your thoughts here. 
Regardless of approach, we need tokens addresses.

**Comment by MoeNick** [comment]
I updated the addresses

**Comment by aminlatifi** [comment]
@MoeNick @jainkrati @MohammadPCh @CarlosQ96 I will rely on coingecko for fetching arbitrum tokens. We cannot use monoswap on arbitrum sepolia since uniswap has not been deployed on this chain.

**Comment by MoeNick** [comment]
We did the same for ETC and Mordor (Testnet of eth classic) for the same reason.  
Im fine with it, but let's monitor the service and make sure it won't make a blocker for donations on other networks with lots of donations, especially during QF rounds. as the coingecko-plan we're using is free.

**Comment by MoeNick** [comment]
@jainkrati 
FYI as we did not change the monoswap and we're using our coingecko API, I will close this as not planned. 

But let's have another issue for monitoring this service.
