### ISSUE TITLE
Arb | Adding Arbitrum Sepolia Network into staging on backend

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1284]
List of Tasks
- [x] Adding Sepolia chain 
- [x] Adding Sepolia ETH token (To Giveth Org) 
- [x] Verification flow on staging with Sepolia ETH

Sepolia Test Net:
- RPC https://sepolia-rollup.arbitrum.io/rpc 
- ChainID: 421614	
- Explorer: https://sepolia.arbiscan.io/
- Faucet:https://bwarelabs.com/faucets/arbitrum-sepolia
- Facet for test tokens: https://testnet.chromatic.finance/faucet

Token List Staging:
- ETH 
- Chromatic test Eth - cETH - 0x93252009E644138b906aE1a28792229E577239B9

**Comment by aminlatifi** [comment]
@MoeNick Do we have any test ERC20 token on arbitrum sepolia for testing purpose? if yes, please include their information (including address) here.

**Comment by MoeNick** [comment]
I mentioned the ETH on Sepolia on stage is enough, you can get it by its Faucet. No need for other tokens

**Comment by aminlatifi** [comment]
> I mentioned the ETH on Sepolia on stage is enough, you can get it by its Faucet. No need for other tokens

Technically, we need to test ERC20 token transfer as well.

**Comment by MoeNick** [comment]
I updated the token list @aminlatifi and added WETH with 0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14
I wrapped Sepolia ETH on uniswap, if you want to get some you can do the same.

**Comment by aminlatifi** [comment]
@MoeNick There is no contract/token with the address 0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14 on arbitrum sepolia network

**Comment by MoeNick** [comment]
Please try this faucet:
https://testnet.chromatic.finance/faucet

Chromatic test Eth - cETH - 0x93252009E644138b906aE1a28792229E577239B9

**Comment by MoeNick** [comment]
I updated the description of this issue, thanks @aminlatifi for reminding me.
