### ISSUE TITLE
Arb | Adding Arbitrum Network (Mainnet) into impact-graph production. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1285]
https://arbiscan.io/

- [x] Write migration for adding tokens on the Arb network (list of tokens)
- [x] Verify donations and transactions
- [x] Checking Infura

Token List production:

1. Arbiterum ETH - ETH
2. Tether USDt -USDT - 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
3. USDC - USDC - 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
4. Chainlink - LINK - 0xf97f4df75117a78c1A5a0DBb814Af92458539FB4
5. Dai - DAI - 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
6. Uniswap - UNI - 0xFa7F8980b0f1E64A2062791cc3b0871572f1F7f0
7. Lido - DAO LDO - 0x13Ad51ed4F1B7e9Dc168d8a00cB3f4dDD85EfA60
8. Arbitrum - ARB - 0x912CE59144191C1204E64559FE8253a0e49E6548
9. Brigded ISDC - USDC.e - 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
10. TrueUSD - TUSD - 0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07
11. The Graph - GRT - 0x9623063377AD1B27544C965cCd7342f7EA7e88C7
12. Frax Share - FXS - 0x9d2f299715d94d8a7e6f5eaa8e654e8c74a988a7
13. USDD - USDD - 0x680447595e8b7b3Aa1B43beB9f6098C79ac2Ab3f
14. WOO - WOO - 0xcafcd85d8ca7ad1e1c6f82f651fa15e33aefd07b
15. Gnosis - GNO - 0xa0b862f60edef4452f25b4160f177db44deb6cf1
16. Curve DAO Token- CRV - 0x11cDb42B0EB46D95f990BeDD4695A6e3fA034978
17. Compound - COMP - 0x354A6dA3fcde098F8389cad84b0182725c6C91dE
18. GMX - GMX - 0xfc5a1a6eb076a2c7ad06ed22c90d7e710e35ad0a
19. Loopring - LRC - 0x46d0cE7de6247b0A95f67b43B589b4041BaE7fbE
20. Treasure - MAGIC - 0x539bdE0d7Dbd336b79148AA742883198BBF60342
21. SushiSwap - SUSHI - 0xd4d42f0b6def4ce0383636770ef773390d85c61a
22. yearn.finance - YFI - 0x82e3A8F066a6989666b031d916c43672085b1582
23. Xai - XAI - 0x4Cb9a7AE498CEDcBb5EAe9f25736aE7d428C9D66
24. XLivepeer - LPT - 0x289ba1701C2F088cf0faf8B3705246331cB8A839
25. XWrapped Bitcoin - WBTC - 0x2f2a2543B76A4166549F7aaB2e75Bef0aefC5B0f
26. Cartesi - CTSI - 0x319f865b287fCC10b30d8cE6144e8b6D1b476999

**Comment by aminlatifi** [comment]
@MoeNick Would you please include the tokens address in this issue?

**Comment by MoeNick** [comment]
I updated teh addresses

**Comment by aminlatifi** [comment]
@MoeNick This one 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8 has USDC as symbol value on smart contract. I use this value in token data

**Comment by MoeNick** [comment]
> @MoeNick This one 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8 has USDC as symbol value on smart contract. I use this value in token data

Isnt it USDC.e? https://arbiscan.io/address/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8

**Comment by MoeNick** [comment]
https://arbiscan.io/token/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8

**Comment by aminlatifi** [comment]
<img width="213" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/5ae3a52f-1770-4b0a-af5a-78d8139b1de3">

**Comment by aminlatifi** [comment]
@MoeNick Which tokens can be considered as stable coin?

**Comment by MoeNick** [comment]
These are the stable coins:
- Tether USDt -USDT - 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
- USDC - USDC - 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
- Dai - DAI - 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
- TrueUSD - TUSD - 0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07
- Bridged USDC - USDC.e - 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
- USDD - USDD - 0x680447595e8b7b3Aa1B43beB9f6098C79ac2Ab3f

BUT the logic of considering the price of them always as $ 1.00000 is the wrong approach. especially in amounts more than hundreds the total donated amount would be wrong, as the pegged price won't be accurate after 2  decimals.

So I'd rather not flag any of them as stables in DB, but you can decide based on our technical barriers. @aminlatifi

**Comment by aminlatifi** [comment]
> These are the stable coins:
> 
> * Tether USDt -USDT - 0xFd086bC7CD5C481DCC9C85ebE478A1C0b69FCbb9
> * USDC - USDC - 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
> * Dai - DAI - 0xDA10009cBd5D07dd0CeCc66161FC93D7c9000da1
> * TrueUSD - TUSD - 0x4D15a3A2286D883AF0AA1B3f21367843FAc63E07
> * Bridged USDC - USDC.e - 0xFF970A61A04b1cA14834A43f5dE4533eBDDB5CC8
> * USDD - USDD - 0x680447595e8b7b3Aa1B43beB9f6098C79ac2Ab3f
> 
> BUT the logic of considering the price of them always as $ 1.00000 is the wrong approach. especially in amounts more than hundreds the total donated amount would be wrong, as the pegged price won't be accurate after 2 decimals.
> 
> So I'd rather not flag any of them as stables in DB, but you can decide based on our technical barriers. @aminlatifi

Thanks @MoeNick , I won't flag them as stable coin so far.
