### ISSUE TITLE
Email Flow for Project Created

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1296]
When a project has been created on Giveth we should notify the project owner and send them an email that gives them more information on the next steps. 

when the activity is triggered we gather this info from the back-end: 

projectTitle
email
projectLink
firstName
lastName

and we send an email to the project owner that looks like this: 

![image](https://github.com/Giveth/impact-graph/assets/67759413/0eba9064-0a00-4607-ae91-ce196d69598c)

the project title should populate correctly, the button view my project should go to the project details page. We collect their firstname and lastname to correctly populate their user names in our CRM for reference, it does not show up on the email.

**Comment by RamRamez** [comment]
@divine-comedian We don't send any email or notification when project is published.

**Comment by divine-comedian** [comment]
> @divine-comedian We don't send any email or notification when project is published.

We should re-enable sending emails but not in-app notifications

**Comment by maryjaf** [comment]
I haven't faced the problem of project name 
this is an email for project creation in my previous tests 

<img width="1257" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/2dcfa030-0aa6-4f33-acd2-5d85d00a41ba">

**Comment by maryjaf** [comment]
> <img alt="image" width="1257" src="https://private-user-images.githubusercontent.com/111529185/310764418-2dcfa030-0aa6-4f33-acd2-5d85d00a41ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTE5ODgsIm5iZiI6MTcwOTc5MTY4OCwicGF0aCI6Ii8xMTE1MjkxODUvMzEwNzY0NDE4LTJkY2ZhMDMwLTBhYTYtNGYzMy1hY2QyLTVkODVkMDBhNDFiYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwN1QwNjA4MDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMWM5OTc3MjBhNzY1YjZmOTUzNDM5MzE3MmRjMGZmZGYzNDgzZjI0MDIwNjlmNzQ4MWQ2N2JkYmM3M2JmNWI1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Q8ui1YWFLfD8Htkg4V7thaAXf3pn9WeRY2avu-rWUUA">

I've checked again and there is no change in the email text compared to the photo above, Is this the final?
