### ISSUE TITLE
Email flow for Received Donation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1297]
When a project receives a donation that is greater than $1 USD in value we should notify the project owner of the received donation. 

We get these values from the donation from our back-end (@RamRamez I removed `verified` and `transactionLink` from here):

projectTitle
donationAmount
donationToken
email
projectLink

when triggered, the project owner should receive an email that looks like this: 

![image](https://github.com/Giveth/impact-graph/assets/67759413/37a8ee29-87af-4a03-8ed5-645bb90f9bc6)

the project title, donation amount and donation token should populate correctly in the email. the button 'view my project' should link to the project details page.

**Comment by RamRamez** [comment]
@maryjaf can you test this issue plz?

**Comment by maryjaf** [comment]
I did this donation but the project owner didn't receive any email

https://polygonscan.com/tx/0xca438ab6998bc169cf05024d792f8be1c81c565cc4db80462e8184578bb2f1cc
project owner:

https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505

**Comment by divine-comedian** [comment]
> I did this donation but the project owner didn't receive any email
> 
> https://polygonscan.com/tx/0xca438ab6998bc169cf05024d792f8be1c81c565cc4db80462e8184578bb2f1cc project owner:
> 
> https://staging.giveth.io/user/0xcd192b61a8dd586a97592555c1f5709e032f2505

Looks like it does not show in the activities - this means it was never sent from the back-end
![image](https://github.com/Giveth/impact-graph/assets/67759413/7315f472-9258-4934-be2f-f7d90bc38b13)

**Comment by RamRamez** [comment]
@maryjaf You had two donations 21 hours ago and allowEmailNotification had been off for both of them. Can you check your notifications settings?
![image](https://github.com/Giveth/impact-graph/assets/73441857/3e8c9d48-e331-4e0e-b8e2-133e66b0cfad)

**Comment by maryjaf** [comment]
> @maryjaf You had two donations 21 hours ago and allowEmailNotification had been off for both of them. Can you check your notifications settings? ![image](https://private-user-images.githubusercontent.com/73441857/304781975-3e8c9d48-e331-4e0e-b8e2-133e66b0cfad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MjQyNDUsIm5iZiI6MTcwNzkyMzk0NSwicGF0aCI6Ii83MzQ0MTg1Ny8zMDQ3ODE5NzUtM2U4YzlkNDgtZTMzMS00ZTBlLWI4ZTItMTMzZTY2YjBjZmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE0VDE1MTkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmY2ZmOTNiNGEzYTY1MWY0OTRiZDFhNWJiNjBlMzNkZDU1OTVhYmY2YmE3YmNiZGE0NjY3ZTM1NDNmNmQ1NzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KmMaJ4J-hcXfUN7waTpu7TqPvRd_yMo3GSeOV26dST8)

It's weird I remember I checked this for my user 
maybe I checked this for  a wrong user
I'm going to check again

**Comment by maryjaf** [comment]
Thanks @RamRamez 
<img width="1368" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/090a821d-1712-4a62-865a-774532c1cc1e">
