### ISSUE TITLE
Email flow for Project Unlisted

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1299]
When a project edits their description or an admin unlists their project we should notify the project owner via email that this important status update has happened. 

we gather these 3 parameters: 
projectTitle
email (of project owner)
projectLink

and show an email like this: 
![image](https://github.com/Giveth/impact-graph/assets/67759413/da257343-e2ba-4850-b975-ce5cbdba8423)

the project title should populate correctly and the view my project button should link to the project details page

**Comment by maryjaf** [comment]
Thanks @RamRamez I've checked and if user changes listed status to Unlist from project list or edit project page, the email has been sent in about 2 mins 
Is that ok or email should be sent immedaitly ?

**Comment by maryjaf** [comment]
Thanks @RamRamez I've checked and if user changes listed status to Unlist from project list or edit project page, the email has been sent in about 2 mins 
Is that ok or email should be sent immedaitly ?

**Comment by divine-comedian** [comment]
> Thanks @RamRamez I've checked and if user changes listed status to Unlist from project list or edit project page, the email has been sent in about 2 mins Is that ok or email should be sent immedaitly ?

2 minutes is an acceptable delay
