### ISSUE TITLE
Email flow for Project Updated (Donor)

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1301]
This email flow will be triggered when a project owner makes an update to its project - any users who donated to this project should receive this email 

it will take in 3 parameters from our back-end: 

projectTitle
email (of donor)
projectUpdateLink

and should send an email that looks like this: 

![image](https://github.com/Giveth/impact-graph/assets/67759413/8925af85-984d-4089-8925-0ba62b7e7b90)

the merge tags should populate correctly with the project title and the view update button should go correctly to the updates tab on the project's page.

**Comment by RamRamez** [comment]
@divine-comedian We don't send any email when project has a new update. We only send dapp notifications to donors.

**Comment by divine-comedian** [comment]
> @divine-comedian We don't send any email when project has a new update. We only send dapp notifications to donors.

Okay lets hold on this one until I figure out why we decided to stop sending emails for it

**Comment by RamRamez** [comment]
> > @divine-comedian We don't send any email when project has a new update. We only send dapp notifications to donors.
> 
> Okay lets hold on this one until I figure out why we decided to stop sending emails for it

@divine-comedian Any updates for this issue?

**Comment by divine-comedian** [comment]
Since we're not sure about this one I moved it to the new epic https://github.com/Giveth/impact-graph/issues/1313
