### ISSUE TITLE
Update Project Verified Status in Orrto

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1302]
When the admin is updating a project's verified status we should not only send emails but also update the person's tags in Ortto

depending on the value returned on the field 'verified-status' in the activity 'Project Verification' we will do either

- On verification approved: send email & add `Verified Project Owner` tag
![image](https://github.com/Giveth/impact-graph/assets/67759413/f84a0046-9a20-45e5-9b52-94e7655833eb)
- On verification rejected: send email
- on verification revoked: send email & remove 'Verified Project Owner' tag

**Comment by maryjaf** [comment]
The emails related to changing verification status have been sent correctly

**Comment by jainkrati** [comment]
@maryjaf can you close this as completed once you have verified all scenarios for this

**Comment by maryjaf** [comment]
I've tested scenarios on stg and moved it to "done" after deploying on prod we could close this

**Comment by maryjaf** [comment]
in verification flow the email be sent if:
-The admin user changes status form "project " menu
-The admin user changes status from project verification form-->setting--> verify project
and we could close the issue 

but in the below flow the email won't be sent and should be resolved on separate issue 
-The admin user changes status from project verification form--> fill checkbox of project name > verify project
