### ISSUE TITLE
Draft Donation Service

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1311]
- Create draft donation entities holding the upcoming donation information
- A matcher service to match pending draft donations with transactions has happened on the network

@jainkrati 

![image](https://github.com/Giveth/impact-graph/assets/5684607/1bb46ad9-b84e-42d4-be09-f94f97f645b5)

**Comment by aminlatifi** [comment]
The backend service with the support of EVM donations is merged into staging. @MohammadPCh is testing with modified version of FE on his machine.

**Comment by jainkrati** [comment]
@maryjaf can you test and complete this? Post that we can deploy latest backend @mohammadranjbarz @mhmdksh

**Comment by maryjaf** [comment]
Please check below video: @aminlatifi @MohammadPCh 
-Tap on reject on metamask modal 
-After that by taping again  on donate button ""transaction rejected" is shown

https://github.com/Giveth/impact-graph/assets/111529185/a0aca4ef-c022-4098-baf2-3f01b8ae6059

**Comment by aminlatifi** [comment]
> Please check below video: @aminlatifi @MohammadPCh -Tap on reject on metamask modal -After that by taping again on donate button ""transaction rejected" is shown
> 
>  Screen.Recording.2024-02-14.at.1.38.35.PM.mov

@MohammadPCh Can you take a look?

**Comment by maryjaf** [comment]
I couldn't complete a solana donation, please take a look

https://github.com/Giveth/impact-graph/assets/111529185/63893c46-e257-4ff6-8d13-e0146675f40c

**Comment by MohammadPCh** [comment]
@maryjaf let's have a call together. I will ping you in discord.

**Comment by maryjaf** [comment]
> Please check below video: @aminlatifi @MohammadPCh -Tap on reject on metamask modal -After that by taping again on donate button ""transaction rejected" is shown

<img width="1414" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/bda322a5-6399-4476-977b-e944d6766deb">
@aminlatifi

**Comment by maryjaf** [comment]
> I couldn't complete a solana donation, please take a look
> 
>  Screen.Recording.2024-02-14.at.2.08.58.PM.mov



> I couldn't complete a solana donation, please take a look

@alireza-sharifpour helped me and did a test on solana donation and everything was ok for him, it seems this problem is related to my network

**Comment by maryjaf** [comment]
> > Please check below video: @aminlatifi @MohammadPCh -Tap on reject on metamask modal -After that by taping again on donate button ""transaction rejected" is shown
> 
> <img alt="image" width="1414" src="https://private-user-images.githubusercontent.com/111529185/304709449-bda322a5-6399-4476-977b-e944d6766deb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5MDg0MDEsIm5iZiI6MTcwNzkwODEwMSwicGF0aCI6Ii8xMTE1MjkxODUvMzA0NzA5NDQ5LWJkYTMyMmE1LTYzOTktNDQ3Ni05NzdiLWU5NDRkNjc2NmRlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxNFQxMDU1MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Y2UyZTMwZjJjMmE4NzkyNTI1YTg5N2RhY2Q3ZDc3Y2ZkNzEyNzExZDc3OTM4MDRiNzJlMTkxNTYxYWJkMjJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2CSWBLI6prA54SBT9zr7z4v0TAWlWilw9MYOwTMXryM"> @aminlatifi

Thanks @aminlatifi this problem has been resolved
there is no more problem on draft donation, it's ready to be deployed
