### ISSUE TITLE
doesnt return reactions in project list and totalHeart is wrong too

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#132]
As you see the project https://giveth.io/project/the-giveth-community-of-makers has 97 hearts
![Screen Shot 1400-06-26 at 09.14.42.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/8a74f03c-10da-4559-ab0f-08099d5544e8)

but in homepage it shows 90 , that is wrong ![Screen Shot 1400-06-26 at 09.16.37.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/9bc726f7-4a0e-47e1-96a8-48bb96b62867)

And if you call graphql directly from https://mainnet.serve.giveth.io/graphql
with this data
```
 query FetchAllProjects($limit: Int, $skip: Int, $orderBy: OrderBy) {
    projects(take: $limit, skip: $skip, orderBy: $orderBy) {
      id
      title
      balance
      image
      slug
      creationDate
      admin
      description
      walletAddress
      impactLocation
      qualityScore
      verified
      listed
      status {
        id
        symbol
        name
        description
      }
      categories {
        name
      }
      reactions {
        reaction
        id
        projectUpdateId
        userId
      }
      qualityScore
      totalDonations
      totalHearts
    }
    categories {
      name
    }
  }
```

you will see that it doesnt return reactions and I think we should not use `totalHeart` anymore because it has conflict with real count of reactions

![Screen Shot 1400-06-26 at 09.14.31.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/427c0c1c-4964-4924-955b-b355394d721b)

**Comment by mohammadranjbarz** [comment]
@MoeNick you can test this issue by going to https://serve.giveth.io/graphql

and enter 
```
# Write your query or mutation here
  query  {
    projects {
      id
      title
      balance
      description
      image
      slug
      creationDate
      admin
      walletAddress
      impactLocation
      qualityScore
      reactions {
      userId
    }
      totalDonations
      totalHearts
      listed
      categories {
        name
      }
      status {
        id
        symbol
        name
        description
      }
    }
  }
```
So click on Play button,
Then you should see the `reactions` field as an array, not null

**Comment by divine-comedian** [comment]
Testing this issue out 
`next.giveth.io` 
clean cache and cookies 

I can see the array from the query is returned with the user IDs who reacted/hearted each project. 

Is this issue going to fix the discrepancy between  the hearts shwon on the projects lists and the hearts shown on the actual project page? Currently there are still differences ... 
![image](https://user-images.githubusercontent.com/67759413/134059386-365443da-da91-4215-b804-a117e1f49394.png)



![image](https://user-images.githubusercontent.com/67759413/134059362-24905fd0-77c0-4dc4-b645-da1a8f81315e.png)
 

now that the reactions array works should `totalHearts` simply be equal to `reactions.length()`?

**Comment by MoeNick** [comment]
@mohammadranjbarz it's not passed by @divine-comedian back to inprogress.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Sorry it's my mistake, because I made two issues one for backend, one for frontend, and this is for backend side, but the frontend PR is still in code review, So I put back this to codeReview after merging frontend RP I would move both frontend and backend issue to UAT column

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
You can test this issue again, this issue and Giveth/giveth-next#228 are related, and both of them are in UAT test column
