### ISSUE TITLE
Add userId to all API calls & merge-by

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1336]
We need to add the userId from the Giveth back-end to all API calls and change the merge_by field to use this userId instead 

I've already defined this in our data source as the default so we no longer need to define the merge_by in our API call bodies 

We should also add the user-id to the person fields of the API body ahead of the email field, I think its like this: 

```
"fields": {
				"str:cm:user-id": "7988",	
				"str::email": "sample@gmail.com"
			},
```

# Project Cancelled
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

# Project Unlisted
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

# Project Listed
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

# Project Created
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

# Donation Received
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

# Project Verification
- [x] send userId field in call
- [x] add userId to person field in body
- [x] remove merge_by strategy from body

**Comment by RamRamez** [comment]
@divine-comedian What about "verification"?

**Comment by divine-comedian** [comment]
> @divine-comedian What about "verification"?

And Verification too! - added it to the checklist
