### ISSUE TITLE
Donorship Integration Announcement

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1344]
We would like to make a simple integration with Donorship https://donorship.io/

They have a donation widget that they would like to put on all crypto related websites that enable users to make crypto donations, and they would like to list Giveth projects! 

We should be able to provide a graphQL API that they can use to pull a list eligible projects. 

They are also able to provide all of the information for donations that happen through their widget/smart contract. We need to confirm what information we need exactly to insert the donations into our DB.

We also need to decide the fee we want to take (for Giveth) for donations made through their widget. 

Also once this is set we need the comms plan and release announcement.

Donations will be made on ETH mainnet through the Donorship widget

### Contract Example
https://etherscan.io/address/0x7f2D73489275799fc7bBeE7d93B723D88ECdB648#writeContract

## Checklist 

- [x] Provide graphQL API for getting projects 
- [x] Define info we need for inserting txs to Donorship team
- [ ] tooltip on widget notifying users that donations may take  up to3 weeks to show up on Giveth platform
- [x] Choose Fee for Giveth
- [ ] Comms Plan for partnership announcement

**Comment by jainkrati** [comment]
@CarlosQ96 as we already discussed last time we need to expose the API which lists the projects. Given we only need to expose an api with relevant fields which already exists in Giveth and is used by Frontend, I dont see significant development work. Do you think you will need more than 3 days to do this?

**Comment by divine-comedian** [comment]
> @CarlosQ96 as we already discussed last time we need to expose the API which lists the projects. Given we only need to expose an api with relevant fields which already exists in Giveth and is used by Frontend, I dont see significant development work. Do you think you will need more than 3 days to do this?

I provided an API to them for exposing projects as well as a token list for them to use. 

However one thing I noticed is in the graphQL call it limites the responses to 50 projects per call - I wasn't able to get more than that many at once, so you have to cycle through the calls grabbing 50 projects at a time...

I couldn't find just one API call to grab all the projects at once via graphQL

**Comment by CarlosQ96** [comment]
@divine-comedian yeah seems we have a limit of 50 forced on the api to prevent loading too much data at once. We could increase it to 100 sounds reasonable. 
Its a heavy operation to simply load all projects from db at once.

**Comment by divine-comedian** [comment]
> @divine-comedian yeah seems we have a limit of 50 forced on the api to prevent loading too much data at once. We could increase it to 100 sounds reasonable. Its a heavy operation to simply load all projects from db at once.

Don't worry about it then, it will require the same amount of work to make a script or whatever they need to iterate through projects

**Comment by MoeNick** [comment]
@divine-comedian would you pls update the priority tag here?

**Comment by divine-comedian** [comment]
Updating here based on the convo in our TG group. 

Their dev deployed a subgraph to index the donations that happen, however the subgraph is not formatted in the right way for us to get the information we need. The events logged by the contract do not log the sender and recipient of the donation - we should modify this subgraph to fit our needs. 

This is the deployed repo that is private https://github.com/Th0raxC0n/donorship-graph for us to see and modify their subgraph on mainnet

**Comment by divine-comedian** [comment]
Could get everything technically from the transaction hash 

Could reuse the script used to find missing donations from polygon round that can get  the to & from on the transaction hash - except that this service is using a contract as a go between so its different from giveth donations.

we need this data for each donation:
to, from, txhash, chainId, token, amount, 

projectId (if possible)

we get currently txHash, chainId is constant, totalDonationAmount - need to figure out what amount is fee from this 

missing, this is not emitted anywhere in the subgraph: 
to, from, token

Mitch will talk to their dev if we can modify their events emitted to fit our needs.

**Comment by divine-comedian** [comment]
Looks like we didn't have to do any work for this one! We are ready to announce and following this up in https://github.com/Giveth/giveth-planning/issues/1740
