### ISSUE TITLE
There is a problem when loading donations page in admin panel

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1353]
https://impact-graph.serve.giveth.io/admin/resources/Donation
<img width="1910" alt="Screenshot 1402-12-03 at 10 35 38 in the morning" src="https://github.com/Giveth/impact-graph/assets/9850545/e0b6ad1e-510b-4215-98bc-609794fa2fe2">

@jainkrati can you set the appropriate priority for this?
And also you can assign to me or @CarlosQ96

**Comment by jainkrati** [comment]
@mohammadranjbarz this looks like a p0, could you take a look now itself?

**Comment by maryjaf** [comment]
This problem has been resolved and "recurring donation" menu has been added
but there is no record in this page, I couldn't complete a recurring donation to be sure this record will be added but this problem isn't exactly related to this issue I close this
