### ISSUE TITLE
Migrate CI/CD from circleci to github actions

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#136]
I think it's better to have unified CI/CD integration, if we use GitHub actions we can see the pipelines in github, 
it's not needed to access users to circleci to wee jobs ( it's extra work)
As I talked with @aminlatifi  we should change it to github actions

@MoeNick pls check this issue priority

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @MoeNick  Now the config has been setup and github actions is completely replaced by github actions and works on staging


![Screen Shot 1400-07-05 at 12.03.31.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/541421eb-93ec-473c-9903-bc0b0feb10e9)

**Comment by aminlatifi** [comment]
> @aminlatifi @MoeNick Now the config has been setup and github actions is completely replaced by github actions and works on staging
> 
> ![Screen Shot 1400-07-05 at 12.03.31.png](https://camo.githubusercontent.com/7c731e11aa88d47f09981366b2d50c31c722f94e104ae81055bc6b0308eafc72/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3566613765643766623039393433323364316136363033342f35343134323165622d393365632d343733632d393930332d626330623066656231306539)

Thanks man

**Comment by mateodaza** [comment]
Loving thissss
