### ISSUE TITLE
Migrate from OP Goerli to OP Sepolia

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1361]

**Comment by aminlatifi** [comment]
Subgraph: https://api.studio.thegraph.com/query/8787/giveconomy-optimism-sepolia/version/latest
GIV Token	0x2f2c819210191750F2E11F7CfC5664a0eB4fd5e6
Token Distro	0x301C739CF6bfb6B47A74878BdEB13f92F13Ae5E7
UnipoolGIVpower	0xE6836325B13819CF38f030108255A5213491A725

**Comment by maryjaf** [comment]
Thanks, I could complete a success donation with eth and GIV on sepolia, but there is some problems

1-
this new test network doesn't exist in list of Eligible Networks in QF round menu in admin @aminlatifi 

<img width="1435" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/a5aef37a-3b12-4cc6-b16b-3eb21bdadecf">

<img width="1256" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/0479b9bc-4791-47cf-8d05-06366cd9fbe9">

**Comment by maryjaf** [comment]
2-
I'm not sure this problem  is exactly related to these changes or not  but super tokens are shown in list of tokens for one-time donation @MohammadPCh @aminlatifi 
<img width="1428" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/10b7d6b8-2f69-4ca2-86da-7d15875b58a2">

**Comment by aminlatifi** [comment]
@divine-comedian ?!

**Comment by maryjaf** [comment]
3- Usd price of GIV token isn't shown in front 

<img width="517" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/263280b5-44b8-4165-a719-6b82dd5786fe">

**Comment by divine-comedian** [comment]
> 2- I'm not sure this problem is exactly related to these changes or not but super tokens are shown in list of tokens for one-time donation @MohammadPCh @aminlatifi <img alt="image" width="1428" src="https://private-user-images.githubusercontent.com/111529185/308117814-10b7d6b8-2f69-4ca2-86da-7d15875b58a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDgxNjQsIm5iZiI6MTcwOTA0Nzg2NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTE3ODE0LTEwYjdkNmI4LTJmNjktNGNhMi04NmRhLTdkMTU4NzViNThhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNTMxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg5MmFhZTAxNGViZThhYTk5NDczYjFlMzUxYzNhM2E5YjhmNjk2NTE2NWFjMTMwYmY4YmExOGU1ZWRiMGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuNu0rMlsQAYgM2RYJCKjsI_AVIKJjgJdoK4eLoC-O4">

That is very strange! I did not touch the token list for those superfluid tokens - they should definitely not be in that list - perhaps it is a config issue @aminlatifi 

Is there something else you wanted me to look at when you tagged me Amin? it's unclear if there's something else I should look at.

**Comment by aminlatifi** [comment]
> > 2- I'm not sure this problem is exactly related to these changes or not but super tokens are shown in list of tokens for one-time donation @MohammadPCh @aminlatifi <img alt="image" width="1428" src="https://private-user-images.githubusercontent.com/111529185/308117814-10b7d6b8-2f69-4ca2-86da-7d15875b58a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDgxNjQsIm5iZiI6MTcwOTA0Nzg2NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTE3ODE0LTEwYjdkNmI4LTJmNjktNGNhMi04NmRhLTdkMTU4NzViNThhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNTMxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg5MmFhZTAxNGViZThhYTk5NDczYjFlMzUxYzNhM2E5YjhmNjk2NTE2NWFjMTMwYmY4YmExOGU1ZWRiMGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuNu0rMlsQAYgM2RYJCKjsI_AVIKJjgJdoK4eLoC-O4">
> 
> That is very strange! I did not touch the token list for those superfluid tokens - they should definitely not be in that list - perhaps it is a config issue @aminlatifi
> 
> Is there something else you wanted me to look at when you tagged me Amin? it's unclear if there's something else I should look at.

@divine-comedian They should not be added? I can remove them then. No, just for tokens

**Comment by aminlatifi** [comment]
> 3- Usd price of GIV token isn't shown in front
> 
> <img alt="image" width="517" src="https://private-user-images.githubusercontent.com/111529185/308150183-263280b5-44b8-4165-a719-6b82dd5786fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTE5NzYsIm5iZiI6MTcwOTA1MTY3NiwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTUwMTgzLTI2MzI4MGI1LTQ0YjgtNDE2NS1hNzE5LTZiODJkZDU3ODZmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjM0MzZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWRjY2YxNGFlNDg0MTlmNjUzMGQ0M2IyNjRlZDhhNGUzZWRiNWFmNjFmYWE1NGJjMWE1MDZhMDEwYzQ5MzNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.klr3YYD027ZESCh6VjLn7NUfwcQAuMb3WPqkzwaMDFQ">

It's a frontend issue... @alireza-sharifpour

**Comment by aminlatifi** [comment]
> Thanks, I could complete a success donation with eth and GIV on sepolia, but there is some problems
> 
> 1- this new test network doesn't exist in list of Eligible Networks in QF round menu in admin @aminlatifi
> 
> <img alt="image" width="1435" src="https://private-user-images.githubusercontent.com/111529185/308116677-a5aef37a-3b12-4cc6-b16b-3eb21bdadecf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTI4NDYsIm5iZiI6MTcwOTA1MjU0NiwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTE2Njc3LWE1YWVmMzdhLTNiMTItNGNjNi1iMTZiLTNlYjIxYmRhZGVjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZmI1MDQwY2Y4ZmJhNGJmYzcwODQ2N2NmZjRiZmVhNmU5ZGYzMDJlNTJlMzJiMDM0YTg3MzIxMDYzYWNhZWEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nfz_MAe8hpGTEqi0TeB4Lv9aebxBsbGhVD_h31vElEY"> <img alt="image" width="1256" src="https://private-user-images.githubusercontent.com/111529185/308218887-0479b9bc-4791-47cf-8d05-06366cd9fbe9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTI4NDYsIm5iZiI6MTcwOTA1MjU0NiwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MjE4ODg3LTA0NzliOWJjLTQ3OTEtNDdjZi04ZDA1LTA2MzY2Y2Q5ZmJlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjQ5MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OWQ4NzAxNTc2MTllYTJhZTk0ZGNjZGQ3ZmRjOWYwYTg0NGM5ZWRkNzk5ZDBjNGQ0ZjQ4ODY1Nzg5MDBiMDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZdS1FL2TCpBXnkCtdDl0gqiIfI0_OQCyFqsBPcAhPtM">

The first image case didn't happen for me, at exact same point (edit item 87)
<img width="447" alt="image" src="https://github.com/Giveth/impact-graph/assets/5684607/6f518b39-e25f-4095-a1ec-6a7b52dae487">

The second one is a FE issue, @alireza-sharifpour

**Comment by divine-comedian** [comment]
> > > 2- I'm not sure this problem is exactly related to these changes or not but super tokens are shown in list of tokens for one-time donation @MohammadPCh @aminlatifi <img alt="image" width="1428" src="https://private-user-images.githubusercontent.com/111529185/308117814-10b7d6b8-2f69-4ca2-86da-7d15875b58a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNDgxNjQsIm5iZiI6MTcwOTA0Nzg2NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTE3ODE0LTEwYjdkNmI4LTJmNjktNGNhMi04NmRhLTdkMTU4NzViNThhMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNTMxMDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMDg5MmFhZTAxNGViZThhYTk5NDczYjFlMzUxYzNhM2E5YjhmNjk2NTE2NWFjMTMwYmY4YmExOGU1ZWRiMGMzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OuNu0rMlsQAYgM2RYJCKjsI_AVIKJjgJdoK4eLoC-O4">
> > 
> > 
> > That is very strange! I did not touch the token list for those superfluid tokens - they should definitely not be in that list - perhaps it is a config issue @aminlatifi
> > Is there something else you wanted me to look at when you tagged me Amin? it's unclear if there's something else I should look at.
> 
> @divine-comedian They should not be added? I can remove them then. No, just for tokens

Yeah as mentioned in our DM - superfluid tokens should not show up in the list of one-time donations - only recurring donations token list.

**Comment by maryjaf** [comment]
> 1-
> this new test network doesn't exist in list of Eligible Networks in QF round menu in admin @aminlatifi

Thanks, 1 & 2 have been resolved, 
the only thing remains is the super tokens are shown in list of one time donation token

**Comment by alireza-sharifpour** [comment]
About the price issue, I'm working on it, we need the backend to add coingeckoId to some of the tokens that missed this field.
I sent the list of all of them with added coingeckoId to our Arbitrum discord thread.
So please someone add them in DB.

About the Icon issue, we need the missing Icons from the design, if it's on staging I think it would be OK for some tokens to not have icons but if it's on staging, the design should send them to us and we will add them.

**Comment by aminlatifi** [comment]
> About the price issue, I'm working on it, we need the backend to add coingeckoId to some of the tokens that missed this field. I sent the list of all of them with added coingeckoId to our Arbitrum discord thread. So please someone add them in DB.
> 
> About the Icon issue, we need the missing Icons from the design, if it's on staging I think it would be OK for some tokens to not have icons but if it's on staging, the design should send them to us and we will add them.

The PR that adds missing Coingecko IDs is already merged. @alireza-sharifpour Let me know if still backend needs any change.

**Comment by maryjaf** [comment]
> 2-
> I'm not sure this problem is exactly related to these changes or not but super tokens are shown in list of tokens for one-time donation @MohammadPCh @aminlatifi

This problem has been resolved
