### ISSUE TITLE
Implement a webservice to update recurring donation info to a project

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1362]
Cherik:
> Updating recurring donation: We didn't have this feature in simple donation. In recurring donation, users can update their recurring donation, and when they try to allocate a share to a Giveth project, the user needs to update their recurring donation and cannot create a new recurring donation. So, we need to handle it. I think it can be similar to creating a recurring donation project, just adding the wallet address to it, because we can only have one recurring donation from one address to another address.

Mutation should be like below ( I checked with @MohammadPCh )

```
mutation ($projectId: Int!,
  $networkId: Int!,
  $txHash: String!
$interval: String!
$amount: Int!
$currency: String!
$walletAddress: String!
) {
  updateRecurringDonation(
    projectId: $projectId
  networkId: $networkId
  txHash:$txHash
  amount:$amount
  currency:$currency
  interval:$interval
  walletAddress:$walletAddress
) {
    txHash
    networkId
    ....
  }
}
```

**Comment by maryjaf** [comment]
by these changes I should be able to test modify existing recurring donation? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> by these changes I should be able to test modify existing recurring donation? @mohammadranjbarz

@maryjaf Sure

**Comment by maryjaf** [comment]
By tapping on modify stream balance and complete deposit /withdraw flow the "Current stream Balance " filed will be updated correctly 
Is this the expected result of this issue? @MohammadPCh @mohammadranjbarz 
<img width="1733" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVVGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fefc2c7d926ab7912928464302ce57fcc6437f8b/image.png" alt="image.png" />

______

There is a problem in showing recurring donation of project (#3093) and I couldn't check this donation in project page after modifying if the expected result is about this 


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVlGQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f65589cff336c34050eab60277587b903b27630e/Screen%20Recording%202024-03-24%20at%204.37.02%20PM.mov)

**Comment by divine-comedian** [comment]
When user creates recurring donation with the blockchain to change status from active to pending, should fix pending problem not the ended problem.

Carlos should remove the active flag from code, when data is fetched from API was setting recurring donation as active - has a bug with ended status
