### ISSUE TITLE
Save & Retrieve fields for saving project social media info 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1364]
Related to https://github.com/Giveth/giveth-dapps-v2/issues/3466

We'll add some more info to project's data for including social media handles that are associated with a given project, the types of social media handles we can accept are: 

- [x] - facebook
- [x] - twitter/X
- [x] - linkedin
- [x] - discord
- [x] - instagram
- [x] - youtube
- [x] - farcaster
- [x] - Lens
- [x] - website
- [x] - reddit

This data is added to the project during the create/edit project flow

**Comment by maryjaf** [comment]
There is no change in cerat project page on STG @RamRamez

**Comment by RamRamez** [comment]
@maryjaf The backend is merged on staging but the FE is not done yet.

**Comment by divine-comedian** [comment]
@RamRamez - Is there anyway to test this since it is in the QA column?

**Comment by RamRamez** [comment]
@divine-comedian Yes, Maryam can test with Postman, but when FE is merged, @maryjaf has to test it again. Anyway, I can show her how to test it with Postman.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by Santozjago** [comment]
Hello am here to bless 10 people with just $12,000 just say bless me to my dm
