### ISSUE TITLE
Add new GIVbacks Eligible tokens to back-end & fetch prices

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1367]
These are some larget market cap tokens we should consider adding to the dapp, we will need to check getting the prices on the front-end as well as the back-end.

Related FE issue is here: 
https://github.com/Giveth/giveth-dapps-v2/issues/3615

- [ ] STETH mainnet https://www.coingecko.com/en/coins/lido-staked-ether
- [ ] RETH mainnet https://www.coingecko.com/en/coins/rocket-pool-eth
- [ ] RETH optimism https://www.coingecko.com/en/coins/rocket-pool-eth
- [ ] GNO Gnosis https://www.coingecko.com/en/coins/gnosis
- [ ] GIV on Solana https://solscan.io/token/3Xi3EhKjnKAk2KTChzybUSWcLW6eAgTHyotHH1U6sJE1
- [ ] OUSD mainnet https://www.coingecko.com/en/coins/origin-dollar
- [ ] OETH mainnet https://www.coingecko.com/en/coins/origin-ether
- [ ] OGN mainnet https://www.coingecko.com/en/coins/origin-protocol
- [x] USDGLO Arbitrum https://www.coingecko.com/en/coins/glo-dollar

**Comment by laurenluz** [comment]
Also, we had a request from a user to add the following tokens, and Griff checked them to make sure they could be GIVbacks eligible - can we include them in this effort?

✅  OUSD: https://www.coingecko.com/en/coins/origin-dollar

✅  OETH: https://www.coingecko.com/en/coins/origin-ether

✅   OGN:https://www.coingecko.com/en/coins/origin-protocol

**Comment by divine-comedian** [comment]
I think from what I understood in these changes #1238  we should be able to add them ourselves using the adminJS panel

**Comment by laurenluz** [comment]
@WhyldWanderer can you try?

**Comment by WhyldWanderer** [comment]
Yeah! As long as all of the token liquidity has been checked and green-lighted, I can see if I can do it in AdminBro...

**Comment by WhyldWanderer** [comment]
I just saw @MoeNick made a comment in the FE end issue that Mitch linked above:
![image](https://github.com/Giveth/impact-graph/assets/74267818/6af74789-29c3-4207-b7e9-08011b4f7f53)

Should I still continue with adding these tokens?
Also, is there a list of the addresses for these tokens?.. it will help to ensure I don't add the wrong one.

**Comment by laurenluz** [comment]
maybe you can try with one of the ones I linked like OUSD - the token addresses are on coingecko is you follow the link.
I'm not sure what "it's buggy" really means - so maybe just try adding it and then you can verify/contest what @MoeNick is saying?

**Comment by WhyldWanderer** [comment]
Here is the message I get in AdminBro
![image](https://github.com/Giveth/impact-graph/assets/74267818/1602e3a3-22bd-4077-9b92-38c0fb968153)

And here is the console:
![image](https://github.com/Giveth/impact-graph/assets/74267818/10aa1854-ce25-40f6-8ee7-d781ab1576b2)

**Comment by WhyldWanderer** [comment]
But it is still showing in the list as if it was added successfully
![image](https://github.com/Giveth/impact-graph/assets/74267818/3cb95deb-01fd-4f7a-94a5-f6cd66834c26)

**Comment by WhyldWanderer** [comment]
It is also showing in the list of tokens that can be donated on Mainnet but it doesn't populate the logo correctly
![image](https://github.com/Giveth/impact-graph/assets/74267818/3f96a985-f6df-4801-ade3-68f7ffcc8dda)

**Comment by WhyldWanderer** [comment]
I will wait for feedback before trying to add any more

**Comment by laurenluz** [comment]
ahh yeah, maybe that's the buggy part @MoeNick - can you confirm?

**Comment by MoeNick** [comment]
Yeah the logo, and sometimes you add coingecko ID and prices wont be accurate due to backend did not save them.
So please check also the price at the time of donation.

These was my experiences before.

@WhyldWanderer @laurenluz

**Comment by WhyldWanderer** [comment]
ah okay.. and how do I go about adding the logo @MoeNick ?

**Comment by MoeNick** [comment]
@jainkrati For adding new tokens:
- For logos it should assign to a frontend dev
- for fixing coingeckoID it should be assigned to a backend dev

I will create a seperate issue to make sure all these steps can done in Admin, but only for tokens on this issues for now, can you manage this one @jainkrati ?

**Comment by divine-comedian** [comment]
JFYI I made this issue -https://github.com/Giveth/impact-graph/issues/1130 which was related to error handling around the add token functionality in adminJS.

**Comment by GriffGreen** [comment]
Adding 
- [x] USDGLO Arbitrum https://www.coingecko.com/en/coins/glo-dollar
Token Address:
0x4f604735c1cf31399c6e711d5962b2b3e0225ad3

Would love to push that fast if we can!

**Comment by MoeNick** [comment]
I found a hack way to prevent the bug in Admin:
1- Add your token.
2- Ignore the error message and get back to the token page, it should be added but without coingekoID
3- Edit the record and add the coingeckoID again

I hope it helps until the bug is fixed. @WhyldWanderer 
CC: @GriffGreen

**Comment by divine-comedian** [comment]
@MoeNick - Is this done or still pending?

**Comment by MoeNick** [comment]
I did only GLO Dollar on Arb as Griff asked for QF round, but the bug in admin is still there. 
But with the above instructions, everyone can do all the above list. 

If I have to do and check all of them in the above, please let me know 
(Im ok to manage all issues related to this. ) 
@divine-comedian

**Comment by divine-comedian** [comment]
@MoeNick - that would be great, I've already added all the necessary logos and add them into the dapp for the FE.

**Comment by laurenluz** [comment]
@MoeNick @divine-comedian @WhyldWanderer 

Can we also add native USDC to all chains? It's missing everywhere.
For example, on Celo, we show no USDC at all
On Polygon, we only show the bridged USDC (not the polygon native version)

native USDC should be GIVbacks eligible

![image](https://github.com/user-attachments/assets/a35241b0-35df-4d16-b40e-b05b600cfd8e)

On Polygon, we only have one USDC, it's just called "USDC" and it's the bridged version.. we should have the native version (0x3c499c542cEF5E3811e1192ce70d8cC03d5c3359), call that USDC... and call the bridged version USDC.e
![image](https://github.com/user-attachments/assets/08074537-ebff-4d85-a1e1-3a5248b25028)

**Comment by MoeNick** [comment]
I can manage it @laurenluz wull get back

**Comment by MoeNick** [comment]
I added USDC on every chain, can you take a look @laurenluz ?

**Comment by MoeNick** [comment]
I just saw the logo problem in the context of this issue, we can assign a frontend dev to fix all logos on all chains. @WhyldWanderer @divine-comedian

**Comment by laurenluz** [comment]
The title of the token USDC.e should be "bridged USDC" not USDC POS on Polygon, imo
![image](https://github.com/user-attachments/assets/9707227f-349c-41a1-b2bd-24c45c4d264a)

also there is an issue with the logos for USDC.e on Polygon.

Probably a frontend dev should check them on all chains to fix the logos? @MohammadPCh can you assign the appropriate person?

**Comment by MoeNick** [comment]
It's named USDC.e on both Polygin scan and Uniswap
![image](https://github.com/user-attachments/assets/e7792c0e-6923-43b3-b0fa-cf7fa5f42b1e)
![image](https://github.com/user-attachments/assets/76a62834-222c-4d63-aa8b-c0f0b3614db6)
I will change the name to Bridged USDC but keep the symbol as USDC.e
@laurenluz

**Comment by laurenluz** [comment]
you can call it USDC.e... but not USDC (POS)... 🤔 . or is that a default?

**Comment by divine-comedian** [comment]
IDK if you can add USDC.e as a valid token name in the dapp - AFAIK the way we find token images we can't handle case sensitivity and special characters @MohammadPCh might be able to correct me.

**Comment by MoeNick** [comment]
It's done you can check.

**Comment by MohammadPCh** [comment]
@divine-comedian Yes, we change all names to lower case so it's not case-sensitive!
@MoeNick Is it Done?

**Comment by divine-comedian** [comment]
## careful adding tokens! 
We had a big error on production today because two different tokens - USDC & Bridged USDC - were saved with the same token symbol - USDC - this caused donations to not be saved by the app, let's be careful with this in the future.

fixed USDC.e on all networks and added the corrected token image, closing this one. 

Any future token add requests let's open a new issue!
