### ISSUE TITLE
Add SuperFluid OP Sepolia tokens 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1368]
We should add these two tokens (for now) to OP Sepolia for streaming donations using Superfluid: 

Super Giveth Token - GIVx - https://sepolia-optimism.etherscan.io/token/0xdfd824f6928b9776c031f7ead948090e2824ce8b
Super ETH - ETHx - https://sepolia-optimism.etherscan.io/address/0x0043d7c85c8b96a49a72a92c0b48cdc4720437d7

**Comment by aminlatifi** [comment]
@divine-comedian Can you suggest name/title for them?

**Comment by divine-comedian** [comment]
> @divine-comedian Can you suggest name/title for them?

Updated!

**Comment by maryjaf** [comment]
1-
My stream balance isn'y shown correctly

https://github.com/Giveth/impact-graph/assets/111529185/83a2bc40-57d3-454d-ab56-af219f273f0e

<img width="1240" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/1c14c623-d90d-40f6-8565-f66f3f9a0819">

**Comment by divine-comedian** [comment]
@jainkrati - who does this go back to for debugging?

**Comment by maryjaf** [comment]
> My stream balance isn'y shown correctly
> 
>  Screen.Recording.2024-02-27.at.1.39.07.PM.mov 
> <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/111529185/308124956-1c14c623-d90d-40f6-8565-f66f3f9a0819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTEzOTUsIm5iZiI6MTcwOTA1MTA5NSwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTI0OTU2LTFjMTRjNjIzLWQ5MGQtNDBmNi04NTY1LWY2NmYzZjlhMDgxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjI0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjQ0Mjg0N2Y2YzMyMGNjZGMyODQyZWM4NGFiYmNhZWQwNTQ5YjUxNzJlNjdhNWRmZDZhZjkwYWU4NDA1ZjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1XwdUW1jx882nfMKCUbfTVMKVX_GtJkhVbhr0NbRkUg">

 Since these balance were on op goerli, should these balance be removed from my account? @aminlatifi

**Comment by maryjaf** [comment]
2-
I couldn't complete a donation flow  on this new network, I got an error in creating allo profile 

https://github.com/Giveth/impact-graph/assets/111529185/0ccf31b8-bf34-4ded-8cbc-3609f32f9a2c

<img width="1116" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/6126e4cd-135b-4935-8acd-aab88be48e17">

**Comment by aminlatifi** [comment]
> > My stream balance isn'y shown correctly
> > Screen.Recording.2024-02-27.at.1.39.07.PM.mov
> > <img alt="image" width="1240" src="https://private-user-images.githubusercontent.com/111529185/308124956-1c14c623-d90d-40f6-8565-f66f3f9a0819.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTEzOTUsIm5iZiI6MTcwOTA1MTA5NSwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MTI0OTU2LTFjMTRjNjIzLWQ5MGQtNDBmNi04NTY1LWY2NmYzZjlhMDgxOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjI0NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YjQ0Mjg0N2Y2YzMyMGNjZGMyODQyZWM4NGFiYmNhZWQwNTQ5YjUxNzJlNjdhNWRmZDZhZjkwYWU4NDA1ZjJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1XwdUW1jx882nfMKCUbfTVMKVX_GtJkhVbhr0NbRkUg">
> 
> Since these balance were on op goerli, should these balance be removed from my account? @aminlatifi

I will do.

**Comment by aminlatifi** [comment]
> 2- I couldn't complete a donation flow on this new network, I got an error in creating allo profile
> 
>  Screen.Recording.2024-02-27.at.7.58.26.PM.mov 
> <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/111529185/308259470-6126e4cd-135b-4935-8acd-aab88be48e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIwOTQsIm5iZiI6MTcwOTA1MTc5NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MjU5NDcwLTYxMjZlNGNkLTEzNWItNDkzNS04YWNkLWFhYjg4YmU0OGUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2YwYmMyOGUzM2Q1Yjc2Y2NiYzUyYTczOTg0ZThjZGM4NzU2NmVkZjMxMDBjZmJjYzVlMmExNjcyNDQ5MjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3oC-qt-CdbfYy2gdeJNuEUvWku5HHcXzEHH4a5Q_RLY">

Wierd... @maryjaf could you reproduce it again? it seems the error is thrown from viem and not calling backend.

**Comment by aminlatifi** [comment]
> > 2- I couldn't complete a donation flow on this new network, I got an error in creating allo profile
> > Screen.Recording.2024-02-27.at.7.58.26.PM.mov
> > <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/111529185/308259470-6126e4cd-135b-4935-8acd-aab88be48e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIwOTQsIm5iZiI6MTcwOTA1MTc5NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MjU5NDcwLTYxMjZlNGNkLTEzNWItNDkzNS04YWNkLWFhYjg4YmU0OGUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2YwYmMyOGUzM2Q1Yjc2Y2NiYzUyYTczOTg0ZThjZGM4NzU2NmVkZjMxMDBjZmJjYzVlMmExNjcyNDQ5MjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3oC-qt-CdbfYy2gdeJNuEUvWku5HHcXzEHH4a5Q_RLY">
> 
> Wierd... @maryjaf could you reproduce it again? it seems the error is thrown from viem and not calling backend.

@alireza-sharifpour do you have any idea?

**Comment by maryjaf** [comment]
> > 2- I couldn't complete a donation flow on this new network, I got an error in creating allo profile
> > Screen.Recording.2024-02-27.at.7.58.26.PM.mov
> > <img alt="image" width="1116" src="https://private-user-images.githubusercontent.com/111529185/308259470-6126e4cd-135b-4935-8acd-aab88be48e17.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwNTIwOTQsIm5iZiI6MTcwOTA1MTc5NCwicGF0aCI6Ii8xMTE1MjkxODUvMzA4MjU5NDcwLTYxMjZlNGNkLTEzNWItNDkzNS04YWNkLWFhYjg4YmU0OGUxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyN1QxNjM2MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mY2YwYmMyOGUzM2Q1Yjc2Y2NiYzUyYTczOTg0ZThjZGM4NzU2NmVkZjMxMDBjZmJjYzVlMmExNjcyNDQ5MjI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3oC-qt-CdbfYy2gdeJNuEUvWku5HHcXzEHH4a5Q_RLY">
> 
> Wierd... @maryjaf could you reproduce it again? it seems the error is thrown from viem and not calling backend.

Yeah, it happens to me again 
and one more thing my GIV balance isn't shown in this modal 
<img width="640" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/cefec037-72af-4f2e-946d-71f71f809f40">
<img width="925" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/143e23c1-ea4f-4892-980a-86dba971e6cb">

**Comment by MohammadPCh** [comment]
I will add them to FE.

**Comment by MohammadPCh** [comment]
Are you aware of the superfluid subgraph for Sepolia?
@divine-comedian

**Comment by divine-comedian** [comment]
@MohammadPCh 

I believe it is this - https://console.superfluid.finance/subgraph?_network=optimism-sepolia

**Comment by divine-comedian** [comment]
https://optimism-sepolia.subgraph.x.superfluid.dev/subgraphs/name/protocol-v1/graphql

POST requests return data
