### ISSUE TITLE
Add GIVbacks Eligible Tokens to Arbitrum

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1370]
We should make GIVbacks eligible the following tokens for the Arbitrum Network and ensure we can fetch prices for them. 

- ARB 
- USDC
- Bridged USDC 
- USDT
- DAI
- WETH
- WBTC

**Comment by MoeNick** [comment]
@divine-comedian I made the above tokens GIVback eligible in AdminJS
@maryjaf to ensure the prices are correct or not, can you please take a look, Im worried the coingeco free plan sometimes failes the price on FE. We tested the DAI on mainnet and it was working fine

@jainkrati we need monitoring on coingecko pricing API to make sure we don't call more than free plan cap.

**Comment by MoeNick** [comment]
btw @divine-comedian I made the native Arb Eth token GIVback eligible, but I can't find Weth on top tokens in this network.
https://arbiscan.io/tokens And I did not ask devs to add WETH. did I miss something or do you mean Native ArbETH by WETH?

**Comment by maryjaf** [comment]
@MoeNick had sent Dai and ETH Token  for testing and I tested the donation and token price with this token 
 I donated almost of them to the @MoeNick's  project
Now I need a test token to test the rest of token list @divine-comedian @jainkrati

**Comment by MoeNick** [comment]
I tested the above list:

1. **ARB - wrong price on FE**
2. USDC - correct on FE
3. Bridged USDC - correct on FE
4. USDT - correct on FE
5. DAI - correct on FE
6. **WETH - we don't have this token at all.**  https://arbiscan.io/token/0x82af49447d8a07e3bd95bd0d56f35241523fbab1 I was not at https://arbiscan.io/tokens so I avoided it on DApp. will address it in another issue. 
7. **WBTC - wrong on FE**

**Comment by MoeNick** [comment]
I think all tokens rather than stable coins are not responding on FE:
![image](https://github.com/Giveth/impact-graph/assets/80677512/a531a770-833e-4e52-b628-f491f51c0800)
@alireza-sharifpour

**Comment by MoeNick** [comment]
This is related:
https://github.com/Giveth/giveth-dapps-v2/issues/3798

**Comment by MoeNick** [comment]
I put it in QA is #3798 is merged.

**Comment by maryjaf** [comment]
> I put it in QA is #3798 is merged.

This change should be deployed on prod 
<img width="877" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/2761b680-d762-49cd-9c5a-a0805b947b32">

**Comment by maryjaf** [comment]
> https://arbiscan.io/tokens And I did not ask devs to add WETH. did I miss something or do you mean Native ArbETH by WETH?

@divine-comedian kindly reminder
Could we close this issue?

**Comment by divine-comedian** [comment]
I added WETH in by the adminJS - according to my understanding we should have no problem now by using the coingecko-id

@maryjaf - since this issue needs to be fully tested on prod we should keep this in QA phase until we can test it properly - don't want to lose track of this one.

**Comment by maryjaf** [comment]
I've tested on prod and WETH is added and the price is shown correctly
<img width="1167" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/40aca289-0e5a-4236-8544-75d3bd12aec5">
<img width="1200" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/5e6bcfdc-dfe1-4d16-b923-5b0404b5a14c">

**But there is a problem that the USD value isn't shown correctly in donation table**

<img width="1421" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/fc6099ca-7c90-4229-aaba-d801db89d83e">

**Comment by aminlatifi** [comment]
@maryjaf coingecko id was not set for WETH on arbitrum mainnet, I did it now. @divine-comedian if the adminjs panel doesn't allow setting coingeckoId in adding token panel, please make an issue for it.

**Comment by maryjaf** [comment]
Thanks @aminlatifi it has been resolved
<img width="904" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/ef7a4b1a-0086-42eb-af5a-31d66c110188">
