### ISSUE TITLE
Tech debts - BE: Upgrade dependencies

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#1376]
BE: Upgrade dependencies

**Comment by RamRamez** [comment]
Some dependencies has been upgraded by @aminlatifi in PR #1271 and #1381
We still have this one remaining #1316

**Comment by aminlatifi** [comment]
It's a dependency that we must upgrade sooner or later

https://github.com/Giveth/impact-graph/issues/1389https://github.com/Giveth/impact-graph/issues/1389

**Comment by RamRamez** [comment]
We have also this one as a dependency upgrade
https://github.com/Giveth/impact-graph/issues/1405

**Comment by jainkrati** [comment]
@RamRamez @maryjaf pls confirm if this is resolved from 1405 or still need to be prioritized.

**Comment by RamRamez** [comment]
@jainkrati #1405 and #1316 is done, #1389 is still remaining

**Comment by jainkrati** [comment]
@RamRamez pls guide @lovelgeorge99 to take #1389 up
