### ISSUE TITLE
Exclude donations from purple list addresses in calculating matching fund

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1384]
As @laurenluz  said in the discord
> we should exclude from matching donations make from purple list addresses... but only if the purple list address corresponds to a project that is listed on the dapp (no draft/unlisted projects

**Comment by divine-comedian** [comment]
@mohammadranjbarz is this completed now? I can see the PR is merged.

**Comment by laurenluz** [comment]
yessir
