### ISSUE TITLE
> @divine-comedian We don't send any email or notification when project is published.

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1386]
> @divine-comedian We don't send any email or notification when project is published.

We should re-enable sending emails but not in-app notifications

_Originally posted by @divine-comedian in https://github.com/Giveth/impact-graph/issues/1296#issuecomment-1933019833_

**Comment by RamRamez** [comment]
Currently we are sending both email and in-app notification for project published, we should keep sending email but disable sending in-app notifications
