### ISSUE TITLE
Upgrade AdminJs dependency 

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1389]
AdminJs is on version 7.7.x, but we use v6.8.3
We must upgrade it as it's the backbone package for the admin panel.
It's worth noting that this dependency upgrade would include more than one package (adminjs, @adminjs/typeorm, ...)

**Comment by divine-comedian** [comment]
@RamRamez - this isn't finished yet, had lots of technical difficulties doing this issue - the latest version of adminJS can only be deployed on ESN but we are using commonJS - need to migrate app. 

He is still working on it

**Comment by divine-comedian** [comment]
@RamRamez what is the update on this issue?

**Comment by divine-comedian** [comment]
@RamRamez please provide an update to this issue

**Comment by divine-comedian** [comment]
will work on this after P0 issue
