### ISSUE TITLE
Check for new verified projects with Optimism addresses: Drop 7

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1393]
We'll need to query the db to check for verified projects that have added an OP address. You know the drill @mohammadranjbarz

Then I will compare against our previous data to find the new projects and setup the distribution of 25 OP each and set it up via our multisig

Once setup and sent we will inform the comms team to make external communication.

Here is the spreadsheet I've been keeping data in for reference
https://docs.google.com/spreadsheets/d/1pZ7SUtFcf6sNZ3A8fZXBvtDGAn_w21qD3WOaB4baDOE/edit?usp=sharing

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
related to https://github.com/Giveth/giveth-dapps-v2/issues/2637#issuecomment-1677422274

## Query

```
SELECT 
    pa."createdAt" as "walletAddressAddedTime",
    pa."projectId",
    pa.address,
    p.slug
FROM 
    project_address pa
JOIN 
    project p ON pa."projectId" = p.id
WHERE 
    pa."networkId" = 10 AND pa."isRecipient" = true AND p.verified = true AND p."statusId"=5
ORDER BY 
    pa."createdAt" ASC;
```

## Response 
[active-verified-projects-that-have-optimism-address-drop7.csv](https://github.com/Giveth/impact-graph/files/14549215/active-verified-projects-that-have-optimism-address-drop7.csv)
