### ISSUE TITLE
Filter Recurring Donations on My Profile page

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1398]
We need some endpoints to return the filtered recurring donations on this table associated with a given user.

There are two filters:
- [x] - type of token being donated (possible tokens are GIVx, USDCx, DAIx, OPx, ETHx) 
- [x] - status of recurring donation (Active or Ended)

![image](https://github.com/Giveth/impact-graph/assets/67759413/56ccfe59-d175-4764-9d23-df21f55a0829)

![image](https://github.com/Giveth/impact-graph/assets/67759413/5f943bab-a3f4-4ef2-ba7a-7d6adff4ab13)

**Comment by maryjaf** [comment]
These filters are shown correctly in my donation tab
<img width="898" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODRvQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5f4133a630ebf67965bc299ad85157d82ab4ddf8/image.png" alt="image.png" />
