### ISSUE TITLE
Endpoint for Archiving Recurring Donation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1399]
When a user wants to archive or end their recurring donation we should update the status on the back-end of this recurring donation to archived. We need an endpoint that can be used on the front-end to change the status of a recurring donation to 'archived' - will need https://github.com/Giveth/impact-graph/issues/1400 to have statuses in place/

When this recurring donation has status of archived we no longer show it on my profile page for user.

![image](https://github.com/Giveth/impact-graph/assets/67759413/5832a86a-9323-4ea0-a25c-9ca8bdf7443f)

**Comment by divine-comedian** [comment]
```
export const updateRecurringDonationQuery = `
       mutation (
        $projectId: Int!,
        $networkId: Int!,
        $currency: String!,
        $txHash: String
        $flowRate: String
        $anonymous: Boolean
        $status: String
        ) {
          updateRecurringDonationParams(
            projectId: $projectId
            networkId: $networkId
            currency:$currency
            txHash:$txHash
            anonymous:$anonymous
            flowRate:$flowRate
            status:$status
        ) {
            txHash
            networkId
            currency
            flowRate
            anonymous
            status
          }
      }
`;
```
Needs projectId, networkId currency & status.
Send status as ended to end recurring donation in DB @MohammadPCh

**Comment by maryjaf** [comment]
I had tested the "end recurring donation"scenarios and the status is changed correctly from ended to archive

**Comment by jainkrati** [comment]
can we close this as done @maryjaf ?
