### ISSUE TITLE
Retrieve Status of Recurring Donation

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1400]
We should have 5 statuses of recurring donation 

- Active (tx was successful and recurring donation is ongoing)
- Pending (tx is pending execution)
- Failed (tx failed)
- Ended (isFinished is true?)
- Archived (isFinished is true & we hide it from my profile page)

We should add these eligible statuses to a recurring donation and we'll also need an endpoint so the front-end can retrieve a recurring donation's status

**Comment by divine-comedian** [comment]
```
export const updateRecurringDonationQuery = `
       mutation (
        $projectId: Int!,
        $networkId: Int!,
        $currency: String!,
        $txHash: String
        $flowRate: String
        $anonymous: Boolean
        $status: String
        ) {
          updateRecurringDonationParams(
            projectId: $projectId
            networkId: $networkId
            currency:$currency
            txHash:$txHash
            anonymous:$anonymous
            flowRate:$flowRate
            status:$status
        ) {
            txHash
            networkId
            currency
            flowRate
            anonymous
            status
          }
      }
`;
```

**Comment by divine-comedian** [comment]
Only need to send projectId and networkId & currency & status - the rest are optional @MohammadPCh

**Comment by maryjaf** [comment]
- [ ] 1-

Please check below scenarios
-I have a donation record to Giveth in recurring donation table and its status is ended
-when I donate to a new project and set donating to giveth also, after completing donation flow
-A new record is added to donation table with "pending " status and after 10 mins it is changed to "Active" correctly
-The donation amount related to Giveth is updated but the status remains ended


![image](https://github.com/Giveth/impact-graph/assets/111529185/64071c60-5f54-4814-bb6d-fdd94c6df21f)
![image](https://github.com/Giveth/impact-graph/assets/111529185/53f15ee9-fd2d-42e4-ac9f-f1949c658785)

**Comment by divine-comedian** [comment]
I think is related to back-end changes not applying to donations made before the hotfix was applied by @CarlosQ96 about ~2 days ago. 

I think there's no practical solution for these old donation statuses - going forward any new donations should have the correct status, right @CarlosQ96 ?

**Comment by maryjaf** [comment]
> I think is related to back-end changes not applying to donations made before the hotfix was applied by @CarlosQ96 about ~2 days ago.
> 
> I think there's no practical solution for these old donation statuses - going forward any new donations should have the correct status, right @CarlosQ96 ?

I need to check the Giveth donation status and in this case I couldn't check it 
in general when I donated to a project and after a while the status changes to ended when I donated again to this project what should happen? a new record should be added or the status of same record changes to pending and. then active 
for Giveth I have only one record in donation table and its amount will be updated but status remains ended

**Comment by maryjaf** [comment]
- [x] 2- one question
When I Modify an active recurring donation and change the flow rate , its status should be changed to pending and then active or it should remain active?
now after modifying and changing flow rate it remains active

**Comment by divine-comedian** [comment]
@maryjaf 

## 1st point
I think any recurring donations made before the hotfixes in the BE (yesterday) are just permanently broken, we should end those streams on the superfluid dashboard and archive them from the FE. 

We should try to start from scratch as much as possible since trying to fix these statuses retroactively isn't the best use of time.

If you have made recurring donations from last night until now and are still encountering errors with recurring donations wrongly having a status of ended then we still have an issue. 

## 2nd point 
if the status remains active it is fine when updating the flow rate

**Comment by maryjaf** [comment]
I'm not sure which issue is more related to this problem 
If i'm wrong let me know to put the comment on right issue 

- [ ] 3-" total donated"  is shown zero in Recurring Donations table for active donations

![image](https://github.com/Giveth/impact-graph/assets/111529185/4a72735f-03ef-48be-be51-62160d1b63fe)

**Comment by divine-comedian** [comment]
> I'm not sure which issue is more related to this problem If i'm wrong let me know to put the comment on right issue
> 
> * [ ]  3-" total donated"  is shown zero in Recurring Donations table for active donations
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/317312879-4a72735f-03ef-48be-be51-62160d1b63fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjMwMjEsIm5iZiI6MTcxMTU2MjcyMSwicGF0aCI6Ii8xMTE1MjkxODUvMzE3MzEyODc5LTRhNzI3MzVmLTAzZWYtNDhiZS1iZTUxLTYyMTYwZDFiNjNmZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxODA1MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03N2ZiZWNlMjcxMWY3NDA2ZmQzYjFhMjU4NjVhNDYxZTE1Zjk0ZDViOTAwYWE4ZDMxZTAyYzBkYTkwYmYyODIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LeZH-T_0jlOXINGPBjWfFojakmV_XKhfOa8nHlGA3bw)

@maryjaf - Can you make a new issue for this one? 

If all other criteria has been met for the 5 statuses defined in the issue description then we can close this one.

**Comment by maryjaf** [comment]
I've tested pending, active, ended and archive status and all of them were ok 
which status remains to be tested? failed?
Is there any way to check failed status? @CarlosQ96

**Comment by CarlosQ96** [comment]
i am not sure how we can get the failed status yet. As there is no indication in the api

**Comment by divine-comedian** [comment]
How do we handle failed status for one-time donations? We have a badge for it

**Comment by maryjaf** [comment]
I had tested pending , active , ended and archive donation and they were ok 
but now there is a problem that status is shown pending 
after resolving this problem we could call this issue as Done

**Comment by CarlosQ96** [comment]
Actually @mohammadranjbarz cronjob includes this, in case the donation failed in the blockchain, we set it as finished True and status Failed. That is enough to cover the failed scenario
