### ISSUE TITLE
Migrate to ESLint

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#1405]
TSLint has been deprecated for more than four years and we need to migrate to ESLint

**Comment by RamRamez** [comment]
@maryjaf to test and verify
No functionality has been changed in this PR and no new functions has been added. Just general testing is needed like donating, creating a project, testing AdminJS functionality, etc

**Comment by maryjaf** [comment]
> @maryjaf to test and verify No functionality has been changed in this PR and no new functions has been added. Just general testing is needed like donating, creating a project, testing AdminJS functionality, etc

I'm not sure this problem is related to this change or not 
like as below video by tapping on "preview"or "publish" the loading icon is shown for both button  

https://github.com/Giveth/impact-graph/assets/111529185/d9281836-11de-40ac-a7d6-793f0c67f552

**Comment by RamRamez** [comment]
> > @maryjaf to test and verify No functionality has been changed in this PR and no new functions has been added. Just general testing is needed like donating, creating a project, testing AdminJS functionality, etc
> 
> I'm not sure this problem is related to this change or not like as below video by tapping on "preview"or "publish" the loading icon is shown for both button
> 
>  Screen.Recording.2024-03-22.at.12.39.58.AM.mov

@maryjaf No, it's not related to my PR, please create an issue for it on FE repo.

**Comment by maryjaf** [comment]
> Just general testing is needed like donating, creating a project, testing AdminJS functionality, etc

Thanks @RamRamez I've not seen problems in these flows on STG

**Comment by jainkrati** [comment]
@maryjaf is this resolved ?

**Comment by maryjaf** [comment]
Yeah I moved it to done
