### ISSUE TITLE
Send Emails for Superfluid Notifications 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1416]
Related to https://github.com/Giveth/notification-center/issues/62

We will add 4 new notifications to the notification center, we will need to trigger some emails when these events occur (depending on user notification settings)

- 1 month stream balance left warning 
- 1 week stream balance left warning 
- user runs out of stream balance
- project owner receives new recurring donation to their project (only if monthly USD value is greater than $20)
   - The project will only receive this email ONCE - when the recurring donation is created - we are able to know how much the user proposed to donate monthly, we can find the tokens and get the USD value. We should NOT send this every month, but only upon the first creation of the recurring donation.

## SuperFluid Balance Warning
We'll use one new activity to capture the first 3 events `act:cm:superfluid-balance-warning` with these variables: 
- `"bol:cm:isended"`: {( true/false - if stream has status of 'ended')}
- `"str:cm:criticaldate"` {1 month || 1 week || null}:
- `"str:cm:email"`: {emailAddress},
- `"str:cm:tokensymbol"`: {underlyingTokenSymbol}
- `"str:cm:userid"`: {userId}

for the balance warnings we will send the same email but replace the text in criticalDate. if the activity is sent with isEnded = true we will send a slightly different email.

## Recurring Donation Received
We should use the existing activity `act:cm:testing-donation-received` and append a new field to it that we send with each activity call

- `"bol:cm:isrecurringdonation"`: {true || false}

and modify existing fields we send: 

- `"str:cm:donationamount"`: {amountDonatedMonthly}
- `"str:cm:donationtoken"`: {underlyingTokenSymbol}

In our existing donation received Journey we will check the value of isRecurringDonation and send a slightly different email if the value = true

---

@RamRamez - @CarlosQ96 has prepared these notifications and you should sync with him on where they need to be triggered from.

**Comment by RamRamez** [comment]
The related PR is not merged yet and I can't start this issue, @CarlosQ96 please ping me when it's ready

**Comment by krmet** [comment]
@divine-comedian have these activities been added to Ortto?

**Comment by divine-comedian** [comment]
> @divine-comedian have these activities been added to Ortto?

Yep! These activites exist already - you can find them from the activities page in Ortto..

**Comment by RamRamez** [comment]
@maryjaf you can test "Recurring Donation Received" (for donations more than 20$ monthly).

SuperFluid Balance Warning is done on my side, but can't be tested yet because the required job to update donations status are not implemented yet. @CarlosQ96 is working on it.

**Comment by maryjaf** [comment]
> @maryjaf you can test "Recurring Donation Received" (for donations more than 20$ monthly)

Thanks @RamRamez I've received an email for received donation more than 20 $
<img width="1043" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/48ee4a33-4e64-42b5-a6c9-579cffff27da">

**Comment by maryjaf** [comment]
> SuperFluid Balance Warning is done on my side, but can't be tested yet because the required job to update donations status are not implemented yet. @CarlosQ96 is working on it.

For other items of this issue, it seems this issue should be moved back to inprogress and assigned to Carlos 
@MoeNick

**Comment by MoeNick** [comment]
@RamRamez 

- [ ] Balance Warning

**Comment by divine-comedian** [comment]
FYI comms issue is here to craft the emails for the notifications - https://www.notion.so/giveth/Superfluid-Email-Journeys-8d4ea008b8ef4cd985e92adf00926ed2

@krmet is assigned.

**Comment by RamRamez** [comment]
For balance warning no emails are sent because Ortto template is missing and for donation received we send normal donation template is sent RN.

The impact-graph and notification-center side for this issue is done.

**Comment by jainkrati** [comment]
Staging is stable now. @RamRamez @maryjaf pls progress on this issue

**Comment by maryjaf** [comment]
> Staging is stable now. @RamRamez @maryjaf pls progress on this issue

I've tested notification and reported the test result on https://github.com/Giveth/notification-center/issues/62 
but for balance  email Ortto template is missing  and it should be ready by marketing team, am I right? @RamRamez

**Comment by RamRamez** [comment]
I tested and it's working but we have some problems:
1. tokenSymbol is passed from notification-center to Ortto activity (I rechecked it) but it's not passed to Ortto journey for some reason
2. I got the "month" email but should have got the "week" email.
3. I got the email in Spam folder (Outlook). Not sure if we can do anything about it.
![image](https://github.com/Giveth/impact-graph/assets/73441857/5bb7fa44-76a4-4091-ad25-254c831e615d)


We need @divine-comedian and @krmet for No.1 and 2

**Comment by divine-comedian** [comment]
@RamRamez - the attribute tags in the email content was misconfigured, I've fixed it and should be working properly now. 

I received the test email in my inbox properly.

### Regarding `donation received` 

We should ensure that you're sending the boolean value `isRecurringDonation` correctly (true if recurring donation, false if regular donation). I also noticed the activity was not capturing the userId so I've added that field in too now, we should make sure we send it (user ID of project owner). 

Lastly, in this we capture the `donationAmount` and use it in the email - we should send this as the monthly amount, not the amount per second.

- [ ] isRecurringDonation sent correctly 
- [ ] send userId in activity 
- [ ] set donationAmount as monthly amount

@maryjaf - there is a different email you should receive if it is a recurring donation, please check it now I've made the necessary updates to the ortto journey.

**Comment by maryjaf** [comment]
- [x] 1-

I've received notification for "runs out in 1 month", **but I haven't received any email yet**
0xA1179f64638adb613DDAAc32D918EB6BEB824104
I've also checked my spam emails 
Please check it @RamRamez 

![image](https://github.com/Giveth/impact-graph/assets/111529185/1b50ad79-5a16-4a1d-9797-7c100e34f9ab)

**Comment by maryjaf** [comment]
- [ ] 2-

I've received email related to recurring donation more than 20 $, 
by tapping on "[VIEW RECURRING DONATIONS](https://pilotl.ink/r?i=ap2-giveth&e=cbrzowt4qzc722arjaadazq6thxpngz24y5duoictiigalfd3systawvdthzu6qsapkjnp6lqjy457kzqnitk5n2qnmww74haprdo4cvc6dq2skjw4lwwl65ffkw5wtfrtrhimdrzspodj44trtifxuvy7lkm45e2n3eyol44wnihhmpaqyvoim5aibaxdnhjeda)" button, user is redirected to "all donation" tab 
Is this accepted ? I think it would be better based on the name of button the user be redirected to "recurring donation" tab

![image](https://github.com/Giveth/impact-graph/assets/111529185/1f65d094-a8f1-4af9-b81e-0000df9be164)
@RamRamez @divine-comedian

**Comment by divine-comedian** [comment]
@maryjaf - I don't understand which page you're referring to - do you have an example link from staging?

**Comment by maryjaf** [comment]
> @maryjaf - I don't understand which page you're referring to - do you have an example link from staging?

All Donation tab
https://staging.giveth.io/project/test101000?tab=donations
![image](https://github.com/Giveth/impact-graph/assets/111529185/d6a90645-73f7-4d05-92d1-d4e788f1ffc4)

**Comment by divine-comedian** [comment]
@maryjaf - I checked for that and there is no route/URL for that recurring donation tab, I agree it would be better but we need to skip it for now.
