### ISSUE TITLE
Test cases fail

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1425]
Action sample:  https://github.com/Giveth/impact-graph/actions/runs/8407975912/job/23023873112

This is blocker for deployment so I should fix it ASAP

**Comment by mohammadranjbarz** [comment]
It returns
 
```
 {
  "status": "0",
  "message": "Query Timeout occured. Please select a smaller result dataset",
  "result": null
}
```

When running draftDonationServices.test and for networkId 100

**Comment by mohammadranjbarz** [comment]
@geleeroyale  knows about it, we talked in discord, so I will assign it to Kay and Moeshehab to update us here

**Comment by geleeroyale** [comment]
This should work again - the maintenance has stopped and I can successfully query the API endpoint from your example:

<img width="1469" alt="image" src="https://github.com/Giveth/impact-graph/assets/317685/1796386d-8724-4e7a-a9b1-91a01dd327c5">

**Comment by mohammadranjbarz** [comment]
> This should work again - the maintenance has stopped and I can successfully query the API endpoint from your example:
> 
> <img alt="image" width="1469" src="https://private-user-images.githubusercontent.com/317685/316521989-1796386d-8724-4e7a-a9b1-91a01dd327c5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzU5NDEsIm5iZiI6MTcxMTM3NTY0MSwicGF0aCI6Ii8zMTc2ODUvMzE2NTIxOTg5LTE3OTYzODZkLTg3MjQtNGU3YS1hOWIxLTkxYTAxZGQzMjdjNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxNDA3MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZhZDdiNTg2NjNiYjRlMGMzMWI3OGQwZWI3MDhkOThhN2QwMGEzOWQ4ZGRkY2E0Y2I5ZTkzNzJkZWE5Zjk1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M2ccbuX-rGNJenTS3s4sF7FY_KR6C0b5LuZPODlW0oc">

Thanks @geleeroyale for letting us know, I brought back test cases and pushed to staging

**Comment by jainkrati** [comment]
can we close this @mohammadranjbarz @mhmdksh

**Comment by mhmdksh** [comment]
Yeah this can be closed now @jainkrati it has been resolved
