### ISSUE TITLE
Update recurring donation status with blockchain network data

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1426]
It was missing and the function was empty so all recurringDonations remain **pending**

**Comment by divine-comedian** [comment]
When user creates recurring donation with the blockchain to change status from active to pending, should fix pending problem not the ended problem.

**Comment by maryjaf** [comment]
- [ ] 1-

Please check below scenarios 
-I have a donation record to Giveth in recurring donation table and its status is ended
-when I donate to a new project and set donating to giveth also, after completing donation flow 
-A new record is added to donation table with "pending " status and after 10 mins it is changed to "Active" correctly
-The donation amount  related to Giveth is updated **but the status remains ended**

<img width="1347" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/79b0a51e-fc30-432f-8a32-c03fecf0365d">

<img width="1275" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/9d26e0d4-b492-4d7d-8803-1bf725e8aabc">

**Comment by mohammadranjbarz** [comment]
@maryjaf  This scenario is just for an specific case, change pending status to active, for the ended problem and the price I believe @CarlosQ96  is working on that

**Comment by maryjaf** [comment]
> @maryjaf This scenario is just for an specific case, change pending status to active

Thanks @mohammadranjbarz change pending to active is ok and there is no problem about this

**Comment by divine-comedian** [comment]
@maryjaf - Can you follow up the Ended/Active issue here? 
https://github.com/Giveth/impact-graph/issues/1400
