### ISSUE TITLE
Receive & Save contact information in project verification form

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1436]
In https://github.com/Giveth/giveth-dapps-v2/issues/3910 we will allow users to provide us with specific contact information on platforms if we need to contact them directly for any issue. 

The verification form will take in these fields: 

- telegram handle
- discord handle
- twitter handle
- whatsApp number

we should allow this information to be received in our back-end and included in the verification form info we save. 

This information should then be accessible through the AdminJS interface.

**Comment by jainkrati** [comment]
@Meriem-BM pls do this with guidance from @RamRamez for FE and @mohammadranjbarz for BE

**Comment by Meriem-BM** [comment]
@mohammadranjbarz, we won't need to make any changes because the social network links are stored as an array of objects containing the name and URL. The frontend is successfully saving this information.

While working on this issue https://github.com/Giveth/giveth-dapps-v2/issues/3910 it was being saved successfully after we modified the social fields.

However, I need confirmation if this implementation already:
- This information should then be accessible through the AdminJS interface.

**Comment by mohammadranjbarz** [comment]
Thanks @Meriem-BM 
I just checked adminJs and saw your social contact info (Whatsapp, ..), you can see it yourself
https://impact-graph.serve.giveth.io/admin/resources/ProjectVerificationForm/records/346/show
So you are right, you don't need to do something in BE side

**Comment by divine-comedian** [comment]
@mohammadranjbarz @Meriem-BM - What is the next step here? Is it ready for QA?

**Comment by Meriem-BM** [comment]
Yes, and this PR https://github.com/Giveth/giveth-dapps-v2/pull/4000 related to this https://github.com/Giveth/giveth-dapps-v2/issues/3910 was approved as well.

**Comment by divine-comedian** [comment]
@maryjaf 

### For testing: 
- go through project verification form for an existing or new project 
- get to page for adding social contact information
- add information (should be fake)
- submit verification
- check in adminJS if your contact details appear correctly

**Comment by maryjaf** [comment]
There is record for telegram and whatsApp in verification flow 
should these two field be added? 

<img width="1371" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHh3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--71c99a2ec6ae5e51069f51bd5cbec585c12e97ff/image.png" alt="image.png" />

<img width="1167" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDV3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dcd5ad60d1b6758a9c7cbbb27db10c8aa0ff91a9/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
Thanks @Meriem-BM 
These fields are added correctly in "project contact" in project page 
https://impact-graph.serve.giveth.io/admin/resources/ProjectVerificationForm/records/350/show

<img width="1143" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0Z3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cd5147aeee2be93bd4fca90da71dbf3dbe7f2ac/image.png" alt="image.png" />

<img width="1121" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN0J3QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08f71d41400acdadce9a072ba75721aa4aa8b0ea/image.png" alt="image.png" />
