### ISSUE TITLE
" total donated"  is shown zero in Recurring Donations table for active donations

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1437]
- [ ] 3-" total donated"  is shown zero in Recurring Donations table for active donations

![image](https://github.com/Giveth/impact-graph/assets/111529185/4a72735f-03ef-48be-be51-62160d1b63fe)

_Originally posted by @maryjaf in https://github.com/Giveth/impact-graph/issues/1400#issuecomment-2022944580_

**Comment by maryjaf** [comment]
I've tested again and it is  shown zero for my new avtive donation

<img width="1043" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/b562ceee-db75-4fdb-b7eb-b87e3010625e">

**Comment by maryjaf** [comment]
-Total donated is shown 0 in user page ,please take a look @CarlosQ96 
public view:
<img width="1302" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/30754201-9a72-40d2-9048-80fda07ab661">
owner view:
<img width="1389" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/b02bc236-3f18-42bb-a8f0-8edb2fcc0b4e">

but now in project page "total donated" and "usd amount" are shown but I'm not sure the showing amount is accurate or not I should check this 
and for "total donated", $ and GIV are shown together 

<img width="1293" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/db0d4c6f-9070-47f7-bdbb-28579b394553">

**Comment by CarlosQ96** [comment]
The totals are not accurate because the api return 0 and sepolia is not supported by coingecko or monoswap library.
We treat them as stable coins.

**Comment by maryjaf** [comment]
> but now in project page "total donated" and "usd amount" are shown but I'm not sure the showing amount is accurate or not I should check this and for "total donated", $ and GIV are shown together
> 
> <img alt="image" width="1293" src="https://private-user-images.githubusercontent.com/111529185/318697739-db0d4c6f-9070-47f7-bdbb-28579b394553.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxNTIwOTUsIm5iZiI6MTcxMjE1MTc5NSwicGF0aCI6Ii8xMTE1MjkxODUvMzE4Njk3NzM5LWRiMGQ0YzZmLTkwNzAtNDdmNy1iZGJiLTI4NTc5YjM5NDU1My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QxMzQzMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xMmE2MmE2ZDk0OTMyOGQ1ZjJkZWM3NTlhNjEyMDdiODEyMjIzMWU2NDFmMDFhODIwZjQ4NDAzMmM4YzA4YmNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5uaZEgsfRYCy1sGgcnCNDIIds2HO7j5ATtVGp26Qmy8">

this is shown 0 again 
(in my previous tests the"total donated" field was ok in project donation page and was shown 0 in user page but now 
in all table is shown 0 )

<img width="1301" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/782a464b-0831-4947-90c8-dbd424f97802">
@CarlosQ96

**Comment by CarlosQ96** [comment]
Thanks Ill check

**Comment by maryjaf** [comment]
https://staging.giveth.io/project/testupdate1000?tab=donations
https://staging.giveth.io/project/test-image-type?tab=donations
https://staging.giveth.io/account?tab=recurring-donations
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf About this one, there is an strange thing, some streams for this recurring donation has been `ETH` and some of them `GIV` so the amount donated is not equal to totalDonatedUsd value
(@divine-comedian  I guess we should not allow donors to change the currency of recurring donations, am I right?)
<img width="1389" alt="Screenshot 1403-01-16 at 12 54 50 in the afternoon" src="https://github.com/Giveth/impact-graph/assets/9850545/8a763c4a-28d5-41b4-bb10-64d2dd0ded99">

<img width="371" alt="Screenshot 1403-01-16 at 12 38 20 in the afternoon" src="https://github.com/Giveth/impact-graph/assets/9850545/6f65c4d7-62e5-40e0-af96-5a269d493a34">

**Comment by maryjaf** [comment]
> (@divine-comedian I guess we should not allow donors to change the currency of recurring donations, am I right?)

the user couldn't be able to change  currency of recurring donations in modifying flow, only the amount could be changed 
<img width="571" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/5d730dd7-b47f-4e5f-a5b2-844d92ca5615">

**Comment by maryjaf** [comment]
Update :
 @CarlosQ96 @mohammadranjbarz 

now the total donated is shown in user and project page for new recurring donations but it seems the showing number is wrong 

user page
<img width="1340" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/da0c1aa4-d00a-4610-9347-e6e2330ece2b">
project page:
<img width="1306" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/3e919d1f-615b-47ec-94d9-e0b61513cd6e">

**Comment by MoeNick** [comment]
@CarlosQ96 seems QA put a comment, would you pls check?

**Comment by maryjaf** [comment]
> Update : @CarlosQ96 @mohammadranjbarz
> 
> now the total donated is shown in user and project page for new recurring donations but it seems the showing number is wrong

-Total donated for GIV donations is still shown zero 
( for ETH donations isn't shown 0 but the amount isn't correct )

<img width="806" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/27a0ea20-049e-4ba4-9164-96b125da22f9">

![image](https://github.com/Giveth/impact-graph/assets/111529185/23f6afc2-5db5-4a18-959f-f6e4077730bb)

**Comment by maryjaf** [comment]
I've tested again after last changes @mohammadranjbarz @CarlosQ96  

<img width="1355" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/c922ae35-5bb1-4080-827a-92dd0ceb8453">

- Total donated has a value for both GIV and ETH donations 
- [x] Some of values are shown like this  6.214312e-7 and should be checked 
- [x] I am not sure about the correctness of the displayed value, can you please guide how we can calculate and make sure it is correct
