### ISSUE TITLE
Add a field to can get archived and not archived recurring donations separedly

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1439]
As I talked witch @MohammadPCh we docided to add a field named `isArchived` to recurringDonation entity, instead of having an `archived` status

JFYI @jainkrati  @CarlosQ96

**Comment by mohammadranjbarz** [comment]
@maryjaf  I think you already have tested this, but will appreciate if you can update this issue as well

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz the problem related ti archive donations has been resolved
