### ISSUE TITLE
Bug in showing recurring donations in public view of user page 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1453]
My user has 4 recurring donations 
3 active and 1 archive 
I see below pic in my recurring donation

<img width="1338" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/c36e8bfc-961d-4173-807b-fbc54b5a127f">

but in **user page (public view)** only 2 recurring donations are shown 

https://staging.giveth.io/user/0xa1179f64638adb613ddaac32d918eb6beb824104?tab=recurring-donations
<img width="1357" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/0f75ffc4-2d57-4a07-b4a4-c14d2d66ff3d">

I've checked this with cc: @MohammadPCh and he said this should be fixed by backend 
cc: @jainkrati @mohammadranjbarz 

expected result:
in **owner view** should be shown all of recurring donations (active, ended, archive, failed, pending)
in **public view ** should be shown all Active recurring donations 
@divine-comedian @MoeNick

**Comment by MoeNick** [comment]
In Public View | profile Page, The backend should filter all recurring donations based on 
1- status: Active
2- Owner

@mohammadranjbarz can you tale a look?

**Comment by mohammadranjbarz** [comment]
> My user has 4 recurring donations 3 active and 1 archive I see below pic in my recurring donation
> 
> <img alt="image" width="1338" src="https://private-user-images.githubusercontent.com/111529185/319560075-c36e8bfc-961d-4173-807b-fbc54b5a127f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM2NDQsIm5iZiI6MTcxMjQ4MzM0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzE5NTYwMDc1LWMzNmU4YmZjLTk2MWQtNDE3My04MDdiLWZiYzU0YjVhMTI3Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMjAxZTA1Zjk5YjNhYTljNjk0YTZkMjZlMDFlN2M0YjgzODRiZDIwODQ1MTk1YTJkZGMxZjdhOGE1NDY0NTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nHEDpXyAjbAE-6cWAzMqPhTRosivrl4BTWNGLu3AlfM">
> but in **user page (public view)** only 2 recurring donations are shown
> 
> https://staging.giveth.io/user/0xa1179f64638adb613ddaac32d918eb6beb824104?tab=recurring-donations <img alt="image" width="1357" src="https://private-user-images.githubusercontent.com/111529185/319561450-0f75ffc4-2d57-4a07-b4a4-c14d2d66ff3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI0ODM2NDQsIm5iZiI6MTcxMjQ4MzM0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzE5NTYxNDUwLTBmNzVmZmM0LTJkNTctNGEwNy1iNGE0LWMxNGQyZDY2ZmYzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QwOTQ5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wYzZjNTRlNjdkODJjNmM2OWQ2NDc1ZGUyZjg0NWE4MzkxMWU2NWI5YWNmN2MxM2IyYWNmZDdjM2ZiOWE0MTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pu8PfmrLEKKcRcJGbs1PhGgVuXt5_56slLu_0KU6r4I">
> 
> I've checked this with cc: @MohammadPCh and he said this should be fixed by backend cc: @jainkrati @mohammadranjbarz
> 
> expected result: in **owner view** should be shown all of recurring donations (active, ended, archive, failed, pending) in **public view ** should be shown all Active recurring donations @divine-comedian @MoeNick

@maryjaf
It seems this problem is fixed now(I mean amount and usd value in recurring donation table) , can you check it especially for new donations

<img width="947" alt="Screenshot 1403-01-19 at 5 13 16 in the afternoon" src="https://github.com/Giveth/impact-graph/assets/9850545/07055c9e-7566-431d-8c24-1a04bdb4a963">



FYI @moenick

**Comment by maryjaf** [comment]
> t seems this problem is fixed now(I mean amount and usd value in recurring donation table) , can you check it especially for new donations

all of my active donations isn't shown in public view of user page and I don't understand why , please take a look @mohammadranjbarz 

owner view:
<img width="1257" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/d0f794c2-3603-489c-a992-f9b06a419404">

public view:
I see only  2 donations of GIV token 
<img width="1249" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/d964cdd6-b827-4243-89a9-08da7223c74a">

**Comment by mohammadranjbarz** [comment]
> > t seems this problem is fixed now(I mean amount and usd value in recurring donation table) , can you check it especially for new donations
> 
> all of my active donations isn't shown in public view of user page and I don't understand why , please take a look @mohammadranjbarz
> 
> owner view: <img alt="image" width="1257" src="https://private-user-images.githubusercontent.com/111529185/320287273-d0f794c2-3603-489c-a992-f9b06a419404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDM1NDQsIm5iZiI6MTcxMjUwMzI0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwMjg3MjczLWQwZjc5NGMyLTM2MDMtNDg5Yy1hOTkyLWY5YjA2YTQxOTQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxNTIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzk3YjI0YTE2MThjNWVhN2Q2OWQ1YmRiYjQxMjUyMDhiM2RiZDhhZDk2ZThkMzQyNDRlM2ZjNGYzN2I3MmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.enwzqbNNWm45wlh0SkDTskb7Aiyn98ObMfZ10aWrpAk">
> 
> public view: I see only 2 donations of GIV token <img alt="image" width="1249" src="https://private-user-images.githubusercontent.com/111529185/320287935-d964cdd6-b827-4243-89a9-08da7223c74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDM1NDQsIm5iZiI6MTcxMjUwMzI0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwMjg3OTM1LWQ5NjRjZGQ2LWI4MjctNDI0My04OWE5LTA4ZGE3MjIzYzc0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxNTIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTQ1ZTE0YzBhMjQwZDIyZTc5ZTEwZWYxNjM3NzcyYmNmZmQ1ZWMzNWEzMzZhNDMwNTI1NDk0MmQ2MzkwMzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DvfLDwqDqhASCZ4KiccVSL4IKlYjwaGHukNmABj1l2o">

Can you give me your wallet address to check in DB?
I guess some of your donations are `anonymous` so we dont show them in owner view

**Comment by maryjaf** [comment]
> > > t seems this problem is fixed now(I mean amount and usd value in recurring donation table) , can you check it especially for new donations
> > 
> > 
> > all of my active donations isn't shown in public view of user page and I don't understand why , please take a look @mohammadranjbarz
> > owner view: <img alt="image" width="1257" src="https://private-user-images.githubusercontent.com/111529185/320287273-d0f794c2-3603-489c-a992-f9b06a419404.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDM1NDQsIm5iZiI6MTcxMjUwMzI0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwMjg3MjczLWQwZjc5NGMyLTM2MDMtNDg5Yy1hOTkyLWY5YjA2YTQxOTQwNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxNTIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzk3YjI0YTE2MThjNWVhN2Q2OWQ1YmRiYjQxMjUyMDhiM2RiZDhhZDk2ZThkMzQyNDRlM2ZjNGYzN2I3MmQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.enwzqbNNWm45wlh0SkDTskb7Aiyn98ObMfZ10aWrpAk">
> > public view: I see only 2 donations of GIV token <img alt="image" width="1249" src="https://private-user-images.githubusercontent.com/111529185/320287935-d964cdd6-b827-4243-89a9-08da7223c74a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDM1NDQsIm5iZiI6MTcxMjUwMzI0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzIwMjg3OTM1LWQ5NjRjZGQ2LWI4MjctNDI0My04OWE5LTA4ZGE3MjIzYzc0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxNTIwNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMTQ1ZTE0YzBhMjQwZDIyZTc5ZTEwZWYxNjM3NzcyYmNmZmQ1ZWMzNWEzMzZhNDMwNTI1NDk0MmQ2MzkwMzAwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DvfLDwqDqhASCZ4KiccVSL4IKlYjwaGHukNmABj1l2o">
> 
> Can you give me your wallet address to check in DB? I guess some of your donations are `anonymous` so we dont show them in owner view

https://staging.giveth.io/user/0xa1179f64638adb613ddaac32d918eb6beb824104

**Comment by mohammadranjbarz** [comment]
The user has 5 active donations that 3 of them are anonymous so owner would see 5 active recurring donations and in public view we show 2 donations.
There is a rare case that we return 4 donations for this case I checked te curl and saw that frontend send `active:false, ended:false` in this case I ignore finish status filter and return all active/ended recurring donations for user, so we return ended recurring donations as well so instead of 2 donations we return 4. @MohammadPCh Now you tell me, either you investigate why frontend send active:false, ended:false or I can don't ignore finishStatus but will return zero donation in this case, so please tell me


This is the curl for 4 donations case

```
curl 'https://impact-graph.serve.giveth.io/graphql' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNBZGRyZXNzIjoiMHhmNTc3QWU4Yjk3ZDgzOUI5YzA1MjJBNjIwMjk5REMwODc5MmM3MzhjIiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA1LTA3VDExOjUwOjQ3LjQzNFoiLCJqdGkiOiIxNzEyNDkwNjQ3NDM0LTY0N2RhY2UwMmIiLCJpYXQiOjE3MTI0OTA2NDcsImV4cCI6MTcxNTA4MjY0Nn0.uvMu_-cdbP2D6iR_f1Kv4gBbbnirT00ZiiFBESEebFE' \
  -H 'authversion: 2' \
  -H 'content-type: application/json' \
  -H 'origin: https://staging.giveth.io' \
  -H 'referer: https://staging.giveth.io/' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'wallet-address: 0xf577ae8b97d839b9c0522a620299dc08792c738c' \
  --data-raw $'{"operationName":"fetchRecurringDonationsByUserId","variables":{"userId":419,"take":10,"skip":0,"orderBy":{"field":"createdAt","direction":"DESC"},"finishStatus":{"active":false,"ended":false},"filteredTokens":[],"includeArchived":false},"query":"query fetchRecurringDonationsByUserId($take: Int, $skip: Int, $status: String, $orderBy: RecurringDonationSortBy, $finishStatus: FinishStatus, $userId: Int\u0021, $filteredTokens: [String\u0021], $includeArchived: Boolean) {\\n  recurringDonationsByUserId(\\n    take: $take\\n    skip: $skip\\n    orderBy: $orderBy\\n    userId: $userId\\n    status: $status\\n    finishStatus: $finishStatus\\n    filteredTokens: $filteredTokens\\n    includeArchived: $includeArchived\\n  ) {\\n    recurringDonations {\\n      id\\n      txHash\\n      networkId\\n      flowRate\\n      currency\\n      anonymous\\n      status\\n      isArchived\\n      amountStreamed\\n      project {\\n        id\\n        title\\n        slug\\n        anchorContracts {\\n          address\\n          isActive\\n        }\\n      }\\n      finished\\n      createdAt\\n    }\\n    totalCount\\n  }\\n}"}'
```

<img width="1111" alt="Screenshot 1403-01-20 at 10 46 24 in the morning" src="https://github.com/Giveth/impact-graph/assets/9850545/87fb30f2-c2e4-4963-afb3-17fabde12e04">

**Comment by maryjaf** [comment]
ُThanks @mohammadranjbarz @MohammadPCh this problem has been resolved and now the showing records in recurring donation for both public view and owner view of user page is correct
