### ISSUE TITLE
Document all existing roles and permissions of admin panel

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1459]
- [x] Document all roles accesses
- [x] Write test cases for all role and permissions to make sure everything works properly

You can see the roles and permissions here, so extract the data from there
https://github.com/Giveth/impact-graph/blob/staging/src/server/adminJs/adminJsPermissions.ts

**Comment by Meriem-BM** [comment]
![Screenshot 2024-04-10 at 13 35 59 (2)](https://github.com/Giveth/impact-graph/assets/59566186/51a0d03d-7647-487a-99f7-d2aabf1ce0a3)

**Comment by mohammadranjbarz** [comment]
@maryjaf  For the test cases you dont need to anything, I have checked that, but it's good if you can check this documentation to make sure the table is reflecting the behaviour of our admin panel correctly
https://github.com/Giveth/impact-graph/blob/staging/docs/adminPermissions.md#resources-and-permissions

**Comment by maryjaf** [comment]
> @maryjaf For the test cases you dont need to anything, I have checked that, but it's good if you can check this documentation to make sure the table is reflecting the behaviour of our admin panel correctly https://github.com/Giveth/impact-graph/blob/staging/docs/adminPermissions.md#resources-and-permissions

Syibi, Project fraud and recurring donation pages should be added 
And these access about project should be added for qf manager  role 
-add project to QF round
-remove project from QF round
-list project

**Comment by Meriem-BM** [comment]
@maryjaf can you check now

**Comment by maryjaf** [comment]
> > https://github.com/Giveth/impact-graph/blob/staging/docs/adminPermissions.md#resources-and-permissions
> 
> Syibi, Project fraud and recurring donation pages should be added And these access about project should be added for qf manager role -add project to QF round -remove project from QF round -list project

There is no change in  this documentation > > https://github.com/Giveth/impact-graph/blob/staging/docs/adminPermissions.md#resources-and-permissions

**Comment by Meriem-BM** [comment]
Yes @maryjaf , I didn't update the documentation yet, just wanted to resolve the blockage you had,  will update as soon as I'm on my personal Machine.

**Comment by Meriem-BM** [comment]
Hey @maryjaf I think the better approach to solve this permissions issue is by focusing on the documentation first, once approved, will proceed to implementing the modifications based on that, especially that I'm just getting to understand this part.

I will provide the permissions table here and let me know if there's something to change.

| Page                       | admin                                                                                                                                                                                          | campaignManager       | reviewer                                                                                                                                                | operator                                                                                                                                                | qfManager                                                |
|----------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------|
| Users                      | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Organization               | list, show                                                                                                                                                                                     | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project status history     | list, show                                                                                                                                                                                     | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Campaign                   | list, new, show, edit, delete                                                                                                                                                                  | list, new, show, edit | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| QF Round                   | list, new, show, edit, returnAllDonationData                                                                                                                                                   | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | list, new, show, edit, returnAllDonationData             |
| QF Round History           | list, show, edit, delete, bulkDelete, updateQfRoundHistories                                                                                                                                   | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project Status Reason      | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project Address            | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project Status             | list, show, edit                                                                                                                                                                               | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project                    | list, show, edit, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject, addToQfRound, removeFromQfRound | list, show            | list, show, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject | list, show, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject | list, show, listProject, addToQfRound, removeFromQfRound |
| Third Party Project Import | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Featured Update            | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Donation                   | list, new, show, edit, delete, exportFilterToCsv                                                                                                                                               | list, show            | list, show, exportFilterToCsv                                                                                                                           | list, show, exportFilterToCsv                                                                                                                           | -                                                        |
| Project Verification Form  | list, show, edit, delete, verifyProject, makeEditableByUser, rejectProject, verifyProjects, rejectProjects                                                                                     | list, show            | list, show, edit, delete, verifyProject, makeEditableByUser, rejectProject, verifyProjects, rejectProjects                                              | list, show                                                                                                                                              | -                                                        |
| Main Category              | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Category                   | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Broadcast Notification     | list, new, show                                                                                                                                                                                | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project Update             | list, show, addFeaturedProjectUpdate                                                                                                                                                           | list, show            | list, show                                                                                                                                              | list, show, addFeaturedProjectUpdate                                                                                                                    | -                                                        |
| Sybil                      | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Project Fraud              | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |
| Recurring donation         | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                        |

**Comment by maryjaf** [comment]
Based on this issue https://github.com/Giveth/impact-graph/issues/1471,  the QF manager role should has full access on Sybil and Project Fraud page
@Meriem-BM

**Comment by Meriem-BM** [comment]
That's right @maryjaf, here is the update.

|            Page            |                                                                                              admin                                                                                             |    campaignManager    |                                                                         reviewer                                                                        |                                                                         operator                                                                        |                               qfManager                              |
|:--------------------------:|:----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|:---------------------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|:-------------------------------------------------------------------------------------------------------------------------------------------------------:|:--------------------------------------------------------------------:|
| Users                      | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Organization               | list, show                                                                                                                                                                                     | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Project status history     | list, show                                                                                                                                                                                     | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Campaign                   | list, new, show, edit, delete                                                                                                                                                                  | list, new, show, edit | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| QF Round                   | list, new, show, edit, returnAllDonationData                                                                                                                                                   | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | list, new, show, edit, returnAllDonationData (export to spreadsheet) |
| QF Round History           | list, show, edit, delete, bulkDelete, updateQfRoundHistories, relateDonationsWithDistributedFunds                                                                                                                                   | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | list, show, updateQfRoundHistories                                   |
| Project Status Reason      | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Project Address            | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Project Status             | list, show, edit                                                                                                                                                                               | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Project                    | list, show, edit, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject, addToQfRound, removeFromQfRound | list, show            | list, show, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject | list, show, exportFilterToCsv, listProject, unlistProject, verifyProject, rejectProject, revokeBadge, activateProject, deactivateProject, cancelProject | list, show, listProject, addToQfRound, removeFromQfRound             |
| Third Party Project Import | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Featured Update            | list, new, show, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Donation                   | list, new, show, edit, delete, exportFilterToCsv                                                                                                                                               | list, show            | list, show, exportFilterToCsv                                                                                                                           | list, show, exportFilterToCsv                                                                                                                           | -                                                                    |
| Project Verification Form  | list, show, edit, delete, verifyProject, makeEditableByUser, rejectProject, verifyProjects, rejectProjects                                                                                     | list, show            | list, show, edit, delete, verifyProject, makeEditableByUser, rejectProject, verifyProjects, rejectProjects                                              | list, show                                                                                                                                              | -                                                                    |
| Main Category              | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Category                   | list, new, show, edit                                                                                                                                                                          | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Broadcast Notification     | list, new, show                                                                                                                                                                                | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
| Project Update             | list, show, addFeaturedProjectUpdate                                                                                                                                                           | list, show            | list, show                                                                                                                                              | list, show, addFeaturedProjectUpdate                                                                                                                    | -                                                                    |
| Sybil                      | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | list, show, new, edit, delete, bulkDelete                            |
| Project Fraud              | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | list, show, new, edit, delete, bulkDelete                            |
| Recurring donation         | list, show, new, edit, delete, bulkDelete                                                                                                                                                      | list, show            | list, show                                                                                                                                              | list, show                                                                                                                                              | -                                                                    |
