### ISSUE TITLE
Webservice for archived qf rounds

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1462]
We require this information to be fetched from the backend. Could you please provide it?

We need to retrieve all ended (archived) QF rounds with the following details:

1. Slug
2. Name
3. Matching pool
4. Total donations amount
5. Unique donors
6. Start date
7. End date

Additionally, we need to sort them by the following criteria:

- Matching pool
- Number of unique donors
- Newest
- Oldest

Thank you.
<img width="1214" alt="Screenshot 2024-04-09 at 1 58 29 PM" src="https://github.com/Giveth/giveth-dapps-v2/assets/17097576/e10c50cd-7688-4192-96b6-640341d37d9d">
cc: @laurenluz @jainkrati

_Originally posted by @MohammadPCh in https://github.com/Giveth/giveth-dapps-v2/issues/3748#issuecomment-2044676561_

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 Can you pick this?

**Comment by RamRamez** [comment]
> @CarlosQ96 Can you pick this?

I'm on it

**Comment by maryjaf** [comment]
Could you please add more data on this issue how can I test it ? @RamRamez

**Comment by RamRamez** [comment]
@maryjaf I think it's better to test it with the FE issue at the same time
https://github.com/Giveth/giveth-dapps-v2/issues/3748
