### ISSUE TITLE
implement draft recurring donations service for make sure not miss any donation

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#1463]
Related to https://github.com/Giveth/giveth-dapps-v2/issues/3974

**Comment by divine-comedian** [comment]
We should make sure we are checking not only when a recurring donation is created but also when it is updated.

**Comment by MohammadPCh** [comment]
@mohammadranjbarz, please note that when updating, we must be able to create draft recurring donations even without having the 'recurringDonationId'. Thanks

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  Your desired changes has been deployed on staging

**Comment by maryjaf** [comment]
- [ ] 1-

I've got Unauthorized error @MohammadPCh @mohammadranjbarz 

![image](https://github.com/Giveth/impact-graph/assets/111529185/7cf05c09-c832-4e9f-b34c-f9c142e15636)

https://github.com/Giveth/impact-graph/assets/111529185/ecbd5dc4-a2c2-4b31-9ad1-ce32cba9374a

**Comment by MohammadPCh** [comment]
@maryjaf Is it happening every time? because we check the user authentication before donating.

**Comment by maryjaf** [comment]
> I've got Unauthorized error @MohammadPCh @mohammadranjbarz

![image](https://github.com/Giveth/impact-graph/assets/111529185/137ebbf3-cec1-4310-bab7-e7fad7ff600b)

curl 'https://impact-graph.serve.giveth.io/graphql' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'authorization;' \
  -H 'authversion: 2' \
  -H 'content-type: application/json' \
  -H 'origin: https://staging.giveth.io' \
  -H 'referer: https://staging.giveth.io/' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  -H 'wallet-address: 0xa1179f64638adb613ddaac32d918eb6beb824104' \
  --data-raw $'{"operationName":"createDraftRecurringDonation","variables":{"projectId":223623,"networkId":11155420,"flowRate":"36170000106169","currency":"GIV","anonymous":false,"isBatch":true,"isForUpdate":false},"query":"mutation createDraftRecurringDonation($networkId: Float\u0021, $currency: String\u0021, $projectId: Float\u0021, $recurringDonationId: Float, $anonymous: Boolean, $isBatch: Boolean, $isForUpdate: Boolean, $flowRate: String\u0021) {\\n  createDraftRecurringDonation(\\n    networkId: $networkId\\n    currency: $currency\\n    recurringDonationId: $recurringDonationId\\n    projectId: $projectId\\n    anonymous: $anonymous\\n    isBatch: $isBatch\\n    isForUpdate: $isForUpdate\\n    flowRate: $flowRate\\n  )\\n}"}'

**Comment by maryjaf** [comment]
- [ ] 2-
 Draft donation doesn't work because there is no change in previous flow and the donation isn't shown in the list of donations  like as before @mohammadranjbarz @MohammadPCh 
 to reproduce:
 -Tap on donate in project page and then select recurring donation tab
 -Set amount 
 -Tap on donate button in donation page
 -Before confirming the metamak transaction, close the dapp window 
 -Confirm metamask transaction
 -See this donation isn't shown in project and user page

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting. The 'Unauthorized' issue appears to be a frontend problem; we need to identify the reproduction steps. However, the second issue is related to the backend.
cc: @mohammadranjbarz @CarlosQ96

**Comment by divine-comedian** [comment]
@jainkrati  who can take this one for the back-end issue bug fix?

> * [ ]  2-
>   Draft donation doesn't work because there is no change in previous flow and the donation isn't shown in the list of donations  like as before @mohammadranjbarz @MohammadPCh
>   to reproduce:
>   -Tap on donate in project page and then select recurring donation tab
>   -Set amount
>   -Tap on donate button in donation page
>   -Before confirming the metamak transaction, close the dapp window
>   -Confirm metamask transaction
>   -See this donation isn't shown in project and user page

**Comment by maryjaf** [comment]
I've tested draft donations scenario and it works now 
Thanks @CarlosQ96 @mohammadranjbarz

**Comment by maryjaf** [comment]
Draft donation problem has been fixed
