### ISSUE TITLE
create segment call for when a project is listed

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#147]
Add in a segment call when a project's listed status === `true`

we will link this into an email on autopilot notifying the project.

**Comment by MoeNick** [comment]
Where is the PR?

**Comment by divine-comedian** [comment]
The PR is linked in the issue .... #148

**Comment by MoeNick** [comment]
Would u pls connect your pr with issue? We need this for versioning

**Comment by divine-comedian** [comment]
the PR is connected in linked pull requests....
