### ISSUE TITLE
By tapping on "refresh score" the user's passport score is changed to 0 on stg

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1472]
By tapping on "refresh score" button, the showing score in my account is changed to 0, but my real score isn't zero on gitcoin passport site 

<img width="1443" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/9a6d1a3f-13f6-4d5b-9d93-d2b193040a96">
<img width="1357" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/129432e1-2b41-4bb6-864a-467429acd51e">

_____

curl 'https://impact-graph.serve.giveth.io/graphql' \
  -H 'accept: */*' \
  -H 'accept-language: en' \
  -H 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNBZGRyZXNzIjoiMHhENWRiM0Y4QjBhMjM2MTc2NTg3NDYwZEM4NUYwZkM1NzA1RDc4NDc3IiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA0LTI2VDA3OjM5OjQ2LjkwN1oiLCJqdGkiOiIxNzExNTI1MTg2OTA0LTI3OGM2MjZjNjMiLCJpYXQiOjE3MTE1MjUxODYsImV4cCI6MTcxNDExNzE4NX0.OBJWdWK7rCbcgs8xXny-eLWWwWQrQzTyMfAvdmjC_Mk' \
  -H 'authversion: 2' \
  -H 'content-type: application/json' \
  -H 'origin: https://staging.giveth.io' \
  -H 'referer: https://staging.giveth.io/' \
  -H 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'sec-ch-ua-platform: "macOS"' \
  -H 'sec-fetch-dest: empty' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-site: same-site' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36' \
  --data-raw $'{"variables":{"address":"0xd5db3f8b0a236176587460dc85f0fc5705d78477"},"query":"query ($address: String\u0021) {\\n  refreshUserScores(address: $address) {\\n    id\\n    firstName\\n    lastName\\n    name\\n    email\\n    avatar\\n    walletAddress\\n    url\\n    location\\n    boostedProjectsCount\\n    likedProjectsCount\\n    donationsCount\\n    projectsCount\\n    passportScore\\n    passportStamps\\n  }\\n}"}'
  
  
  cc: @jainkrati

**Comment by maryjaf** [comment]
Could you please assign this issue to a developer? @jainkrati

**Comment by CarlosQ96** [comment]
@maryjaf does the issue occur always? I tried to reproduce it code wise locally fetching data. But im getting everything correctly.

**Comment by maryjaf** [comment]
> @maryjaf does the issue occur always? I tried to reproduce it code wise locally fetching data. But im getting everything correctly.

I've tested with 2 users on stg and this bug happens
0xcd192b61a8Dd586A97592555c1f5709e032F2505
0xD5db3F8B0a236176587460dC85F0fC5705D78477

https://github.com/Giveth/impact-graph/assets/111529185/6fba3565-7c1c-407c-9953-369f3b3d83d2

**Comment by MohammadPCh** [comment]
@maryjaf It seems the problem is on BE side because it returns zero.

**Comment by maryjaf** [comment]
Yeah and it was  assigned to @CarlosQ96

**Comment by CarlosQ96** [comment]
@maryjaf lets test it tomorrow in a meeting. My testing didnt lead to the right bug. So something else must be setting it to zero.

**Comment by maryjaf** [comment]
> @maryjaf lets test it tomorrow in a meeting. My testing didnt lead to the right bug. So something else must be setting it to zero.

Sure,
It happened also for @RamRamez

**Comment by maryjaf** [comment]
Did you check the above curl that I shared in description ? @CarlosQ96 
In the response of this request passportScore" is shown 0 
but based on below pic this score doesn't 0 in gitcoin passport 


curl --location 'https://impact-graph.serve.giveth.io/graphql' \
--header 'accept-language: en' \
--header 'authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwdWJsaWNBZGRyZXNzIjoiMHhENWRiM0Y4QjBhMjM2MTc2NTg3NDYwZEM4NUYwZkM1NzA1RDc4NDc3IiwiZXhwaXJhdGlvbkRhdGUiOiIyMDI0LTA0LTI2VDA3OjM5OjQ2LjkwN1oiLCJqdGkiOiIxNzExNTI1MTg2OTA0LTI3OGM2MjZjNjMiLCJpYXQiOjE3MTE1MjUxODYsImV4cCI6MTcxNDExNzE4NX0.OBJWdWK7rCbcgs8xXny-eLWWwWQrQzTyMfAvdmjC_Mk' \
--header 'authversion: 2' \
--header 'content-type: application/json' \
--header 'origin: https://staging.giveth.io' \
--header 'referer: https://staging.giveth.io/' \
--header 'sec-ch-ua: "Google Chrome";v="123", "Not:A-Brand";v="8", "Chromium";v="123"' \
--header 'sec-ch-ua-mobile: ?0' \
--header 'sec-ch-ua-platform: "macOS"' \
--header 'sec-fetch-dest: empty' \
--header 'sec-fetch-mode: cors' \
--header 'sec-fetch-site: same-site' \
--data '{"query":"query ($address: String!) {\n refreshUserScores(address: $address) {\n id\n firstName\n lastName\n name\n email\n avatar\n walletAddress\n url\n location\n boostedProjectsCount\n likedProjectsCount\n donationsCount\n projectsCount\n passportScore\n passportStamps\n }\n}","variables":{"address":"0xd5db3f8b0a236176587460dc85f0fc5705d78477"}}'


![image](https://github.com/Giveth/impact-graph/assets/111529185/9a6dc28f-cde9-4a64-baec-6aba0453ce11)
![image](https://github.com/Giveth/impact-graph/assets/111529185/6c18837a-8b5c-4821-8bfe-b83c9f9b4f3d)

**Comment by maryjaf** [comment]
It happens on prod also @CarlosQ96 @jainkrati 
and should be check with high priority 

https://github.com/Giveth/impact-graph/assets/111529185/c82fdc28-020f-4361-8f2f-b421d709c143

**Comment by CarlosQ96** [comment]
From my testings. 

My original score was 10, now it's 0. 
I updated some stamps and im back to 2.6 and it's updated, when clicking the button.

Seems Gitcoin expired all scores by default and most people went back to 0. @laurenluz @jainkrati  in that case I can't do anything about it.

People must go inside their profile in gitcoin and get more stamps to increase their score. There seems to be an expiration, but it's hard to tell which, documentation say it may be 3 months. But in https://www.scorer.gitcoin.co/#/dashboard/scorer
Im unable to configure such setting. 

@maryjaf

**Comment by CarlosQ96** [comment]
https://docs.passport.gitcoin.co/building-with-passport/major-concepts/expirations docs about expiration

**Comment by CarlosQ96** [comment]
Refreshing scores
The score displayed in the Passport app is refreshed automatically, whenever the user makes any change to their Passport. However, API users may find the scores returned by the API sometimes differs from the score displayed in the app. If this happens, refresh the Passport score by making a POST request to submit-passport.

POST /registry/submit-passport

So ill separate it into two actions. REFRESH then FETCH

**Comment by maryjaf** [comment]
I've tested on prod today, and the problem related to showing 0 for score has been resolved 
but there is a difference between score in response of graphql and score in gitcoin passport dashboard, take a look on below video 
dapp score: 1.030878
gitcoin dashboard:0.53
@CarlosQ96 

https://github.com/Giveth/impact-graph/assets/111529185/f0fbd9c8-d13f-4754-8f7d-86cc59b99160

**Comment by maryjaf** [comment]
There is a problem On stg for user with passport score 0 @CarlosQ96 
The passport score of this user 0xf577Ae8b97d839B9c0522A620299DC08792c738c is 0 on gitcoin passport dashboard

but on stg, in the response of "query UserByAddress", passport score is shown null: "passportScore": null,
and it makes in front, loading icon is shown, pic 1
and on production, in the response of "query UserByAddress", passport score is shown 0:  "passportScore": 0,pic 2

STG
<img width="1061" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2c5527ddab4ee5b24b7b167d535a38d6c93ad6f2/image.png" alt="image.png" />
_______
PROD
<img width="1361" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmFiQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8ee07d4bb64be7eee8ea7e1d4f311218e857a71b/image.png" alt="image.png" />

**Comment by mohammadranjbarz** [comment]
@maryjaf We have two users with this wallet address (one of them are lowercase and the other one is not) so it makes this problem, your data is old and now we just save walletAddresses ad lowercase and it's unique so it would not happen for other addresses, now if you want I can change the wallet address of one of your users to another thing if you want to.
So I think it's not a blocker for this release. 
@maryjaf  @jainkrati  WDYT?

**Comment by maryjaf** [comment]
> @maryjaf We have two users with this wallet address (one of them are lowercase and the other one is not) so it makes this problem, your data is old and now we just save walletAddresses ad lowercase and it's unique so it would not happen for other addresses, now if you want I can change the wallet address of one of your users to another thing if you want to. So I think it's not a blocker for this release. @maryjaf @jainkrati WDYT?

Thanks @mohammadranjbarz I've checked by another user with score 0 and this problem doesn't happen 
I also think this isn't a blocker for release
