### ISSUE TITLE
The showing "id" in response of "updateRecurringDonationQuery" isn't correct 

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#1478]
in my new try I haven't seen unauthorized error again, i try to reproduce

but now by tapping on archive and complete flow , the status isn't changed from ended to archive and it is still shown ended
I've checked this with @MohammadPCh and this scenario happens for Giveth project that I already have a archive donation for this and it should be checked on backend side @mohammadranjbarz 

https://github.com/Giveth/giveth-dapps-v2/assets/111529185/455d0989-8e38-4162-a141-5b7d8abe5caf

_Originally posted by @maryjaf in https://github.com/Giveth/giveth-dapps-v2/issues/3990#issuecomment-2049355805_

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  I'm still busy with draft donation service, can you take care of this?
The problem is that we get projectId in update service, because I imagined that we have just one recurring donation per project for each user, so when user have more than one recurring donation for a project we find wrong recurringDonationId and update that one, we should change the service and get recurringDonationId from frontend and find by that

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up today itself

**Comment by CarlosQ96** [comment]
Ill take it!

**Comment by maryjaf** [comment]
You can reproduce this in this flow @CarlosQ96 
-There is a "Archived" donation for example for "giveth" project in user's recurring donation table 
-There is also an "Ended" donation for giveth project
-Tap on "Archive Donation" button to change this ended donation in to "archived"
-see error

**Comment by divine-comedian** [comment]
We should consider that I can make a recurring donation multiple times in a given token (start/end then start a new one) 

I can also be donating in different tokens to the same project at the same time.  (GIVx, USDCx, ETHx)

**Comment by CarlosQ96** [comment]
Yeah I'm fixing the recurringDonationUpdate service to accept the recurringDonationId. This should fix it. But its a breaking change. Leaving Pr!

**Comment by CarlosQ96** [comment]
Linked Pr to issue

**Comment by MohammadPCh** [comment]
@CarlosQ96 @mohammadranjbarzit seems like the recurringDonationId is now required. Can we consider changing this requirement? Currently, when modifying recurring donations on the donation page, we don't have access to the ID. On the donation page, we rely on data from the superfluid subgraph to ensure updates, which doesn't provide the donation ID. 
My suggestion is to have two types of requirements: 
1. recurringDonationId as mandatory
2. projectID, networkId, and currency as mandatory.

wdyt?
CC: @jainkrati

**Comment by divine-comedian** [comment]
> @CarlosQ96 @mohammadranjbarzit seems like the recurringDonationId is now required. Can we consider changing this requirement? Currently, when modifying recurring donations on the donation page, we don't have access to the ID. On the donation page, we rely on data from the superfluid subgraph to ensure updates, which doesn't provide the donation ID. My suggestion is to have two types of requirements:
> 
> 1. recurringDonationId as mandatory
> 2. projectID, networkId, and currency as mandatory.
> 
> wdyt? CC: @jainkrati

Regarding the second requirement - would this cause any issues when a user for example had a recurring donation a project, they end it, then start a new one to the same project in the same currency? Would the FE be able to distinguish them as two separate recurring donations or does it not matter in those scenarios?

**Comment by CarlosQ96** [comment]
Ok ill revert the changes and define a better way to find the recurringDonation, maybe add another service for updating.

**Comment by CarlosQ96** [comment]
Ill add both services one with the recurringDonationId and one with currency, chainId, projectId

**Comment by MohammadPCh** [comment]
@CarlosQ96 Thanks

**Comment by maryjaf** [comment]
Now I couldn't complete Archive flow for all of my ended donations
@MohammadPCh @CarlosQ96 

![image](https://github.com/Giveth/impact-graph/assets/111529185/7cd10a16-01eb-4080-8109-e60af400bcf6)


https://github.com/Giveth/impact-graph/assets/111529185/4acce1b3-0e86-4d40-a2d7-8eea8aed822d

**Comment by MohammadPCh** [comment]
@maryjaf It seems it was a temporary situation, but I will set a call with you to test. thanks

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 @MohammadPCh this issue has been resolved

**Comment by jainkrati** [comment]
@maryjaf pls mark done if this is verified

**Comment by maryjaf** [comment]
> @maryjaf pls mark done if this is verified

This issue has already been moved to Done column
