### ISSUE TITLE
[May 10] As a Donor, I want to receive GIVbacks from my recurring donations.

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1483]
Users should get GIVbacks for making recurring donations to verified projects with GIVbacks eligible tokens 

We can use the accounting API to track the amount and dollar value of super fluid streams made between two points in time. We can add this into our regular GIVbacks calculations 
https://accounting.superfluid.dev/v1/swagger

I think we should have this happen in the background, automatically, and not add any complexity to the UI.

Tagging @laurenluz to see what she thinks 

----
After making a GIVbacks eligible recurring donation users should receive GIVbacks based on the USD value of the recurring donation(s) made during the specific GIVbacks round

example: 

User sets stream for 10 DAI / month to project A - that's approx $ 0.328 per day

GIVbacks round is 14 days - user has recurring donation for entire duration of round that should mean they have $4.6 of GIVbacks eligible donations when running the calculation

Any recurring donation value made outside the GIVbacks range should not be included in calculation. Having multiple recurring donations to many projects or the same project with different tokens should also be taken into account similarity

## AC 

- [x] user can create recurring donation to a project w/ Optimism address
- [x] when donating token logos show up with GIVbacks eligible symbol on them
- [x] on success page users sees some text confirming they will get GIVbacks from their recurring donation
- [x] GIVbacks calculation for recurring donation returns correct amount
- [x] value of recurring donations made outside of givbacks calculation dates are not counted
- [x] givbacks factor from project's rank is applied correctly
- [ ] donations to non-verified projects  are not included in calculation
- [ ] recurring donations made to several projects by the same user, within the givbacks calculation dates are calculated correctly
- [ ] several recurring donations in different tokens, made to the same project is calculated correctly
- [x] token prices are fetched correctly in givbacks calculation for OP, ETH, DAI, USDC, GIV 
- [ ] GIVbacks factor changes when recurring donation is applied across multiple rounds is applied correctly (project increases or decreases in rank)

**Comment by laurenluz** [comment]
Sounds good!

I don't think we need add anything special to the UI for givbacks.

**Comment by divine-comedian** [comment]
@jainkrati  - who can we give this one too for the research?

**Comment by jainkrati** [comment]
@mohammadranjbarz can you guide @RamRamez to take this up and give to QA by May 10

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz can you guide @RamRamez to take this up and give to QA by May 10

Sure, good idea, @RamRamez please ping me when you decided to work on this

**Comment by divine-comedian** [comment]
Use the mini donations to count towards the GIVbacks calculation, not the accounting API

We have everything in the data already including GIVbacks factor to add it into the calculations, if we used the accounting API we would miss this.

**Comment by mohammadranjbarz** [comment]
@mhmdksh  Can you give me the link of givback-calculation staging, because the current link you already sent me doesn't work, and we need it for testing this issue (and also @maryjaf  needs that for another issue)
And CD pipeline doesn't work for staging of givback-calcualtion project, it might be related to that

**Comment by mohammadranjbarz** [comment]
@mhmdksh  Can you give me the link of givback-calculation staging, because the current link you already sent me doesn't work, and we need it for testing this issue (and also @maryjaf  needs that for another issue)
And CD pipeline doesn't work for staging of givback-calcualtion project, it might be related to that

**Comment by mohammadranjbarz** [comment]
@maryjaf

**Comment by WhyldWanderer** [comment]
Just a heads up that Round 61 & 62 GIVbacks are currently on hold waiting for this implementation.

Users are asking... 
Is there an ETA for this to be completed? I can communicate this with them.
Thanks!

**Comment by maryjaf** [comment]
> * GIVbacks calculation for recurring donation returns correct amount
> * [ ]  value of recurring donations made outside of givbacks calculation dates are not counted
> * [ ]  givbacks factor from project's rank is applied correctly
> * [ ]  donations to non-verified projects  are not included in calculation
> * [ ]  recurring donations made to several projects by the same user, within the givbacks calculation dates are calculated correctly
> * [ ]  several recurring donations in different tokens, made to the same project is calculated correctly
> * [ ]  token prices are fetched correctly in givbacks calculation for OP, ETH, DAI, USDC, GIV
> * [ ]  GIVbacks factor changes when recurring donation is applied across multiple rounds is applied correctly (project increases or decreases in rank)

For complete these ACs I need your help and access @mohammadranjbarz If you have a chance, let's set up a call

and please take a look on this Tx @mohammadranjbarz 
-I donated to a project(recurring donation) 
-but I didn't see this tx in response of get_eligible_donations
0xc643e72a324241c2348842f2db266df42c38a5a37de00d46e1a66a9f2c08bbdc

<img width="1677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3dTQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c309385a1b06dea52b502a56563b42ec51b25e14/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
> and please take a look on this Tx @mohammadranjbarz
> -I donated to a project(recurring donation)
> -but I didn't see this tx in response of get_eligible_donations
> 0xc643e72a324241c2348842f2db266df42c38a5a37de00d46e1a66a9f2c08bbdc

also for this donation:
0x1bbdd9cab93c5f14b8551584e33278fca01d01ed394af6dcad5396a4567649a2
https://staging.giveth.io/project/mejan?tab=donations
![image](https://github.com/Giveth/impact-graph/assets/111529185/7c14f3e3-b65b-4681-b01b-53d99889fa90)

**Comment by mohammadranjbarz** [comment]
@maryjaf I will set a call  with you

**Comment by laurenluz** [comment]
@maryjaf @mohammadranjbarz - what's the status on here? is ashley able to pull this givbacks data yet for review?

**Comment by jainkrati** [comment]
@maryjaf @mohammadranjbarz pls close this issue, if not already done

**Comment by WhyldWanderer** [comment]
I have pulled the data needed for the GIVbacks rounds and it seems that we are now showing recurring donations!! 
Woohoo! 

Hard to tell if they were all included or if we missed some but I do see that they are showing in the data now.
Thanks!

**Comment by divine-comedian** [comment]
Okay, is there anyway to verify the rest of the acceptance criteria I've posted above?

**Comment by maryjaf** [comment]
> > and please take a look on this Tx @mohammadranjbarz
> > -I donated to a project(recurring donation)
> > -but I didn't see this tx in response of get_eligible_donations
> > 0xc643e72a324241c2348842f2db266df42c38a5a37de00d46e1a66a9f2c08bbdc
> 
> also for this donation: 0x1bbdd9cab93c5f14b8551584e33278fca01d01ed394af6dcad5396a4567649a2 https://staging.giveth.io/project/mejan?tab=donations ![image](https://private-user-images.githubusercontent.com/111529185/334130563-7c14f3e3-b65b-4681-b01b-53d99889fa90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5MTcxMDYsIm5iZiI6MTcxNzkxNjgwNiwicGF0aCI6Ii8xMTE1MjkxODUvMzM0MTMwNTYzLTdjMTRmM2UzLWI2NWItNDY4MS1iMDFiLTUzZDk5ODg5ZmE5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwOVQwNzA2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNGEyMDE4ZWRiZGQ4MmMyYjI0MmQ4OWU4NDY4ODhkOWZkZGIzNTVjYzhmYzQ2OWY0OGNiNTdmMzQwZTNhOTAzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5yyxCsYcZ6LDfwO-yBugwGsVzR6kFGsLp20vhfBFkd0)

I've checked with @mohammadranjbarz and this link https://givback.develop.giveth.io/api-docs/ returns the data of production not stg
Could you please check it @mhmdksh

**Comment by maryjaf** [comment]
> I've checked with @mohammadranjbarz and this link https://givback.develop.giveth.io/api-docs/ returns the data of production not stg
> Could you please check it @mhmdksh

I checked givback for recurring donation on production link https://givbacks.giveth.io/api-docs/ and it seems everything is fine,
but this problem on stg should be fixed by devops team.
 this link https://givback.develop.giveth.io/api-docs/ returns the data of production not stg

**Comment by jainkrati** [comment]
@mhmdksh could you please help

**Comment by mhmdksh** [comment]
> > I've checked with @mohammadranjbarz and this link https://givback.develop.giveth.io/api-docs/ returns the data of production not stg
> > Could you please check it @mhmdksh
> 
> I checked givback for recurring donation on production link https://givbacks.giveth.io/api-docs/ and it seems everything is fine, but this problem on stg should be fixed by devops team. this link https://givback.develop.giveth.io/api-docs/ returns the data of production not stg

@maryjaf @jainkrati I'll be taking a look today

**Comment by divine-comedian** [comment]
@mhmdksh - What is the update please? Can we test?

**Comment by mhmdksh** [comment]
@divine-comedian @maryjaf There was a misconfig on the staging givback calculation service we changed the below two values:
```
GIVETHIO_BASE_URL=https://impact-graph.serve.giveth.io
GIVETHIO_DAPP_URL=https://staging.giveth.io
```
It should be returning the right info now, @maryjaf Can you confirm please
