### ISSUE TITLE
Fix Ortto Givbacks round

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#1487]
related to [ticket from Kieran](https://discord.com/channels/679428761438912522/1227371867862597773/1227372016341094442).

**Comment by RamRamez** [comment]
cc @jainkrati @WhyldWanderer

**Comment by RamRamez** [comment]
@maryjaf to test and verify
Now, GIVBacks round number tag for each person should be correct in Ortto

**Comment by maryjaf** [comment]
Please take a look on below video, it seems this flow is buggy @RamRamez 

1- my donation to "[The Giveth Community of Makers](https://giveth.io/project/the-giveth-community-of-makers)" project with account "yama test" is shown in "Givbacks 61" tag
2- when I donate to this project with another user "Mary yama"
3- In  [Givbacks 61](https://ortto.app/ap2-giveth/cdp/people/filter/6620e1a718ba97274679236b) previous user"yama test" is changed to "Mary yama"
4- I expect that a new record be added to "Givbacks 61" tag

https://github.com/Giveth/impact-graph/assets/111529185/436fc485-a7e0-4c4b-87b4-d552bde02832

**Comment by RamRamez** [comment]
UserID is updating, but actually it shouldn't. I think it's merging the user by email, because @maryjaf had same email for both accounts, but should merge by userID.

![image](https://github.com/Giveth/impact-graph/assets/73441857/d68bca15-899e-4404-8758-622450e51552)

@divine-comedian can you please check? when sending request, I don't specify the merge method, as we agreed before, and when userID exists, it should merge by that, and if it don't, should merge by email address.

**Comment by divine-comedian** [comment]
@maryjaf - I've created a new issue #1494 to follow up the bug you reported, 

Let's check if the round number is being recorded correctly in the tag and if so, we can call this issue done.
