### ISSUE TITLE
Can't fetch project by slug, when slug contains special characters like quotation

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#149]
this issue was discovered from Giveth/giveth-next#173

![Screen Shot 1400-07-10 at 17.18.50.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/1512c8fe-bd67-41f6-b948-9f438649aafd)

**Comment by mohammadranjbarz** [comment]
@divine-comedian  @MoeNick 
You can test it now, it's ok
https://next.giveth.io/project/jesus-thinks-you're-awesome

**Comment by divine-comedian** [comment]
the project shows correctly and same with other projects that have `'` in them. However I tried to create a new project with apostrophes `'` in them and was thrown an error saying I can't use special characters in my project title.

![image](https://user-images.githubusercontent.com/67759413/135778114-9159a6b5-312f-4c56-8391-30d174d823fb.png)


However I can edit my project title after it's been created and add in whatever characters I want from here which, eventually can produce errors:
\
![image](https://user-images.githubusercontent.com/67759413/135778373-cd27cafc-e7cb-4b59-90a4-3f044788625f.png)
\
![image](https://user-images.githubusercontent.com/67759413/135778349-1230ca36-8352-444d-8df3-c01434037685.png)
\
I'm not sure if this counts as the same issue but it does seem to be part of a bigger problem. Moving this one back to in progress.

**Comment by mohammadranjbarz** [comment]
> the project shows correctly and same with other projects that have `'` in them. However I tried to create a new project with apostrophes `'` in them and was thrown an error saying I can't use special characters in my project title.
> 
> ![image](https://user-images.githubusercontent.com/67759413/135778114-9159a6b5-312f-4c56-8391-30d174d823fb.png)
> 
> However I can edit my project title after it's been created and add in whatever characters I want from here which, eventually can produce errors: ![image](https://user-images.githubusercontent.com/67759413/135778373-cd27cafc-e7cb-4b59-90a4-3f044788625f.png) ![image](https://user-images.githubusercontent.com/67759413/135778349-1230ca36-8352-444d-8df3-c01434037685.png) I'm not sure if this counts as the same issue but it does seem to be part of a bigger problem. Moving this one back to in progress.

@divine-comedian As I understood the business says we should not allow special characters, so we should check project title in edit form like how we do in create form, 
I just create another issue for that
Giveth/giveth-next#280
