### ISSUE TITLE
Make sure Ortto is merging by userID, not email

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1494]
UserID is updating, but actually it shouldn't. I think it's merging the user by email, because @maryjaf had same email for both accounts, but should merge by userID.

![image](https://github.com/Giveth/impact-graph/assets/73441857/d68bca15-899e-4404-8758-622450e51552)

@divine-comedian can you please check? when sending request, I don't specify the merge method, as we agreed before, and when userID exists, it should merge by that, and if it don't, should merge by email address.

_Originally posted by @RamRamez in https://github.com/Giveth/impact-graph/issues/1487#issuecomment-2063781422_

**Comment by RamRamez** [comment]
I created two accounts with same email address on prod and did different testings by donating and changing user name, but the correct user is updating in Ortto

**Comment by RamRamez** [comment]
We have an activity called Custom: user id changed, that's causing changing user ID, and it's connected to Onboarding, that is merging by email.

Lots of user IDs are changing and I don't know how and when it's being called

<img width="1375" alt="Screenshot 2024-04-19 at 3 20 26 PM" src="https://github.com/Giveth/impact-graph/assets/73441857/9b789a95-ca43-4c9f-be35-ca6182d35b42">

**Comment by divine-comedian** [comment]
It looks like users are signing up to the Onboarding page - which is what is creating the new entries and assigning them a userId - you can see in the details for each activity entry it assigns new value, it doesn't replace an old one, except in the case of mary maya...


The first issue I noticed and resolved when you reported was to fix the merge strategy - which was not correctly setup to use UserId first.. 

However we should clarify where this API is being used on our website and where it is getting this userId value from... I believe @ahmadabugosh set this one up.

**Comment by ahmadabugosh** [comment]
@divine-comedian This was setup with the built in form builder from Ortto and embedding their default form ([see here)](https://ortto.app/ap2-giveth/capture/646b4736a2882bf86587185d/design?from=capture-index&key=--). 

I didn't see any options in the form setting related to userId, so it must be a built in function to create a new id for each submission.

**Comment by RamRamez** [comment]
It happened on 24 Apr, I noticed @maryjaf ID was changed on about 2AM local time, but @maryjaf wasn't online that time, actually she abandoned work on 8PM that day.

![image](https://github.com/Giveth/impact-graph/assets/73441857/965830c0-89b7-4458-a0b7-6739a74dcfc9)

**Comment by divine-comedian** [comment]
@RamRamez - Maybe we need to find a way to not use this webform and handle it using our regular BE services... WDYT?

**Comment by RamRamez** [comment]
I sent PR for impact-graph and notification-center, forcing Ortto to merge by email when not on production, I think that should fix the problem.
@divine-comedian what webform do you mean? do mean the external script that is used in /onboarding page to catch emails?

**Comment by divine-comedian** [comment]
Yes exactly - the external script is for an embeddable webform, just as ahmad shared. If we put this in ourselves we could have more control/oversight on how it is used. I don't think it would take very much work.

WDYT?

![image](https://github.com/Giveth/impact-graph/assets/67759413/db730d3e-7ec8-4711-a558-f94857491571)

**Comment by RamRamez** [comment]
It's still not clear for me why we are using that embedded form, and why not using Ortto to create templates just like listing, verification and other templates that we already have?

If we can create an Ortto activity for that, next would be only creating new endpoint in BE and passing the email address to that activity.

**Comment by divine-comedian** [comment]
I think at the time they wanted to make a no-code solution to the onboarding form, and we hadn't yet made the full migration from autopilot to the new ortto service.

I'll make a new issue for this one.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
I've tested on stg but i'm not sure if it is deployed on prod or not ? @RamRamez

**Comment by RamRamez** [comment]
> I've tested on stg but i'm not sure if it is deployed on prod or not ? @RamRamez

Yes, it's on production
