### ISSUE TITLE
Prevent recurring donations from impacting QF estimated matching... for now 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1503]
Until we can fully commit to integrating QF matching on recurring donations as part of https://github.com/Giveth/giveth-dapps-v2/issues/3284 we should prevent recurring donations from impacting the QF estimated matching.

@mohammadranjbarz says he only needs to comment out a few lines of code

cc: @maryjaf

**Comment by mohammadranjbarz** [comment]
@divine-comedian  I had commented it before the release, so we should not have them in qf_round data.
@maryjaf  is it ok?

https://github.com/Giveth/impact-graph/blob/staging/src/services/recurringDonationService.ts#L215-L226

**Comment by maryjaf** [comment]
> @divine-comedian I had commented it before the release, so we should not have them in qf_round data. @maryjaf is it ok?
> 
> https://github.com/Giveth/impact-graph/blob/staging/src/services/recurringDonationService.ts#L215-L226


I've checked again and recurring donations aren't included in QF matching calculation for this project correctly 
https://staging.giveth.io/project/mejan?tab=donations

but for Giveth project based on below pics, the number of donations in QF donation tab in project page and the excel of QF round report are not same and I'm not sure what the reason of this 
could you please take a look @mohammadranjbarz 

![image](https://github.com/Giveth/impact-graph/assets/111529185/5200fb76-7182-4ca9-ad36-246e2afb3cb9)
![image](https://github.com/Giveth/impact-graph/assets/111529185/163d7a7a-276e-475a-983e-5f72b2333882)
QF roundId 90 (Galactic Giving)
https://docs.google.com/spreadsheets/d/1Wk8_bG75uQGZnVywos2Ii2t-4QosHoC0pRkMlZ85Ga8/edit#gid=1183805558

**Comment by maryjaf** [comment]
> but for Giveth project based on below pics, the number of donations in QF donation tab in project page and the excel of QF round report are not same and I'm not sure what the reason of this
> could you please take a look @mohammadranjbarz

By last change has been made by @mohammadranjbarz this problem is also resolved and there is no problem about this issue any more
