### ISSUE TITLE
Return appropriate error message and status code when project not found by slug

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#151]
related to Giveth/giveth-next#274

**Comment by MoeNick** [comment]
@RamRamez @mohammadranjbarz I dont know I have to close it or not?

**Comment by mohammadranjbarz** [comment]
> @RamRamez @mohammadranjbarz I dont know I have to close it or not?

<img width="1440" alt="Screen Shot 1400-09-19 at 12 45 34" src="https://user-images.githubusercontent.com/9850545/145548910-173afc39-6dc0-4305-a1d5-b7eefc5b7e9e.png">
@RamRamez  has fixed this, I think we don't need API change and you can close this
