### ISSUE TITLE
Trigger Ortto Activity when user saves their profile info for the first time

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1511]
When a user completes their profile for the first time on Giveth we will send them on an email journey. 
![image](https://github.com/Giveth/impact-graph/assets/67759413/00a28a94-4f4a-4bb4-a822-0cf7e955ff18)

We this activity to be triggered in our back-end to send the activity to ortto.

endpoint: `https://api-us.ortto.app/v1/activities/create`
activity name: `act:cm:created-profile` 

attributes: 
- "str:cm:email": 
- "str:cm:firstname": 
- "str:cm:lastname": 
- "str:cm:userid": 

fields:
 "str::email":
"str:cm:userid": 

merge by
"str:cm:userid":

**Comment by RamRamez** [comment]
ok, I will make it so that it will be triggered only when user completes this journey
https://giveth.io/onboard

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
Thanks @RamRamez 
I've created new account and received an email 
![image](https://github.com/Giveth/impact-graph/assets/111529185/a4ed5ab0-64c3-4739-8d4c-c8ae0633fed9)
by tapping on "visit giveth" button I've redirected to Givback menu in giveconomy, Is this expected?
@RamRamez @divine-comedian 
https://giveth.io/givbacks?apcid=0065e888835924ce20e28b00&utm_campaign=new-user-onboarding-templa&utm_content=welcome-email&utm_medium=email&utm_source=ortto

**Comment by divine-comedian** [comment]
Should be fixed now MJ! Good catch, to test you'll need to try it with a new profile or you can send yourself a test email manually from Ortto - DM me if you need more instruction.

**Comment by maryjaf** [comment]
Thanks @divine-comedian 
This problem has been resolved
