### ISSUE TITLE
Find a way to do email verification on project verification form through Ortto 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1512]
Currently we are using [dappmailer](https://github.com/Giveth/dapp-mailer) services for only this one feature: 

When a user needs to verify their email on the project verification form
![image](https://github.com/Giveth/impact-graph/assets/67759413/c957c2cc-0e39-4a32-a6ff-4ae7fe32da6b)

![image](https://github.com/Giveth/impact-graph/assets/67759413/dfb394f1-d2cd-43ac-bc1c-b87ff2a94bee)

Would it be possible to send this verification URL via an email sent by Ortto? If so we can switch to this method, shutdown the dappmailer service and save some $$$ on our monthly infra.

cc: @geleeroyale

**Comment by geleeroyale** [comment]
ok interesting. in my test I disabled the dappmailer service for a couple of minutes and donated to my own campaign (Muhaha). I only got emails when the service was enabled - so I think the hook to dappmailer is used in probably all email flows?

**Comment by divine-comedian** [comment]
> ok interesting. in my test I disabled the dappmailer service for a couple of minutes and donated to my own campaign (Muhaha). I only got emails when the service was enabled - so I think the hook to dappmailer is used in probably all email flows?

Could you confirm if this is true @RamRamez ? 

@geleeroyale by campaign do you mean project?

**Comment by divine-comedian** [comment]
@RamRamez - Can you please provide an update on this issue?

**Comment by RamRamez** [comment]
@divine-comedian I need an Ortto activity for that with two inputs:
1. the email address that form will be sent to (we don't use userId here)
2. the link to the verifying email address

<img width="484" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/4800a640-24fc-4fed-9f4c-fb85587329e9">

**Comment by divine-comedian** [comment]
## endpoint 
```
https://api-us.ortto.app/v1/activities/create
```
## headers
```
headers: {
        'Content-Type': 'application/json',
        'X-Api-Key': '{{ APIKey }}',
        'Content-Length': data.length
    }
```

## body 

```
{
	"activities": [
		{
			"activity_id": "act:cm:verification-form-email-verification",
			"attributes": {
				"str:cm:email": {email},
				"str:cm:verificationlink": {verificationLink}
			},
			"fields": {
				"str::email": "contact@email.com"
			},
			"location": {
				"source_ip": "172.217.4.1",
				"custom": null,
				"address": null
			}
		}
	],
	"merge_by": [
		"str::email"
	]
}
```


Then you should receive an email that looks like this: 
![image](https://github.com/Giveth/impact-graph/assets/67759413/2341ce48-646d-4fea-ba16-cf252913346e)

**Comment by RamRamez** [comment]
@divine-comedian The activity is capturing the events but the campaign is not sending emails. Could you check please?
<img width="1166" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/2100a25c-abff-42e7-8840-343f5ee7ec90">

**Comment by divine-comedian** [comment]
@RamRamez - sorry about that, the journey was published... but it wasn't turned on, WHO DESIGNED THIS SYSTEM!?!?! 

should be working now

**Comment by RamRamez** [comment]
@maryjaf please test and verify
Ortto needs one minute to send the verification email.

**Comment by maryjaf** [comment]
It seems "resend email" doesn't work, by tapping on this button I didn't receive any email @RamRamez

**Comment by RamRamez** [comment]
@maryjaf I tested and it's ok for me

<img width="898" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/69314625-066e-486a-aba9-1b7646cd7040">

**Comment by divine-comedian** [comment]
> It seems "resend email" doesn't work, by tapping on this button I didn't receive any email @RamRamez

Maybe @RamRamez can setup you with an API call you can make in postman and test if it works that way - I double checked the journey and email setup and you should be able to enter the journey and receive the email multiple times.

**Comment by maryjaf** [comment]
I've checked again and it has been resolved for me.
I've received this email for verification:

![image](https://github.com/Giveth/impact-graph/assets/111529185/0cb609ef-7544-4281-8ee8-d572d766893a)
