### ISSUE TITLE
Too many calls for refresh project_donation_summary_view materialized view

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1535]
There are plenty of such logs generated on the backend. Refreshing the materialized view is a heavy process that must not be done frequently. 
We must revise the policy of updating this materialized view, like debouncing!
```
query failed: |  
-- | --
  |   | error: error: canceling statement due to statement timeout |  
  |   |   |  
  |   | REFRESH MATERIALIZED VIEW project_donation_summary_view |  
  |   | query failed: |  
  |   | error: error: canceling statement due to statement timeout |  
  |   |   |  
  |   | REFRESH MATERIALIZED VIEW project_donation_summary_view |  
  |   | query failed:

```

**Comment by geleeroyale** [comment]
After @Rolazo set a time-limit for queries we can notice which queries are affected. Above query is constantly timing out. We will collect all the timed out queries in issues like this, but this seems to be the **most unoptimized one**

**Comment by maryjaf** [comment]
Does this issue need to be tested on QA side?  @CarlosQ96 @aminlatifi

**Comment by maryjaf** [comment]
Does this issue need to be tested on QA side?  @CarlosQ96 @aminlatifi

**Comment by Rolazo** [comment]
The merge didnt work, after disabling time our, `refresh project_donation_summary_view materialized view` was getting 6 minutes to be executed.

**Comment by jainkrati** [comment]
@CarlosQ96 pls guide @RamRamez for this

**Comment by RamRamez** [comment]
project_donation_summary_view is completely removed.

@maryjaf please test and verify

- [x] sumDonationValueUsd and countUniqueDonors should be shown correctly for each project.
- [ ] after each successful donation, sumDonationValueUsd and countUniqueDonors should be updated correctly

**Comment by maryjaf** [comment]
> * after each successful donation, sumDonationValueUsd and countUniqueDonors should be updated correctly

after new donation the total donation has been updated correctly, but the number of donor isn't changed 

-I've donated to[ this project](https://staging.giveth.io/project/how-many-photos-is-too-many-photos?tab=donations) with [new donor ](https://staging.giveth.io/user/0x0b2d7ccd6bef317749641431d54ec9d76dff7efb?tab=donations)
-I haven't donated with this user before
-I expect that the number of donor be changed from 41 to 42 but it isn't changed

**Comment by RamRamez** [comment]
> > * after each successful donation, sumDonationValueUsd and countUniqueDonors should be updated correctly
> 
> after new donation the total donation has been updated correctly, but the number of donor isn't changed
> 
> -I've donated to[ this project](https://staging.giveth.io/project/how-many-photos-is-too-many-photos?tab=donations) with [new donor ](https://staging.giveth.io/user/0x0b2d7ccd6bef317749641431d54ec9d76dff7efb?tab=donations) -I haven't donated with this user before -I expect that the number of donor be changed from 41 to 42 but it isn't changed

@maryjaf We had some other problems causing unexpected errors that are fixed now.
Please test again.

**Comment by maryjaf** [comment]
The problem related to number of contributor hasn't been fixed in Qf round donation tab 

https://github.com/Giveth/impact-graph/issues/1607#issuecomment-2164669986

**Comment by RamRamez** [comment]
> The problem related to number of contributor hasn't been fixed in Qf round donation tab
> 
> [#1607 (comment)](https://github.com/Giveth/impact-graph/issues/1607#issuecomment-2164669986)

@maryjaf if the problem you mentioned [here](https://github.com/Giveth/impact-graph/issues/1535#issuecomment-2156441710) is resolved we can move it to done, we can track the [other issue](https://github.com/Giveth/impact-graph/issues/1607#issuecomment-2164669986) in its specific issue

**Comment by maryjaf** [comment]
Yeah, I've tested and the problem related to number of unique donors has been resolved.
