### ISSUE TITLE
Replace ortto External Embedded Webform for Onboarding guide

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1548]
Currently we have an Onboarding guide listed on https://giveth.io/onboarding that includes a form for users to input their email to receive onboarding guide series of emails. 

![image](https://github.com/Giveth/impact-graph/assets/67759413/2428dbcb-87fd-442c-b61f-9a62fcff6db2)

This webform is using an embedded external script, built by Ortto and uses it's own API key to make updates to our CRM and send emails out. Currently it is causing unpredictable behaviour in our CRM, such as changing the userId of customers in our CRM. 

We should not use an external script an instead create the form directly into our website and call our API with explicitly the data and behaviour we want to update our CRM.

We also need to edit the journey that is sending this onboarding guide to look for the new activity that will trigger it.

![image](https://github.com/Giveth/impact-graph/assets/67759413/db730d3e-7ec8-4711-a558-f94857491571)

_Originally posted by @divine-comedian in https://github.com/Giveth/impact-graph/issues/1494#issuecomment-2096804849_

**Comment by RamRamez** [comment]
Thanks @divine-comedian 
do we have and Ortto activity for that? because I can't find it in activities list

**Comment by divine-comedian** [comment]
> Thanks @divine-comedian do we have and Ortto activity for that? because I can't find it in activities list

Just made it - 
![image](https://github.com/Giveth/impact-graph/assets/67759413/cc5d0327-53fe-488a-a3a5-b16dbe6abb2a)

### endpoint 
```
https://api-us.ortto.app/v1/activities/create
```


### body attributes
```
	"activities": [
		{
			"activity_id": "act:cm:onboarding-form",
			"attributes": {
				"str:cm:email": "example string value",
			},
			"fields": {
				"str::email": "contact@email.com"
			},
			
```

**Comment by RamRamez** [comment]
@divine-comedian activity is triggered but I didn't receive any email. Could you check please?
<img width="660" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/fb963a0b-41e2-4801-84a5-3d75e925400c">

**Comment by divine-comedian** [comment]
Sorry about that @RamRamez  - there was no journey connected to the activity - it should work now 

![image](https://github.com/Giveth/impact-graph/assets/67759413/e3fedba2-3411-4272-8446-b8f5224fd834)

**Comment by RamRamez** [comment]
@divine-comedian I tested with three different email addresses but didn't get any email.

**Comment by divine-comedian** [comment]
> @divine-comedian I tested with three different email addresses but didn't get any email.

OMG then I have to turn on each individual email - WHO DESIGNED THIS!!!

It should work now @RamRamez :sweat_smile:

**Comment by RamRamez** [comment]
I received email for my gmail but didn't receive any email for my outlook account although Ortto activity has been triggered

<img width="439" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/89b49d21-51b8-4bd0-85b5-2cc483241be6">

**Comment by RamRamez** [comment]
@divine-comedian Journey is not triggered for `ramin first`

<img width="1061" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/363a8d51-f84b-4e65-845a-5aa49f9a3fbb">

**Comment by divine-comedian** [comment]
@RamRamez - I can see it here in the activity panel, maybe it was a bit slow
![image](https://github.com/Giveth/impact-graph/assets/67759413/12f7ffe7-32c4-46e5-8b74-4c87e7dd45dc)

FYI you can only receive each email ONCE per email address

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi Please test and verify

https://staging.giveth.io/onboarding

**Comment by maryjaf** [comment]
There is no problem in sending emails.
but it would be good a message is shown when user set an invalid email address

**Comment by RamRamez** [comment]
@maryjaf We have this error for invalid address
<img width="801" alt="image" src="https://github.com/Giveth/impact-graph/assets/73441857/d552701a-29bc-4cc3-b59f-f9218ce4f032">

**Comment by divine-comedian** [comment]
> There is no problem in sending emails. but it would be good a message is shown when user set an invalid email address

There is only the warning we give when user enters the text in an invalid email format. If I understood you correctly I would consider it out of scope to check if the user entered a real email address into the input box.

**Comment by divine-comedian** [comment]
@RamRamez - LMK when this passes QA and hits production so I can delete the other source API that's being used on the current production webform
