### ISSUE TITLE
Issue in setting pg_trgm parameters in postgres

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1551]
The search similarity functionality uses the pg_trgm extension on Postgres. The way it works is to filter projects based on similarity scores between search terms and fields.  
The records are filtered if their similarity scores exceed the threshold defined by `pg_trgm.similarity_threshold` or `pg_trgm.word_similarity_threshold`.
We have implemented updating those parameters per boost with values defined in the `PROJECT_SEARCH_SIMILARITY_THRESHOLD` env of the impact graph, but it doesn't work. Today I manually set the db parameters to fix the search.

**Comment by aminlatifi** [comment]
Ref 
- https://github.com/Giveth/impact-graph/pull/1545
- https://github.com/Giveth/impact-graph/pull/1546

**Comment by aminlatifi** [comment]
Till this issue be fixed, I manually set the parameters. I set them to 0.1 on the production and staging env.

**Comment by jainkrati** [comment]
@aminlatifi can you spend 1 hour everyday to fix this? That way you can continue working on deVouch as well.

**Comment by aminlatifi** [comment]
> @aminlatifi can you spend 1 hour everyday to fix this? That way you can continue working on deVouch as well.

I am not sure I could manage to do it myself. But, I am up to review the PR going to solve it.

**Comment by aminlatifi** [comment]
The issue is the variable resets to its default value, 0.3, per new session. I and @mhmdksh Are working on that

**Comment by mhmdksh** [comment]
From what I've seen there seems to be an issue with our DB provider to permanently set these values which I think is effecting this functionality. Currently trying to have a workaround on this

**Comment by divine-comedian** [comment]
@mhmdksh @aminlatifi is this issue resolved?

**Comment by aminlatifi** [comment]
> @mhmdksh @aminlatifi is this issue resolved?

@RamRamez Finally made the latest update. Ramin is it resolved?

**Comment by RamRamez** [comment]
@divine-comedian yes we can close this issue
