### ISSUE TITLE
Create db replica infra for test env

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#1552]
To test the correct implementation of db read-only replica use, it would be super helpful if we could have such infra (master db + a read-only replica) on local host and test env

**Comment by mhmdksh** [comment]
Thanks @aminlatifi for creating this.

Once we create this we can also integrate it with our CI-CD Pipeline in which the tests can run on a HA DB Cluster (Which makes the tests more real)

**Comment by mhmdksh** [comment]
@Rolazo What's the update on that??

**Comment by Rolazo** [comment]
@mhmdksh @aminlatifi  @CarlosQ96 please see the commit, there's a main postgres database with its own replica,
[check here](https://github.com/Giveth/impact-graph/commit/193a4d5e79e23c485c719d66791ac0f3d5435ee1)
Under the branch **db_read-only**

**Comment by mhmdksh** [comment]
> @mhmdksh @aminlatifi @CarlosQ96 please see the commit, there's a main postgres database with its own replica, [check here](https://github.com/Giveth/impact-graph/commit/193a4d5e79e23c485c719d66791ac0f3d5435ee1) Under the branch **db_read-only**

@Rolazo Please share what would be the connection strings that we should input in the impact-graph configurations.
