### ISSUE TITLE
Base | Adding Base Network (Mainnet) into impact-graph production.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1558]
- Base Mainnet
- RPC Endpoint	https://mainnet.base.org
- Chain ID	8453
- Currency Symbol	ETH
- Block Explorer	https://basescan.org

### Token To-Do List
- [ ]  **Base Eth** (ETH) as chain native token
- [ ] **USDC** (USDC) - 0x833589fcd6edb6e08f4c7c32d4f71b54bda02913
- [ ] **Dai Stablecoin** (DAI) - 0x50c5725949a6f0c72e6c4a641f24049a917db0cb
- [ ] **Rocket Pool ETH** (rETH) - 0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c
- [ ] **Synthetix Network Token** (SNX) - 0x22e6966b799c4d5b13be962e1d117b56327fda66
- [ ] **Coinbase Wrapped Staked ETH** (cbETH) - 0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22
- [ ] **Prime** (PRIME) - 0xfA980cEd6895AC314E7dE34Ef1bFAE90a5AdD21b
- [ ] **Aerodrome** (AERO) - 0x940181a94a35a4569e4529a3cdfb74e38fd98631
- [ ] **Degen** (DEGEN) - 0x4ed4e862860bed51a9570b96d89af5e1b0efefed
- [ ] **Osaka Protocol** (OSAK) - 0xbFd5206962267c7b4b4A8B3D76AC2E1b2A5c4d5e
- [ ] **BTRST** (BTRST) - 0xa7d68d155d17cb30e311367c2ef1e82ab6022b67
- [ ] **SmarDex Token** (SDEX) - 0xfd4330b0312fdeec6d4225075b82e00493ff2e3f
- [ ] **Spectral Token** (SPEC) - 0x96419929d7949d6a801a6909c145c8eef6a40431
- [ ] **Heroes of Mavia** (MAVIA) - 0x24fcFC492C1393274B6bcd568ac9e225BEc93584
- [ ] **Maverick Token** (MAV) - 0x64b88c73a5dfa78d1713fe1b4c69a22d7e0faaa7
- [ ] **Dola USD Stablecoin** (DOLA) - 0x4621b7a9c75199271f773ebd9a499dbd165c3191
- [ ] **USD+** (USD+) - 0xb79dd08ea68a908a97220c76d19a6aa9cbde4376
- [ ] **Magic Internet Money** (MIM) - 0x4A3A6Dd60A34bB2Aba60D73B4C88315E9CeB6A3D
- [ ] **Seamless** (SEAM) - 0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85
- [ ] **Extra Finance** (EXTRA) - 0x2dad3a13ef0c6366220f989157009e501e7938f8
- [ ] **agEUR** (agEUR) - 0xa61beb4a3d02decb01039e378237032b351125b4
- [ ] **SubQueryToken** (SQT) - 0x858c50C3AF1913b0E849aFDB74617388a1a5340d
- [ ] **Rai.Finance** (SOFI) - 0x703d57164ca270b0b330a87fd159cfef1490c0a5
- [ ] **MBS** (MBS) - 0x8fbd0648971d56f1f2c35fa075ff5bc75fb0e39d
- [ ] **Rigo Token** (GRG) - 0x09188484e1ab980daef53a9755241d759c5b7d60
- [ ] **DEUS** (DEUS) - 0xde5ed76e7c05ec5e4572cfc88d1acea165109e44
- [ ] **Alongside Crypto Market Index** (AMKT) - 0x13f4196cc779275888440b3000ae533bbbbc3166

**Comment by MoeNick** [comment]
I sent some base eth to @mohammadranjbarz 
https://basescan.org/tx/0x38261dd1fd1e10d9d351e627f53c7bc33a9464ef5419be064dad626be3a4cdcc

For tokens you can swap on uniswap to any above tokens.

**Comment by mosaeedi** [comment]
I've added all of the logos here -> [Figma link](https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=4767-71303&t=ak5FEekFyiwetF40-4)

CC: @MoeNick

**Comment by mohammadranjbarz** [comment]
> * Base Mainnet
> * RPC Endpoint	https://mainnet.base.org
> * Chain ID	8453
> * Currency Symbol	ETH
> * Block Explorer	https://basescan.org
> 
> ### Token To-Do List
> * [ ]   **Base Eth** (ETH) as chain native token
> * [ ]  **USDC** (USDC) - 0x833589fcd6edb6e08f4c7c32d4f71b54bda02913
> * [ ]  **Dai Stablecoin** (DAI) - 0x50c5725949a6f0c72e6c4a641f24049a917db0cb
> * [ ]  **Rocket Pool ETH** (rETH) - 0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c
> * [ ]  **Synthetix Network Token** (SNX) - 0x22e6966b799c4d5b13be962e1d117b56327fda66
> * [ ]  **Coinbase Wrapped Staked ETH** (cbETH) - 0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22
> * [ ]  **Prime** (PRIME) - 0xfA980cEd6895AC314E7dE34Ef1bFAE90a5AdD21b
> * [ ]  **Aerodrome** (AERO) - 0x940181a94a35a4569e4529a3cdfb74e38fd98631
> * [ ]  **Degen** (DEGEN) - 0x4ed4e862860bed51a9570b96d89af5e1b0efefed
> * [ ]  **Osaka Protocol** (OSAK) - 0xbFd5206962267c7b4b4A8B3D76AC2E1b2A5c4d5e
> * [ ]  **BTRST** (BTRST) - 0xa7d68d155d17cb30e311367c2ef1e82ab6022b67
> * [ ]  **SmarDex Token** (SDEX) - 0xfd4330b0312fdeec6d4225075b82e00493ff2e3f
> * [ ]  **Spectral Token** (SPEC) - 0x96419929d7949d6a801a6909c145c8eef6a40431
> * [ ]  **Heroes of Mavia** (MAVIA) - 0x24fcFC492C1393274B6bcd568ac9e225BEc93584
> * [ ]  **Maverick Token** (MAV) - 0x64b88c73a5dfa78d1713fe1b4c69a22d7e0faaa7
> * [ ]  **Dola USD Stablecoin** (DOLA) - 0x4621b7a9c75199271f773ebd9a499dbd165c3191
> * [ ]  **USD+** (USD+) - 0xb79dd08ea68a908a97220c76d19a6aa9cbde4376
> * [ ]  **Magic Internet Money** (MIM) - 0x4A3A6Dd60A34bB2Aba60D73B4C88315E9CeB6A3D
> * [ ]  **Seamless** (SEAM) - 0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85
> * [ ]  **Extra Finance** (EXTRA) - 0x2dad3a13ef0c6366220f989157009e501e7938f8
> * [ ]  **agEUR** (agEUR) - 0xa61beb4a3d02decb01039e378237032b351125b4
> * [ ]  **SubQueryToken** (SQT) - 0x858c50C3AF1913b0E849aFDB74617388a1a5340d
> * [ ]  **Rai.Finance** (SOFI) - 0x703d57164ca270b0b330a87fd159cfef1490c0a5
> * [ ]  **MBS** (MBS) - 0x8fbd0648971d56f1f2c35fa075ff5bc75fb0e39d
> * [ ]  **Rigo Token** (GRG) - 0x09188484e1ab980daef53a9755241d759c5b7d60
> * [ ]  **DEUS** (DEUS) - 0xde5ed76e7c05ec5e4572cfc88d1acea165109e44
> * [ ]  **Alongside Crypto Market Index** (AMKT) - 0x13f4196cc779275888440b3000ae533bbbbc3166

@MoeNick 
I think there are some missing data for these token, like decimal and coingeckoId

**Comment by MoeNick** [comment]
@mohammadranjbarz I updated the decimals manually as you can see below. 

- Name (Symbol) / decimals
- [ ]  **Base Eth** (ETH) as chain native token
- [ ] **USDC** (USDC) / 6
- [ ] **Dai Stablecoin** (DAI) / 18
- [ ] **Rocket Pool ETH** (rETH) / 18
- [ ] **Synthetix Network Token** (SNX) / 18
- [ ] **Coinbase Wrapped Staked ETH** (cbETH)  / 18
- [ ] **Prime** (PRIME)/ 18
- [ ] **Aerodrome** (AERO) / 18
- [ ] **Degen** (DEGEN) / 18
- [ ] **Osaka Protocol** (OSAK) / 18
- [ ] **BTRST** (BTRST) / 18
- [ ] **SmarDex Token** (SDEX) / 18
- [ ] **Spectral Token** (SPEC) / 18
- [ ] **Heroes of Mavia** (MAVIA) / 18
- [ ] **Maverick Token** (MAV) / 18
- [ ] **Dola USD Stablecoin** (DOLA) / 18
- [ ] **USD+** (USD+) / 6
- [ ] **Magic Internet Money** (MIM) /  18
- [ ] **Seamless** (SEAM) / 18
- [ ] **agEUR** (agEUR) / 18
- [ ] **SubQueryToken** (SQT)  / 18
- [ ] **Rai.Finance** (SOFI) / 18
- [ ] **MBS** (MBS)  / 18
- [ ] **Rigo Token** (GRG) -/ 18
- [ ] **DEUS** (DEUS) / 18
- [ ] **Alongside Crypto Market Index** (AMKT) / 18

**Comment by maryjaf** [comment]
this issue  should be tested on production, on stg there is only Base(ETH) token

**Comment by MoeNick** [comment]
I was assuming, after the first round of testing, we will have another preview connected to production impact graph, and we can test before FrontEnd merge. 

@mohammadranjbarz @maryjaf
