### ISSUE TITLE
Base| Adding Base Sepolia Network into staging on backend

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1559]
Base Testnet (Sepolia)
- Base Sepolia
- RPC: https://sepolia.base.org
- Chain ID	84532
- Currency Symbol	ETH
- Block Explorer	https://sepolia-explorer.base.org
- 

Tokens:
- ETH as native: 
- Faucet ETH:  https://www.ethereum-ecosystem.com/faucets/base-sepolia
- LINK as token - 0xe4ab69c077896252fafbd49efd26b5d171a32410 
- Faucet of LINK:  https://faucets.chain.link/base-sepolia

**Comment by MoeNick** [comment]
Some ETH on Base Sepolia has been sent to @mohammadranjbarz 
https://base-sepolia.blockscout.com/tx/0xb5d86c9337e362ad81d18126300d1c46aa9d5c1d0834df36880b9d5250ff371e

**Comment by MoeNick** [comment]
Sent some LINK test token to @mohammadranjbarz to test also tokens. 
https://base-sepolia.blockscout.com/tx/0x14d677b68c415a1fb936febd718659fafaabc006faa8272c9e4f057cb36f9a63

**Comment by MoeNick** [comment]
@maryjaf you can use teh faucets aboev to get some Base ETH and test LINK. if you could not, pls let me know.

**Comment by maryjaf** [comment]
> Tokens:
> 
> * ETH as native:
> * Faucet ETH:  https://www.ethereum-ecosystem.com/faucets/base-sepolia
> * LINK as token - 0xe4ab69c077896252fafbd49efd26b5d171a32410
> * Faucet of LINK:  https://faucets.chain.link/base-sepolia

only "ETH" is in the list of tokens on STG @mohammadranjbarz
