### ISSUE TITLE
Base | Adding Price Support for Base tokens

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1561]
**We need to find the coingeckoID for these tokens**
 
- [ ] Base Eth (ETH) as chain native token
- [ ]  USDC (USDC) - 0x833589fcd6edb6e08f4c7c32d4f71b54bda02913
- [ ]  Dai Stablecoin (DAI) - 0x50c5725949a6f0c72e6c4a641f24049a917db0cb
- [ ]  Rocket Pool ETH (rETH) - 0xb6fe221fe9eef5aba221c348ba20a1bf5e73624c
- [ ]  Synthetix Network Token (SNX) - 0x22e6966b799c4d5b13be962e1d117b56327fda66
- [ ]  Coinbase Wrapped Staked ETH (cbETH) - 0x2ae3f1ec7f1f5012cfeab0185bfc7aa3cf0dec22
- [ ]  Prime (PRIME) - 0xfA980cEd6895AC314E7dE34Ef1bFAE90a5AdD21b
- [ ]  Aerodrome (AERO) - 0x940181a94a35a4569e4529a3cdfb74e38fd98631
- [ ]  Degen (DEGEN) - 0x4ed4e862860bed51a9570b96d89af5e1b0efefed
- [ ]  Osaka Protocol (OSAK) - 0xbFd5206962267c7b4b4A8B3D76AC2E1b2A5c4d5e
- [ ]  BTRST (BTRST) - 0xa7d68d155d17cb30e311367c2ef1e82ab6022b67
- [ ]  SmarDex Token (SDEX) - 0xfd4330b0312fdeec6d4225075b82e00493ff2e3f
- [ ]  Spectral Token (SPEC) - 0x96419929d7949d6a801a6909c145c8eef6a40431
- [ ]  Heroes of Mavia (MAVIA) - 0x24fcFC492C1393274B6bcd568ac9e225BEc93584
- [ ]  Maverick Token (MAV) - 0x64b88c73a5dfa78d1713fe1b4c69a22d7e0faaa7
- [ ]  Dola USD Stablecoin (DOLA) - 0x4621b7a9c75199271f773ebd9a499dbd165c3191
- [ ]  USD+ (USD+) - 0xb79dd08ea68a908a97220c76d19a6aa9cbde4376
- [ ]  Magic Internet Money (MIM) - 0x4A3A6Dd60A34bB2Aba60D73B4C88315E9CeB6A3D
- [ ]  Seamless (SEAM) - 0x1c7a460413dd4e964f96d8dfc56e7223ce88cd85
- [ ]  Extra Finance (EXTRA) - 0x2dad3a13ef0c6366220f989157009e501e7938f8
- [ ]  agEUR (agEUR) - 0xa61beb4a3d02decb01039e378237032b351125b4
- [ ]  SubQueryToken (SQT) - 0x858c50C3AF1913b0E849aFDB74617388a1a5340d
- [ ]  Rai.Finance (SOFI) - 0x703d57164ca270b0b330a87fd159cfef1490c0a5
- [ ]  MBS (MBS) - 0x8fbd0648971d56f1f2c35fa075ff5bc75fb0e39d
- [ ]  Rigo Token (GRG) - 0x09188484e1ab980daef53a9755241d759c5b7d60
- [ ]  DEUS (DEUS) - 0xde5ed76e7c05ec5e4572cfc88d1acea165109e44
- [ ]  Alongside Crypto Market Index (AMKT) - 0x13f4196cc779275888440b3000ae533bbbbc3166
- [ ]

**Comment by MoeNick** [comment]
@mohammadranjbarz please let me know how can I help to find the coingecko ID of them , I remember @alireza-sharifpour did the same with an script for Arbitrium's integration.

**Comment by mohammadranjbarz** [comment]
@MoeNick maybe you can find them in the list of supported tokens of coingecko

**Comment by MoeNick** [comment]
Based on our direct chat:
https://api.coingecko.com/api/v3/coins/list

**Comment by MoeNick** [comment]
@mohammadranjbarz I updated the coingecko ID here, manually: 

- Name (Symbol) / coingeckoId
- [ ] Base Eth (ETH) as chain native token / ethereum
- [ ]  USDC (USDC) / usd-coin
- [ ]  Dai Stablecoin (DAI)  / dai
- [ ]  Rocket Pool ETH (rETH) /  rocket-pool-eth
- [ ]  Synthetix Network Token (SNX) / havven
- [ ]  Coinbase Wrapped Staked ETH (cbETH) / coinbase-wrapped-staked-eth
- [ ]  Prime (PRIME) / echelon-prime
- [ ]  Aerodrome (AERO) / aerodrome-finance
- [ ]  Degen (DEGEN)/ degen-base
- [ ]  Osaka Protocol (OSAK) / osaka-protocol
- [ ]  BTRST (BTRST) / braintrust
- [ ]  SmarDex Token (SDEX) / smardex
- [ ]  Spectral Token (SPEC) / spectral 
- [ ]  Heroes of Mavia (MAVIA) / heroes-of-mavia
- [ ]  Maverick Token (MAV) / maverick-protocol
- [ ]  Dola USD Stablecoin (DOLA) / dola-usd
- [ ]  USD+ (USD+) / usd
- [ ]  Magic Internet Money (MIM) / magic-internet-money
- [ ]  Seamless (SEAM)  / seamless-protocol
- [ ]  Extra Finance (EXTRA) / extra-finance
- [ ]  agEUR (agEUR)  / ageur-plenty-bridge
- [ ]  SubQueryToken (SQT) / subquery-network
- [ ]  Rai.Finance (SOFI)  / rai-finance
- [ ]  UNJD (MBS) / monkeyball
- [ ]  Rigo Block (GRG)  / rigoblock
- [ ]  DEUS (DEUS) / deus-finance-2
- [ ]  Alongside Crypto Market Index (AMKT)  / alongside-crypto-market-index

**Comment by mohammadranjbarz** [comment]
Thanks @MoeNick

**Comment by MoeNick** [comment]
shall I put it to done?
