### ISSUE TITLE
Base | AdminJS|  AddToeken | Bug in adding coingeck ID 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1564]
Right now when we add coingeckoID in adminJs for a token it would save without that information and cause an error for users.

**Comment by mohammadranjbarz** [comment]
@MoeNick Are you sure about it?
I tested it and changed/set coingeckoId for tokens but it works well
@maryjaf  Can you test it and see if it has problem or not?

**Comment by MoeNick** [comment]
@mohammadranjbarz  It happens by adding new token not editing a token. @divine-comedian is also aware of this bug.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz It happens by adding new token not editing a token. @divine-comedian is also aware of this bug.

Got it, I fixed it in the https://github.com/Giveth/impact-graph/pull/1579
