### ISSUE TITLE
Total Amount Raised on project page not updating/does not match

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1566]
On the project details page the all time amount raised section(s) appear to be not updating after successful donations. In some cases they don't match across different parts of the page. 

This include the section shown next to the Donate Button showing s DONATE FIRST when on the project donations table it says they have received $90 in donations already

In other cases the section shown next to the donate button is a different number than the one shown next to the project donations table

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/aab7b0be-8508-4261-9f90-0f0b87dad4c5

https://github.com/Giveth/giveth-dapps-v2/assets/67759413/f8e4b0d7-ff1b-4d7b-858c-0e727bbdf633

In the last video posted above :point_up:  you can notice the number next to the donation table is LOWER than the amount shown above the donate button. I also made a donation to this project and it shows up successfully in the donation table but the number above the donate button remains unchanged, the all time donation amount next to the donation table updates correctly.

---

This one is related to us using two different variables from the projectData

totalDonations and sumDonationValueUsd

AFAIK due to our recent issues with refreshing the materialized view the latter variable is not able to update, however totalDonations still is updating

Shouldn't we use the same variable for everything? If so, which one should be used? @CarlosQ96 @mohammadranjbarz

**Comment by MohammadPCh** [comment]
@divine-comedian We only show the data comes from the BE.
so We have to check it with BE guys.

**Comment by divine-comedian** [comment]
I noticed while checking how we handle it on the FE 

inside of the `projectData` object we have two values - 'totalDonations' and `sumDonationValueUsd`  - which appear to refer to the same thing... total USD value of donations project has received.

totalDonations appears to be working fine... sumDonationValueUsd has stopped working since several days - at least 5 based on user reports, it is no longer being updated. AFAIK this is related to issues @mohammadranjbarz and @mhmdksh  are investigating related to materialized view updating.. 

also countUniqueDonors is not working as another side note... 

![image](https://github.com/Giveth/giveth-dapps-v2/assets/67759413/0c8a9611-9bf8-4afb-aafb-99fc7a9b6bc4)

We should follow this up when the fix is made to ensure these fields are working properly... 

We should also not have two object fields fetching the same information
Moving this to the back-end..

**Comment by maryjaf** [comment]
Has this change been deployed on production? @CarlosQ96

**Comment by maryjaf** [comment]
I've tested on prod 
-for this project that mentioned in description "total donation" in donation tab and project detail  are same   https://giveth.io/project/coletivo-xv-0?tab=donations

-I tested with my test project and total donation is updated correctly https://giveth.io/project/maryam-test?tab=donations 

-but i've seen a discrepancy on "total donation" field for this project https://giveth.io/project/giveth-house?tab=donations

<img width="1274" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d6357825a6157d297363d00500ccc2f0376128ff/image.png" alt="image.png" />

**Comment by maryjaf** [comment]
I've tested on stg and production and this  discrepancy in "total donation" on donation tab and project detail exists for some projects 

for example:
stg:
https://staging.giveth.io/project/teach-music-to-children?tab=donations

prod:
https://giveth.io/project/giveth-house?tab=donations

**Comment by divine-comedian** [comment]
@CarlosQ96 - from our discussion yesterday it looks as if the `sumDonationValueUsd` is still not updating (we thought it was fixed) 


As you can see the variable `totalDonations` updates almost instantly and has the correct number, but `sumDonationValueUsd` appears to not be updating on either staging or prod... 
![image](https://github.com/Giveth/impact-graph/assets/67759413/ce36b801-be32-440e-a6cd-2f8c006dbc78)

We should find a solution for this quickly since it means it likely is affecting all projects on production

**Comment by CarlosQ96** [comment]
Pushed hotfix to staging and prod. Prod project totals are now fine.  Staging takes longer to sync
 @maryjaf  please validate again.

**Comment by CarlosQ96** [comment]
Staging doesnt seem to update ill keep looking, might be its performance issues.

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 
I've checked on production and after donate to a project , the "all time donation" in donation tab and "total amount raised" in project card and detail is updated correctly 

Before donate :
![image](https://github.com/Giveth/impact-graph/assets/111529185/3f8c5173-5e39-4d21-bfd6-e5f726af4199)

After donate:
![image](https://github.com/Giveth/impact-graph/assets/111529185/6871e4f2-3a91-4eda-8b30-2af6b0a25c78)

**Comment by divine-comedian** [comment]
Just checked on production as well, the values appear to be the same for both variables and update very quickly after making a donation.. 

last question now @CarlosQ96 

In the FE should we use only `sumDonationValueUsd` or `totalDonation` or keep everything as is?

**Comment by CarlosQ96** [comment]
Should use totalDonations in the frontend. And dont query the sumDonationValueUsd so we deprecate it.
