### ISSUE TITLE
Implement a Web Scraper that extracts the description of the project from the GivingBlocks Website.

### ISSUE THREAD

**Issue by cquinterom096** [Giveth/impact-graph#157]

**Comment by CarlosQ96** [comment]
@MoeNick This is not required. After testing with prod data, there is another endpoint that has a web-blocks section. This contains the HTML strings with the description, youtube, twitter and other data. Ill close this issue as the webscrapped is not required.

**Comment by CarlosQ96** [comment]
@WhyldWanderer  Webscraped not required, it was easier through another endpoint of the api :)
