### ISSUE TITLE
Add transactions manually into database

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1580]
We should add the following transactions into the database manually: 

- [ ] https://etherscan.io/tx/0x12d699a9c3eb3605aebbeeea9453286a16d2772738a837efe36cd4a891f75893

**Comment by mohammadranjbarz** [comment]
@divine-comedian The fromAddress of this user doesn't have a profile in our DB, should I create profile for it?

**Comment by WhyldWanderer** [comment]
Hey guys... I dont think I can add transactions in AdminBro yet. Right @mohammadranjbarz?

I can make them GIVbacks eligible or not if they already exist however, the last time I asked, I couldnt add any that didnt already exist.

Happy to help with these things in the future once that is an option for me.

**Comment by divine-comedian** [comment]
> @divine-comedian The fromAddress of this user doesn't have a profile in our DB, should I create profile for it?

Wow really? Hmm that's very suspicious, there's a chance the user never actually made this donation through our UI. 

If we can't find this donation anywhere in our back-up service nor does their profile exist (they never signed into the app) my guess is they never made this transfer through Giveth - plus I can confirm this is the project owner donating to their own project..

Let's close this one. The project owner wasn't very insistent about this donation being added.

**Comment by mohammadranjbarz** [comment]
> Hey guys... I dont think I can add transactions in AdminBro yet. Right @mohammadranjbarz?
> 
> I can make them GIVbacks eligible or not if they already exist however, the last time I asked, I couldnt add any that didnt already exist.
> 
> Happy to help with these things in the future once that is an option for me.

No unfortunately we can't add donations in the DB right now, we just can make them givback eligible or givback not eligible by admin panel
