### ISSUE TITLE
Round Banner Bug

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/impact-graph#1590]
I tried to create a round and upload an image for it. However, after uploading and saving the round, when I try to fetch the round's information, I encountered the following issue:

<img width="1252" alt="Screenshot 2024-05-27 at 12 08 16 PM" src="https://github.com/Giveth/impact-graph/assets/17097576/1cc8c091-af05-4264-b527-505bd0948faf">

Could you please investigate and resolve this bug? Thank you!
cc: @jainkrati

**Comment by MohammadPCh** [comment]
I can't even edit that round.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 I couldn't fix it, can you take a look as you implemented this feature you might can fix it sooner

**Comment by divine-comedian** [comment]
@CarlosQ96 @mohammadranjbarz is this issue still relevant?

**Comment by CarlosQ96** [comment]
I dont think this is relevant any more, we have updated the banner succesfully in all rounds later. And there has been some changes. If it happens again we can reopen it.
