### ISSUE TITLE
remove The Giving Block projects 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1599]
following the integration of Endaoment projects we should remove ALL of The Giving Block projects from Giveth. Or at least make it so they no longer show up on our UI.

**Comment by RamRamez** [comment]
I can change their status to cancelled so no one can see them by having their URL, or I can unlist them, so they can only be seen by having the url, or maybe completely remove them from DB?
@divine-comedian WDYT?

**Comment by divine-comedian** [comment]
> I can change their status to cancelled so no one can see them by having their URL, or I can unlist them, so they can only be seen by having the url, or maybe completely remove them from DB? @divine-comedian WDYT?

Let's remove from the DB all Giving Block projects that have never received a donation

We should cancel giving block projects that have received at least one donation before. The owners maybe come later to claim these projects and might request we reactivate them.

BUT we shouldn't do this until the Endaoment Projects have been successfully added

**Comment by divine-comedian** [comment]
We should not be able to see any Giving Block projects with $0 in donations on staging -> production when merged. 

@mohammadranjbarz   can add organization filter in project tab in admin panel. 

when this is done we can proceed to QA

**Comment by mohammadranjbarz** [comment]
> We should not be able to see any Giving Block projects with $0 in donations on staging -> production when merged.
> 
> @mohammadranjbarz can add organization filter in project tab in admin panel.
> 
> when this is done we can proceed to QA

I added it 
https://impact-graph.serve.giveth.io/admin/resources/Project

<img width="1913" alt="Screenshot 1403-04-28 at 11 30 32 in the morning" src="https://github.com/user-attachments/assets/e342af39-4a95-4060-81de-dce541551c7f">

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test Status: Pass

No Giving Block Project with $0 could be found on the Giveth staging

**Comment by divine-comedian** [comment]
@WhyldWanderer informed me today that we should remove ALL of the Giving Block projects - including the one's that have received donations. 

Since we still want those donations to count in our analytics we will keep & simply deactivate these remaining projects from the AdminJS

@WhyldWanderer please update us when those project statuses have been changed on production and we can close this issue!

**Comment by WhyldWanderer** [comment]
The projects have all been updated! Best feeling ever....
