### ISSUE TITLE
Re-purpose category banners to be used for endaoment project banners

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1600]
In #1664 we have mapped categories of Endaoment projects into existing Giveth categories 

Currently in Giveth we have banners shown on the headers of each main category specific page that lists all projects that belong to a specific category. 

![Image](https://github.com/Giveth/impact-graph/assets/67759413/091ed526-19cf-4ec9-befa-5ea3af51cd8b)

We should re-work these category banners so they fit appropriately to be used as project banners for Endaoment import projects. 

When setting the banners then for the specific Endaoment projects, projects that belong to multiple categories we will assign them the banner corresponding to the 1st encountered category that they belong to, apart from the separate "Endaoment" sub-category  under NGO

**Comment by divine-comedian** [comment]
The banners are ready! 

https://www.figma.com/design/W9Ace1RyCdykWM72fsSa3t/Giveth-Marketing-2024?node-id=7307-16434&t=GTSJdwbrDb3QCWGQ-1
![Image](https://github.com/user-attachments/assets/b14d68c5-a4a5-4982-a87e-c0b27aff9bc6)

so to reiterate - from the #1664 we should take the main category of the 2nd sub category added (if there is no 2nd sub category then we should use the 1st category - NGO) and find the corresponding banner in these new designs and that should be set as the project banner image for endaoment projects.

## for example 



![Image](https://github.com/user-attachments/assets/44d08c86-5bef-4c46-91e1-e18dd160aa32)

from the mapping sheet we can see on row 2 if we gave an endaoment project a 2nd sub category of "Public Goods" that would be under the "Community" main category - so we should use the Community project banner that was linked in the figma file.


![Image](https://github.com/user-attachments/assets/c2f70944-d453-4178-bf7a-0e0b4cdebb50)

on row 7 we mapped the category to "Health Care" if the endaoment project then has a 2nd category of Health Care then the main category is "Health & Wellness" 



![Image](https://github.com/user-attachments/assets/477f21a3-4a1f-4a44-8052-721d1034d243)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi @mohammadranjbarz - what is the update on this issue? We should have this ready and tested ASAP. Is it ready for QA?

**Comment by mohammadranjbarz** [comment]
@divine-comedian  It's ready to test and I think it's working(Sorry I forgot to mention here after deployment), as today is @LatifatAbdullahi OFF day, @maryjaf can you test it?

**Comment by maryjaf** [comment]
- [ ] For this project https://staging.giveth.io/project/Project-Sweetie-Pie , the only sub category is food and main category is community 

but as you can see in below screen record the "Health & Wellness"  banner is shown 

https://github.com/user-attachments/assets/13c79d09-55ac-4fe5-818f-a80636b79607

and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research
the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology

![image](https://github.com/user-attachments/assets/ac74c28b-f18d-4dad-9e65-c2b5e4fa8ef0)

**Comment by maryjaf** [comment]
https://github.com/user-attachments/assets/7c960997-8136-4fe5-be23-e4e5520eb8bf

**Comment by mohammadranjbarz** [comment]
@maryjaf My bad, I was just thinking the main category of food is Health-wellness but it's community am I right?
I can change it to that if you confirm it

**Comment by maryjaf** [comment]
> and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research
> the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology

‌‌Have you seen this also ?

**Comment by maryjaf** [comment]
> > and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research
> > the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology
> 
> ‌‌Have you seen this also ?

It seems there are some problems in showing banner based on the category 
for example for this project https://giveth.io/project/Hope-Healthcare-Services based on the file,  the banner related to "Health & Wellness" category (   nteeCode: 'E30')should be shown but its banner is related to community

**Comment by divine-comedian** [comment]
could be issue with associating the subcategory with the incorrect main category @mohammadranjbarz to review code he wrote. 

problem between relating the banners to the categorys - could have assigned the wrong banner to main category.

**Comment by divine-comedian** [comment]
@HrithikSampson  to take on fixing this issue, will coordinate with @maryjaf and @mohammadranjbarz

**Comment by HrithikSampson** [comment]
Hi,
I have a query regarding this issue.

I have done some local Database changes using typeorm migration and grouped the categories for the projects.

<img width="782" alt="Screenshot 2024-08-23 at 11 31 08 AM" src="https://github.com/user-attachments/assets/d09ffb73-941a-4f82-afea-9b3641d742f3">

I am not super clear whether this is fulfills the requirement.

**Comment by divine-comedian** [comment]
@mohammadranjbarz can guide you to understand the technical aspects of this issue - unfortunately I don't have the expertise to tell you if this is right.

**Comment by divine-comedian** [comment]
Still waiting for PR Review from @mohammadranjbarz then we can move to QA - https://github.com/Giveth/impact-graph/pull/1778

**Comment by mohammadranjbarz** [comment]
@maryjaf 
It's on the staging, can you test it now?

FYI @divine-comedian

**Comment by maryjaf** [comment]
> and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology

@mohammadranjbarz for this project the wrong banner is shown, could you please take a look?

**Comment by mohammadranjbarz** [comment]
> > and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology
> 
> @mohammadranjbarz for this project the wrong banner is shown, could you please take a look?

@HrithikSampson Can you take care of it?

**Comment by HrithikSampson** [comment]
Sure @mohammadranjbarz

**Comment by HrithikSampson** [comment]
I just had one question the enteeCode for this is H00

but the category in the database is still Health & Wellness, NGO and Technology.


  {
    name: 'Krebsforschung Schweiz / Swiss Cancer Research',
    description:
      "In existence since 1990, the Swiss Cancer Research foundation, with the help of donations, provides funding for all areas of cancer research: basic, clinical, epidemiologic, and psychosocial research. A special focus is the funding of patient-centred research projects that result as far as possible in direct patient benefit. The SCR foundation board is responsible for distributing the funds to researchers. The board's funding decisions are based on the recommendations made by the Scientific Committee, which reviews the grant applications according to clearly defined criteria. The SCR also supports the development and implementation of measures to fight cancer in Switzerland.",
    logoUrl: 'https://www.globalgiving.org/pfil/organ/31743/orglogo.jpg',
    nteeCode: 'H00',
    nteeDescription: 'Medical Research',
    mainnetAddress: '0x119e2945d379028fe8f6e2f7247975cd9a848d99',
    opAddress: '0x119e2945d379028fe8f6e2f7247975cd9a848d99',
    baseAddress: '0xe4526484df52b6a18cdc5a0ee318f508e9bb0b26',
  },
  
  H00 categories are the following.
  
  {
    nteeCode: 'H00',
    nteeDescription: 'Medical Research',
    category1: 'Endaoment',
    category2: 'Research',
    category3: 'Health Care',
    category4: '',
  },
  
  I was wondering if categories of Krebsforschung-Schweiz-Swiss-Cancer-Research is Health & Wellness, NGO and Technology

> > > and for this https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research the "Education" banner is shown but the categories of this project are Health & Wellness, NGO and Technology
> > 
> > 
> > @mohammadranjbarz for this project the wrong banner is shown, could you please take a look?
> 
> @HrithikSampson Can you take care of it?

**Comment by divine-comedian** [comment]
the nteeCode and nteeDescription are not from Giveth they are from Endaoment, so I mapped all of the possible nteeCodes to existing giveth sub categories 

We will use the main/parent category associated with `category2`

So in this example you shared above category2 is Research and the parent category is Technology. 
![image](https://github.com/user-attachments/assets/af26af4d-b9e7-4a91-9bfb-0d2c5efe1610)

**Comment by divine-comedian** [comment]
@HrithikSampson what is the update on this issue?


There was also one missing banner I noticed related to the parent category "environment & energy" - it should be available here 

![Image](https://github.com/user-attachments/assets/edb92c7d-2da2-4b16-8e59-03d499d3a34e)

**Comment by HrithikSampson** [comment]
@divine-comedian , I was just waiting for https://github.com/Giveth/impact-graph/pull/1813 review but i will make this change and request for review again. I had mapped all envioronment & energy to nature before. SO i will make the change now.
I have made this change of adding environment-energy.png

**Comment by divine-comedian** [comment]
> @divine-comedian , I was just waiting for #1813 review but i will make this change and request for review again. I had mapped all envioronment & energy to nature before. SO i will make the change now. I have made this change of adding environment-energy.png

OK - please inform when this is ready to be tested

**Comment by HrithikSampson** [comment]
@maryjaf, This issue is ready to be tested

**Comment by maryjaf** [comment]
I've forgotten how can I check the first category of projects , could you please share the api ? @HrithikSampson 
In UI I see the first category is Health and wellness  for this project https://staging.giveth.io/project/Krebsforschung-Schweiz-Swiss-Cancer-Research but I think it isn't exactly correct
![image](https://github.com/user-attachments/assets/b89f9ca4-a68f-413d-895d-2415f19573fe)

**Comment by maryjaf** [comment]
> It seems there are some problems in showing banner based on the category
> for example for this project https://giveth.io/project/Hope-Healthcare-Services based on the file, the banner related to "Health & Wellness" category ( nteeCode: 'E30')should be shown but its banner is related to community

could you please take a look on this ? @HrithikSampson 
for this project the "Health & Wellness" banner should be shown
https://giveth.io/project/Hope-Healthcare-Services

 {
    name: 'Hope Healthcare Services',
    description:
      'Hope healthcare services ministers to the physical and spiritual health burdens of uninsured people in our community as the hands and feet of Jesus.',
    logoUrl:
      'https://storage.cloud.google.com/endaoment-static/org-assets/HOPE-logo-FINAL-NOtag-HORIZ%2B(1).png?authuser=0',
    nteeCode: 'E30',
    nteeDescription: 'Health Treatment Facilities (Primarily Outpatient)',
    mainnetAddress: '0xf59e6fbff1e0d9051949b26fc60897373936b8c3',
    opAddress: '0xf59e6fbff1e0d9051949b26fc60897373936b8c3',
    baseAddress: '0x016d866246dd74e27300e43a207c6a70da21ad06',
  },
  
  
    {
    nteeCode: 'E30',
    nteeDescription: 'Health Treatment Facilities (Primarily Outpatient)',
    category1: 'Endaoment',
    category2: 'Health Care',
    category3: '',
    category4: '',
  },

**Comment by HrithikSampson** [comment]
Hi @maryjaf ,
I thnk it is merged to staging .
https://staging.giveth.io/project/Hope-Healthcare-Services is showing Health Care banner. It isnt merged to production.

**Comment by maryjaf** [comment]
Yeah, you're right 
it has been fixed on staging, thanks
