### ISSUE TITLE
I am no longer able to transfer project ownership via the AdminBro

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1602]
It seems that some changes were made and I am no longer able to transfer ownership of the project to a different user profile.

When I try to change the "Admin" field of the project, it says that it was successfully updated but it doesn't actually transfer the project to the new admin that I specified.

Is there a different way that I should do this now? Or maybe something needs to be added to the AdminBro?

Thanks for checking! Let me know if I can provide more details.

**Comment by WhyldWanderer** [comment]
![image](https://github.com/Giveth/impact-graph/assets/74267818/39950af4-6315-4450-b3c0-33690e813b65)

**Comment by RamRamez** [comment]
@maryjaf please test and verify

**Comment by maryjaf** [comment]
This problem has been fixed.
