### ISSUE TITLE
Run the Materialized View with `CONCURRENTLY` Option

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/impact-graph#1607]
Follow the details on this link for the discord discussion: https://discord.com/channels/679428761438912522/1235061511152603226/1247479598690729984

We need to add the `CONCURRENTLY` option whenever we call the Materialized View, so that we are able to query the DB with `SELECT` while the Materialized View is refreshing.

As Normal refreshing will cause the DB to block all `SELECT` Queries.

More info here: https://www.postgresqltutorial.com/postgresql-views/postgresql-materialized-views

**Comment by maryjaf** [comment]
I donated to this project https://staging.giveth.io/project/abcdhgjkk?tab=donations and I expected that the estimated matching be changed to $48 but it wasn't changed and there is no estimated matching for this project
@CarlosQ96 

![image](https://github.com/Giveth/impact-graph/assets/111529185/8772f4f6-dff6-41d4-a569-754debb8c1f5)

**Comment by mhmdksh** [comment]
@CarlosQ96 Can you confirm if the work on this after merging this PR: https://github.com/Giveth/impact-graph/pull/1611 was successful??

**Comment by CarlosQ96** [comment]
@mhmdksh moved to qa, migrations ran and tables are refreshing. 
@RamRamez will decrease the refresh rate of the estimated matching view table and that should be it.

**Comment by maryjaf** [comment]
> I donated to this project https://staging.giveth.io/project/abcdhgjkk?tab=donations and I expected that the estimated matching be changed to $48 but it wasn't changed and there is no estimated matching for this project @CarlosQ96
> 


- [ ] I've checked again, the estimated matching has been updated, how long does it take to the estimated matching be updated ? @CarlosQ96 

but as you see in below pic 
This project has a donation in a round but in the right box in qf round donation tab, "Be the first to give!" is shown 

![image](https://github.com/Giveth/impact-graph/assets/111529185/46ed3bae-03df-4164-8f36-589b8919ea38)

@CarlosQ96

**Comment by maryjaf** [comment]
- [ ] 1- I see some strange behavior on stg 

- I created new round 
- I added projects to this round 
- I haven't donated to these project yet 
- but in qf round donation tab , there is a donation amount for project this round

for example for  this project https://staging.giveth.io/project/how-many-photos-is-too-many-photos?
donation in round  is shown $0.75 and Raised from 6 contributors  but actually there is no donation for this project in the round 

https://staging.giveth.io/project/how-many-photos-is-too-many-photos?tab=donations
![image](https://github.com/Giveth/impact-graph/assets/111529185/4e6310a1-d5c3-497a-b4e6-48d498bf3ddc)

_____

https://staging.giveth.io/project/mejan?tab=donations
![image](https://github.com/Giveth/impact-graph/assets/111529185/141895c7-7943-4f15-b9ab-db6090ef7a90)


_____

https://staging.giveth.io/qf/all
![image](https://github.com/Giveth/impact-graph/assets/111529185/240381ed-7a56-4f38-8ced-04930d5d0aa0)

**Comment by maryjaf** [comment]
> This project has a donation in a round but in the right box in qf round donation tab, "Be the first to give!" is shown

- [x]  2- It seems this problem hasn't been fixed 

Please take a look on below screen record @CarlosQ96 @RamRamez 
Number of contributor and total donation in the round should be shown 2 unique donor and 31$ like as total donations 
 https://staging.giveth.io/project/abcdhgjkk?tab=donations 

https://github.com/Giveth/impact-graph/assets/111529185/f0a18f36-3411-4cea-82cd-7bf749705177

**Comment by maryjaf** [comment]
- [x] 3- when the round is over, the amount of donation and estimated matching is removed from QF donation round tab 

![image](https://github.com/Giveth/impact-graph/assets/111529185/c515320c-abab-4c4d-9864-3fa88ff74e93)

**Comment by RamRamez** [comment]
@maryjaf No.1 and No.3 are fixed.
For No.2 please note that in the table we don't show recurring donations but we count them in the total USD value and unique donors

**Comment by maryjaf** [comment]
> * 1- I see some strange behavior on stg
> * I created new round
> * I added projects to this round
> * I haven't donated to these project yet
> * but in qf round donation tab , there is a donation amount for project this round

It hasn't been fixed @RamRamez 
https://staging.giveth.io/project/how-many-photos-is-too-many-photos?tab=donations
Maybe there is a problem for this project "how-many-photos-is-too-many-photos"
![image](https://github.com/Giveth/impact-graph/assets/111529185/e83df5ff-4c7a-4b8b-937f-465254b80587)

**Comment by RamRamez** [comment]
@maryjaf that project had some old data in total donations column, if you add project to a new QF round or if you donate, old data will be deleted, I just donated to that projects and stats updated correctly.

**Comment by mhmdksh** [comment]
@CarlosQ96 @Rolazo @maryjaf Is the progress on this final?? Can you provide the latest update on this??
Moreover, is this pushed to `staging` and `production`??

**Comment by RamRamez** [comment]
@mhmdksh It's only on staging now because @maryjaf is not finished yet with testing. It will be on production on next release.
