### ISSUE TITLE
zkEVM | Adding zkEVM (Mainnet) into impact-graph production

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1617]
Token list:

**-Name,	Symbol, decimals, address, coingeckoID**

- Matic Token,	MATIC,  18,  0xa2036f0538221a77a3937f1379699f44945018d0, matic-network
- Wrapped Ether,	WETH , 18 , 0x4F9A0e7FD2Bf6067db6994CF12E4495Df938E6e9, weth
- USD Coin,	USDC,   6,   0xa8ce8aee21bc2a48a5ef670afcc9274c7bbbc035, usd-coin
- Tether USD,	USDT,   6,   0x1e4a5963abfd975d8c9021ce480b42188849d41d, tether
- Dai Stablecoin,	DAI,  18,   0xc5015b9d9161dca7e18e32f6f25c4ad850731fd4, dai
- PancakeSwap Token,	CAKE,    18 ,   0x0D1E753a25eBda689453309112904807625bEFBe, pancakeswap-token
- Rocket Pool ETH,	rETH,   18,    0xb23c20efce6e24acca0cef9b7b7aa196b84ec942, rocket-pool-eth
- Frax,	FRAX ,   18,    0xFf8544feD5379D9ffa8D47a74cE6b91e632AC44D, frax
- Staked MATIC,	stMATIC ,   18  , 0x83b874c1e09d316059d929da402dcb1a98e92082, lido-staked-matic
- Balancer,	BAL,     18 ,    0x120ef59b80774f02211563834d8e3b72cb1649d6, balancer
- Curve DAO Token,	CRV ,  18   , 0x3d5320821bfca19fb0b5428f2c79d63bd5246f89, curve-dao-token
- Gravita Debt Token	GRAI   18    0xca68ad4ee5c96871ec6c6dac2f714a8437a3fe66, grai
- ChainLink Token,	LINK ,  18  ,   0x4b16e4752711a7abec32799c976f3cefc0111f2b, chainlink
- EURA aka agEUR,	EURA,  18 ,   0xa61beb4a3d02decb01039e378237032b351125b4, ageur
- Aave Token,	AAVE,   18 ,    0xa61beb4a3d02decb01039e378237032b351125b4, aave
- Wrapped BTC,	WBTC ,     8 ,   0xea034fb02eb1808c2cc3adbc15f447b93cbe08e1, 
- Ankr Staked ETH,	ankrETH ,  18, 0x12d8ce035c5de3ce39b1fdd4c1d5a745eaba3b8c, ankreth
- USD Coin, USDC.E, 6, 0x37eaa0ef3549a5bb7d431be78a3d99bd360d19e5, bridged-usdc-polygon-pos-bridge
- Frax Ether ,frxETH, 0xCf7eceE185f19e2E970a301eE37F93536ed66179, frax-ether

**Make top 10 GIVback eligible**

**Comment by mohammadranjbarz** [comment]
@MoeNick  Who will give me the logos for the tokens?
and I will set isGivbackEligible :false for all of them, you can change them alter if you want to

**Comment by mohammadranjbarz** [comment]
@MoeNick Who will give me the logos for the tokens? (As I'm going to implement FE side as well)

**Comment by MoeNick** [comment]
@mosaeedi will give us today.

**Comment by mosaeedi** [comment]
Hey,
We had most of the token on the DS,

Just add these missing ones: 
CAKE, GRAI, EURA

I couldn't find anything for this one,

` USD Coin, USDC.E, 6, 0x37eaa0ef3549a5bb7d431be78a3d99bd360d19e5, bridged-usdc-polygon-pos-bridge `


I think it's the same as USDC, which we have it! 

Take a look here -> [Figma Link](https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=4767-71303&t=gQq77yBb8Db8xrPg-4)

**Comment by mohammadranjbarz** [comment]
@MoeNick These two tokens have the same address in the issue secription, can you give me the correct data for them?

* EURA aka agEUR, EURA, 18 , 0xa61beb4a3d02decb01039e378237032b351125b4, ageur
* Aave Token, AAVE, 18 , 0xa61beb4a3d02decb01039e378237032b351125b4, aave

**Comment by MoeNick** [comment]
- agEUR: 0xa61beb4a3d02decb01039e378237032b351125b4 - https://zkevm.polygonscan.com/token/0xa61beb4a3d02decb01039e378237032b351125b4
 - AAVE: 0x68791cfe079814c46e0e25c19bcc5bfc71a744f7 - https://zkevm.polygonscan.com/token/0x68791cfe079814c46e0e25c19bcc5bfc71a744f7 
 
 Sorry for the mistake. Aave should change
