### ISSUE TITLE
Endaoment Projects can participate in the GIVeconomy 

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1627]
Endaoment projects should be able to benefit and provide benefits associated with GIVbacks and GIVpower

- [ ] Users that donate to Endaoment projects can receive GIVbacks and donations are included in givbacks calculations
- [ ] Users can boost Endaoment projects with GIVpower
- [ ] GIVpower table shows correct data
- [ ] estimated ranking shows correctly

FYI @laurenluz

**Comment by divine-comedian** [comment]
Needs to test that donation to Endaoment project was captured in our givbacks-calculation on staging 

to test: 
make a donation to an endaoment project - check on the givbacks-calculation API and adjust to the dates to look for ONLY when you made the donations to endoament 

check that your address is included in the query response and there is an amount of GIVbacks you would receive

test as well that you can use GIVpower boosting on Endaoment projects, here's the guide! https://docs.giveth.io/giveconomy/givpower

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @Rolazo 

Do we have the URL of givebacks calculations for staging? so I can verify

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

After successfully making donations to 2 Endaoment projects, checked the the Givback calculations API, but it didnt return any data for the donations I made, I couldnt find my wallet address as well as the Givbacks donated.



These are the Endaoment Projects I donated to


![image](https://github.com/user-attachments/assets/9f3d59c4-bb06-4a6b-9e74-6b5663c258bc)


![image](https://github.com/user-attachments/assets/dd6e0869-3802-4712-ab56-ea8551c83cad)

**Comment by divine-comedian** [comment]
@mohammadranjbarz can you check this failed test 

So we're on the same page I was informed these are the givbacks-calculation deployments we should use:

givbacks calc staging (https://givback.develop.giveth.io/api-docs/)
givbacks calc production (https://givbacks.giveth.io/api-docs/)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - could you provide the tx hashes of the donations you made that did not appear in the givbacks-calculations

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 


You can check with these transaction hashes

0x1239387141284d846569f51de729a978968ad93842612650fd46cca1e27a45bd
0x6f2e8cc0565c0c7275584eb06f5ae62ef923ad5e70ddf766a2bfc1ffd313a73c

**Comment by mohammadranjbarz** [comment]
> 0x6f2e8cc0565c0c7275584eb06f5ae62ef923ad5e70ddf766a2bfc1ffd313a73c

@LatifatAbdullahi 

Ok got it, you know in the givback-calculation we have a term named `purple list`, there some addresses that we exclude them from givbacks, for instance the recipient address of verified projects are not eligible for givbacks. I checked you address and saw you are in the purple list so it's a normal behaviour to not include your donations, you can see the purple list here
https://givback.develop.giveth.io/api-docs/#/default/get_purpleList 

So in these cases the donations would not be in the eligible-donations list, but you still can find them in the not-eligible-donations
https://givback.develop.giveth.io/api-docs/#/default/get_not_eligible_donations

<img width="1512" alt="Screenshot 1403-05-11 at 11 49 40 in the morning" src="https://github.com/user-attachments/assets/119d9671-5f6b-4980-90d7-d9bd422933bb">


Please donate with a new wallet that is not in the purple list (is not recipient of any verified project) and check this issue again

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 


I have attempted to make donations to different Endaoment projects on staging but they all failed and throwing same error message, please do you know why? 


![image](https://github.com/user-attachments/assets/af30a1f4-75f4-4d93-86db-c8bb0b80283e)

Console tab

![image](https://github.com/user-attachments/assets/cae475cb-eaf7-4dc4-b918-b5ee27061c61)



Network tab
![image](https://github.com/user-attachments/assets/94f97ce9-4a25-43ff-80e3-a8e335341160)

**Comment by divine-comedian** [comment]
I was able to donate successfully, can you please re-test @LatifatAbdullahi 



![Image](https://github.com/user-attachments/assets/66a17d70-aa5b-4886-bc99-6fc955416868)

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

Test Update: **Pass**

This works as expected, I donated successfully to an Endaoment project and the details are present in the GIV calculation API


![image](https://github.com/user-attachments/assets/3d1e9d62-1a0d-4b1b-a7a4-0a07a29c6916)



https://github.com/user-attachments/assets/8cb96358-ba3f-4d44-bcc1-0a2f1a831f0f
