### ISSUE TITLE
Allow user to sign over any network for getting token 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#163]
If we comment network cheking in front after signing message to get token we get error

![photo_2021-10-13 20.29.33.jpeg](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/a772d396-4c27-45d8-afe3-571177bf6eb8)

**Comment by mohammadranjbarz** [comment]
@divine-comedian @divine-comedian  Test scenario for this issue is that you can login to your account with 
Rinkbey, Mainnet, xdai, ...
before we were forcing user to sign login message over xdai network

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` 

I can successfully sign in to giveth from MOST networks via metamask. 
I tested all test networks (rinkeby,kovan,goerli,ropsten), xDAI, polygon, BSC, mainnet and was able to do it no problem

however when I tried on Avalanche (AVAX) the pop-up to sign-in came, I signed it. however I was not signed in and was stuck on this screen - 

![image](https://user-images.githubusercontent.com/67759413/137814673-75023eb2-9e5b-444b-8dd8-b3c7dd525e80.png)

**Comment by mohammadranjbarz** [comment]
> testing on `next.giveth.io`
> 
> I can successfully sign in to giveth from MOST networks via metamask. I tested all test networks (rinkeby,kovan,goerli,ropsten), xDAI, polygon, BSC, mainnet and was able to do it no problem
> 
> however when I tried on Avalanche (AVAX) the pop-up to sign-in came, I signed it. however I was not signed in and was stuck on this screen -
> 
> ![image](https://user-images.githubusercontent.com/67759413/137814673-75023eb2-9e5b-444b-8dd8-b3c7dd525e80.png)

Nice catch, it is fixed now and deployed
you can test it again on 
https://next.giveth.io

**Comment by divine-comedian** [comment]
successful log in on AVAX! 

![image](https://user-images.githubusercontent.com/67759413/137914933-2c210f17-1044-4fdc-b3e5-28eaebea3def.png)
