### ISSUE TITLE
Endaoment projects are eligible for QF

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1641]
Endaoment imported projects should be eligible and totally compatible with QF, this includes: 

- [ ] Can be added to a QF round
- [ ] Can receive donations while inside a QF round
- [ ] estimated matching shows properly
- [ ] associated project card shows properly on donate page
- [ ] donations made show up properly in associated QF donation table

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test Update

 Can be added to a QF round - Pass
 Can receive donations while inside a QF round - Pass
 estimated matching shows properly - Pass
 associated project card shows properly on donate page - Pass
 donations made show up properly in associated QF donation table - Pass


![ru](https://github.com/user-attachments/assets/d6b8fc95-e77e-4eb6-a4d7-cc8eb4b9222f)


![mtc](https://github.com/user-attachments/assets/6641cf4e-441c-4afc-b7f2-047ab1ffb84f)


![image](https://github.com/user-attachments/assets/87b07517-66d3-4f26-b537-f4bf8579401d)


![image](https://github.com/user-attachments/assets/7a451183-3d72-449c-86d2-8f07f8d7fa9d)
