### ISSUE TITLE
Prevent badge revoke status change of endaoment projects from lack of updates

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1642]
Typically when a project does not a provide an update in a certain time frame we change its revoked status, eventually after a while of not posting updates the project moves to a "ready to revoke" status, indicating it as eligible to have its verified badge revoked by the project support team. 

Since Endaoment projects won't be able to provide updates we should prevent this behaviour for those projects. Endaoment projects should not have their  "ready to revoke" or verification status changed from not providing updates

## AC

- [ ] endaoment projects don't have their status changed from not providing updates 
- [ ] regular projects still have their status changed from not providing updates

**Comment by divine-comedian** [comment]
@mohammadranjbarz - how does it currently work on staging? does the badge revoke status change when they have not provided an update - how long does it take on staging? Can we update it to be an amount of time that can be reasonably tested.

**Comment by mohammadranjbarz** [comment]
@divine-comedian We do these actions on staging:
- After `45` days: Send notification to warn about adding project update
- After `90` days: Send notification in order to last warning about adding project update
- After `104` days: Change status of project to **Up For Revoke** so Ashley review them and make them unverufued


Yes we can change them for staging ENV, please tell me to change days to what you want

**Comment by divine-comedian** [comment]
> @divine-comedian We do these actions on staging:
> 
> * After `45` days: Send notification to warn about adding project update
> * After `90` days: Send notification in order to last warning about adding project update
> * After `104` days: Change status of project to **Up For Revoke** so Ashley review them and make them unverufued
> 
> Yes we can change them for staging ENV, please tell me to change days to what you want

Let's change only the first warning notification to **10 minutes** - we should assume that even the first notification should never be fired for these projects so let's limit the changes to only this first one.

**Comment by divine-comedian** [comment]
@mohammadranjbarz what is the update on this remaining issue?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz what is the update on this remaining issue?

We just can set days, so the minimum time that I could set is `1` day, I did it now

**Comment by divine-comedian** [comment]
@LatifatAbdullahi to test this issue - we should check on the staging admin panel and ensure for endaoment projects that the Verified Status should be empty/null

![image](https://github.com/user-attachments/assets/9fa030f7-bf87-4b16-9215-1a50e0ab6bd3)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

Test Update

The "Verification status" for Endaoment projects is empty/null


![VER](https://github.com/user-attachments/assets/e0c75080-6332-41c0-a0dc-9888d51cb553)
