### ISSUE TITLE
query cache is not working in some functions

### ISSUE THREAD

**Issue by ae2079** [Giveth/impact-graph#1650]
When I was changing some code related to my issue, I realized that in some functions like this line:
https://github.com/Giveth/impact-graph/blob/50b943bfa5dae4e48446c89bdeea8c9d5232f1dc/src/repositories/donationRepository.ts#L250-L257
query.cache() method is called after the query execution, so the cache is not set, thus the cache does not work.

**Comment by ae2079** [comment]
@RamRamez 
Do we need a QA test for this or we can move this issue to done state?

**Comment by RamRamez** [comment]
@ae2079 I think it's ok to move it to done

**Comment by ae2079** [comment]
Thank you @RamRamez
