### ISSUE TITLE
Create Documentation for Integration

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1659]

**Comment by mohammadranjbarz** [comment]
# System Architecture Documentation (Phase 1)

## Overview
This document provides a clear overview of our current system architecture and proposes enhancements to better manage organizational preferences and project presentations. It outlines managing organizations, projects, and tokens within a blockchain-based environment, focusing on scalability and robustness.

## Current Architecture

### Entity Relationship Diagram
[![](https://mermaid.ink/img/pako:eNptkMEOgjAMhl9l6Rl4AG5EiUETMMjJ7DJYBSLbzNhiDPDuDhETjb21_b4_aQeoFEcIAfW2ZbVmgkriKst3UZqcoyLJUjKOvq8GcsyzfbwpSEgoNKyn8BcNgnEkRXaI019w9ScX55gvb0ZL7JSse2LUaiwxw9LMJa0oUROJ5q70NeHLZqISPBCoBWu5u-UlUDANCqQwR3O8MNuZOXdyKLNGnR6ygtBoix7YG2cG3w-A8MK6_jONeWuUXsjpCcn-Xo0?type=png)](https://mermaid.live/edit#pako:eNptkMEOgjAMhl9l6Rl4AG5EiUETMMjJ7DJYBSLbzNhiDPDuDhETjb21_b4_aQeoFEcIAfW2ZbVmgkriKst3UZqcoyLJUjKOvq8GcsyzfbwpSEgoNKyn8BcNgnEkRXaI019w9ScX55gvb0ZL7JSse2LUaiwxw9LMJa0oUROJ5q70NeHLZqISPBCoBWu5u-UlUDANCqQwR3O8MNuZOXdyKLNGnR6ygtBoix7YG2cG3w-A8MK6_jONeWuUXsjpCcn-Xo0)



### Entity Descriptions
- **Organization**: Represents entities like NGOs or social enterprises, managing multiple projects and having access to various tokens.
- **Project**: Specific initiatives or campaigns managed by an organization.
- **Token**: Different types of cryptocurrency tokens, each associated with a `networkId` identifying the blockchain network.

## Proposed Enhancements

### Updated Entity Relationship Diagram
[![](https://mermaid.ink/img/pako:eNptkcFugzAMhl8l8rntA3CrBprYJJg6dplyMcTQaCGekrBpAt59UNaKrvUt8fd_cpweKlYEEZCLNTYOW2nFVPnhcZ-l7_sizTMxDNst9-LlkD8lD4WIhIQjegl30d1uGESRPyfZf_CcHyfdxFzlZrQkw7bxIvA5sWj65TCXD07bRlgK3-w-UrV0xjuDrEIlsyG0wnLQta4waLax9lgaUjfqir_IpS029ObMrcNR1bkZjNmeRD6xK9F4_dLVEJc-bKAl16JW09ZPgIRwpJYkzEtQVGNnwryBcUKxC_z6YyuIgutoA92nwkB_XwVRjcZfbhOlA7uFHH8BysWS_Q?type=png)](https://mermaid.live/edit#pako:eNptkcFugzAMhl8l8rntA3CrBprYJJg6dplyMcTQaCGekrBpAt59UNaKrvUt8fd_cpweKlYEEZCLNTYOW2nFVPnhcZ-l7_sizTMxDNst9-LlkD8lD4WIhIQjegl30d1uGESRPyfZf_CcHyfdxFzlZrQkw7bxIvA5sWj65TCXD07bRlgK3-w-UrV0xjuDrEIlsyG0wnLQta4waLax9lgaUjfqir_IpS029ObMrcNR1bkZjNmeRD6xK9F4_dLVEJc-bKAl16JW09ZPgIRwpJYkzEtQVGNnwryBcUKxC_z6YyuIgutoA92nwkB_XwVRjcZfbhOlA7uFHH8BysWS_Q)
### Changes to Organization Entity
- **notificationDisabled**: A boolean indicating whether notifications or emails should be sent for projects of this organization.
- **coverImageUrl**: A URL pointing to a cover image for projects associated with the organization.
- **recurringDonationsEnabled**: A boolean to enable or disable recurring donations for projects.

## Examples

### Current Organizations
- **Trace**
- **Giveth**
- **Giving Blocks**

### Proposed Organization Examples
- **Trace**
  - **Notification Disabled**: True
  - **Cover Image URL**: "https://example.com/trace-cover.jpg"
  - **Recurring Donations Enabled**: True

- **Giveth**
  - **Notification Disabled**: True
  - **Cover Image URL**: "https://example.com/giveth-cover.jpg"
  - **Recurring Donations Enabled**: True

- **Giving Blocks**
  - **Notification Disabled**: False
  - **Cover Image URL**: "https://example.com/givingblocks-cover.jpg"
  - **Recurring Donations Enabled**: True


### Tokens examples:
- **ETH (Ethereum)** - `networkId: 1`
- **WBTC (Wrapped Bitcoin)** - `networkId: 10`
- **USDC (USD Coin)** - `networkId: 100`
