### ISSUE TITLE
Fetch email addresses of related project owner addresses

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1673]
A campaign from the Devcon team has issued deep discounts on Devcon tickets for certain project owners on Giveth. I coordinated this criteria with them and they have issued the tickets to the project owner addresses. 

We need to find out their email addresses so we can send them an email, informing them of their discount. There's over 200 addresses so a script would be a good time saver for us :D 

Here's a JSON file of the included project owner addresses: 
https://github.com/efdevcon/monorepo/blob/main/discounts/outputs/pg-projects-giveth.json

**Comment by RamRamez** [comment]
@divine-comedian I sent you the list in DM
