### ISSUE TITLE
GIVbacks - use on-chain data to calculate GIVbacks

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#168]
@mohammadranjbarz creating things issue as per your comment in the dev call! we don't want users to be able to "game the system" by using just the APIs to determine donation amounts and therefore GIVback allocations.

Want to use on-chain data for this.

Keep us posed here if you have any updates.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz creating things issue as per your comment in the dev call! we don't want users to be able to "game the system" by using just the APIs to determine donation amounts and therefore GIVback allocations.
> 
> Want to use on-chain data for this.
> 
> Keep us posed here if you have any updates.

Thanks for creating this issue 
I would set updates here

**Comment by laurenluz** [comment]
verifying on backend that the tx has gone through

**Comment by mohammadranjbarz** [comment]
@MoeNick 
This is the issue that I said in Sync call
https://github.com/Giveth/GIVeconomy/issues/103

**Comment by MoeNick** [comment]
Shal I close this? @mohammadranjbarz
