### ISSUE TITLE
bug in detecting donations on ETC and Solana dev nets on the Staging

### ISSUE THREAD

**Issue by ae2079** [Giveth/impact-graph#1681]
@divine-comedian @ae2079 

![dn](https://github.com/Giveth/analytics-dashboard/assets/112261242/aa1ac531-2e5d-486f-aa82-25b1cd387efe)

I have made multiple donations in Ethereum Classic Mordor Network, although they were successful, they all show pending here and also does not reflect in the Analytics board.

_Originally posted by @LatifatAbdullahi in https://github.com/Giveth/analytics-dashboard/issues/9#issuecomment-2222403552_

**Comment by ae2079** [comment]
https://github.com/Giveth/analytics-dashboard/issues/9#issuecomment-2219937525
https://github.com/Giveth/analytics-dashboard/issues/9#issuecomment-2209264357
and also about these comments

**Comment by ae2079** [comment]
and maybe related to these issues:
https://github.com/Giveth/giveth-dapps-v2/issues/4371
https://github.com/Giveth/giveth-dapps-v2/issues/4368

**Comment by divine-comedian** [comment]
We should retest the feature requirements for https://github.com/Giveth/analytics-dashboard/issues/9 on ETC mordor and solana devnet once this issue is fixed.

**Comment by ae2079** [comment]
> We should retest the feature requirements for [Giveth/analytics-dashboard#9](https://github.com/Giveth/analytics-dashboard/issues/9) on ETC mordor and solana devnet once this issue is fixed.

the bug related to Solana dev net is because of using test net id (102) instead of devnet id (103), and now it is compatible with the backend and fixed

**Comment by divine-comedian** [comment]
> > We should retest the feature requirements for [Giveth/analytics-dashboard#9](https://github.com/Giveth/analytics-dashboard/issues/9) on ETC mordor and solana devnet once this issue is fixed.
> 
> the bug related to Solana dev net is because of using test net id (102) instead of devnet id (103), and now it is compatible with the backend and fixed

@ae2079 - did you also discover why ETC mordor was not working?

**Comment by ae2079** [comment]
> > > We should retest the feature requirements for [Giveth/analytics-dashboard#9](https://github.com/Giveth/analytics-dashboard/issues/9) on ETC mordor and solana devnet once this issue is fixed.
> > 
> > 
> > the bug related to Solana dev net is because of using test net id (102) instead of devnet id (103), and now it is compatible with the backend and fixed
> 
> @ae2079 - did you also discover why ETC mordor was not working?

no, I'm on it

**Comment by ae2079** [comment]
@divine-comedian 
The bug on not detecting Mordor ETC donations was related to not setting environment variables, and as I don't have access to change the deployments, asked @RamRamez to set the correct value of them, and now by adding a default value for Mordor ETC URL, the bug is fixed and now we can donate to projects with etc mordor on staging @maryjaf @LatifatAbdullahi 
(I donated to this project successfully: https://staging.giveth.io/project/teach-music-to-children?tab=donations )

**Comment by divine-comedian** [comment]
Ok thanks! 

@LatifatAbdullahi - this was related to when testing the analytics features on those two devnets.

### to test 

1. make donations using ETC mordor and solana devnet
2. ensure donations show as success and not pending if the donation was successful.(might take up to 5 mins to confirm)
3. check  https://staging.stats.giveth.io/ to ensure donations appear there as well - donation count, total usd donation value (if token donated had a tracked price)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @ae2079 

**Test Update**

-make donations using ETC mordor - Pass
-make donations using solana devnet - Pass
-ensure donations  with ETC Mordor show as success and not pending if the donation was successful - Pass
-ensure donations  with Solana devnet show as success and not pending if the donation was successful - Pass


**Analytics**
**ETC Mordor**
- Project count -  Pass
- Donors count - Pass
- Donations count - Pass
- Total donations in USD - Pass

**Solana Devnet**
- Project count -  Pass
- Donors count - Pass
- Donations count - Pass
- Total donations in USD - Pass

![image](https://github.com/user-attachments/assets/22606388-b51d-41f5-92eb-64d57824815d)











The staging Analyticst throws this error ocassionally

![image](https://github.com/user-attachments/assets/68b93c54-8a89-40aa-ad4f-eff88a91ed6b)

**Comment by LatifatAbdullahi** [comment]
@divine-comedian 

Although this issue is fixed, I found  two new issues with donating with Solana devnet

https://github.com/Giveth/impact-graph/issues/1710
https://github.com/Giveth/impact-graph/issues/1711
