### ISSUE TITLE
prevent users from selecting endaoment as sub-category on project creation and edit

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1685]
We should not allow users to set their project category as Endaoment while creating or editing a project

**Comment by divine-comedian** [comment]
not implemented yet - we should do it before we release.

**Comment by mohammadranjbarz** [comment]
@LatifatAbdullahi @maryjaf  @divine-comedian 
Now you can test it on staging

**Comment by LatifatAbdullahi** [comment]
@divine-comedian  @mohammadranjbarz 


**Create Project**

I was able to select "Endaoment" when creating a new project, but at the point of publishing, it threw a response **This category is not valid**, I was unable to complete the creation process.

![image](https://github.com/user-attachments/assets/692931ca-444a-4d91-ae50-1bd276e42add)



**Edit Project**

I was able to select the Endaoment option when editing a project, but couldn't update successfully as it threw same response


![image](https://github.com/user-attachments/assets/0f07a8b6-5c0b-4cd2-b584-c3713bcb2dfd)



Please let me know if the implementation is okay this way, so I can close the task @divine-comedian

**Comment by mohammadranjbarz** [comment]
> @divine-comedian @mohammadranjbarz
> 
> **Create Project**
> 
> I was able to select "Endaoment" when creating a new project, but at the point of publishing, it threw a response **This category is not valid**, I was unable to complete the creation process.
> 
> ![image](https://private-user-images.githubusercontent.com/112261242/350535533-692931ca-444a-4d91-ae50-1bd276e42add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDkxMDYsIm5iZiI6MTcyMTQ0ODgwNiwicGF0aCI6Ii8xMTIyNjEyNDIvMzUwNTM1NTMzLTY5MjkzMWNhLTQ0NGEtNGQ5MS1hZTUwLTFiZDI3NmU0MmFkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNDEzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmIzNmM1MTBhYjRkMTE5MmVjMjM2MGM1ZDQ5NDMzMjYxYjI0OTlkYTlkMmQ2NDJkNWI1MTBlZDdjNDcyNTIyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.RmSIXRWP8OYVQ7aGWO6enRjBpOJJx9F1yQJkG5VCY_A)
> 
> **Edit Project**
> 
> I was able to select the Endaoment option when editing a project, but couldn't update successfully as it threw same response
> 
> ![image](https://private-user-images.githubusercontent.com/112261242/350536380-0f07a8b6-5c0b-4cd2-b584-c3713bcb2dfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0NDkxMDYsIm5iZiI6MTcyMTQ0ODgwNiwicGF0aCI6Ii8xMTIyNjEyNDIvMzUwNTM2MzgwLTBmMDdhOGI2LTVjMGItNGNkMi1iNTg0LWMzNzEzYmNiMmRmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyMFQwNDEzMjZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NzNkMGI2MTUyYTM3NGFlNTZlYzc0MWU2ZTc4OWU0NWYxNzljYjVkNmFjMmM3YzMwNGNkZDdlNmM4ZWI5NDYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R7AcD40t0LEX-Q8C-zbni9MOenuJP0KEE-W97SzOKlA)
> 
> Please let me know if the implementation is okay this way, so I can close the task @divine-comedian

Thanks @LatifatAbdullahi  for reporting
It's ok now

<img width="932" alt="Screenshot 1403-04-30 at 12 33 19 in the afternoon" src="https://github.com/user-attachments/assets/07720586-8908-4b99-aebe-b02ac1191fa5">

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz 

When creating a project, there is now no "Endaoment" category.
However, when editing projects I observed that all the categories are missing for Users to probably change to a different category or choose from.

![se](https://github.com/user-attachments/assets/09167989-8ec2-4e69-b498-4d2ac48aa71f)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - can you please test this again.

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @mohammadranjbarz 

This issue with Category is no longer reproducible

![image](https://github.com/user-attachments/assets/731a8cec-72a9-4bac-b839-ad214507754d)



Therefore, Users are unable to select "Endaoment" as a sub-category when creating a project or editing a project.
