### ISSUE TITLE
Stellar | Adding Stellar into impact-graph (main DB)

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1688]
**Explorer:** https://stellar.expert/explorer/public

**Token List:**
- Symbol, Name, address, coingeckoID, nonEVM
- XLM, Stellar Lumens, CAS3J7GYLGXMF6TDJBBYYSE3HQ6BBSMLNUQ34T6TZMYMW2EVH34XOWMA, stellar, isEVM=false

**Notes:**
- [ ] Stellar tokens are different from 0x addresses, we currently have non-evm fields, Im suggesting adding another as `isQR`   for those tokens that we handle with QR without the need of connecting to the DApp. 
- [ ] For more details on changes please read #1690 (backend) and https://github.com/Giveth/giveth-dapps-v2/issues/4422 (Frontend)

**Comment by maryjaf** [comment]
This token is added in admin @MoeNick
https://impact-graph.serve.giveth.io/admin/resources/Token/records/306/show
