### ISSUE TITLE
Stellar | Support stellar on some endpoints

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#1690]
- [x] SaveDonation
- [x]  VerificationDonation
- [x]  Filter token list
- [x]  Create project
- [x]  Add recipient address to a project 
- [x]  Filter projectlist (AcceptFunds)

Also please check if saveDoantion backup service can get affected by adding a new chain or not.

**Comment by maryjaf** [comment]
> * SaveDonation
> * [ ]   VerificationDonation

I couldn't complete the donation flow yet

**Comment by maryjaf** [comment]
> Also please check if saveDoantion backup service can get affected by adding a new chain or not.

How can I check it ? @Meriem-BM @MoeNick

**Comment by maryjaf** [comment]
> > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> 
> How can I check it ? [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)

Kindly reminder

**Comment by Meriem-BM** [comment]
> > > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> > 
> > 
> > How can I check it ? [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)
> 
> Kindly reminder

@maryjaf will just wait for review and will tag you on every issue

**Comment by maryjaf** [comment]
> > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> 
> How can I check it ? [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)

I had  a question about test of this part 

"Also please check if saveDoantion backup service can get affected by adding a new chain or not."

**Comment by MoeNick** [comment]
> > > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> > 
> > 
> > How can I check it ? [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)
> 
> I had a question about test of this part
> 
> "Also please check if saveDoantion backup service can get affected by adding a new chain or not."

More context for @Meriem-BM on this:
The functionality of the donation backup service is for successful donations on-chain that BE failed to save, in this case, we save them in MONGODB so we can retry verifying or saving them by impact-graph. in our case I guess as we don't load the donation modal, it won't trigger that process and it will be fine. However, we have to make sure it won't trigger for Stellar.

**Comment by maryjaf** [comment]
I think for test the mechanism of donation backup  service I need your help @Meriem-BM 
How can we produce this situation?

for example I complete donation in LOBSTR, but there is a problem in getting last status for a few hours, in this situation what is the status of donation  in our dapp?

**Comment by Meriem-BM** [comment]
> > > > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> > > 
> > > 
> > > How can I check it ? [@Meriem-BM](https://github.com/Meriem-BM) [@MoeNick](https://github.com/MoeNick)
> > 
> > 
> > I had a question about test of this part
> > "Also please check if saveDoantion backup service can get affected by adding a new chain or not."
> 
> More context for @Meriem-BM on this: The functionality of the donation backup service is for successful donations on-chain that BE failed to save, in this case, we save them in MONGODB so we can retry verifying or saving them by impact-graph. in our case I guess as we don't load the donation modal, it won't trigger that process and it will be fine. However, we have to make sure it won't trigger for Stellar.

Hey @mohammadranjbarz if you can explain me when the backup service is triggered.

**Comment by MoeNick** [comment]
@MohammadPCh usually makes it testable. :)

**Comment by maryjaf** [comment]
> Also please check if saveDoantion backup service can get affected by adding a new chain or not.

based on conversation on chat I think it needs your final approvement @Meriem-BM 
cc: @MoeNick

**Comment by Meriem-BM** [comment]
> > Also please check if saveDoantion backup service can get affected by adding a new chain or not.
> 
> based on conversation on chat I think it needs your final approvement @Meriem-BM 
> cc: @MoeNick  
> 
> 
> 
> 

I'll DM @mohammadranjbarz about this.

**Comment by divine-comedian** [comment]
@Meriem-BM still needs to DM @mohammadranjbarz

**Comment by divine-comedian** [comment]
1 BLOCKER - need a confirmation that the backup service when a user donates with Stellar. 

@Meriem-BM and @mohammadranjbarz still need to chat

**Comment by Meriem-BM** [comment]
I checked the code and I saw that the backup service isn't triggered for the Stellar chain, it's only triggered with the regular donation nodal.

Can we move it to done @maryjaf?

**Comment by divine-comedian** [comment]
@Meriem-BM does this require a hotfix or is it already on production?

**Comment by MoeNick** [comment]
It's on production.
