### ISSUE TITLE
Return all data that front need for project detail page in an endpoint

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#170]
In giveth-next when leading the project detail page the client call multiple requests continuous to get the page needed information you can see the front code here

https://github.com/Giveth/giveth-next/blob/mateo-mig/pages/project/%5Bslug%5D.js#L45-L91

@RamRamez  wants a query from backend then we can return all needed data for him, then he can just call one endpoint and then render the page.
@CarlosQ96  if you have any solution or you can implement it or you think it's not a good solution, please help us

**Comment by CarlosQ96** [comment]
After checking the project details, projects with 900 donations like Giveth are taking over 3.8-4.5 seconds to load all that data. Now imagine if it had 400 project updates and reactions, this would keep getting worse. 

Even if we move all to server side, we would be loading a lot of data in-memory, which isn't the best idea either under heavy traffic.

**Comment by CarlosQ96** [comment]
I have a few thoughts @RamRamez @mohammadranjbarz:

First, I think unifying everything into one endpoint is not the ideal way, as reactions, project updates and donations can grow indefinitely. I remember Mateo back in July removed the donations from the query because it was causing timeout errors on the impact graph.
Maybe if we upgrade to piñata pro plan this won't be an issue, not sure if @geleeroyale did any server upgrade that fixed the issue, or the recent frontend optimizations alleviated the problem.

Another point against unifying them, is that adding pagination in the same endpoint for each entity would be more complex and lead to retrieving redundant data and remapping said info every-time.

**Comment by CarlosQ96** [comment]
@MoeNick @mohammadranjbarz @RamRamez 
My two proposals are:
1. We keep them separated, but unify some, like so:
    - Project by slug will include the admin user. Right now Giveth-Next makes 1 extra request to retrieve 1 user which is redundant and adds latency.
    - Add pagination to the donations endpoint, we shouldn't need to retrieve the 900+ records in one go. This can include the totalCount to calculate the pages and the total ethAmount.
    - We leave the projectUpdates/reactions as is, I'll leave the pagination optional. There is a lot of logic in the view regarding this, potentially lots of breaking changes, so not sure if combining them is a good idea.
    - Add cache to projectBySlug endpoint.

2. **(Don't recommend)** Considering we are close to launch: We unify them into one graphql query, and add cache for subsequent fast results, moving all the loading to the server. 
However, we would need to revisit this in the future if a project grows wayyy too much, and adding pagination will be more complex. I would rebuild this props object from the backend (excluding trace):
 ```javascript
 props: {
    project: traceProject || project || null,
    donations: donations || null,
    updates: updates || null,
    reactions: reactions || null,
    admin: admin?.data?.user || {},
    error: errors ? JSON.stringify(errors) : false
 }
 ```
 
 I think we should go with **No. 1**

**Comment by CarlosQ96** [comment]
The Main bottleneck is the huge amount of donations and the images.
Images issue can be alleviated if we configure a CDN with piñata pro.

Keep in mind we can add cache to many of those graphql queries too.

Let me know if you guys have more ideas.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
Thanks man 
@RamRamez 
I think adding pagination is the good one, but if frontend is slow because it just waiting for 4-5 requests to load, you can change the frontend structure to not wait for all those requests before loading page, so in this step we don't need to change backend, in the next step Carlos would add pagination for donations and project updates, and then you can use it.

@RamRamez @CarlosQ96 what do you think?

**Comment by CarlosQ96** [comment]
I agree.
I will be working on the pagination and removing the adminUser request, which will be added to the projectBySlug query.

**Comment by mohammadranjbarz** [comment]
It's now ready for test and I think @RamRamez  can approve this, @CarlosQ96  has implemented 2 queries that you can use it in project detail page to optimize your requests from client:
* It gives you project owner info alongside project info
```
query{
  projectWithAdminBySlug(slug:"agenda2030:-the-decade-of-ecological-restoration"){
    project {
      slug
    	id
    	title
    }
    admin {
      id
      firstName
    }
  }
}
```

* It fetches donations with pagination for a specific project

```
query{
  donationsByProjectId(take:10, skip: 0, projectId:36){
    donations {
      id
      valueUsd
    }
    totalCount
    totalUsdBalance
  }
}
```

**Comment by RamRamez** [comment]
@CarlosQ96 @mohammadranjbarz I need project owner on "projects" endpoint
Currently I'm using "users" but it's empty for some projects

![image](https://user-images.githubusercontent.com/73441857/141101745-d4ea5f60-a41b-41f8-b7a6-5eac358d330c.png)

**Comment by mohammadranjbarz** [comment]
> @CarlosQ96 @mohammadranjbarz I need project owner on "projects" endpoint Currently I'm using "users" but it's empty for some projects
> 
> ![image](https://user-images.githubusercontent.com/73441857/141101745-d4ea5f60-a41b-41f8-b7a6-5eac358d330c.png)

Thanks Ramin
@CarlosQ96  will do that

**Comment by MoeNick** [comment]
@CarlosQ96 back it again to in-progress

**Comment by CarlosQ96** [comment]
@MoeNick Updating the Issue I added the adminUser for Ramin a while ago. I think we should have updated the issue, but it is ready.

**Comment by CarlosQ96** [comment]
![image](https://user-images.githubusercontent.com/92376054/144282426-9f38433c-cd42-43dc-9361-c555c2a47f2d.png)
@RamRamez Already implemented this last week. We didnt update the issue sorry for that Moe.

**Comment by CarlosQ96** [comment]
Moving back to staging.
