### ISSUE TITLE
When Users attempt to donate using Solana Devnet, after inputting decimal figures, like 0.001, the value automatically turns back to 0

### ISSUE THREAD

**Issue by LatifatAbdullahi** [Giveth/impact-graph#1711]
Given User is connected to a Wallet and Signed in.
And Users attempts to doantae using Solana Devnet network
When Users input decimal figures e.g 0.0001
Then the value automatically changes back to 0
When User attempts to proceed with the donation process

https://github.com/user-attachments/assets/d122e929-978d-46ab-9563-c0a450222a16

**Comment by divine-comedian** [comment]
@MohammadPCh - can you check this out or delegate it to another FE dev?

@LatifatAbdullahi - you can confirm this only applies when on solana devnet? no other chains are affected by this bug?

**Comment by MohammadPCh** [comment]
@lovelgeorge99 can you take it? Thanks

**Comment by lovelgeorge99** [comment]
ok will work on this

> @lovelgeorge99 can you take it? Thanks
