### ISSUE TITLE
I can no longer see the email address attached to a project in the AdminBro on production

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1712]
Hey team!

I need to do some outreach to projects regarding qf rounds here soon. 

I used to be able to see the email address attached to the project in the project tab. 
But I can no longer see this :(

I no longer see it on the project tab or the project 'view' page.
![image](https://github.com/user-attachments/assets/199a921e-1801-4846-bc4c-acfff49a50c2)

https://mainnet.serve.giveth.io/admin/resources/Project/records/3007/show

Is there a way we can bring that back? I suppose I could try to copy the admin ID and then filter on the user page and get the email there. However, it It will make the process super tedious to fetch all of the email addresses that I need to do the outreach. 

@divine-comedian - not sure who to assign this to.

**Comment by divine-comedian** [comment]
@RamRamez - can you investigate this and make the required changes, I've marked this bug as P0 as we need to carry out the prep for the QF Round and Ashley is blocked.

**Comment by RamRamez** [comment]
@WhyldWanderer It's fixed on production

@maryjaf @LatifatAbdullahi please test and verify on production

**Comment by divine-comedian** [comment]
@WhyldWanderer - can you test to see if your issue is fixed

**Comment by RamRamez** [comment]
@divine-comedian it's on adminUserId column, just like before

**Comment by WhyldWanderer** [comment]
yes! Its fixed... you guys are the best! 
@divine-comedian
