### ISSUE TITLE
Optimism transaction hash is wrong

### ISSUE THREAD

**Issue by kkatusic** [Giveth/impact-graph#1719]
@mohammadranjbarz after checking generated csv file from eligible donstion: https://givbacks.giveth.io/api-docs/#/default/get_eligible_donations me and @WhyldWanderer found that when you try check some transaction hash on https://optimistic.etherscan.io/ network hash was wrong/not found for some reason. Some of has is ok, some not. 

Example hash is: https://optimistic.etherscan.io/tx/0x826976d7c600d45fb8287ca1d7c76fc8eb732030-0xa8928b33e44a3e03048a83232d0426119cf8b001-0x4cab5b9930210e2edc6a905b9c75d615872a1a7e-0.0-0.0-1719446428

I think that this "long" txHash is generated when you done some recurring donation, maybe you need to check this hash and resolve it. Seems that has contains donator address, contract address and receiver address as I can debug.

**Comment by divine-comedian** [comment]
@mohammadranjbarz just a nudge here

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz after checking generated csv file from eligible donstion: https://givbacks.giveth.io/api-docs/#/default/get_eligible_donations me and @WhyldWanderer found that when you try check some transaction hash on https://optimistic.etherscan.io/ network hash was wrong/not found for some reason. Some of has is ok, some not.
> 
> Example hash is: https://optimistic.etherscan.io/tx/0x826976d7c600d45fb8287ca1d7c76fc8eb732030-0xa8928b33e44a3e03048a83232d0426119cf8b001-0x4cab5b9930210e2edc6a905b9c75d615872a1a7e-0.0-0.0-1719446428
> 
> I think that this "long" txHash is generated when you done some recurring donation, maybe you need to check this hash and resolve it. Seems that has contains donator address, contract address and receiver address as I can debug.

@divine-comedian  @WhyldWanderer  @kkatusic 

For the donations that we create in order to track streamed donations for recurring donation we set a desired txHash, that have the recurringDonation txHash, some other data inside that, so no worries, there isn't anything wrong
