### ISSUE TITLE
Transfer Ownership of Projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#1737]
I have received a request from a user to transfer these projects as follows.
https://discord.com/channels/679428761438912522/1265487229099184179/1267721160573849621

This project: https://giveth.io/project/ecosynthesisx-real-eco-solutions
Transfer to this user: https://giveth.io/user/0x7380a42137d16a0e7684578d8b3d32e1fbd021b5

This project: https://giveth.io/project/greenpill-phangan
Transfer to this user: https://giveth.io/user/0x4a5599597c0b30742163933a2e7b0f91add87fd6

According to the Tech Leads document, I assume that I should tag @RamRamez here as he is listed for AdminBro

**Comment by RamRamez** [comment]
@WhyldWanderer transferring the ownership is possible via AdminJS project tab
first in user tab, search for the new owner and write down the user ID.
then in project tab -> select desired project -> click edit -> change Admin User Id to the new user id

**Comment by WhyldWanderer** [comment]
Hey @RamRamez - The user is wondering what is the status of this transfer. HAs it been completed?

Also.. we spoke about this already but I will comment here also for transparency that at this point I am no longer able to transfer projects via adminbro. Refer to this issue: https://github.com/Giveth/impact-graph/issues/1602

**Comment by RamRamez** [comment]
Hey @WhyldWanderer!
I've fixed transferring ownership via AdminJS and it's on staging now.

For two projects above, I changed the ownership manually, could you please check and verify?

**Comment by WhyldWanderer** [comment]
Looks good @RamRamez <3

We can close this issue now
