### ISSUE TITLE
Modify project statuses to handle Verified & GIVbacks Eligible

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1743]
With this new feature the current "Verified" project status will be modified and a new status of GIVbacks eligible will be introduced.

## Verified
Projects can become Verified by receiving the required amount of vouches through DeVouch - handled by https://github.com/Giveth/impact-graph/issues/1740

Verified projects have less benefits than GIVbacks Eligible projects, they are: 
- can be boosted by GIVpower
- is affected by instant boosting (shows higher up on list of projects when sorted by GIVpower)

## GIVbacks Eligible
Projects can become GIVbacks Eligible by following the current Project Verification process. 
- Project fills out "verification form" 
- Admin either approves or rejects application
- on approval from admin project receives status of GIVbacks Eligible

![Image](https://github.com/user-attachments/assets/52324d94-6341-431f-8838-bcc458613d8c)

----

What we'll need ASAP @MohammadPCh is the ability to change project's status to either of these new statuses at least from the admin panel and be able to apply the corresponding benefits as described above for Verified & GIVbacks Eligible.

# for testing 
## making a project "vouched" status 
- go to admin panel
- select under "Project" tab and choose a project to make vouched
- click verify button
![Image](https://github.com/user-attachments/assets/b381e22d-13a5-4ba4-b711-b75f03eae143)
- project should be able to be boosted with GIVpower
- donations to this project SHOULD NOT be eligible for GIVbacks
- check eligible donations response using https://givback.develop.giveth.io/api-docs/
- donation to project that is only vouched should not show up

## making a project GIVbacks Eligible
- check if project has submitted "GIVbacks Eligiblity" form (formerly verification form) 
- go to admin panel, "Project Verification Form" tab
- find application form from given project 
- press approve project button
![Image](https://github.com/user-attachments/assets/48bc1f96-6d64-47ff-b1be-ecba216b744e)
- this project should be able to be boosted with GIVpower
- donations to this project should be eligible for GIVbacks
- check eligible donations response using https://givback.develop.giveth.io/api-docs/
- donation to this project that is GIVbacks eligible should show up in response

**Comment by divine-comedian** [comment]
Mohammad said to wait to merge - we need to figure out givbacks-calculation issue before we can merge it

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh  @divine-comedian 

Test Update

**Vouched Project**

- Project should be able to be boosted with GIVpower - **Pass**
- Donations to this project SHOULD NOT be eligible for GIVbacks - **Pass**
- Donation to project that is only vouched should not show up - **Pass**


**GIVback Eligible Projects**


- This project should be able to be boosted with GIVpower  - **Pass**
- Donations to this project should be eligible for GIVbacks - **Pass**
- Donation to this project that is GIVbacks eligible should show up in response - **Pass**
