### ISSUE TITLE
Find missing USDC.e donations and insert them into app

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1747]
We were experiencing an issue related to Bridged USDC donations on Arbitrum not being saved on the app because the symbol was duplicate of USDC. The issue has been fixed now via the admin panel and the Bridged USDC tokens have had their symbol renamed to USDC.e 

We will need to however find the donations made on the app that we failed to save because of this mistake. 

@MohammadPCh mentioned the best way is to look on the server logs for `Smart contract address is not equal to transaction` to find the associated failed donations. We were using the incorrect token symbol on both Arbitrum and Polygon so we should check for both of those networks.

We know from a user support ticket that there is at least one donation here that will need to be inserted into the app: 

- [donation txHash](https://arbiscan.io/tx/0xa72e9a2203920390b03e100fabae6600c0c2cc13b5074f5dfaf505f0668eb685) -> to [this project](https://giveth.io/project/shielded-voting-private-and-fair-governance)

### token addresses 
Arbitrum -> https://arbiscan.io/address/0xff970a61a04b1ca14834a43f5de4533ebddb5cc8
Polygon -> https://polygonscan.com/address/0x2791bca1f2de4661ed88a30c99a7a9449aa84174

Ideally we can complete this task ASAP and DEFINITELY before the end of the QF round. 

cc: @koday1

**Comment by koday1** [comment]
Thanks for catching this and creating the issue @divine-comedian. Would be great to catch these missed donations before the current QF round ends on Aug 13. @MohammadPCh I'll be tracking this issue but let me know if you're able to take a look into this early next week

**Comment by MohammadPCh** [comment]
Hey @koday1
let me talk with @mohammadranjbarz. I'll make sure to keep you posted.

**Comment by koday1** [comment]
Sounds good, thank you @MohammadPCh

**Comment by geleeroyale** [comment]
To my knowledge this has been solved, right @mhmdksh ?
