### ISSUE TITLE
Deprecate Goerli and add Sepolia on Staging

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1748]
In order to adequately test the DeVouch integration into Giveth and also test future features affecting ETH mainnet we should remove Goerli network from the Giveth staging app and replace it with Sepolia. 

This integration will only feature wallet connections, multisig connections, donations & adding recipient addresses for Sepolia to projects. No GIVeconomy, No recurring donations. 

Chain Info --> https://chainlist.org/chain/11155111

You'll need an RPC node from devOps -> https://github.com/Giveth/devops/issues/250

## Requirements

- [ ]  Users can connect with their web wallet to the staging app with ETH Sepolia network
- [ ] users can connect to the app via the current multisig connection feature on ETH Sepolia
- [ ]  Sepolia shows as an option on switch network modal from web3modal from "Switch Network" navbar dropdown menu option when user is signed in
- [ ] Project owners can add a recipient address to their project for the Sepolia network
- [ ] Users can successfully donate native ETH on Sepolia network
- [ ] Users can successfully donate ERC20 token on Sepolia network, add this token -> [WETH](https://sepolia.etherscan.io/token/0xfff9976782d46cc05630d1f6ebab18b2324d6b14)
- [ ] Goerli does not show up as option on ANY switch network modal on web3modal
- [ ] Goerli does not show up as option to add for recipient address for project owners for their projects
- [ ] Admins can add and edit token information registered on the app via the admin panel for ETH sepolia
- [ ] donations made to verified projects on Sepolia show up in givbacks calculations

**Comment by mhmdksh** [comment]
@MohammadPCh I have DM'd you the Sepolia Endpoint URL

**Comment by divine-comedian** [comment]
@MohammadPCh - what is the progress on this task?

**Comment by divine-comedian** [comment]
@maryjaf this is ready to test - We've added Sepolia to the website on STAGING and removed Goerli. This feature does not include any GIVfarm features

**Comment by maryjaf** [comment]
Stellar issues are assigned to me and It seems stellar has more priority 
If there is no rush I'll pick it after completing stellar testing

**Comment by divine-comedian** [comment]
@LatifatAbdullahi can you pick this one up, this is blocking DeVouch integration so it also has some urgency to it :D

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh  @divine-comedian 


Test Update

Users can connect with their web wallet to the staging app with ETH Sepolia network - **Pass**
 users can connect to the app via the current multisig connection feature on ETH Sepolia - **Pass**
 Sepolia shows as an option on switch network modal from web3modal from "Switch Network" navbar dropdown menu option when user is signed in - **Pass**
 Project owners can add a recipient address to their project for the Sepolia network - **Pass**
 Users can successfully donate native ETH on Sepolia network - **Failed**
 
 **It kept requesting to switch to other networks even though Sepolia was added to recipient address and was added to the project successfully.**
 
![dy](https://github.com/user-attachments/assets/085ba772-239d-4b74-9a3b-0bae103ef0c1)
![image](https://github.com/user-attachments/assets/289e09b2-c46c-4fb7-8915-f41ec5c7119e)


![image](https://github.com/user-attachments/assets/1f5950a0-6e04-4865-9518-afd354f7b56c) 
 Goerli does not show up as option on ANY switch network modal on web3modal - **Pass**
 Goerli does not show up as option to add for recipient address for project owners for their projects - **Pass**
 Admins can add and edit token information registered on the app via the admin panel for ETH sepolia- **Failed**
 
 **There was no option for "Sepolia" in the NETWORK ID drop down list**
 

https://github.com/user-attachments/assets/06ade226-958a-4fc7-8e36-5a13e3d309de




 donations made to verified projects on Sepolia show up in givbacks calculations - **Pending**
 
 
 
 
 
![se](https://github.com/user-attachments/assets/c233511d-7ee9-4773-8ecc-0ea56fcbcd24)

![sw](https://github.com/user-attachments/assets/1c3ae4b8-1c22-4434-b7f3-dc296e34047b)

![adddddd](https://github.com/user-attachments/assets/999a4740-8457-45e8-8347-bdaef71a344c)


No Goerli
![image](https://github.com/user-attachments/assets/16bcefd7-e33c-42ff-9d8d-959144deefab)

**Comment by MohammadPCh** [comment]
@LatifatAbdullahi Thanks for reporting the issues! My PR has been merged—could you please recheck them? Thanks.  
cc: @divine-comedian

**Comment by LatifatAbdullahi** [comment]
Thanks  @MohammadPCh, however I attempted to donate using ETH native token but the transaction keeps getting rejected




https://github.com/user-attachments/assets/cc33e535-4d80-4447-8f7a-0cc8743d360f



In addition, regarding this "**Admins can add and edit token information registered on the app via the admin panel for ETH sepolia**" when adding a new token at the AdminJs,  got this error below


![image](https://github.com/user-attachments/assets/659d0250-05bd-435d-962a-0a2d52ac6a6a)



https://github.com/user-attachments/assets/f34640d9-1695-4ce3-84fc-60a955e6cc56

![image](https://github.com/user-attachments/assets/5353fb3f-59b6-4a29-878e-ce0e437380ce)

![image](https://github.com/user-attachments/assets/64eded1b-09cb-456f-95d4-718f2d5a8177)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi - when you add a token it needs to be a legitimate token that exists on the blockchain, from your screen recordings you didn't add a token address or decimals, which is likely why it fails. If you need help to understand please reach out to @maryjaf who can show you how to find and add token information.

Also for your failed transactions it is necessary for you to show the console tab, not the network tab in the developer panel, it is hard to understand the nature of your issue without seeing the console logs


![image](https://github.com/user-attachments/assets/9bd46ee6-5138-4110-92aa-5bd119a0e52b)

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh 


Here is the Console tab

![image](https://github.com/user-attachments/assets/de51054f-ebaf-4ac0-98dc-f887d7ae50d4)


https://github.com/user-attachments/assets/84cbe2fb-508e-4db2-9e7c-e6c49fa08f56


@divine-comedian got it, as you know already know, this is the first time I would add or edit token therefore, information about how it is done would have helped, so I would connect with @maryjaf when she is available tomorrow.

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh @divine-comedian 

Admins can add and edit token information registered on the app via the admin panel for ETH sepolia- **Passed**


https://github.com/user-attachments/assets/e20e4f86-dccc-4870-9b6d-1811bb6d98df




Users can successfully donate native ETH on Sepolia network - **Failed** (please check the previous attachment for error response from the  console tab)
Donations made to verified projects on Sepolia show up in givbacks calculations - **Pending**

**Comment by LatifatAbdullahi** [comment]
@MohammadPCh 


Thanks to @divine-comedian , he suggested donating to another project that wasnt mine and it went through successfully
![image](https://github.com/user-attachments/assets/cd844717-eb4e-4329-bf5c-b28c0dfa4889)
https://staging.giveth.io/project/testing-the-success-view?tab=donations



When I tried with other projects from "My Projects" it through same error message

https://github.com/user-attachments/assets/c0d44892-6736-490e-be06-5e835927f9ec


![image](https://github.com/user-attachments/assets/f3bd1a5a-4269-47ff-abbb-80bd1e1cc9f9)

**Comment by divine-comedian** [comment]
@LatifatAbdullahi you should not be able to donate to your own projects so I think it is working as expected. 

However you should not even be able to get to the donate page and generate the transaction so we will need to follow up a new issue to make sure this case is covered and users can't experience this error

**Comment by LatifatAbdullahi** [comment]
@divine-comedian @MohammadPCh 


**Test Update**


Users can connect with their web wallet to the staging app with ETH Sepolia network - Pass
users can connect to the app via the current multisig connection feature on ETH Sepolia - Pass
Sepolia shows as an option on switch network modal from web3modal from "Switch Network" navbar dropdown menu option when user is signed in - Pass
Project owners can add a recipient address to their project for the Sepolia network - Pass
Users can successfully donate native ETH on Sepolia network - **Pass**
Users can successfully donate native ETH on Sepolia network - **Pass**
Donations made to verified projects on Sepolia show up in givbacks calculations - ***Pass***

![image](https://github.com/user-attachments/assets/317479bc-fcb1-4aa6-9d1c-5f1a82ce60f7)
