### ISSUE TITLE
prevent duplicate tokens being added in adminJS

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1777]
On a few different occasions now we have had instances of donations going missing because of duplicate tokens being added to the adminJS. We should create some checks and error conditions to prevent this from recurring. 

We should check two conditions when a user is adding a new token for a given network and throw an error if true

- the token SYMBOL already exists in the DB on the given network
- the token address already exists in the DB for the given network

the error thrown should be descriptive depending on the condition that triggers it 

> i.e "This token symbol already exists for {network}", "This token address already exists for this network"

**Comment by divine-comedian** [comment]
@RamRamez have you had a chance to investigate this issue?

**Comment by RamRamez** [comment]
@maryjaf please test and verify.

Users shouldn't be able to add a token when:
* the token SYMBOL already exists in the DB on the given network
* the token address already exists in the DB for the given network

(FYI We have a full page error for these scenarios and I couldn't customize the error page in adminjs)

**Comment by maryjaf** [comment]
- [x] I can create new token with a symbol that is already exist @RamRamez 

![Image](https://github.com/user-attachments/assets/bca9397e-fa0f-497a-b79c-9f1ec2577dc4)

but when I try to add token with address that is already exist on our db I got below error 


![Image](https://github.com/user-attachments/assets/79ea61ca-e998-43b4-a9f3-e55b78a08036)

**Comment by RamRamez** [comment]
@maryjaf those tokens you added are on different chains. This was scenario:
"the token SYMBOL already exists in the DB `on the given network`"

The error you showed is ok.
"(FYI We have a full page error for these scenarios and I couldn't customize the error page in adminjs)"

**Comment by maryjaf** [comment]
> @maryjaf those tokens you added are on different chains. This was scenario:

![image](https://github.com/user-attachments/assets/13413e8f-4c27-417c-8f1d-f8784d8a125e)

**Comment by RamRamez** [comment]
> > @maryjaf those tokens you added are on different chains. This was scenario:
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/373222315-13413e8f-4c27-417c-8f1d-f8784d8a125e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NTQzNDQsIm5iZiI6MTcyNzk1NDA0NCwicGF0aCI6Ii8xMTE1MjkxODUvMzczMjIyMzE1LTEzNDEzZThmLTRjMjctNDE3Yy04ZjFkLWY4Nzg0ZDhhMTI1ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QxMTE0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDFkNTJlY2IwN2VmMDhjZTQwNmY4YjkyNWFiMzNlYjY2YjI1ZWI0OWQwODBiNGFhOGJlNDI2YmMyN2E2ZjY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vW9Yk9MPEzE8f2T9xpwXapGcMQ5471djVE-W25jUvCE)

@maryjaf This is the token I added myself for testing.

**Comment by maryjaf** [comment]
now the Acs have bben passed .
Thanks @RamRamez
