### ISSUE TITLE
Check duplicate title while editing

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#179]
Consider user have a project with the title of "my title" and he wants to edit the title to "My title", he get this error 'There is a project ...'.

related to [#317](https://github.com/Giveth/giveth-next/issues/317)

@mohammadranjbarz Can you check it?

![image](https://user-images.githubusercontent.com/73441857/138769532-93326209-f8e6-443b-a95c-d9ef89424173.png)

**Comment by mohammadranjbarz** [comment]
@RamRamez Thanks Ramin , I hace created a new PR for fixing that

**Comment by mohammadranjbarz** [comment]
@divine-comedian 
Test scenario sample :  you can create a project with the title `test` and after that, you should change it to `TEst` on the edit page, you should not get error

**Comment by divine-comedian** [comment]
testing on `next.givethi.io` 

I successfullly changed my project's title from "testing_" to "TESing_"

![image](https://user-images.githubusercontent.com/67759413/138926621-4d1743c1-91a1-4fa7-b473-f16d1f2ce017.png)


looks good?

**Comment by mohammadranjbarz** [comment]
> testing on `next.givethi.io`
> 
> I successfullly changed my project's title from "testing_" to "TESing_"
> 
> ![image](https://user-images.githubusercontent.com/67759413/138926621-4d1743c1-91a1-4fa7-b473-f16d1f2ce017.png)
> 
> looks good?

It's great,
this issue was just for this problem, so we can assume it's ok now
