### ISSUE TITLE
Adjust givbacks factors for verified vs. givbacks eligible

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1798]
With the coming changes of Decentralized Verification we will have two tiers of "verification" statuses. `verified` and `givbacksEligible`.

`verified` projects can participate in GIVpower, have a rank, but DO NOT yield GIVbacks to their donors

`givbacksEligible` projects have GIVpower and yield GIVbacks to their donors. 

we will need to be able to make the changes to our givbacks calculations in order to handle this change. 

As an example, ff we have 100 projects total that have the statuses GIVbacks Eligible and Verified, then we would handle GIVbacks like below:

| Project Rank | Status | GIVbacks Factor |
| --- | --- | --- |
| 1 | GIVbacks Eligible | 80% |
| 2 | Verified | 0% |
| 3 | GIVbacks Eligible | 79% |
| 4 | GIVbacks Eligible | 78% |
| 5 | Verified | 0% |
| 6 | Verified | 0% |
| 7 | GIVbacks Eligible | 77% |

As you can see verified projects can potentially have a higher rank than `givbacksEligible` projects, however we should not consider them when calculating the givbacks factor. When calculating the givbacks factor we skip over the not `givbacksEligible` projects and only consider the next `givbacksEligible` projects as if it were the next lowest rank project.

additionally we should ensure project data that shows the predicted givbacks factor are showing the correct percentages @MohammadPCh 

![Image](https://github.com/user-attachments/assets/809716e0-81b8-4b3d-96a3-b079fc738c84)

# for testing 
## making a project "vouched" status 
- go to admin panel
- select under "Project" tab and choose a project to make vouched
- click verify button
![Image](https://github.com/user-attachments/assets/b381e22d-13a5-4ba4-b711-b75f03eae143)
- donations to this project SHOULD NOT be eligible for GIVbacks
- check eligible donations response using https://givback.develop.giveth.io/api-docs/
- donation to project that is only vouched should not show up

## making a project GIVbacks Eligible
- check if project has submitted "GIVbacks Eligiblity" form (formerly verification form) 
- go to admin panel, "Project Verification Form" tab
- find application form from given project 
- press approve project button
![Image](https://github.com/user-attachments/assets/48bc1f96-6d64-47ff-b1be-ecba216b744e)
- donations to this project should be eligible for GIVbacks
- check eligible donations response using https://givback.develop.giveth.io/api-docs/
- donation to this project that is GIVbacks eligible should show up in response

## checking GIVbacks factor
- get how many ranked projects there are on staging https://impact-graph.serve.giveth.io/graphql
- enter query to get response for amount of ranks exist on staging
```
query {
  getTopPowerRank
}
```
the top ranked project yields 80% givbacks factor
bottom ranked project yields 50% givbacks factor
the difference between the top and bottom rank givbacks factor is 30% (50-80)

so for example if there are 50 ranked projects that are GIVbacks eligible then 

30 / 50  = 0.6  so each project from the top rank down should have 0.6% less GIVbacks factor 

- check top ranked project that is GIVbacks eligible yields 80% GIVbacks factor to donors 
- check next highest ranked project that is GIVbacks eligible and if the GIVbacks factor is correct.

**Comment by mohammadranjbarz** [comment]
@MohammadPCh Has separated **Givback Eligible** and **verified* in this PR https://github.com/Giveth/impact-graph/pull/1770

And for this phase we can't separate ranking for verified and givback eligible projects, for that purpose we need to create a new materialized view , ...

@divine-comedian  Should we hold on and don't merge that PR till implement this issue or we can merge it and for second phase we apply these requirements?

**Comment by divine-comedian** [comment]
Following up on this in our convo - we need to make sure we can handle GIVbacks correctly even for the first phase of this feature. 

projects that are not givbacks eligible should not receive GIVbacks. We'll need to figure out and estimate the necessary work.

**Comment by divine-comedian** [comment]
@mohammadranjbarz what is the update on this issue?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz what is the update on this issue?

I made the Pr and @CarlosQ96 approved it, I just didn't merge it to staging because I wanted to do it after the release, if we don't have any release soon, I can merge the PRs

**Comment by divine-comedian** [comment]
related to this PR 
https://github.com/Giveth/impact-graph/pull/1770

**Comment by divine-comedian** [comment]
@mohammadranjbarz  should need to make tiny changes to the givbacks-calculation repo - he says only 1 hour of work 

let's make sure we get it done!

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

Test update


Vouched status

-Donations to this project SHOULD NOT be eligible for GIVbacks - Pass
-Donations to project that is only vouched should not show up in the eligibledonations API- Pass

GIVback Eligible status

-Donations to this project should be eligible for GIVbacks - **Pending**
-Donation to this project that is GIVbacks eligible should show up in response - **Pending**

GIVback Factor

- Check top ranked project that is GIVbacks eligible yields 80% GIVbacks factor to donors - **Pass**
- Check next highest ranked project that is GIVbacks eligible and if the GIVbacks factor is correct - **Pass**





Whilst testing the eligibledonation API the whole page went blank showing this error

https://givback.develop.giveth.io/api-docs/

![image](https://github.com/user-attachments/assets/faee27bb-f010-4448-a083-243437a6f16d)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @divine-comedian
> 
> Test update
> 
> Vouched status
> 
> -Donations to this project SHOULD NOT be eligible for GIVbacks - Pass -Donations to project that is only vouched should not show up in the eligibledonations API- Pass
> 
> GIVback Eligible status
> 
> -Donations to this project should be eligible for GIVbacks - **Pending** -Donation to this project that is GIVbacks eligible should show up in response - **Pending**
> 
> GIVback Factor
> 
> * Check top ranked project that is GIVbacks eligible yields 80% GIVbacks factor to donors - **Pass**
> * Check next highest ranked project that is GIVbacks eligible and if the GIVbacks factor is correct - **Pass**
> 
> Whilst testing the eligibledonation API the whole page went blank showing this error
> 
> https://givback.develop.giveth.io/api-docs/
> 
> ![image](https://private-user-images.githubusercontent.com/112261242/369458969-faee27bb-f010-4448-a083-243437a6f16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY5ODk5MDksIm5iZiI6MTcyNjk4OTYwOSwicGF0aCI6Ii8xMTIyNjEyNDIvMzY5NDU4OTY5LWZhZWUyN2JiLWYwMTAtNDQ0OC1hMDgzLTI0MzQzN2E2ZjE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyMlQwNzIwMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MzM1MjcwYzRlN2RmMTQ0NmM0ZDRiODRiZDVkMTNkN2I1ZDc4YTRlMDIyMTQ4ZmNhNGUwNzQzNzFhZmYwNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.z1_vvhZF-0r3XzbAAqdazCyPBSgC04Akh8Tnq_-eglI)

It's up and running now, can you test it again?

**Comment by LatifatAbdullahi** [comment]
@mohammadranjbarz @divine-comedian 

Test update

Vouched status

-Donations to this project SHOULD NOT be eligible for GIVbacks - **Pass**
-Donations to project that is only vouched should not show up in the eligibledonations API- **Pass**

GIVback Eligible status

-Donations to this project should be eligible for GIVbacks - **Pass**
-Donation to this project that is GIVbacks eligible should show up in response - **Pass**

GIVback Factor

Check top ranked project that is GIVbacks eligible yields 80% GIVbacks factor to donors - **Pass**
Check next highest ranked project that is GIVbacks eligible and if the GIVbacks factor is correct - **Pass**
