### ISSUE TITLE
Add USDGLO as recurring donation token

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1810]
We should add USDGLO as an option to donate for recurring donations made on Optimism

They have already added their Super Token which can be found here: 
https://optimistic.etherscan.io/address/0x9f41d0aa24e599fd8d0c180ee3c0f609dc41c622

We have also added USDGLO into the dapp so the token icon should be ready. Here is the underlying token address
https://optimistic.etherscan.io/address/0x4f604735c1cf31399c6e711d5962b2b3e0225ad3

Since there is no testnet version we will need to test this in production

## AC:
- Users can choose to deposit USDGLO into their stream balance 
- user can create recurring donation using USDGLO 
- users can end recurring donation in USDGLO
- users can deposit and withdraw USDGLO from stream balance while it has an active stream
- user can modify recurring donation made in USDGLO
- recurring donations with USDGLO are GIVbacks eligible

**Comment by divine-comedian** [comment]
@HrithikSampson - want to try this one out

Recurring donations use Superfluid in the background https://www.superfluid.finance/ - this feature is ONLY deployed on Optimism on Giveth atm.

how it works is we have an underlying token which is a regular ERC-20 token such as USDGLO in this case, the underlying token needs to get wrapped in the super token contract, converting it to USDGLOx - this allows the token to be "streamed" from one address to another

We'll need to configure setting up USDGLO as an elegible token to deposit and stream using the recurring donations feature

Check out how we handle other eligible ERC20 tokens such as USDC, DAI, GIV and OP

@CarlosQ96 and @mohammadranjbarz should be able to support you with info

**Comment by HrithikSampson** [comment]
is it possible to get a very small amount of USDGLO to test it

**Comment by divine-comedian** [comment]
From the FE when I try to open the token drop down menu from the recurring donation page I get an application error

https://github.com/user-attachments/assets/039d900b-6f90-44fc-ad52-5cf753da674c

**Comment by HrithikSampson** [comment]
@divine-comedian , I had a small doubt is it coming sometimes or all the time. I couldnt duplicate the error.

<img width="857" alt="Screenshot 2024-10-02 at 2 19 28 AM" src="https://github.com/user-attachments/assets/5163a2e5-d54c-4bb5-84bb-526efec449d6">

**Comment by divine-comedian** [comment]
working now on production! https://optimistic.etherscan.io/tx/0x233ab8872a0925ca45a114656c0bef5ba97894ec032fb0b74e94cdc9b1836a32

![Image](https://github.com/user-attachments/assets/668de098-44c0-413e-b567-60970319ccfa)
