### ISSUE TITLE
remove GIVpower sort from project search results

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1811]
Based on feedback from users and stakeholders we should further improve how we handle our search results returned on the app. 

When a user currently searches for a project on Giveth we take the keywords and look for the closest match. We then sort those results based on the GIVpower of the projects returned. This means the project that might have matched closest to the search query is not returned at the top, and in some cases it is found several pages down, leading users to think the search is broken! 

When a user is searching for a project by default we should not apply any sorting to the results, if the user wishes they can apply a sort to it after the initial results have been returned. 

![Image](https://github.com/user-attachments/assets/028c1b74-6e93-46d5-87a5-b81368e00862)

@aminlatifi tagging you on this since you have the latest experience in tuning our search queries. Let me know when you can pick this up after your immediate priorities on QACC have settled.

## AC
- user searches should apply the closest match to the project title and/or description and show up as the highest results 
- on sorting menu user should see Best Match selected when they have made a search query along with the above mentioned icon
- Best Match sorting option does not show up as an option if user has not made a search query
- user can select from sorting menu other sorting options for search query such as "newest", "givpower", "GIVbacks %"

**Comment by MohammadPCh** [comment]
Hmm, I believe we need to update the UI/UX for this. In the current user flow, the "Sort by" option is visible and already has a value, which could be causing some confusion.

One option could be to skip the sorting when a search term is entered, or we could add something like a "No order" option in the sort menu.

What do you think, @divine_comedian?

**Comment by divine-comedian** [comment]
> Hmm, I believe we need to update the UI/UX for this. In the current user flow, the "Sort by" option is visible and already has a value, which could be causing some confusion.
> 
> One option could be to skip the sorting when a search term is entered, or we could add something like a "No order" option in the sort menu.
> 
> What do you think, @divine_comedian?

I would recommend we could show an option in the sort drop down that says "Best Match" which refers to closest match to the keyword entered

let's use this icon from the DS to be shown along with this option 
![image](https://github.com/user-attachments/assets/4ac0671b-6fac-49d8-aa46-661d93c875f8)
https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=5121-4309&t=vkrYF2vXuyvXp5QF-4

when user is not using search feature we should not show this option.

**Comment by MohammadPCh** [comment]
OK, I think the best way for us is to use `elastic search` in the future, but for now, I'll leave a PR for it.

**Comment by aminlatifi** [comment]
> > Hmm, I believe we need to update the UI/UX for this. In the current user flow, the "Sort by" option is visible and already has a value, which could be causing some confusion.
> > One option could be to skip the sorting when a search term is entered, or we could add something like a "No order" option in the sort menu.
> > What do you think, @divine_comedian?
> 
> I would recommend we could show an option in the sort drop down that says "Best Match" which refers to closest match to the keyword entered
> 
> let's use this icon from the DS to be shown along with this option ![image](https://private-user-images.githubusercontent.com/67759413/368659550-4ac0671b-6fac-49d8-aa46-661d93c875f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NDUzNDksIm5iZiI6MTcyNjc0NTA0OSwicGF0aCI6Ii82Nzc1OTQxMy8zNjg2NTk1NTAtNGFjMDY3MWItNmZhYy00OWQ4LWFhNDYtNjYxZDkzYzg3NWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDExMjQwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4NGZkYmUzOTVmMDM0OGRlM2VjYmE1MjZiNGE4MTQwZjU1MmRlZGE1ZGJkMjExMzUxNzY3MmIzMTJlNmZhOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KL5WZuRKA43b9eqYi4XljSAQS0CVEKlyDhp6B224WUg) https://www.figma.com/design/d3ciTS36toS9mra0RAPMe2/Giveth-Design-System-v0.1?node-id=5121-4309&t=vkrYF2vXuyvXp5QF-4
> 
> when user is not using search feature we should not show this option.

"Most Relevant" is also can be a good fit :)

**Comment by MohammadPCh** [comment]
@divine-comedian Should we adjust the sort to 'best match' when a user performs a search? For example, if a user has sorted by 'newest' but enters a new search term, should we automatically switch the sort to 'best match' or keep it as is?

**Comment by divine-comedian** [comment]
yes

**Comment by maryjaf** [comment]
https://staging.giveth.io/projects/all?searchTerm=how&sort=BestMatch

> * user searches should apply the closest match to the project title and/or description and show up as the highest results
> * on sorting menu user should see Best Match selected when they have made a search query along with the above mentioned icon
> * Best Match sorting option does not show up as an option if user has not made a search query
> * user can select from sorting menu other sorting options for search query such as "newest", "givpower", "GIVbacks %"

All Acs have been passed

**Comment by divine-comedian** [comment]
@MohammadPCh we'll need to handle this same scenarios above when a search is made from the navbar and apply it as a hotfix

![image](https://github.com/user-attachments/assets/e2f2bad6-aa1c-48c9-801b-dec64cf53111)
