### ISSUE TITLE
update draft donation service to prevent missed donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1819]
@mohammadranjbarz from our dev daily call today we should document and track the fixes required in order to prevent the draft donation service from missing donations

**Comment by mohammadranjbarz** [comment]
A missed donation reported by @laurenluz 
https://polygonscan.com/tx/0x4fec9dd3ed1e6c3d4790af4671de9c01def7944116596dfbc0e9d8d60d5eb299

**Comment by divine-comedian** [comment]
@mohammadranjbarz are we just missing a PR to solve this issue?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz are we just missing a PR to solve this issue?

It is is an extra thing that @aminlatifi suggested, without that PR our verification and draft system still works fine

**Comment by divine-comedian** [comment]
Thanks for the update @mohammadranjbarz is there anything we should do to test this?

**Comment by mohammadranjbarz** [comment]
> Thanks for the update @mohammadranjbarz is there anything we should do to test this?

No, it's a super rare case, it's hard to test it

**Comment by divine-comedian** [comment]
OK! Please update this issue when the PR is merged and we can move it to done.
