### ISSUE TITLE
adminBro dashboard "delisted" status is confusing

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#182]
in the adminBro dashboard we have multiple different status and booleans we can change... 

in the case of unlisting projects the button appears to have changed to `Delist Project` which triggers `Listed` to `false` or `No`.

however in the event of cancelling a project or `Cancel Project` it appears we are changing the status of the project to `delisted` which is not the same thing as being unlisted. 

this terminology needs to become more distinguishable because having two terms with `delist` that effectively deal with two different values is extremely confusing to contributors who may use this dashboard 

![image.png](https://images.zenhubusercontent.com/5fff1c86d883b3d9a858ddbc/3554b856-7a11-4f87-8fd4-2019cd3c6c88)

**Comment by divine-comedian** [comment]
inb4 @MoeNick  says "I told you so."

**Comment by CarlosQ96** [comment]
@divine-comedian I think we don't need any special changes on the backend, we have a project status tab on the adminbro. The name and descriptions are modifiable, I tested and it works good when updating the project showing the modified names.

However we refactored the adminbro a bit. So do this after we merge the changes.

**Comment by CarlosQ96** [comment]
Deleting project statuses is disabled, because sadly the backend is tied to the IDs. 
We should refactor this later but it's a delicate thing to do, we should prioritize other issues.

**Comment by CarlosQ96** [comment]
@divine-comedian this can be tested now on staging. Editing the name and description of the project status

**Comment by divine-comedian** [comment]
> @divine-comedian this can be tested now on staging. Editing the name and description of the project status

can you clarify what a successful test should look like?

**Comment by divine-comedian** [comment]
so testing out the changes carlos implemented.. 

it looks like I can go into a project and set its status from anyone of the options from the drop down menu, however only the active status will make it show up on the dapp. 

however some of the original issue remains where as when i click to cancel a project from the dashboard it sets the status to delisted. However, when I click `delist project` from the dashboard actions it changes `listed` from yes -> no. Does it make sense how this is confusing?

Logically when you click a button that says cancel project it should change a project's status to cancelled. As well to make existing terminology we list and **unlist** projects we do not "delist" them

maybe this is something further down the road but we'll have to deal with this mess of project statuses

**Comment by MoeNick** [comment]
@CarlosQ96  any ideas?

**Comment by CarlosQ96** [comment]
@DonnaOftadeh @divine-comedian if you have some time today lets meet and define de names. Honestly is more a matter of renaming things. So let's list them. 
Right now we can edit the status names and descriptions to make it more clear, but I would rename it in the admin bro too.

**Comment by MoeNick** [comment]
@CarlosQ96 @divine-comedian @DonnaOftadeh we sum it up to this result: any ideas? 
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/27518573-cead-4995-85d8-ab2449cdc329)

**Comment by divine-comedian** [comment]
> @CarlosQ96 @divine-comedian @DonnaOftadeh we sum it up to this result: any ideas? ![image.png](https://camo.githubusercontent.com/aa8080cc6bbf17bc3856efc07c5de4bbabc4048bfa21f7f6dc22930befabf8a4/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3630346632343263323831396435646136343236616430332f32373531383537332d636561642d343939352d383564382d616232343439636463333239)

Exactly this, thank you for making it into a clear format Moe 

I would only add that Admins can also activate and deactivate projects from AdminBro

**Comment by CarlosQ96** [comment]
Great I think this is fine. We can rename the statuses and Ill rename it on the adminbro.

**Comment by CarlosQ96** [comment]
@MoeNick Renamed the delist to unlist project for better terminology.
Explained Mitch how to rename statuses on the admin bro so they show up correctly.
And Mitch edited the Exception Message. 
All of this is on staging. I don't think for now anything else needs to be done. 
Moving it back to done with Mitch issue.
