### ISSUE TITLE
prevent queries from hanging and blocking other queries

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1820]
some queries are hanging when the dapp is under load. the hanging queries are preventing other queries from being ran and causing errors for users on the app

**Comment by CarlosQ96** [comment]
![image](https://github.com/user-attachments/assets/53ac3ae1-8845-4feb-8d54-ae79e3188120)
These are some of the queries that are hanging. 
There queries that hang the most seems related to querying the recurring donations and selecting the squareroot sum for estimated matching.

**Comment by CarlosQ96** [comment]
<img width="1194" alt="image" src="https://github.com/user-attachments/assets/a0ce831a-dad6-47ec-8455-245c56f07318">

**Comment by divine-comedian** [comment]
@CarlosQ96 what is the update on this issue?

**Comment by CarlosQ96** [comment]
I been cleaning the queries manually every now and then. The main query fetching the square root is the culprit. 
As I'm finishing issues, ill jump to this between today and tomorrow.

**Comment by divine-comedian** [comment]
Yikes! Definitely not sustainable to manually clean queries, thanks for investigating and please update us when you have the fix.

**Comment by divine-comedian** [comment]
was related to cronjob -  @CarlosQ96  will keep working on it this week with estimated matching query fixes.

**Comment by divine-comedian** [comment]
@CarlosQ96 what is the update on this issue?

**Comment by kkatusic** [comment]
> <img alt="image" width="1194" src="https://private-user-images.githubusercontent.com/92376054/366957902-a0ce831a-dad6-47ec-8455-245c56f07318.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NTMxNTEsIm5iZiI6MTcyODY1Mjg1MSwicGF0aCI6Ii85MjM3NjA1NC8zNjY5NTc5MDItYTBjZTgzMWEtZGFkNi00N2VjLTg0NTUtMjQ1YzU2ZjA3MzE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDEzMjA1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiYmE2MzFiNDc4ODM1YjRkYTdkYmE4NDUxNzE2YmU0ZWEwNGM3NmM5MjA0Y2RmMTFmNTQxYjM5ZGI3ZmUzYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2h3a9kSlD3OlYqt5dFRFzGQQutMUxsYkZfe5e0MD48M">

@CarlosQ96 can we introduce here some function and trigger for database, there are a lots of the SUM, COUNT... queries here on this list? only suggestion ;)

**Comment by CarlosQ96** [comment]
I can make a list of the heaviest queries and see how we can optimize them.
