### ISSUE TITLE
insert missing GIV-a-Palooza donations

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1821]
We've missed a few donations it seems and we need to make sure they are inserted into the app, for now we are aware of these missing transactions: 

- [x] Project: https://giveth.io/project/Sostento-Inc
Donation Hash: https://etherscan.io/tx/0x7c7efe6843d59663092b189ba9f0dc85c5b32db8530051763cb2db3f88deada6

- [x] Project: https://giveth.io/project/giveth-house?tab=donations
Donation Hash: https://polygonscan.com/tx/0x4fec9dd3ed1e6c3d4790af4671de9c01def7944116596dfbc0e9d8d60d5eb299

**Comment by mohammadranjbarz** [comment]
@divine-comedian Ok now Polygon donation has been added, but both donations are failed, I made an hotfix to verify them correctly, I think after merging #1825 and change status of those donations to `pending` every thing should be solved and we should not face this error again

FYI @jainkrati

**Comment by mohammadranjbarz** [comment]
@divine-comedian @laurenluz  @jainkrati As I guessed after merging the hotfix both donations got verified, so I think the problem that we had on the beginning of this qf round would not happen again and I think we caught all the missed donations (about 6-7 donations)
