### ISSUE TITLE
Make email and one of firstName and lastName required in update user

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#183]
This issue came from https://github.com/Giveth/giveth-next/issues/348#issuecomment-955021591

**Comment by mohammadranjbarz** [comment]
Currently @RamRamez  Doesn't let both `firstName` and `lastName` be empty in frontend, so no one can test this issue except Ramin

**Comment by RamRamez** [comment]
@mohammadranjbarz It seems there is a problem and profile forms can't be submitted

![image](https://user-images.githubusercontent.com/73441857/139679649-7402d6a2-61d1-43c9-85b7-59e861b994be.png)

**Comment by MoeNick** [comment]
@DonnaOftadeh 
Test it pls, with given scenarios.

**Comment by MoeNick** [comment]
seems ok to me
