### ISSUE TITLE
remove unused project badges from staging

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1839]
we have a couple of old badges that show up on staging 

- impact @ denver
- givpower is here

![Image](https://github.com/user-attachments/assets/1939b61e-423b-4f76-ba44-e693fd64800f)

we should understand why do they show up and how they are applied to projects. if possible we should remove them from our code to prevent any confusion while testing.

It appears that GIVpower is here is now showing on all projects that are GIVbacks eligible but not on projects that are only vouched.

**Comment by MohammadPCh** [comment]
this is the code snippet:
```
{campaigns &&
				campaigns?.length > 0 &&
				campaigns.map(campaign => (
					<ProjectBadge
						key={campaign.id}
						badgeText={campaign.title}
						wrapperColor={neutralColors.gray[900]}
					/>
				))}
```
If a project has associated campaigns, we display the badges here.

@divine-comedian, should I remove this logic? I believe it might be better to retain the badges and just manage which projects appear in the campaigns.

**Comment by divine-comedian** [comment]
We should keep that logic in the front-end in case we have campaigns in the future.

If it's a staging only thing then this issue isn't as high a priority.

 However it seems the GIVpower campaign badge is being applied to almost/all GIVbacks Eligible projects on staging and I don't know why.

**Comment by MohammadPCh** [comment]
It’s not a bug! But maybe we can look into why all these projects were added to this campaign.
there are some exceptions too, like:
https://staging.giveth.io/project/giveth-tour-bridge-the-world
@divine-comedian
