### ISSUE TITLE
naming changes & reorganization of buttons for deverification in adminJS

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1847]
We should consider re-naming some to make it more clear for admins 

rename Verify and Reject on Project tab to "approve vouched" & "remove vouched"

change name of Revoke Badge = "Revoke GIVbacks Eligible"

![image](https://github.com/user-attachments/assets/07c3768f-9469-4c3b-8375-4dd2bd8f6b1a)

anything else to add here? @NikolaCreatrix @WhyldWanderer

**Comment by WhyldWanderer** [comment]
I think that covers it Mitch!

**Comment by maryjaf** [comment]
- [ ] when I tap on "reject" button in project page the verified status is changed to NO(pic 1) but I still see "vouched" tag in project page (pic 2)

 Is it a bug or the development hasn't been completed yet?
 
![image](https://github.com/user-attachments/assets/7c5d382b-6fd6-4fe4-a9c8-4ea212ffc177)

![image](https://github.com/user-attachments/assets/cf929a09-9e51-4a60-8407-cb61e17ddc95)

https://staging.giveth.io/project/testdraft?tab=givpower

@RamRamez @divine-comedian

**Comment by maryjaf** [comment]
- [ ] should the name of "verification status" be changed?

![image](https://github.com/user-attachments/assets/28ea9447-56df-4dbe-8d17-def440996013)

@divine-comedian

**Comment by RamRamez** [comment]
> * [ ]  when I tap on "reject" button in project page the verified status is changed to NO(pic 1) but I still see "vouched" tag in project page (pic 2)
> 
> Is it a bug or the development hasn't been completed yet?
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/373188051-7c5d382b-6fd6-4fe4-a9c8-4ea212ffc177.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDgyNDIsIm5iZiI6MTcyNzk0Nzk0MiwicGF0aCI6Ii8xMTE1MjkxODUvMzczMTg4MDUxLTdjNWQzODJiLTZmZDYtNGZlNC1hOWM4LTRlYTIxMmZmYzE3Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwOTMyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMWJiZjE4M2RlZTg2ZWY5OWYwMDhjNmY4ZmNlYzgxOTlkZjFkYjgzMTc4N2IwZTViYjAwZTNhNzIyMWJmMmVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MJTQi8qfXSFA56oh_bgia_PVhCP4qNTu6eJ5GoceIjI)
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/373188207-cf929a09-9e51-4a60-8407-cb61e17ddc95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc5NDgyNDIsIm5iZiI6MTcyNzk0Nzk0MiwicGF0aCI6Ii8xMTE1MjkxODUvMzczMTg4MjA3LWNmOTI5YTA5LTllNTEtNGE2MC04NDA3LWNiNjFlMTdkZGM5NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwM1QwOTMyMjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZmIzODcwY2U1NmZjOWMyMGQzNTBhNTdlM2RlMDhhYzI1NGVlY2VhZDVhYzgyYTBkY2I5OTg2MjY1ZmYxYThkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.wVbZcCdAb-yz05UoCa4ZzNHDmEvNXq_ggbrP8CpqOqw)
> 
> https://staging.giveth.io/project/testdraft?tab=givpower
> 
> @RamRamez @divine-comedian

I'm not sure why we use both "verified" and "isGivbackEligible" fields for showing "vouched" badge in FE.
https://github.com/Giveth/giveth-dapps-v2/blob/2bcbfe0f90530e006f29467b8a701145d3c73ec3/src/components/views/project/ProjectBadges.tsx#L28

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify this issue:
* rename Verify and Reject on Project tab to "approve vouched" & "remove vouched"
* change name of Revoke Badge = "Revoke GIVbacks Eligible"

**Comment by divine-comedian** [comment]
@maryjaf these are good observations and we can follow them up in a later issue after this pending release - for now let's stick to the bullet points Ramin shared above

**Comment by divine-comedian** [comment]
tested this out - renaming looks good and the buttons functions still work as expected! 

![image](https://github.com/user-attachments/assets/c40b4f15-75fd-4b58-9234-4a03e3b2d956)
