### ISSUE TITLE
move revoke badge to project verification form section in adminJS

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1854]
Move Revoke Badge button in adminJS from Project -> Project Verification form tab
![image](https://github.com/user-attachments/assets/a3b761cc-6bb3-4be9-9b78-c4b4c9d8b127)
![image](https://github.com/user-attachments/assets/a5bb3a07-7e39-4a8e-bb1d-1da63b92143f)

**Comment by RamRamez** [comment]
we already have approve and reject projects button on verification form tab, that will switch isGivbackEligible field on and off and I think there's no need for a duplicate button.
@divine-comedian So, just for clarification, you only need to remove "revoke badge" button from project tab?

**Comment by divine-comedian** [comment]
> we already have approve and reject projects button on verification form tab, that will switch isGivbackEligible field on and off and I think there's no need for a duplicate button. @divine-comedian So, just for clarification, you only need to remove "revoke badge" button from project tab?

The revoke button triggers different things in the admin than the reject button, so we will need it in the project verification form tab. 

- it triggers a different email in Ortto - rejected vs. revoked email
- changes verificationStatus of project to Revoked (related to mandatory updates)

**Comment by RamRamez** [comment]
@maryjaf @LatifatAbdullahi please test and verify

**Comment by maryjaf** [comment]
> Move Revoke Badge button in adminJS from Project -> Project Verification form tab

The tests have been passed 

![Image](https://github.com/user-attachments/assets/f65a35f7-21d6-4c84-b971-63a090e3e848)

![Image](https://github.com/user-attachments/assets/2ecd8118-9c28-4882-9acf-f415f47d1124)
