### ISSUE TITLE
Regression Testing for SuperFluid Back-end Merge

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#1894]
We should do some general regression testing on staging following the merge of https://github.com/Giveth/impact-graph/pull/1893

### General tests should include: 
- Sign in with EVM
- Sign in with Solana
- Donation Flow
- Recurring Donation on Optimism
- GIVpower boosting 
- Create Project
- Edit Project
- Edit User Profile Information
- Project Page (public view & owner view)
- GIVbacks eligibility form

When this passes we will push staging back-end to production and repeat the process to ensure we have not introduced any new bugs into the dapp.

cc: @CarlosQ96

**Comment by maryjaf** [comment]
- [ ] 1- In create or edit project flow, by tapping on OP or Base network, "enable" button for recurring donation is shown , but by tapping on it nothing happens

https://github.com/user-attachments/assets/f5f8464e-bdf8-4a9d-823b-1c762124d786

**Comment by kkatusic** [comment]
@maryjaf I tried on staging and it's working for me:

![Screenshot 2024-12-17 at 10 20 32](https://github.com/user-attachments/assets/41d9d72b-98f9-43a1-8b25-6cb8935f3cd8)

can you try standard procedure or create new account inside metamask?

**Comment by maryjaf** [comment]
> * [ ]  1- In create or edit project flow, by tapping on OP or Base network, "enable" button for recurring donation is shown , but by tapping on it nothing happens


- [ ] 2- there is another problem please take a look on below screen record 

-I enabled recurring donation option
-when I tap on edit project 
-I see the "enable" button again 

https://github.com/user-attachments/assets/e73f1ec4-8a2c-439e-8795-f2ac1508e181

- [ ] 3- and one question: when I try to enable recurring donation on prod I should complete the flow related to recurring donation setup(like a following video) 
but in this new version there is no flow for this in create project scenario, is this ok?


https://github.com/user-attachments/assets/df03df76-ea1f-4287-aacb-433c99d53bae

**Comment by kkatusic** [comment]
> * [ ]  and one question: when I try to enable recurring donation on prod I should complete the flow related to recurring donation setup(like a following video)
>   but in this new version there is no flow for this in create project scenario, is this ok?
> 
this is good question I think @mateodaza have answer on that, as I can see inside his code it will ask you for switching to the Base or OP network. Will left this comment here that he can see.

**Comment by maryjaf** [comment]
> ### General tests should include:
> * Sign in with EVM :**Pass**
> * Sign in with Solana :**Pass**
> * Donation Flow :**Pass**
> * Recurring Donation on Optimism: **waiting for: "Total donated" field in recurring donation table is changed from 0 into >0 after running job**
> * GIVpower boosting:**Pass**
> * Create Project:**failed** https://github.com/Giveth/impact-graph/issues/1894#issuecomment-2548010522
> * Edit Project: **failed** https://github.com/Giveth/impact-graph/issues/1894#issuecomment-2548010522
> * Edit User Profile Information:**Pass**
> * Project Page (public view & owner view):**Pass**
> * GIVbacks eligibility form:**Pass**

**Comment by kkatusic** [comment]
> * [x]  1- In create or edit project flow, by tapping on OP or Base network, "enable" button for recurring donation is shown , but by tapping on it nothing happens
> 
>  Screen.Recording.2024-12-17.at.12.13.08.PM.mov

@maryjaf this hasn't solved, I found same problem on creating new project. Try to create same on Etherium network and than enable recurring donation. I'm investigating this ;)

**Comment by kkatusic** [comment]
@divine-comedian, cc @maryjaf, @mateodaza, tried to fix, but we have problem on _enabling_ recurring donation address on project creation form. For enable recurring donation address either on OP or Base we need to have _project data_ but we don't have that inside creation form, the project has not been created yet. Option is to move recurring donation opt-out to the edit project form.
