### ISSUE TITLE
Bring back  totalDonations and totalHearts fields and make them be updated

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#193]
We need to add these fields in the project entity, then when we want to sort by hearts or donations we can simply use it ( performance is much higher than joining when sorting by donations), and it's good when frontend wants to show the number of hearts of projects, and amount of donations

**Comment by MoeNick** [comment]
@mohammadranjbarz appreciate if you can update us on this.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz appreciate if you can update us on this.

Yes we have it now, you can close this issue
