### ISSUE TITLE
Add Admin to the allProjects Query

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#201]

**Comment by MoeNick** [comment]
@mohammadranjbarz @CarlosQ96 How can I test it?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @CarlosQ96 How can I test it?

It's changing in API responses, 
@RamRamez  can approve this

**Comment by RamRamez** [comment]
> @mohammadranjbarz @CarlosQ96 How can I test it?

You can test this through graphQL query.
Also you can check the [new App](https://typescript.giveth.io/):
In Homepage, projects page and single project page, the owner of the projects should be shown correctly. (Done in PR [#17](https://github.com/Giveth/giveth-io-typescript/pull/17))

**Comment by divine-comedian** [comment]
testing in `https://serve.giveth.io/graphql`
I noticed there's a few project queries that are missing the admin field - 

projectsByUserId
projects
topProjects

@mohammadranjbarz  will this affect any important functionality?

**Comment by CarlosQ96** [comment]
The TopProjects query I think is not used right now in some version or will not be used anymore.
Can you put a screenshot? I see all projects with admin field filled, no project has it null in staging.  @divine-comedian

**Comment by divine-comedian** [comment]
this is returning from querying `projects` on `https://serve.giveth.io/graphql`

https://serve.giveth.io/graphql

![image](https://user-images.githubusercontent.com/67759413/146983401-f37959e6-3cc4-496d-89de-17ac16ca044f.png)

**Comment by CarlosQ96** [comment]
Ok ok, to clarify the actual name of the admin object field is now adminUser

The reason for this is our database library has a bunch of bugs, so we had to set a new field for just querying and setting the admin in the results.

Also the projects query is now the search query so it has a different structure:
```
query {
  projects(take: 11, skip: 0, orderBy: { field: Donations, direction: ASC }) {
    projects {
      id
      title
      admin
      adminUser
      verified
      donations {
        valueUsd
      }
      reactions {
        id
      }
    }
    totalCount
    categories {
      name
    }
  }
}
```

**Comment by divine-comedian** [comment]
testing that out on the playground - I can see adminUser needs a set of subfields to be ran 
I can also query admin and adminUser  together and they output different things
![image](https://user-images.githubusercontent.com/67759413/146985093-8bda7dc1-dc43-4e92-9c5c-5aa37adcf1c0.png)

that would be the only modification you would need from that query you pasted above @CarlosQ96  the whole query seems pretty inefficient but I don't know enough technically to suggest anything else.. move to DONE or what do you think ?

**Comment by CarlosQ96** [comment]
Since the query does a lot of things (search, filter, order, paginate) its a bit more slower/complex compared to the previous one that didn't query so much info.

To clarify:
Admin field is just an id. 
AdminUser is literally doing another database query to get the user with its fields using the admin_id from the admin field. (same attributes as a regular user, id, name, lastName, email,etc)

@divine-comedian

**Comment by CarlosQ96** [comment]
For now this is done.
