### ISSUE TITLE
Add UpdatedAt / Last Updated to projects for new design

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#204]

**Comment by CarlosQ96** [comment]
@RamRamez What actions modify the updatedAt? 
This is my list:
1. Editing the project
2. removing or adding a project update

optional in my opinion:
3. Adding a donation.

**Comment by RamRamez** [comment]
> @RamRamez What actions modify the updatedAt? This is my list:
> 
> 1. Editing the project
> 2. removing or adding a project update
> 
> optional in my opinion: 3. Adding a donation.

@MoeNick @mohammadranjbarz What do you think?
