### ISSUE TITLE
add number of updates in projectBySlug

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#206]
@mohammadranjbarz @CarlosQ96 Is it possible to add No. of updates in projectBySlug?

I need it for new design

![image](https://user-images.githubusercontent.com/73441857/143064483-03e2e62e-6e62-4fe5-8c20-bccb5bf6a381.png)

**Comment by RamRamez** [comment]
@mohammadranjbarz @CarlosQ96 When I use the new query in PR #209 for [this](https://next.giveth.io/project/ram-second-metamask-2) project, it returns 3 for totalProjectUpdates.
But using getProjectUpdates, it returns 2 updates.

**Comment by MoeNick** [comment]
@CarlosQ96 @MohammadPCh shall we bring it back?

**Comment by MoeNick** [comment]
@CarlosQ96 Ramin said it shows +1 donation, I make it back to in-progress.

**Comment by CarlosQ96** [comment]
@MoeNick @RamRamez Found the issue. The count is "correct" but we have in all projects a Hidden projectUpdate that is empty for some reason..... It's created as default ProjectUpdate when the project is created.
I'll update the code to ignore this.

**Comment by mohammadranjbarz** [comment]
@RamRamez 
We have deployed it on staging, could you check it, please?

**Comment by RamRamez** [comment]
> @RamRamez We have deployed it on staging, could you check it, please?

It seems good.

**Comment by divine-comedian** [comment]
does this issue need further testing or can it be moved to done?

**Comment by CarlosQ96** [comment]
I think we can move it to Done, this is all done. We keep the total project updates # updated at all times every time a new projectUpdate is added or deleted.
