### ISSUE TITLE
add orderBy Traceable for projects

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#208]
I need sortBy Traceable projects in projects page.

@CarlosQ96 @mohammadranjbarz Can you add it?

**Comment by mohammadranjbarz** [comment]
> I need sortBy Traceable projects in projects page.
> 
> @CarlosQ96 @mohammadranjbarz Can you add it?

Sure, as soon as possible we will do it

**Comment by MoeNick** [comment]
@DonnaOftadeh pls take a look and confirm

**Comment by RamRamez** [comment]
We have traceable projects but it returns none

![image](https://user-images.githubusercontent.com/73441857/144269825-a14d40ac-1c0a-4344-95f3-6ac2e523a094.png)

**Comment by MoeNick** [comment]
@mohammadranjbarz @CarlosQ96 move it back. ;(

**Comment by mohammadranjbarz** [comment]
> We have traceable projects but it returns none
> 
> ![image](https://user-images.githubusercontent.com/73441857/144269825-a14d40ac-1c0a-4344-95f3-6ac2e523a094.png)

I should fill their `traceCampaignId` manually
I'll do that

**Comment by CarlosQ96** [comment]
@mohammadranjbarz actually if you do direction: ASC it shows them. So Ramin told me is in inverted Order. So we would need to reinvert the order or modify the orderBy just for this field so it's consistent.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz actually if you do direction: ASC it shows them. So Ramin told me is in inverted Order. So we would need to reinvert the order or modify the orderBy just for this field.

Yeah you are right, it's for staging
but I still should the DB changes for production

**Comment by CarlosQ96** [comment]
Uploaded the PR it seems the ordering is fine, but the issue was the nulls. So I inverted the Order of when the TraceCampaignId = Null, so sorting makes sense.

**Comment by divine-comedian** [comment]
@CarlosQ96  can you provide more context on how to test this issue?

**Comment by MoeNick** [comment]
If filter by Trace is working fine on UI, its done.

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` 

I can sort by traceable and all of the traceable projects show up at the top, but also non traceable projects show up as we continue to scroll down - 
![image](https://user-images.githubusercontent.com/67759413/146984080-693307d6-b64d-40b6-b030-79620916b155.png)![image](https://user-images.githubusercontent.com/67759413/146983900-2455d460-c7d1-4e7f-a6d9-f8e18da0f196.png)
load more will continute to load more projects including ones that are not traceable

ideally similar to other sort/filter features - such as `accepts GIV token` we should limit this sort function to only traceable projects - moving back to in progress

**Comment by MoeNick** [comment]
I think we decided to have filter/sort behavior not only filtering.
So GIVonly also should behave like first GivOnly then other projects. This is because we tell the user in UI we're gonna  only sort them.

**Comment by divine-comedian** [comment]
okay but the issue is that we sort by traceable and we are shown projects that are not traceable - this should be filtering them out

**Comment by MoeNick** [comment]
This issue was created when we dont have any filter/sort by trace, and its working right now.
But I agree with you that we have to decide we just filter or sort? For example: Sort by verified query is just behave like sort by trace and includes non-verified projects but after verified ones as a SORT BY query. 
So I think we talked and we decide to just sort, its fine for now because we have "load more". 

But if we want to revise, yeah we can add just Filter behavior for those queries: verified, accepts GIV and Trace. 
Appreciate if @mohammadranjbarz    and @CarlosQ96 @mateodaza put their comments.

**Comment by CarlosQ96** [comment]
Yeah it all came down to things we decided on the calls. It would be a sort not a filter in the case of the traceable projects.

But yeah a filter can also be added.

**Comment by divine-comedian** [comment]
it really doesn't make sense if you want to sort by traceable and then non-tracable projects show up - what's the point then? 

I think sorting by traceable should have the filter functionality

**Comment by mateodaza** [comment]
> it really doesn't make sense if you want to sort by traceable and then non-tracable projects show up - what's the point then?
> 
> I think sorting by traceable should have the filter functionality

this is solved now
