### ISSUE TITLE
duplicate projects on admin Dashboard

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#217]
It seems that on the admin dashboard whenver we change the title of a project a new entry is added to the admin dashboard. This means that we can have many entries on AdminBro for the same project. Will this pose any issues?

These are all the same project for example: 
![image](https://user-images.githubusercontent.com/67759413/143921120-0580f934-0b89-4142-9432-48b7c6efdcc5.png)

**Comment by MoeNick** [comment]
Thanks for that. We may discuss it tomorrow with @mohammadranjbarz and @CarlosQ96
