### ISSUE TITLE
User Profile Showing Non-owned Projects

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#231]
Issue in Prod, it seems the wrong query was being used. However will make a new one with pagination taking into account our memory issues.

**Comment by divine-comedian** [comment]
I tested my project in `giveth.io` and only my one single test project showed up 

how else can I test this issue?

**Comment by CarlosQ96** [comment]
This was mostly a bug, there was no filter per user. So any user was seeing every project on giveth. 
It should only show the user owner projects.

**Comment by divine-comedian** [comment]
okay well then looks to be resolved on production!
