### ISSUE TITLE
problem in donationsByProjectId

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#237]
@mohammadranjbarz @CarlosQ96 
For `skip: 0`, `take: 11` it's ok but for `skip: 11` it is not!

![image](https://user-images.githubusercontent.com/73441857/145259703-63a121c4-72f6-4078-a7d4-0915a4abd528.png)

**Comment by CarlosQ96** [comment]
I'll upload a hotfix soon ASAP. On it!

**Comment by CarlosQ96** [comment]
@RamRamez Please check this should have fixed the issue. 
![image](https://user-images.githubusercontent.com/92376054/145265219-89e88c98-4bcf-4199-97a5-a59c73f2f737.png)
Skip is sometimes buggy but that is another PR I am working on so it fixes the issue once and for all but it shouldn't break now this query.

**Comment by mohammadranjbarz** [comment]
I think it's in an old issue and it no longer exists
@RamRamez @MoeNick  Can we close this?

**Comment by MoeNick** [comment]
Lets keep it on UAT and test again
