### ISSUE TITLE
Call projectById query cause crash in backend

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#238]
```
query {
  projectById(id:1){
  	title
    slug
    totalProjectUpdates
  }
}
```

**Comment by divine-comedian** [comment]
testing this out on graphql staging - 
![image](https://user-images.githubusercontent.com/67759413/147155713-96737e3c-88b0-4519-aced-c71098eccfdf.png)

I can successfully run this query and don't see any error - output looks good 

was there anything else to test on this issue @mohammadranjbarz ?

**Comment by mohammadranjbarz** [comment]
> testing this out on graphql staging - ![image](https://user-images.githubusercontent.com/67759413/147155713-96737e3c-88b0-4519-aced-c71098eccfdf.png)
> 
> I can successfully run this query and don't see any error - output looks good
> 
> was there anything else to test on this issue @mohammadranjbarz ?

No that's it , the playground is disabled but backend is up
I think this testing is enough
