### ISSUE TITLE
Add a field which can be seen in admin panel that shows a project is traceable or not 

### ISSUE THREAD

**Issue by DonnaOftadeh** [Giveth/impact-graph#241]

**Comment by CarlosQ96** [comment]
Tha main list has a limited amount of fields, so we gotta choose which to trade off for the traceCampaignId

**Comment by mateodaza** [comment]
Moved to the impact graph as it relates to the admin bro

**Comment by MoeNick** [comment]
@mateodaza can you mention the related issue in impact-graph repo?
