### ISSUE TITLE
Allow authenticated users to set anonymous donations

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#248]
Changes before the launch. Allowing the authenticated users to set if they want to keep their donation anonymous.

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` 

signed in on my autheticated account and donating to a project - I click donate anonymously and donate some ETH 
![image](https://user-images.githubusercontent.com/67759413/146440265-cb35813c-117f-45e5-ac0e-c721ee81bbf0.png)

the donation goes through and shows up as `anonymous` on the project's page - I also tested non-anonymous donation and it shows up properly as well! 
![image](https://user-images.githubusercontent.com/67759413/146440780-32ee0c51-aefd-449c-8e6d-b649dc7df46e.png)
