### ISSUE TITLE
Disable Apollo playground in production

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#261]

**Comment by mohammadranjbarz** [comment]
@MoeNick 
The backend is up in staging but if you go https://serve.giveth.io/graphql you can't see apollo playground

**Comment by divine-comedian** [comment]
navigating to `https://mainnet.serve.giveth.io/graphql`

this is currently what appears 
![image](https://user-images.githubusercontent.com/67759413/152166571-851c32c7-d79b-4c00-9175-65f254798996.png)


would we consider this state effectively disabled @mohammadranjbarz ?

**Comment by mohammadranjbarz** [comment]
> navigating to `https://mainnet.serve.giveth.io/graphql`
> 
> this is currently what appears ![image](https://user-images.githubusercontent.com/67759413/152166571-851c32c7-d79b-4c00-9175-65f254798996.png)
> 
> would we consider this state effectively disabled @mohammadranjbarz ?

Yeah exactly, it mean playground had been disabled successfully
