### ISSUE TITLE
Set Project as pending review after edited

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#264]

**Comment by divine-comedian** [comment]
testing this on `next.giveth.io` I tried editing a few projects - 
https://next.giveth.io/project/TESting_-0
https://next.giveth.io/project/lets-see-whats-over-here

I check to see their listed status on both the admin dashboard and on graphql and both projects still have listed as `true` and both can still be found on the DApp. 
![image](https://user-images.githubusercontent.com/67759413/146977137-a28767f8-b516-48ba-a87f-59fe627885f7.png)

I don't think this is the expected flow, moving back to in progress

**Comment by divine-comedian** [comment]
awaiting PR merge to test ....

**Comment by MoeNick** [comment]
@mohammadranjbarz i think the pr is waiting for you

**Comment by mohammadranjbarz** [comment]
@divine-comedian @MoeNick 

It's on the staging now

**Comment by mohammadranjbarz** [comment]
@MoeNick 
The backend is done and seems ok, I think when users want to edit a project we should show them dialogue and say them that their project will be unlisted after an edit otherwise they will be confused

**Comment by divine-comedian** [comment]
okay testing this out on the admin dashboard and `next.giveth.io` 

I edit my project - changing uniquely either the wallet address, project title, project description and the project goes back into `not reviewed` status for listed - this seems to be working as described! 

![image](https://user-images.githubusercontent.com/67759413/147125317-65ed946b-8caa-4ade-a325-089521c26de2.png)

**Comment by divine-comedian** [comment]
@mohammadranjbarz  made a follow up issue for the front-end https://github.com/Giveth/giveth-next/issues/578
