### ISSUE TITLE
Add Filter to SortBy Trace and Verified Queries

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#267]
it really doesn't make sense if you want to sort by traceable and then non-tracable projects show up - what's the point then? 

I think sorting by traceable should have the filter functionality

_Originally posted by @divine-comedian in https://github.com/Giveth/impact-graph/issues/208#issuecomment-999093822_

**Comment by MoeNick** [comment]
@CarlosQ96 Mohammad got busy for GIV launch, can you pls take this?

**Comment by CarlosQ96** [comment]
Ok, added a filter by Trace

**Comment by CarlosQ96** [comment]
@MoeNick however should we keep both sort by and filter by? Because, honestly they are different things.
Or should I remove the sortby?

Filter will only return the projects with traceId
and sortby will prioritize the order of those with traceID but will return the other results too.

**Comment by mohammadranjbarz** [comment]
@MoeNick  Carlos has implemented it and it's on staging, now the UI can be implemented

**Comment by MoeNick** [comment]
@mateodaza can you pls take this in frontend?

**Comment by divine-comedian** [comment]
I want to clarify that technically filterBy and sortBy are different functions, from a user perspective (not a dev perspective) they are relatively similar - I would highly recommend to simply change the functionality of the traceable sorting to filterBy instead of making unnecessarily complicated modifications to the UI

**Comment by MoeNick** [comment]
Yeah it's all done, we just made it filterBy in currant design we have. Would you pls test it again?

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` 
clean cache and cookies

it appears the functionality has not changed at all  - choosing to sort by traceable should apply the filter and not show me projects that aren't traceable 


![image](https://user-images.githubusercontent.com/67759413/147492055-a0d4a315-0c26-4489-b783-5825b38c7e62.png)
![image](https://user-images.githubusercontent.com/67759413/147492102-06909755-8685-4433-9a3b-79a85b28132c.png)

**Comment by CarlosQ96** [comment]
@divine-comedian I made the filter on the filter dropdown. 
Should I remove the SortBy then? Or maybe it is a frontend thing. Gotta validate with Mateo.

**Comment by MoeNick** [comment]
@CarlosQ96 @mateodaza This is the success criteria:
1- User Select "Traceable" and/OR "Verified" in Sort By Menu in UI
2- User should only see Traceable project and/or verified projects.

**Comment by divine-comedian** [comment]
testing on `next.giveth.io `

I can see while filtering by traceable in the "sort by" menu I can quickly see there are non-traceable projects in this view - I should only see traceable projects 
![image](https://user-images.githubusercontent.com/67759413/152167868-ac61fa9e-b5fe-4869-8d57-df3bb9a4f385.png)


similarily here I filter by verified in the sort by drop down and I am still able to see non-verified projects - I should only see verified projects 
![image](https://user-images.githubusercontent.com/67759413/152167697-9e24c201-39fd-49db-a2e7-4a99c4e71961.png)

**Comment by divine-comedian** [comment]
hey guys - revisiting this issue on the new dapp 
`staging.giveth.io` 

I can see the filter for traceable projects work well but when I sort by verified I can still see non-verified projects in the list. 

![image](https://user-images.githubusercontent.com/67759413/160037066-6f182570-fa3e-4623-8159-72695f8b4112.png)

**Comment by divine-comedian** [comment]
testing on `staging.giveth.io` 

now when I sort by `Verified` ONLY verified projects show up on this list! this final issue seems to be resolved! great work. 

![image](https://user-images.githubusercontent.com/67759413/161159421-f67bab5a-09f0-4c8f-affc-3049dfd3e36b.png)
