### ISSUE TITLE
Frontend: Add youtube link and website url to the givingblocks projects page

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#271]
We saved in our database the youtube link presentation of the project and the website url.
They may not be present for some projects.

**Comment by CarlosQ96** [comment]
@MoeNick Leaving the issue here for later or we can prioritize.

**Comment by mateodaza** [comment]
@MoeNick does this have priority now?

**Comment by MoeNick** [comment]
If we have bandwidth we’d better fix it, the visual view of giving block projects are not interesting at all 😔

**Comment by jeevanplus007** [comment]
@MoeNick Need to check if this issue needs a fix keep in mind the priority and efforts.
