### ISSUE TITLE
Setup integration test infrastructure

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#280]
- [x] Migration Files
- [x] Write at least one integration test that calls graphql query/mutation
- [x] Maybe need some seeder for filling DB before running tests

**Comment by MoeNick** [comment]
Shall I move it to UAT? 
did all the above get the check-list. @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Shall I move it to UAT? did all the above get the check-list. @mohammadranjbarz

Yeah all of check list items has been implemented, but it's still in code review
