### ISSUE TITLE
Sort by raised amount with trace donations counted. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#285]
We need to implement a query to count trace donation plus io donations we may need it for TP version.

**Comment by mohammadranjbarz** [comment]
@mateodaza 

You can use this query in staging 

```

query {
  projects(

  orderBy: {
      field: TraceDonations,
      direction: DESC
  }
) {
    totalCount
    projects {
      traceCampaignId
      id
      title
      slug
      qualityScore
      walletAddress
      creationDate
      adminUser{
        name
      }
      users {
        name
      }
      updatedAt
      totalReactions
      totalDonations
      totalTraceDonations
    }
    categories {
      name
    }
  }
}

```

**Comment by MoeNick** [comment]
@divine-comedian can you find a band with and help us on this with service testing:
1- total amount donated for a non-traceable project should be correct and the same with DB
2- total amount donated for a traceable project should be correct: all donations with giveth.io + its campaign donation amount in trace. 
All of them in staging.

**Comment by divine-comedian** [comment]
testing out donations on trace vs. donations on IO 
develop.giveth.io
next.giveth.io

right now I can see zero consistency between the two dapps. I tested making a few donations on both via Ropsten
https://develop.giveth.io/campaign/testing-trace-endpoint
https://next.giveth.io/project/testing-trace-endpoint
![image](https://user-images.githubusercontent.com/67759413/152071470-5ee5ce16-85e2-4374-ac01-aede38bda6b3.png)

I made two separate transactions each for 0.003 ETH to each project (trace and IO) so it should show both donations but only shows the one I made on the platform (sorry I used the same amount so it makes it more confusing)
![image](https://user-images.githubusercontent.com/67759413/152072134-e980e312-7c3b-4b6b-82f6-c39b4e28814c.png)
https://develop.giveth.io/campaign/ram-4th-project
https://next.giveth.io/project/ram-4th-project

**Comment by mohammadranjbarz** [comment]
@divine-comedian @MoeNick Sorry I had missed the last comment of Mitch, I have created a PR for fixing query in featehrs after merging that it would fix this issue

**Comment by mohammadranjbarz** [comment]
@divine-comedian And the frontend side is not implemented yet, so we need to test it with calling webservice directly

**Comment by divine-comedian** [comment]
@mohammadranjbarz  okay - how can I test this issue? should we wait for the frontend implementation?

**Comment by mohammadranjbarz** [comment]
> testing-trace-endpoint

You can call queries directly like this, to see sort by trace donations amount works

```
query {
  projects(
    take: 10,
    searchTerm: "",
    category: "" ,
    orderBy: { 
        field: TraceDonations,
        direction: DESC
         }
  ) {
    totalCount
    projects {
      traceCampaignId
      id
      title
      slug
      qualityScore
      walletAddress
      creationDate
      adminUser{
        name
      }
      users {
          name
      }
      updatedAt
      totalReactions
      totalDonations
      totalTraceDonations
    }
    categories {
      name
    }
  }
}
```

**Comment by MoeNick** [comment]
@mateodaza can you pls make sure it's being used for next and v2 version together.
