### ISSUE TITLE
Use premium Infura key as web3 provider in all projects

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#299]
- [x] Giveth Trace - Develop
- [x] Giveth Trace - Production
- [x] Bridge monitor - develop
- [x] Giveth bridge - production
- [x] Impact-graph - develop
- [x] Impact-graph - staging
- [x] Impact-graph - production
- [x] Giveth Trace Simulation - develop
- [x] Giveth Trace Simulation - produciton

@aminlatifi  Please add servers/applications that I have missed

**Comment by MoeNick** [comment]
which of them block us to provide service to our users in production? 
which of them are essential for V2?

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/299?planning-poker) with ZenHub @aminlatifi @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@MoeNick  @aminlatifi I think we can move it to done
