### ISSUE TITLE
Write integration tests for all graphql query/mutation 

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#308]
If you want to run tests locally you should have a running postgres with auth info that is in 
https://github.com/Giveth/impact-graph/blob/staging/config/test.env#L4-L9

Just be aware because it will delete all of your existing records before running test, I suggest you just run `docker-compose-local-postgres.yml` it will bring up two instances of postgres, one for your normal use and another one for using in tests.

For running tests you need to have an account https://www.quicknode.com, https://infura.io and https://etherscan.io and get `API_KEYS` from there, in fact for running the application you need it as well, this run command for tests (If you are from giveth organization, tell me to give you these keys)

```
ETHERSCAN_API_KEY={etherscanApiKey} INFURA_API_KEY={infuraApiKey} ETHEREUM_NODE_ID={infuraApiKey} XDAI_NODE_HTTP_URL={link from https://www.quicknode.com}   npm run test
```

We need to have some success scenario and all possible failed scenario for test cases, I will create a subtask for every query/mutaion to know what we are doing, feel free to add subtasks and pick every issue that you want and write test cases, I think it's a good start for new contributors to get familiar with our codes and our product

**PS** You can start picking issues after https://github.com/Giveth/impact-graph/pull/307 has been maerged

JFYI
@aminlatifi  @CarlosQ96 @MoeNick

**Comment by aminlatifi** [comment]
Nice, thanks @mohammadranjbarz. Definitely it's a landmark in solving our technical debts

**Comment by divine-comedian** [comment]
@aminlatifi @mohammadranjbarz 

Do we still need to work on these issues to resolve our technical debts?

**Comment by aminlatifi** [comment]
@divine-comedian Let's plan them as we can during our sprints. Putting in sprint backlog is good practice

**Comment by MoeNick** [comment]
@jainkrati  updating these test cases can be part of the plan for related to technical debts.

**Comment by jainkrati** [comment]
Not prioritizing this right away because BE devs are packed.

**Comment by divine-comedian** [comment]
There are some graphql tests on impact-graph 

We should wait to start this epic - might need to change the way we test it - please let us know @jainkrati 

This issue is an EPIC let's not forget
