### ISSUE TITLE
Write test cases for donationsByDonor() in donationResolver.test.ts

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#332]

**Comment by CarlosQ96** [comment]
This card was actually helpful to setup the testing of donations for other issues: #342

**Comment by mohammadranjbarz** [comment]
@MoeNick As it's just technical I think we can skip UAT and just move it to DONE

**Comment by CarlosQ96** [comment]
I'll move it to Done. This was mostly technical and a great start to setup future tests related to donations.
