### ISSUE TITLE
Write test cases for saveDonation() in donationResolver.test.ts

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#333]

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/333?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
I thinks it's one of our importnant mutaiotns we should consider these cases when writing automatic tests:

- [x] Creating donations for not logged in users
- [x] Create donation for logged in users
- [x] Create donation for logged in users bu anonymously
- [x] Create donations with  whitelist tokens
- [x] Create donations with not white listed tokens
- [x] Fill USD value for whitelisted tokens after creation
- [x] Check `segmentNotified` after creating donations
- [x] Create donations with invalid input data like invalid projected
- [x] Create donations when `projectId` and `toWalletAddress` are not matched

**Comment by CarlosQ96** [comment]
I agree with the test cases and the estimate.

**Comment by CarlosQ96** [comment]
I think we should add a transak donation test case too and for the webhook.

**Comment by MoeNick** [comment]
is it in progress?

**Comment by mohammadranjbarz** [comment]
> is it in progress?

Yes through working on admin bro issues, I didn't spend time on this issue

**Comment by mohammadranjbarz** [comment]
@MoeNick 
As it has just technical side, you can move it to  **DONE**
