### ISSUE TITLE
Write test cases for userByAddress() in userResolver.test.ts

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#336]

**Comment by mohammadranjbarz** [comment]
It has been implemented on #357

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/336?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by CarlosQ96** [comment]
@mohammadranjbarz I saw you added tests for this already, added one for an empty case and thats it. But this is practically done.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I saw you added tests for this already, added one for an empty case and thats it. But this is practically done.

Thank you man
