### ISSUE TITLE
Frontend: Backend errors are displayed as success in the donations view

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#338]
Related to issue: https://github.com/Giveth/impact-graph/issues/304

The issue found was that backend was returning errors to the frontend when making a donation, but the frontend was still displaying as success.

**Comment by MoeNick** [comment]
Happy you guys find it. @CarlosQ96 @mateodaza 
I really love to bring backend errors to Sentry as well. Ideas?

**Comment by CarlosQ96** [comment]
@mohammadranjbarz added sentry logger manually so when an error occurs it's sent to the backend. I think we are just missing configuring the email.

**Comment by CarlosQ96** [comment]
@mateodaza is this on a PR? or merged? So we can do the final test.

**Comment by MoeNick** [comment]
@mateodaza @CarlosQ96 any updates on this?

**Comment by CarlosQ96** [comment]
Tested the following escenarios:
1. Create the same donation twice (same tx hash) to force the return of error from the backend.
2. Turn off the backend to reproduce a service unavailable error.

Evidence:
1. I created a donation the success page showed, I forced the same tx hash and the frontend displayed an error modal:
![image](https://user-images.githubusercontent.com/92376054/152471862-19d9862e-67ed-4dd3-9098-b4780e1108c5.png)
2. I did another donation but turned off the backend temporarily:
![image](https://user-images.githubusercontent.com/92376054/152471914-f85b51a9-8f52-4bfe-8e5e-608c7b4ad42d.png)

**Comment by CarlosQ96** [comment]
@MoeNick since this is a code reproduced test I think we can move it to done. It's hard to do it live or in staging.
But I think this shows the changes Mateo did, work. 
Before it was showing the success modal like nothing was wrong regardless of anything.
Let me know what you think.

**Comment by CarlosQ96** [comment]
It's showing error modals correctly!

**Comment by CarlosQ96** [comment]
The graphql errors might not be that pretty, but I'd make another issue to map them differently.
