### ISSUE TITLE
Writing Auto Test for changing Statuses Scenarios

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#343]
- [x] If Listing=Null stayed more than N days, automatically set it to "Listed"
- [x] Edit Projects: won't affect Verification status - changes listing to "not reviewed" means listing=null
- [x] Deactivating (Archiving): won't affect Verification status - won't affect listing status. 
- [x] Activating (Unarchiving): won't affect Verification status - changes listing to "not reviewed"
- [x] Cancelling (By admin): make it unverified & delisted. 
- [x] Verification approved: won't affect the listing status
- [x] Verification removed: won't affect listing status. 
- [x] Delisting: won't affect the verification status,
- [x] Listing: won't affect the verification status,

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/343?planning-poker) with ZenHub @mohammadranjbarz @CarlosQ96

**Comment by CarlosQ96** [comment]
I'll put 8, as I have to get familiar with certain testing tools first.

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  @MoeNick  I saw the code and I noticed the user can not active a deactivated/cancelled project, so this endpoint is useless, and I can't write test for this
**Activating (Unarchiving): won't affect Verification status - changes listing to "not reviewed"**
If it's a bug please tell me to fix that otherwise we can remove that from checklist

**Comment by mohammadranjbarz** [comment]
> @WhyldWanderer @MoeNick I saw the code and I noticed the user can not active a deactivated/cancelled project, so this endpoint is useless, and I can't write test for this **Activating (Unarchiving): won't affect Verification status - changes listing to "not reviewed"** If it's a bug please tell me to fix that otherwise we can remove that from checklist

Sorry it was my mistake, the description of statuses was misleading, so I misunderstood,

just another question if **User** activate the deactivated project we should change `listed` to null, what about when Admin activates a project?
@MoeNick

**Comment by mohammadranjbarz** [comment]
@MoeNick 
I wrote a migration file to change description/name of statuses in this PR, and I wrote a table for that, you can see that here
https://github.com/Giveth/impact-graph/tree/f_343_write_tests_for_changing_statuses_scenarios#statuses

**Comment by CarlosQ96** [comment]
PR approved! All tests correlate the list.

**Comment by MoeNick** [comment]
We had a talk with @mohammadranjbarz 

> > @WhyldWanderer @MoeNick I saw the code and I noticed the user can not active a deactivated/cancelled project, so this endpoint is useless, and I can't write test for this **Activating (Unarchiving): won't affect Verification status - changes listing to "not reviewed"** If it's a bug please tell me to fix that otherwise we can remove that from checklist
> 
> Sorry it was my mistake, the description of statuses was misleading, so I misunderstood,
> 
> just another question if **User** activate the deactivated project we should change `listed` to null, what about when Admin activates a project? @MoeNick

@WhyldWanderer can u pls elaborate more in this usecase?
