### ISSUE TITLE
"walletAddressIsValid" is case sensitive

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#359]
The results of this endpoint should be case in-sensitive

**Comment by mohammadranjbarz** [comment]
Thanks
@CarlosQ96  or I would take it ASAP

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/359?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  I take this issue

**Comment by mohammadranjbarz** [comment]
@RamRamez  I didnt see the problem that you said, I even wrote test cases for `walletAddressIsValid` to make sure, and I couldn't reproduce the problem that you said, could you give me two data to test with them?

For instance both of below queries return same result
```
{
walletAddressIsValid(address:"0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93B")
}
```

```
{
  walletAddressIsValid(address:"0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b")
}
```
<img width="1007" alt="Screen Shot 1400-11-25 at 09 28 11" src="https://user-images.githubusercontent.com/9850545/153808346-7bad7aa8-dcaa-4bbc-bc6e-da8cb1332bda.png">
<img width="1064" alt="Screen Shot 1400-11-25 at 09 28 20" src="https://user-images.githubusercontent.com/9850545/153808356-ba52a403-df23-4679-b999-2d4427d02445.png">

**Comment by RamRamez** [comment]
@mohammadranjbarz 
just by changing last character, it says "Eth address not valid"
![image](https://user-images.githubusercontent.com/73441857/153854308-6a788e46-0b9c-425e-823d-9b937bac23d1.png)

**Comment by mohammadranjbarz** [comment]
@RamRamez  That part is where we validate ethereum address with web3 , you can test it your self

1. 
```
const  Web3 = require('web3')
console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93B'))
```
return **true**

2.
```
const  Web3 = require('web3')
console.log(Web3.utils.isAddress('0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b'))
```
return **true**

3. 
```
const  Web3 = require('web3')
console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93b'))
```
return **false**

So I think you can't just make just one of characters lowercase otherwise the wallet address would not be validated by `web3`
and it's out of our control, because in this query first of all we check validity of sent address by web3

@aminlatifi  do you have any idea about this?

**Comment by mohammadranjbarz** [comment]
@RamRamez 

You can test the address here https://www.rfctools.com/ethereum-address-validator/ as well, and you would see the address is not valid

<img width="1145" alt="Screen Shot 1400-11-25 at 15 20 42" src="https://user-images.githubusercontent.com/9850545/153859332-f409ed41-b535-454b-98cd-b4af0c91e5fb.png">

**Comment by aminlatifi** [comment]
> @RamRamez That part is where we validate ethereum address with web3 , you can test it your self
> 
> 
> ```
> const  Web3 = require('web3')
> console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93B'))
> ```
> 
> return **true**
> 
> 
> ```
> const  Web3 = require('web3')
> console.log(Web3.utils.isAddress('0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b'))
> ```
> 
> return **true**
> 
> 
> ```
> const  Web3 = require('web3')
> console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93b'))
> ```
> 
> return **false**
> 
> So I think you can't just make just one of characters lowercase otherwise the wallet address would not be validated by `web3` and it's out of our control, because in this query first of all we check validity of sent address by web3
> 
> @aminlatifi do you have any idea about this?

The address should be all lowercase, all uppercase, or be in the correct format. It's not possible to randomly make the characters lower and upper case

**Comment by aminlatifi** [comment]
> > @RamRamez That part is where we validate ethereum address with web3 , you can test it your self
> > ```
> > const  Web3 = require('web3')
> > console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93B'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > return **true**
> > ```
> > const  Web3 = require('web3')
> > console.log(Web3.utils.isAddress('0x5ac583feb2b1f288c0a51d6cdca2e8c814bfe93b'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > return **true**
> > ```
> > const  Web3 = require('web3')
> > console.log(Web3.utils.isAddress('0x5AC583Feb2b1f288C0A51d6Cdca2e8c814BFE93b'))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > return **false**
> > So I think you can't just make just one of characters lowercase otherwise the wallet address would not be validated by `web3` and it's out of our control, because in this query first of all we check validity of sent address by web3
> > @aminlatifi do you have any idea about this?
> 
> The address should be all lowercase, all uppercase, or be in the correct format. It's not possible to randomly make the characters lower and upper case

https://piyopiyo.medium.com/how-to-convert-ethereum-address-to-checksum-address-cd3e2305e2fc
