### ISSUE TITLE
Having Draft Status for Projects and all of it's side-effects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#361]
As the project owner I need to have an option to save the project as draft, (or having a preview of the project) so I can make edits and publish it late. 

**Details:** 
0- we need to have a draft status in DB

1- 
saveProject():
Add an optional field, isDraft otherwise it would be active  by default

2-
getProject(I dont know exactly the name)
For draft status , user should be logged in and be admin of project

3-
activateProject
draft status can be activated as well

PS: The cronjob that make projects listed after a time , should check the project status and not make listed the draft projects
All endpoints should be backward compatible 

4-
Get project list by owner ( we dont know wht's the query name )
My account --> My projects
Should check user authentication and return all projects including draft, cancelled, deactive, active, ...

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/361?planning-poker) with ZenHub @mohammadranjbarz @CarlosQ96

**Comment by CarlosQ96** [comment]
Taking up this issue today and tomorrow.

**Comment by MoeNick** [comment]
> Taking up this issue today and tomorrow.

Appreciate it, shall we have some estimates before we start?

**Comment by CarlosQ96** [comment]
Did points 0, 1, 3, 4 and the cronjob modified.
Regarding 2, I think logic regarding the status is done on the frontend. I'll modified it so it returns null if you are not logged in. Drafts shouldn't be visible. I assume it's the project by slug query and projectbyId

**Comment by mohammadranjbarz** [comment]
@MoeNick 

When getting list of projects of user should we return just `listed` and `active` projects?
I mean when visiting someone else projects not my projects tab

**Comment by MoeNick** [comment]
> @MoeNick
> 
> When getting a list of projects of users should we return just `listed` and `active` projects? I mean when visiting someone else projects not my projects tab

Yes, yes :)

**Comment by MoeNick** [comment]
We have owner view and public view,  listed and active is for getting in all public view (search, home page, projects, and project list of public profile ) 

But for the owner view, all statuses should be visible on my account -> list if projects,

We have a little bit different scenario for Project-Single page which is not the case, but we can discuss it in DM, thanks

**Comment by mohammadranjbarz** [comment]
> We have owner view and public view, listed and active is for getting in all public view (search, home page, projects, and project list of public profile )
> 
> But for the owner view, all statuses should be visible on my account -> list if projects,
> 
> We have a little bit different scenario for Project-Single page which is not the case, but we can discuss it in DM, thanks

Thanks Moenick

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  implemented this issue

@MohammadPCh  @RamRamez  @mateodaza 

When calling `addProject` mutation, you can pass `isDraft?: boolean` to indicate after creation project should be `drafted` or `active` and `drafted` projects are visible just for project owner in `projectById` , `projectBySlug`, `myProjects` queries, 
And you can't see `drafted` projects in `projects` and `projectsByUserId` queries

@MoeNick  If there is anything unclear, please tell us, I and Carlos would fix it
