### ISSUE TITLE
Authentication for uploading pictures

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#366]

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/366?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by CarlosQ96** [comment]
This is done, it calls the checkIfUserInRequest and if user exists. If we do make another endpoint for cherik I'll include it on the other issue and reuse the same auth.
