### ISSUE TITLE
Admin Dashboard - Need an export to .csv option

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#367]
As an admin, I want to be able to export a set of data into a .csv file.

**Comment by CarlosQ96** [comment]
Writing a middle ware for downloading csv. Might take a bit longer.

**Comment by divine-comedian** [comment]
teting on `serve.admin`

I'm not sure this is working..

on the project page in the admin dashboard I see the option to export filter to CSV I've tried a few things all with the same result:

- selecting a few or all projects on the page with the checkbox and hitting export
- applying a filter and hitting export
- applying a filter then selecting a few projects then hitting export

all attempts to export anything are met with this:
![image](https://user-images.githubusercontent.com/67759413/175644368-6be90857-0afd-4499-bc6c-e138cf902c4f.png)

also, this is only available on the project section, is it intended to be available on other sections as well?

moving this to backlog!

**Comment by jeevanplus007** [comment]
@CarlosQ96 Can you look into this ?
