### ISSUE TITLE
Admin Dashboard  - Improve search functionality (title)

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#368]
As an admin, It would be very useful to be able to search for projects by a title that may not be exact.

As of now if I search for a project it is case-sensitive and I am required to search for the 'exact' title, I would love to have more flexibility within the search.

**Comment by CarlosQ96** [comment]
Underestimated this task, seems I gotta investigate a bit more, Adminbro not that flexible.

**Comment by CarlosQ96** [comment]
@MoeNick I think this can wait a bit so we can do the Change API integration. Gotta rewrite a big chunk of adminbro. I don't think it's a good idea, unless I find an easier solution.

**Comment by RamRamez** [comment]
We did some improvements on search functionality and I think we can close this. @WhyldWanderer WDYT?

**Comment by WhyldWanderer** [comment]
Thanks Ramin!

I think its working better than when I made the issue.

However, its still strange to me that when I search "codex" or "CODEX" on the projects page, I do not get this project at all:
https://giveth.io/project/codex

It seems that the "$" sign keeps it from being searchable somehow. It seems that this would be something that we could account for? I think its disheartening for project owners when they search their project on the page and don't see it show up on the list.

I will keep an eye out as Im searching projects etc for use cases such as this and post any here that I find in the coming days in case that might be helpful.

**Comment by RamRamez** [comment]
@Reshzera Can you please take this?

**Comment by Reshzera** [comment]
@RamRamez Sure

**Comment by WhyldWanderer** [comment]
Im sorry @RamRamez.. I was out of my element. There are 2 issues involving search functionality and I thought I was in the other issue. Apologies!

I would hate to put too much dev resources into this issue as it is really just a nice to have.

If Carlos doesnt think its a good idea, I trust his knowledge of the issue.
I think we can close this one

**Comment by Reshzera** [comment]
@RamRamez @WhyldWanderer I couldn't find a solution to this issue, because I couldn't find some way to change the built-in filters on AdminJs.

**Comment by CarlosQ96** [comment]
Sadly customizing the query of the filter directly is not posible, only the html form. 
I have rewriten before queries in the admin js but its a massive ordeal and will probably force you to rewrite the whole filter component.

**Comment by CarlosQ96** [comment]
Upon further investigation this is simply not posible on adminjs. Not even overriding filters. It basically only allows adding custom html dropdowns, but not modify queries. 
There is a 2023 PR on Adminjs main repo that fixes this issue, but it has not been merged to adminjs Master.
I don't think we should spend more time on this. 

@WhyldWanderer Ill close the issue as it's imposible without overwriting database adapters from the framework (not recommended as we would need to fork). We can hope they merge the PR to Adminjs Repo sometime this year.

Refer to this conversations for adminjs: 
https://github.com/SoftwareBrothers/adminjs-sequelizejs/issues/107

We can reopen the issue, if they merge Postgresql PR, so all we would need to do is to update the framework.
