### ISSUE TITLE
Admin Dashboard - Improve Search Functionality (slug)

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#369]
As an admin, I want to be able to search for a project by slug.

**Comment by CarlosQ96** [comment]
This issue is on staging :D

**Comment by MoeNick** [comment]
@CarlosQ96 When we can merge it to productiob? Ashley already accept it

**Comment by CarlosQ96** [comment]
I think we should coordinate a release, we haven't deploy some other features that are being worked on in the ts version. I shall talk to mohammad.

**Comment by WhyldWanderer** [comment]
I realized that this issue is redundant: https://github.com/Giveth/giveth-next/issues/646

**Comment by divine-comedian** [comment]
@CarlosQ96 Did this one ever get done?

**Comment by WhyldWanderer** [comment]
yes! I am able to search projects by slug now on production.. closing this issue
