### ISSUE TITLE
Admin Dashboard - Improve Search Functionality (date range)

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#370]
As an admin, I would like to be able to search for all projects created between Date A and Date B.

**Comment by WhyldWanderer** [comment]
its not showing correctly
for instance it says that only one project was created between May 13th 2021 and Feb 8th 2022
![image](https://user-images.githubusercontent.com/74267818/155212991-4c235a71-a411-4de3-b467-9b5f1c711ff2.png)

**Comment by MoeNick** [comment]
@CarlosQ96 I think another filter is applying here beside date range.

**Comment by CarlosQ96** [comment]
Haven't been able to reproduce this issue

**Comment by divine-comedian** [comment]
@WhyldWanderer is this feature still broken?

**Comment by WhyldWanderer** [comment]
Seems to be working fine now.. I just checked! @divine-comedian 
I think we can close it
