### ISSUE TITLE
Admin Dashboard - Mandatory updates for verified projects

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#371]
Verified projects will be required to make updates on their projects. If they go 3 months without making an update, their badge should automatically be revoked within the AdminBro.

If they make an update to their project after the badge has been revoked, it will need to be reviewed by the team and the badge reinstated... however the project should not need to resubmit a verification application.

How do we differentiate between updates that have been provided by projects that were previously verified vs. updates provided by projects that have never had a verified badge?

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/371?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by CarlosQ96** [comment]
Like we talked in the meeting. The scope is creating the cronjob that revokes badges only. 
No more work is required.

**Comment by mohammadranjbarz** [comment]
> Like we talked in the meeting. The scope is creating the cronjob that revokes badges only. No more work is required.

We should add some history records for these changes as well

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  When revoking the badge of this kind of projects, is it needed to send email to project owner?

**Comment by CarlosQ96** [comment]
I think we can reuse the same revoke badge event I made for the adminbro.
However, I just noticed it's not being recorded in the segment analytics debugger.
I am not sure if there is a limit on events.

**Comment by mohammadranjbarz** [comment]
> I think we can reuse the same revoke badge event I made for the adminbro. However, I just noticed it's not being recorded in the segment analytics debugger. I am not sure if there is a limit on events.

Thanks for mentioning, I will look at that part of code

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer When revoking the badge of this kind of projects, is it needed to send email to project owner?

Yes. The reject button will trigger an email saying "your verification application was rejected" The revoke button will trigger an email saying "your badge has been revoked"

Carlos mentioned that we could do this using logic on the button itself..

**Comment by CarlosQ96** [comment]
> > @WhyldWanderer When revoking the badge of this kind of projects, is it needed to send email to project owner?
> 
> Yes. The reject button will trigger an email saying "your verification application was rejected" The revoke button will trigger an email saying "your badge has been revoked"
> 
> Carlos mentioned that we could do this using logic on the button itself..

Yeah I did it for the adminbro I will add it also on the revoke badge task.

**Comment by mohammadranjbarz** [comment]
@CarlosQ96 
Please add `isImported` field to project entity, then write a migration file to set this `true` for givingblocks and trace projects, and when creating those projects set `true` for those projects

And in revoke badge job exclude `isImported` projects

@MoeNick Am I right?

**Comment by CarlosQ96** [comment]
Yeah I think we can use that field for any imported project. (whether they are from giving blocks or in the future the change api)

**Comment by WhyldWanderer** [comment]
I am realizing something about this...

When this is implemented, it will revoke all badges of projects that havent added updates in the past 3 months. 
We need to have time to communicate this to current project owners so that they have a chance to add updates before revoking their badges. Unless there is a way to make our current project list exempt for a certain amount of time after implementation.

Also, what will happen with the Giving Block project badges? These projects do not have admins to add updates to them.

What happens to traceable projects when the verified badge gets revoked? Is there traceable badge also removed?
The way it has been working is that they have to have a verified project to upgrade to TRACE right?

These are some topics we should discuss before implementing this on production.

**Comment by CarlosQ96** [comment]
On top of this, I was talking to Mitch, and we should add emails for every month/two months telling the project to add updates. 
Regarding the GivingBlocks they are excluded from this project.
What do you think about the traceable badge? @mohammadranjbarz  Should I exclude trace projects too?

I shall add and activation date for this process so we can get the communications going.

**Comment by mohammadranjbarz** [comment]
> On top of this, I was talking to Mitch, and we should add emails for every month/two months telling the project to add updates. Regarding the GivingBlocks they are excluded from this project. What do you think about the traceable badge? @mohammadranjbarz Should I exclude trace projects too?
> 
> I shall add and activation date for this process so we can get the communications going.

It's business decision but from technical side I would tell it's not good to revoke givingBlock and traceable badge, because with revoke that we are telling that they are not connected to third party, but there are, so we need to add some additional fields, and additional checking that they  may our codes and logics  messy

@MoeNick  What do you think about all these stuff?

**Comment by MoeNick** [comment]
@mohammadranjbarz @CarlosQ96 
1- please exclude trace and givingblock and third party projects from this change.
2- Sending emails is not in this issue, this issue which is planned is only applying to the discussed job. 
3- pls keep the track of changing log, aiming that we can add a view to adminbro later showing the status reason of "not proving updates in 3 months"

**Comment by WhyldWanderer** [comment]
I plan to create a spec document for mandatory updates to include the requirements for all WGs involved. 
I will share the document here once I have started. It will be good to have this so that we can make sure that all parties are ready for implementation on production before migrating from staging. (Comms, Dev, Design, Admin, etc)

**Comment by CarlosQ96** [comment]
@WhyldWanderer I have this. pull request there. Let me know if this feature still in the horizon or should I close it?
