### ISSUE TITLE
Define integrate with third parties ( like givingblock, change, ...) policy

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#379]

**Comment by aminlatifi** [comment]
1. If a project is removed, there is no webhook, CHANGE API said they would send us an email if necessary
Have a corn job that rechecks regularly and deactivates projects which are not available on givingblock anymore. 
2. Only eth accepted
Preparing a service in the backend to resolve the valid tokens-network for every project.
3. SOME Projects in the CHANGE API  are also present in the Givingblocks, should we have repeated projects one for givingblocks and one for Change?
How do we know two projects are the same?

**Comment by CarlosQ96** [comment]
CHANGE API: https://docs.getchange.io/api/#Nonprofits-Show-a-nonprofit
GIVINGBLOCKSAPI: https://the-giving-block.gitbook.io/public-api-documentation/endpoints-documentation

**Comment by CarlosQ96** [comment]
V1 Diagram of CHANGE API integration: (ignore the api/v1/donations endpoint, I was told they handle that on their side)
[![](https://mermaid.ink/img/pako:eNptVE1v2zAM_SuEL9sAt8Wwmw8dlqZdh2Fr0KTbxRdGYmwttuRJcrOs6H8vFdmJk1i-WCL5-Pj5kggjKckSR39b0oKmCguLda6BD7be6LZeku3uwhsLT66_N2i9EqpB7eHOGu1Jy3PJD_JYo1ufSyYo1qMmNyXqgr7Mvp2LppNcx9fKmAbmWy1Kdq3-E_w0embNSnkHM7LKSCWwqrZRO5zOH1xcXx9cZHBHXpTBGnrzjfIlfL1dwBU26ur545U2uomyA5o2nsA8kx1iPTmlC_AlgUBPhbGKHKADR2jZCUeC9QBjb7nj1PHL4JF8a7U74jTDQmnGlOPxTCcZzPF5kIUYxe3iHjacBvKAUlpyoxHsPTNECEBjTSlQjapKOdGFScEZobDqrHdVi7-hHXYM-g7I4HcolDcgTSAc1Q6-Dno3JYk1cGL_kPBnLKNdr71z0bcSsK0lxgZvUTvuS2U6_b3KRTAI5Dio0mxAGL1Sth5aQGOatjkJowfI4GF9CjmIkinsfwum7f_doythuYUNLT-NcB-mmEDTJqZnT3ykGL-wUjJE2Wu-c6D0ysTKjucthZYjSeHyMsKO9kiPF4oUBiooTicxZb1BjP8cZNDsjySMlTDt0Lq5mT3MD4PTe-r6ZtDvRzl5-H6ahIGbRak4bhfI8qOsOHv7ueCJ2pqWx4MFsFRV5eC95V2mLMnPH874H_dp8Hr8weAkaVKT5RGQvB9fgixPeLBrypOMfyWtsK18nuT6lVXbJlTqVipekUnmbUtpEvZnWFD9Pep0KzY-vr4BR_bTRw)](https://mermaid.live/edit/#pako:eNptVE1v2zAM_SuEL9sAt8Wwmw8dlqZdh2Fr0KTbxRdGYmwttuRJcrOs6H8vFdmJk1i-WCL5-Pj5kggjKckSR39b0oKmCguLda6BD7be6LZeku3uwhsLT66_N2i9EqpB7eHOGu1Jy3PJD_JYo1ufSyYo1qMmNyXqgr7Mvp2LppNcx9fKmAbmWy1Kdq3-E_w0embNSnkHM7LKSCWwqrZRO5zOH1xcXx9cZHBHXpTBGnrzjfIlfL1dwBU26ur545U2uomyA5o2nsA8kx1iPTmlC_AlgUBPhbGKHKADR2jZCUeC9QBjb7nj1PHL4JF8a7U74jTDQmnGlOPxTCcZzPF5kIUYxe3iHjacBvKAUlpyoxHsPTNECEBjTSlQjapKOdGFScEZobDqrHdVi7-hHXYM-g7I4HcolDcgTSAc1Q6-Dno3JYk1cGL_kPBnLKNdr71z0bcSsK0lxgZvUTvuS2U6_b3KRTAI5Dio0mxAGL1Sth5aQGOatjkJowfI4GF9CjmIkinsfwum7f_doythuYUNLT-NcB-mmEDTJqZnT3ykGL-wUjJE2Wu-c6D0ysTKjucthZYjSeHyMsKO9kiPF4oUBiooTicxZb1BjP8cZNDsjySMlTDt0Lq5mT3MD4PTe-r6ZtDvRzl5-H6ahIGbRak4bhfI8qOsOHv7ueCJ2pqWx4MFsFRV5eC95V2mLMnPH874H_dp8Hr8weAkaVKT5RGQvB9fgixPeLBrypOMfyWtsK18nuT6lVXbJlTqVipekUnmbUtpEvZnWFD9Pep0KzY-vr4BR_bTRw)
