### ISSUE TITLE
Valid token/network per project endpoint

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#380]
OrganisaionTable:
ThP name (Giveth / Givengblock etc) 
Endpoint
OrganizationType

Policies Table: 
eligible network
Token List

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/380?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Now we have an endpoint that frontend can use that for knowing a projects accept what tokens, I think you can create an issue for frontend DEVs to implement it later

This is the graphql query sample:

```
query{
  getProjectAcceptTokens(projectId:1){
      id
      symbol
      networkId
      address
      name
  }
}
`
```

**PS** 
As the changes are huge besides testing this query I think  all of main scenarios, like create/edit projects and donation should get tested through this issue
