### ISSUE TITLE
Track image uploader users

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#383]
- We should record who has uploaded each image. 
- Also, it will be beneficial if we record image size too in order to allow us to put a limit on how much each user can upload.
- We should track which images are used. If a user uploads an image (edit profile, create a project, etc.) but does not used it we should be able to remove it (release it on ipfs) after a while
- The image field in other entities (project, user, etc.) should be a PK to this table

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/383?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by aminlatifi** [comment]
About file resizing, pinata has an image optimizer feature... good news.
It would be nice to create images in different sizes (Project page, project card, profile image in menu, ...). It would improve page load time significantly. WDYT @MohammadPCh ?

**Comment by jainkrati** [comment]
@MoeNick what is the priority of this issue? p2?

**Comment by MoeNick** [comment]
It's a nice to have @jainkrati 
Would help loading of pages
