### ISSUE TITLE
Admin Dashboard - Search for project by recipient address

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#385]
as an admin it would be nice to be able to find a project by its recipient eth address using the filter feature

**Comment by divine-comedian** [comment]
@CarlosQ96 @mohammadranjbarz  this would be an awesome feature

**Comment by CarlosQ96** [comment]
I can add this, there is not much effort to it. But some projects have their addresses lowercase/uppercase so ill check that first. Maybe ill have to convert all to lowercase.

**Comment by divine-comedian** [comment]
@CarlosQ96 is this one still relevant?
