### ISSUE TITLE
Importing projects from CHANGE API in our staging

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#390]

**Comment by MoeNick** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/All-Devs-61644589b92edf0016f6999c/issues/Giveth/impact-graph/390?planning-poker) with ZenHub @CarlosQ96 @mohammadranjbarz

**Comment by CarlosQ96** [comment]
To test this, go into the adminbro:
Enter **Third Party Project Imports** link to the left. It will take you to this page where you will be able to create a new import from the changeAPI.
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/92376054/160735694-61a1840d-77b9-4a79-99d1-c57a33875b3f.png">

This project should be visible in the site. To import the project write the exact title or IEN from the change website. Example: 
https://getchange.io/nonprofit/?address=D1XBJG85gs7DT43TraBBpUiLpDBQ8zrTLyjneP5onaWw

Title: Electronic Frontier Foundation
The EIN is on the bottom of the page: 
<img width="120" alt="image" src="https://user-images.githubusercontent.com/92376054/160735869-52467255-3f0f-4576-9f4f-eeae976c9bd0.png">


Form:
<img width="1464" alt="image" src="https://user-images.githubusercontent.com/92376054/160735964-af4eb207-6e0f-4818-8909-68bf81b08676.png">

**Comment by CarlosQ96** [comment]
Project duplication is not allowed. Honestly this is pointing to prod projects because there is no staging on the changeAPI.
I wrote some tests for testing donations.

**Comment by CarlosQ96** [comment]
@MoeNick you can search more projects in this link https://getchange.io/nonprofit/?address=D1XBJG85gs7DT43TraBBpUiLpDBQ8zrTLyjneP5onaWw in the search bar.
And import them.
I think this is ready to be merged after testing in staging.

**Comment by MoeNick** [comment]
Good job @CarlosQ96 Thanks
The funny thing is we say it's a GivingBlock project on our UI. Like this: 
https://giveth-dapps-v2.vercel.app/project/alzheimers-association
Do we set proper Org config for them?

**Comment by CarlosQ96** [comment]
Hello @MoeNick I think the frontend has to do a change, thanks for finding it.
On the db it has the proper org
<img width="122" alt="image" src="https://user-images.githubusercontent.com/92376054/160836145-e20b6e98-8a52-4fb0-ad7c-0fe3f4bb02d7.png">

Frontend now has the organization available by the organization attribute. Mateo used it for the custom tokens.
@mateodaza
