### ISSUE TITLE
Implement createProject mutation to work with new version

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#396]
This webservice get image as pinataUrl in input

**Comment by mohammadranjbarz** [comment]
@RamRamez  please move it done when you thought this works good

**Comment by jeevanplus007** [comment]
@RamRamez @mohammadranjbarz - Any Scope for Testing for this Issue ? Any Scenarios to be considered that would help ?

**Comment by jeevanplus007** [comment]
**Test Status :** PASS in STAGING

**Test URL :** https://staging.giveth.io/create

**Test Results :** Create Projects are working fine.

**Snapshot - Create Project :**
![image.png](https://images.zenhubusercontent.com/62a3cf4962612d632dd3b42a/40149022-c058-445e-b1f2-cfcf69bbc6d2)

**Comment by mohammadranjbarz** [comment]
> @RamRamez @mohammadranjbarz - Any Scope for Testing for this Issue ? Any Scenarios to be considered that would help ?

It was just some refactoring, if create project works, it means it's ok

**Comment by jeevanplus007** [comment]
It is Test Complete. Moving to DONE.
