### ISSUE TITLE
Implement updateProject mutation to work with new version

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#398]
This webservice get image as pinataUrl in input, after finalizing new version of giveth.io we will remove `editProject` mutation

**Comment by mohammadranjbarz** [comment]
@RamRamez  please move it done when you thought this works good

**Comment by RamRamez** [comment]
> @RamRamez please move it done when you thought this works good

I don't have permission to move.

**Comment by mohammadranjbarz** [comment]
> > @RamRamez please move it done when you thought this works good
> 
> I don't have permission to move.

@MoeNick  Ramin approved this change, you can move it to `Done`

**Comment by jeevanplus007** [comment]
@mohammadranjbarz  @RamRamez - Any Scenarios to Test this. ? Are we Testing "Updates" Tab Project Section ?

**Comment by jeevanplus007** [comment]
**Test Status :** PASS in STAGING

**Test URL :** https://staging.giveth.io/create

**Test Results :** Update Projects are working fine.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @RamRamez - Any Scenarios to Test this. ? Are we Testing "Updates" Tab Project Section ?

It was just some refactoring, if updating project works, it means it's ok
