### ISSUE TITLE
Backend Validation issues over project status businesses

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#416]
Talking about all detail information, not list view: 

- [x]  Prevent Public View of Draft Projects 
- [x] Prevent Public View of Cancelled Projects 
- [x] Show the Cancelled Project to the owner
- [x] Show the Draft Project to the Owner

---------
- [x] Prevent Editing on a project without owner credentials
- [x] Prevent ANY donations over deactivated projects
- [x] Prevent ANY donations over canceled projects
- [x] Prevent ANY donations over "draft" projects
- [x] Prevent deactivating / activating by public user. 
 --------

- [ ] As an admin, I can do all the above without any prevention.

**Comment by mohammadranjbarz** [comment]
I'll handle #381 in this issue

**Comment by mohammadranjbarz** [comment]
@MoeNick  I set validation to just `active` projects accept donation
