### ISSUE TITLE
Using asymmetric sign for jwt, to frontend can validate token by public key

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#426]
@aminlatifi 
If we implement this, then frontend can always validate access token locally by just a function call

**Comment by divine-comedian** [comment]
@mohammadranjbarz is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is this issue still relevant?

With Authentication microservice we don't need this anymore
