### ISSUE TITLE
Add PoignArt donations automatically to our db

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#433]
We should write a job to periodically check PoignArt subgraph and for every withdrawal we need to create a donation in our db
https://hackmd.io/pQpfEtW7T4u93D6Q7O3-yQ

We should use this query
```
{
  withdrawals(where: {recipient:$unchainAddress}) {
    recipient {
      id
    }
    amount
    transaction {
      id
      timestamp
      blockNumber
    }
  }
}
```

`$unchainAddress` : **0x10E1439455BD2624878b243819E31CfEE9eb721C** ( @laurenluz  gave me this) and this is the walletAddress of https://giveth.io/project/unchain-fund

**PS**: the transfers are just `ETH` so we should not be concerned about `erc20` tokens

we should consider these:
- [x] Donations should have `verified` status
- [x] We should get Eth price in that tx from https://givback.develop.giveth.io/api-docs/#/default/get_givPrice and fill the value for those donations
- [x] Cronjob interval time should be in config
- [ ] In the end we should see the donations in https://givback.develop.giveth.io/api-docs/#/default/get_eligible_donations

**Comment by CarlosQ96** [comment]
@MoeNick This is also ready the cronjob is running in staging with the poignArt and it added the two test donations to our server
![image](https://user-images.githubusercontent.com/92376054/161100398-e4d73356-8b21-45c2-9d71-5394ca59cfb1.png)

**Comment by CarlosQ96** [comment]
![image](https://user-images.githubusercontent.com/92376054/161106362-e4b4db69-e97e-4032-95c7-831256accf8c.png)
on staging they are visible on my project
https://giveth-dapps-v2.vercel.app/project/ok-title

**Comment by CarlosQ96** [comment]
But as you can see the donor is empty because this is a contract doing the donations and we fetch from their subgraph. 
What should we show in the donor? We added a donationType='poignArt'
I didn't feel setting it as anonymous was right.

**Comment by CarlosQ96** [comment]
This is the test address they gave us to simulate this in staging, donations are added to that project as you can see in the pictures: 0x66f59a4181f43b96fe929b711476be15c96b83b3

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  Thanks man for finishing it
