### ISSUE TITLE
Improve create rainbow roll donation page

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#434]
- [ ] Should set `isProjectVerified` to `project.verified` for these donations, currently we set `false` for it ( and we should remove it's checkbox)
- [ ] Select clear name  for segment notified checkbox
- [ ] We can send the segment immediately instead of delegate it to our job to send it later

**Comment by MoeNick** [comment]
Im not aware of this issue, do we still need it? 

FYI: @jainkrati @divine-comedian
