### ISSUE TITLE
Support custom tokens for Giveth (not third party) projects

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#441]

**Comment by mohammadranjbarz** [comment]
- [x] Set a field name `supportCustomToken` to `organization` table ( with `false` as default value)
- [x] Write a migration file to set this field `true`  `giveth` and `trace` organization
- [x] In `donation` table we should add a field `isTokenEligibleForGivback`
- [x] in `saveDonation` mutation we should check if sent token is not in project(organzation) token list , we check if organization support custom token we allow user to donate but we set `isTokenEligibleForGivback:false`  for this donations ( other donations should have `isTokenEligibleForGivback:true` )
- [x] Return organization (join table) in `projects` query response
- [x] Return organization (join table) in `projectById` query response
- [x] Return organization (join table) in `projectBySlug` query response
- [x] Return organization (join table) in `projectByAddress` query response

**Comment by CarlosQ96** [comment]
The isTokenEligibleForGivbacks should go in the token table also too no?
Maybe other tokens might be in the list but not elegible for givbacks. Correct me if I am wrong with the business logic.

Everything else seems good.
Do we still use ```projectByAddress``` ? if so we should also return the organization there.

**Comment by mohammadranjbarz** [comment]
> The isTokenEligibleForGivbacks should go in the token table also too no? Maybe other tokens might be in the list but not elegible for givbacks. Correct me if I am wrong with the business logic.
> 
> Everything else seems good. Do we still use `projectByAddress` ? if so we should also return the organization there.

Thanks, nice suggestion about `projectByAddress`

`isTokenEligibleForGivbacks` can't be in token, because a token can be eligible for givback for an organization but for another organization it can be not-eligible, so when creating donation we should consider that and fill this field in donation ( and givback-calculation would check that field

**Comment by mohammadranjbarz** [comment]
@RamRamez 
After merging PR of this issue you can get organization when getting project/projects
example:

```
query{
  projectBySlug(slug:"how-many-photos-is-too-many-photos"){
    slug
    slugHistory
    updatedAt
    listed
    id
    title
    traceCampaignId
    totalReactions
    totalDonations
    image
    totalTraceDonations
    status{
        id
        name
    }
    organization {
    name
    label
    supportCustomTokens
    }
  }
}
```

**Comment by mohammadranjbarz** [comment]
> projectByAddress

I asked @RamRamez  and he said they dont use `projectByAddress` in frontend

**Comment by mohammadranjbarz** [comment]
> > The isTokenEligibleForGivbacks should go in the token table also too no? Maybe other tokens might be in the list but not elegible for givbacks. Correct me if I am wrong with the business logic.
> > Everything else seems good. Do we still use `projectByAddress` ? if so we should also return the organization there.
> 
> Thanks, nice suggestion about `projectByAddress`
> 
> `isTokenEligibleForGivbacks` can't be in token, because a token can be eligible for givback for an organization but for another organization it can be not-eligible, so when creating donation we should consider that and fill this field in donation ( and givback-calculation would check that field

I asked @RamRamez and he said they dont use projectByAddress in frontend

**Comment by mateodaza** [comment]
we're currently using givingBlocksId to know if the project comes from there, should we move this to the organization field? do change projects have their own ID?

**Comment by CarlosQ96** [comment]
@mateodaza PRojects now have a column called isImported which tells you if its a third party project.
But you should check the organization to know from where it is.
This are the labels.
```
export const ORGANIZATION_LABELS = {
  GIVETH: 'giveth',
  TRACE: 'trace',
  CHANGE: 'change',
  GIVING_BLOCK: 'givingBlock',
};
```

**Comment by mateodaza** [comment]
@CarlosQ96 cool yes! I saw, but I mean the ID, maybe we need that? not sure if CHANGE have one, I know trace and giving block do

**Comment by CarlosQ96** [comment]
For now it's, Change also has an id.
changeId
<img width="232" alt="image" src="https://user-images.githubusercontent.com/92376054/160838108-39f4c0b2-e589-410e-aeaa-097af14fc1c6.png">

**Comment by CarlosQ96** [comment]
<img width="232" alt="image" src="https://user-images.githubusercontent.com/92376054/160838065-81754667-dc34-431b-856d-114130c72c37.png">

**Comment by mateodaza** [comment]
> For now it's, Change also has an id. changeId <img alt="image" width="232" src="https://user-images.githubusercontent.com/92376054/160838108-39f4c0b2-e589-410e-aeaa-097af14fc1c6.png">

ok! maybe consider moving that to the organization field it's gonna be cleaner for the frontend to read

**Comment by CarlosQ96** [comment]
Yeah but the organization ID is per project so I can't move it to the org. Unless we do an intermediete model. between org and project.
