### ISSUE TITLE
Issue add uniqueness to emails

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#445]
This is causing issues in the adminbro login, multiple people with the same email. OR we move the adminbro login to another entity

**Comment by CarlosQ96** [comment]
This is serious as we are having duplicated users with different wallets but same email, this can also conflict many other log ins.

@MoeNick

**Comment by CarlosQ96** [comment]
This could be the reason people can't see their projects.
They log in, but the db matches a duplicate without their project, the UI says they are logged in with correct address/email but in reality they aren't. So they can't see their project. I remember there was 1 report of this issue before.

**Comment by CarlosQ96** [comment]
Maybe adding uniqueness RIGHT AWAY isn't the solution. But moving the adminUser to another entity would reduce login issues.

**Comment by MoeNick** [comment]
I didn't get the point, sorry
we added uniqueness of email for admin bro login?

**Comment by CarlosQ96** [comment]
No. Look at the image:
![image](https://user-images.githubusercontent.com/92376054/160285300-3fdf85b5-f3ce-4ea8-9254-e7c33850d0f9.png)

**Comment by CarlosQ96** [comment]
So while testing with Ashley some other stuff. We found she had in prod 6 accounts. 1 of them is the admin account too.

So when trying to log in by email in the adminbro. The db was selecting the wrong user (that doesn't have password) and returning error that it didn't match her password.

**Comment by CarlosQ96** [comment]
Admins from adminbro use the same entity as the normal Users, so they can overlap, we should separate them.

**Comment by CarlosQ96** [comment]
And as we can see, emails are not unique. They can be repeated.

**Comment by MoeNick** [comment]
Oh thanks @CarlosQ96 I got it.

**Comment by MoeNick** [comment]
Thank for making it clear @CarlosQ96, another solution might be adding roles to the user table, so only admins are considered as AdminBro users. 
We may need this for further multi-level account feature in the future.
