### ISSUE TITLE
WalletAddress should be case insensitive on users

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#446]
WALLETS are CURRENTLY CASE SENSITIVE
This can cause the issue when an admin changes the address and then the user logs in with the wallet, creating two different users. Old users experience this issue more.

Wallet should be case insensitive @MoeNick

**Comment by divine-comedian** [comment]
@CarlosQ96 is this issue still relevant?

**Comment by divine-comedian** [comment]
@CarlosQ96 double check if we fixed this issue already.
