### ISSUE TITLE
Adminbro User table is stretched out 

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#447]
Minor issues gotta fix the table its looking bad.
<img width="693" alt="image" src="https://user-images.githubusercontent.com/92376054/160255812-7d220bd2-ff77-4d97-acab-97936446ef3f.png">

**Comment by divine-comedian** [comment]
@CarlosQ96 is this issue still relevant?

**Comment by CarlosQ96** [comment]
No longer relevant @divine-comedian updating the framework fixed it
