### ISSUE TITLE
Add isGivbackEligible t token entity

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#462]
During the weekley sync meeting we talked about tokens and as result I think we should these steps
- [x] Add a boolean to token entity named `isGivbackEligible`
- [x] Write a migration to set `true` for `isGivbackEligible` for existing tokens, these should be checked by @laurenluz 
- [x] When in donationResolver.saveDonation() we fill `isTokenEligibleForGivback` we should consider just we can set it true if token is givback eligible
- [x] Write at least two test cases for above item, create donation with `givback eligible token` and `givback not eligible token` and check the saved donation's `isTokenEligibleForGivback` field
- [x] #463
 
 **PS** When client call `getProjectAcceptTokens` query, it should get all accepted tokens (eligible + not eligible)

**Comment by CarlosQ96** [comment]
Just missing the adminbro item, will think it through tomorrow. Not completely sure how do do the organization selection part just yet, considering the adminbro inflexibility.
Probably a custom entity again...
