### ISSUE TITLE
Add an adminbro tab to create new tokens that are accepted and relate it to organizations.

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#463]

**Comment by mohammadranjbarz** [comment]
@MoeNick @WhyldWanderer 
Now the PR of @CarlosQ96 is depoyed on UAT, 
you can test it now, I made a checklist for anyone who wants to test
- [x] Relate/Unrelate organizations to tokens (After these changing you should see the changes of token list in donate page of projects)
- [x] Add new tokens
- [x] Edit existing tokens
- [x] Only admin can edit tokens ( Operators  can't)

**Comment by divine-comedian** [comment]
testing on `https://serve.giveth.io/admin`

I am on the `Token` tab I try to add a new token - I enter all the information and hit save and this error appears: 

![image](https://user-images.githubusercontent.com/67759413/163633580-c1bf3026-7293-420f-a211-1269522f6323.png)

however the token appears to be successfully added to the list 
![image](https://user-images.githubusercontent.com/67759413/163633650-da04e693-cb13-42c4-8791-39122d32edc7.png)

and it shows up on the donate page and I can successfully donate to a project with it - 
![image](https://user-images.githubusercontent.com/67759413/163634187-fd43a293-de3a-421b-9f7a-ac32e95a32bb.png)
the donation shows up appropriately on the donations tab of the project's page

**Comment by CarlosQ96** [comment]
Funny it says, Error 200, when 200 is status OK

**Comment by CarlosQ96** [comment]
I'll take a look

**Comment by divine-comedian** [comment]
More Testing - I can successfully edit the info of a token. changing the name and changing which platform it can be used on. when i remove it from giveth it no longer shows on the donate page. however when I add it to Trace I can not find the token anywhere on the list to donate - however we can see there are many tokens eligible in trace to be donated 

![image](https://user-images.githubusercontent.com/67759413/163635141-7b375769-780f-4b9b-980c-918334f962b5.png)

![image](https://user-images.githubusercontent.com/67759413/163635298-1d11db3f-fe6e-4948-9488-2a52b77f3670.png)

also on the first photo above you can see I have two tokens with separate names but they have the same token address - this shouldn't be allowed.

**Comment by divine-comedian** [comment]
I only have access to an admin account - do we have a dummy operator account I can test with @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
I don't but you can create it in the user admin page if you are an admin

**Comment by CarlosQ96** [comment]
Fixed the routing and also my index for unique addresses is working but we are allowing saving address with capital letters (considered different). 

Adding the lowercase constraint on the form, so regardless if you type it uppercase or lowercase it will always be lowercase when inserting to the db.

**Comment by CarlosQ96** [comment]
@RamRamez @MohammadPCh Regarding trace not showing tokens in the frontend, is there any constraint there?
We have tests in the backend validating trace tokens returning just fine, and I don't see any complex logic that excludes trace tokens.
Let me know if you find anything.

**Comment by CarlosQ96** [comment]
@pkretzschmar

**Comment by divine-comedian** [comment]
confirming that as an operator I can't edit the token lists - 
![image](https://user-images.githubusercontent.com/67759413/163808514-d701ae9b-8e5e-4455-9c58-925dd95950f3.png)

I'll wait for updates and come back to testing the rest of this issue

**Comment by CarlosQ96** [comment]
@mateodaza

**Comment by mateodaza** [comment]
![image](https://user-images.githubusercontent.com/18689480/163824981-2a78e797-6f1e-46e4-ba43-f55eab7f050d.png)

Trying with this new token it works. Can you confirm with a new token @divine-comedian

**Comment by divine-comedian** [comment]
@mateodaza  
`staging.giveth.io`

no ser I tried a couple different keywords and scrolled the entire list and could not find your token - I also have a different token that shows up on the same keyword search.. 
![image](https://user-images.githubusercontent.com/67759413/164005683-4dc025b0-fef7-4914-8931-862113748771.png)

**Comment by divine-comedian** [comment]
sorry there was a misunderstanding on this issue - I was testing to see if the tokens showup on `develop.giveth.io` but the intention was for the tokens to show up for traceable projects on giveth.io - I check w/ mateo and the test token he created does show up on `staging.giveth.io`

![image](https://user-images.githubusercontent.com/67759413/164016288-90da15b0-d2b3-48c8-ad2a-61b09df75463.png)

**Comment by divine-comedian** [comment]
any other blockers to call this DONE?

**Comment by CarlosQ96** [comment]
I call it DONE!

**Comment by MoeNick** [comment]
@divine-comedian would you please check it on production and make sure it's correct? Especially for Change and Givingblock projects on different networks.

**Comment by divine-comedian** [comment]
> @divine-comedian would you please check it on production and make sure it's correct? Especially for Change and Givingblock projects on different networks.

what does "Change" signify? what do you mean by different networks? mainnet and Gnosis Chain?

**Comment by divine-comedian** [comment]
testing on `giveth.io` 

I added a new token (EOS) on `mainnet` to all organizations and it appears they show up for traceable projects 

![image](https://user-images.githubusercontent.com/67759413/164275483-d674a873-49cb-415c-a2bc-69821584b71f.png)

as well as for Giving Block projects 
![image](https://user-images.githubusercontent.com/67759413/164275961-985cf9b5-112b-4eb8-bf21-ec840f9140f8.png)

I can also add tokens on `xdai` and they show up on traceable projects 

![image](https://user-images.githubusercontent.com/67759413/164277316-96fb73ad-c309-4580-87e5-cf6d8a21383e.png)

and I can also add them giving block projects on gnosis chain - but I assume we should remove this since giving block projects can't receve on gnosis chain.. @MoeNick 
![image](https://user-images.githubusercontent.com/67759413/164277029-afa5a555-43a2-4200-835e-7b41caca1b4e.png)

**Comment by CarlosQ96** [comment]
Mateo fixed the frontend some frontend issues but this was a month ago and we approved this card, moving it to done.
