### ISSUE TITLE
Refactor DB queries ( by moving them from resolvers and reuse them)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#470]
We use queries directly in our resolvers , and it makes our code messy, I suggest we should move the queries to a separated file like https://github.com/Giveth/impact-graph/blob/staging/src/repositories/userRepository.ts in this way we can write unit tests for every function(query) and we can reuse them ( currently we have written some queries in several resolvers and it makes it hard to maintain), besides doing this will make it easier to change our ORM/DB in the future , and it's good practice to encapsulate DB queries 

PS: I thinks it's not responsibility of resolvers to call DB queries
https://en.wikipedia.org/wiki/Single-responsibility_principle

- [ ] Move queries from categoryResolver
- [ ] Move queries from donationResolver
- [ ] Move queries from projectResover
- [ ] Move queries from reactionResolver
- [ ] Move queries from statusReasonResolver
- [ ] Move queries from userResolver

Please pay attention to these items during doing these stuffs :
1. Write some sucess/fail scenario test cases for every function that you write for queries
2. Check https://github.com/Giveth/giveth-dapps-v2/tree/develop/src/apollo/gql to see frontend uses what fields in response, maybe some `joins` are unnecessary ( @MohammadPCh  All the query/mutations that you use are in here or we should check somewhere else as well?)
3. when writing test cases, for function that use join , be aware to check wether join works correctly or not

@CarlosQ96  @aminlatifi  Correct me if you have another opinion about what I said

**Comment by divine-comedian** [comment]
@mohammadranjbarz  is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is this issue still relevant?

We can close it
