### ISSUE TITLE
View the list of requests made by a client and the status of the request

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#478]

**Comment by mohammadranjbarz** [comment]
related to https://github.com/Giveth/apiGive/issues/5

**Comment by maryjaf** [comment]
How do I test this issue? @mohammadranjbarz 
Please add a brief description on this issue.

**Comment by mohammadranjbarz** [comment]
> How do I test this issue? @mohammadranjbarz Please add a brief description on this issue.

Have you ever tested anything on apiGive?
if you didn't , I should onboard you on this project then  you can test issues

**Comment by MoeNick** [comment]
I will onboard @maryjaf of APIgiv. 
Did she receive the APIgiv postman collection to start working with it?
If not, can @mohammadranjbarz you please send her out?

**Comment by mohammadranjbarz** [comment]
> I will onboard @maryjaf of APIgiv. Did she receive the APIgiv postman collection to start working with it? If not, can @mohammadranjbarz you please send her out?

Thanks man, we have swagger for apiGive so we don't need postman 

https://staging.apigive.giveth.io/docs
https://staging.apigive.giveth.io/admin
