### ISSUE TITLE
Get a List of Projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#479]

**Comment by CarlosQ96** [comment]
@MoeNick I'll take this task, but could we add some more specific details?
Will it have?
* pagination
* sorting
* filter
Like our projects list in giveth.io or is it more simplified version.

**Comment by CarlosQ96** [comment]
Also sorting and filtering based on what fields?

**Comment by mohammadranjbarz** [comment]
I think we dont need it as we don't use apiGiv anymore

**Comment by MoeNick** [comment]
Hey why did you close it, it should be on backlog ready when we want to implement it. it's part of APIgiv Epic

**Comment by MoeNick** [comment]
fyi: @divine-comedian

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Do we need apiGive?
because we don't use that project ( @divine-comedian  told us to check the new issues and close some of them that do not needed anymore, especially about tests) and I thought we don't need apiGiv epic anymore

**Comment by MoeNick** [comment]
It's on our roadmap, maybe not for this quarter, but if we have the bandwidth we may do it.

**Comment by mohammadranjbarz** [comment]
> It's on our roadmap, maybe not for this quarter, but if we have the bandwidth we may do it.

Ok got it, thanks

**Comment by divine-comedian** [comment]
> > It's on our roadmap, maybe not for this quarter, but if we have the bandwidth we may do it.
> 
> Ok got it, thanks

Yup let's keep it in the backlog or icebox it until we can prioritize apiGIV
