### ISSUE TITLE
priceUsd of imported poignArt donations is invalid

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#485]
I figured it out that donaiton has invalid price

query:
```
select id,"priceUsd",amount,currency, "priceEth", "valueEth" from donation
where "donationType"='poignArt'
```

* Produciton Donation
![Screen Shot 1401-01-22 at 18.21.18.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/a7d906ae-d77d-43a9-a268-44c39ab55f65)

* Staging donation
![Screen Shot 1401-01-22 at 18.24.37.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/93af69f1-cdb5-4616-93d9-d951cbeaca3c)

**Comment by maryjaf** [comment]
Can we move this issue to Done? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf Yeah it's fixed now
