### ISSUE TITLE
We should not use ts-node in production to improve time of project launch

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#493]
https://stackoverflow.com/questions/60581617/is-it-a-bad-practise-to-use-ts-node-in-production#:~:text=No%20you%20shouldn't%20use,compiler%20and%20files%20in%20memory.

We use `ts-node` in production, but best practice is that we build the ts files and in production we just use the js file and start that file

**Comment by mohammadranjbarz** [comment]
We can get idea from this project 
https://github.com/Giveth/apiGive

**Comment by divine-comedian** [comment]
@mohammadranjbarz - is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
I think we can change the label of this issue to technical debt

**Comment by jainkrati** [comment]
@mohammadranjbarz pls guide Ali Ebrahmi to take this up

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz pls guide Ali Ebrahmi to take this up

Sure

**Comment by mohammadranjbarz** [comment]
@jainkrati 
I talked with @ae2079  and we saw it's already implemented, we can close this issue
