### ISSUE TITLE
Set validations for creating donations

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#496]
According to [THIS ISSUE - happening on staging ](https://github.com/Giveth/giveth-dapps-v2/issues/596) we have to set validations for input parameters on creating donations, like: Amount, Token, and all necessary input parameters which have effects on the DAPP functionality.

**Comment by mohammadranjbarz** [comment]
@MoeNick 
Setting validation for `Token` is impossible, because we don't have a list of all tokens, we just can validate the name structure, for instance the tokens should contain just alphabet characters, not numbers or special characters

**Comment by CarlosQ96** [comment]
This have the face of tests done by the security team  spoofing doc that was published.
Ill confirm, but like mohammad said, a perfect validation of the token is imposible with just what we have and allowing custom tokens.

We can add some other validations like numbers positive and things like that.

**Comment by MoeNick** [comment]
Im going to create other issues related to security reported issues

**Comment by mohammadranjbarz** [comment]
@MoeNick 
These validationhave been  added by @FatemeGhasemi 

* Amount of donations should be greater than 0 
* Token symbols should just contain alphabet characters and length of that should be less than 10 
* There is a migration for deleting donations with negative amount from DB (For fixing https://github.com/Giveth/giveth-dapps-v2/issues/596)
