### ISSUE TITLE
Change source images should be uploaded to ipfs/pinata

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#501]
@MoeNick @CarlosQ96 

currently we can't show `change` project images on project card because the src of images are unknown subdomain of cloudfront
e.g.: https://d2jyzh4ah9xf6q.cloudfront.net/n712i7lou0l782u36ktvlvfybsgh%22

Please upload current and future `change` projects to pinata/ipfs

![image](https://user-images.githubusercontent.com/73441857/165737139-583b38d8-b339-40bb-be24-cdacf6c3ee63.png)

**Comment by divine-comedian** [comment]
@RamRamez is this issue still relevant?

**Comment by RamRamez** [comment]
@divine-comedian if are not going to import more projects from Change, it's ok and we can close this issue.
Otherwise, we should add the image URL of each Change project one by one in Nextjs config
