### ISSUE TITLE
Docker container had been stopped suddenly

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#505]
After 4 days of our last deployment, all of a sudden we saw that our backend is down and after checking production server I noticed that the docker container is not running anymore, I brought up the docker-compose and the problem has been fixed, but now our question is why this happened, and how we can prevent it, I know the problem is very vague but this is the only data we have

@geleeroyale  I couldn't find Moeshehab username so I assigned this issue to you

**Comment by divine-comedian** [comment]
@geleeroyale @mohammadranjbarz - is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @geleeroyale @mohammadranjbarz - is this issue still relevant?

After changing deployments and docker structure by @mhmdksh  and @geleeroyale  I didn't see this error anymore, so we can move this issue to DONE

**Comment by mhmdksh** [comment]
Yeah I think this is not relevant anymore, since now we have so much more visibility and reliability that if any of these issues happen again, we should be able to track the reason of why they were happening instead of leaving the issue open for 2 years haha.

This can be closed yes
