### ISSUE TITLE
Currently we dont care about ENS addresses when verifying donations

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#517]

**Comment by divine-comedian** [comment]
@mohammadranjbarz - is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz - is this issue still relevant?

@divine-comedian I think we use wallet addresses in filling donation fromAddress and toAddress, so don't need it anymore, @MohammadPCh  @RamRamez Can you confirm it?

**Comment by RamRamez** [comment]
@mohammadranjbarz do you mean in createDonation and updateDonationStatus mutations? we don't send walletAddress in those two.

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz do you mean in createDonation and updateDonationStatus mutations? we don't send walletAddress in those two.

Oh you are right, we get it from the user access token, but we send toWalletAddress and we don't support ENS, am I right?
