### ISSUE TITLE
Should just return all field of users to the user himself  ( security issue)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#521]
Someone else should not be able to get another person's email ( and maybe other fields)

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  @RamRamez  @mateodaza 

Does it make problem in frontend?

**Comment by RamRamez** [comment]
@mohammadranjbarz Yeah, for the public profile view we need these information:

![image](https://user-images.githubusercontent.com/73441857/170857482-8b24a9bc-b59a-4e07-b634-dda5d8a5355f.png)

**Comment by RamRamez** [comment]
@mohammadranjbarz If this is a security issue related to email address, we can talk with design team and remove it but we need the user name.
which end-point you mean? just `userByAddress` or all end-points related to user info?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz If this is a security issue related to email address, we can talk with design team and remove it but we need the user name. which end-point you mean? just `userByAddress` or all end-points related to user info?

I think all end-points related to user info makes sense,  I think it's ok to have name there

**Comment by maryjaf** [comment]
I tested this issue on staging and the email address of other user has not been displayed 
for example(https://staging.giveth.io/user/0x2a3522042d44278689a7a15aa2ef5fabed1a9c8e)

But when I select  my user(maryjaf), I don't see my email address. This is true? @mohammadranjbarz 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/192085836-86376c3c-1e38-456b-967d-24ae41a46ece.png">

**Comment by RamRamez** [comment]
> I tested this issue on staging and the email address of other user has not been displayed for example(https://staging.giveth.io/user/0x2a3522042d44278689a7a15aa2ef5fabed1a9c8e)
> 
> But when I select my user(maryjaf), I don't see my email address. This is true? @mohammadranjbarz <img alt="image" width="1440" src="https://user-images.githubusercontent.com/111529185/192085836-86376c3c-1e38-456b-967d-24ae41a46ece.png">

This page (`/user/[wallet]`) is public profile. In public profile email address shouldn't be shown (that is related to this issue).
In my account (`/account`) page, email (if associated with user), will be shown.
