### ISSUE TITLE
Add status filter for donationsByProjectIdand donationsByUserId query

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#524]
related to https://github.com/Giveth/giveth-dapps-v2/issues/730

**Comment by mohammadranjbarz** [comment]
That filter should be optional, frontend would handle to show what donations to who

- [x] donationsByUserId
- [x] donationsByProjectId

**Comment by divine-comedian** [comment]
@mohammadranjbarz @CarlosQ96 is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @CarlosQ96 is this issue still relevant?

I don't think so
