### ISSUE TITLE
Implement a webservice for validating accessToken

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#529]
> Ramin said
with need an end-point in the back-end to check user token validity
for the cases that the user token is expired or wrong for some reason

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  
@FatemeGhasemi 
Do you have bandwidth for implementing this?

**Comment by aminlatifi** [comment]
I think we should see it in all write API calls!

**Comment by jeevanplus007** [comment]
@mohammadranjbarz Please update your latest comments

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @MoeNick  
We already have a resolver (meResolver) that @RamRamez  use that to know wether accessToken is valid or not, I think that's enough for now, and we don't need this issue ( at least for now)
