### ISSUE TITLE
Adding Manual Donation in Admin

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#548]
Regarding this https://github.com/Giveth/giveth-dapps-v2/issues/811 For adding donations to the backend, I'd say let's have a feature in Admin, which Admins be able to provide trx hash and it saved in db and get verified later by the cronjob.

**Comment by MoeNick** [comment]
@mohammadranjbarz you run the verification job after adding this trx? Admin may enter the wrong trx hash. WHat do you suggest?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz you run the verification job after adding this trx? Admin may enter the wrong trx hash. WHat do you suggest?

Actually admin just enter the txHash and we get all data from blockchain ( amount, fromAddress, toAddress, currency), so it's definitely verified, we just can't get price from blockchain and admin enters manually, for instance we are sure that 2 HNY transferred through this transaction, but admin says the HNY was **76$** at that time, and it's the only place that admin can mistake and should be catious

**Comment by mohammadranjbarz** [comment]
<img width="1097" alt="Screen Shot 1401-04-26 at 10 49 55" src="https://user-images.githubusercontent.com/9850545/179386594-760ffa04-0466-437d-b91c-d75f58451526.png">

**Comment by MoeNick** [comment]
jfyi @WhyldWanderer about probable mistake of admin to use wrong price, it's possible
