### ISSUE TITLE
Verify old donations manually to make sure about statistics

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#551]
Yass wanted some statistics from me about total donations in all the time , when providing this report I knew that we have some donations from last year that their status are `failed` because of some reasons like `toAddress` of transaction is not the same wallet address of project ( it could happen if project address has been changed after adding verification system for donations)

So now we have about **35,000 $** conflicts between donations that got verified by network and all donations, so I think it worth to spend some time review those donations to see wether we should count them in statistics or not

@MoeNick  @laurenluz  @GriffGreen 

<img width="880" alt="Screen Shot 1401-04-12 at 12 31 18" src="https://user-images.githubusercontent.com/9850545/177034253-fc940252-5a1d-4c76-b5fc-a3648bdb986a.png">
<img width="1111" alt="Screen Shot 1401-04-12 at 12 34 14" src="https://user-images.githubusercontent.com/9850545/177034257-519ffd4d-3988-4eb2-9922-abca9afab9fd.png">

**Comment by laurenluz** [comment]
I think that's a good idea... if we find out that they did actually go through ok and say "failed" because of the verification update, can you change that in the database so they look like good donations & can be tracked well?

**Comment by mohammadranjbarz** [comment]
> I think that's a good idea... if we find out that they did actually go through ok and say "failed" because of the verification update, can you change that in the database so they look like good donations & can be tracked well?

Yeah we can change the status directly in db and add a description to that to know it has changed manually

**Comment by divine-comedian** [comment]
@mohammadranjbarz is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz is this issue still relevant?

@divine-comedian 
I think we can close this
