### ISSUE TITLE
Collect some data about donations for Yass

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#554]

**Comment by mohammadranjbarz** [comment]
I wrote an script for giveth.io donations breakdown by categories ( and generate a csv of donations)

https://gist.github.com/mohammadranjbarz/cb7d843a36c759e23d688af2fc8a60e9#file-giveth-io-donations-report

A query to get all donations USD values in impact-graph(giveth.io):
```
SELECT SUM("valueUsd") AS "totalDonations"
FROM donation
```

A query to get all donation of trace.giveth.io
```
db.getCollection('donations')
.aggregate({ $match: {homeTxHash: {$exists: true}, status: "Committed"} },              {$group: {_id: null, sum:{$sum: "$usdValue"}}})
```

I sent the result to Yass in DM

**Comment by mohammadranjbarz** [comment]
@spectoregia 
If you dont need more data for now, we can close this issue

JFYI @MoeNick  @jeevanplus007

**Comment by spectoregia** [comment]
Thanks @mohammadranjbarz I have everything needed for the calculations. you can close this ticket. :)
