### ISSUE TITLE
Admin: Export is not working. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#564]

**Comment by CarlosQ96** [comment]
Google API error - [404] Requested entity was not found.
This is the error I think the spreadsheet was either blocked off from access or the user was removed or it was deleted.

**Comment by CarlosQ96** [comment]
I'll setup a new spreadsheet or user.

**Comment by CarlosQ96** [comment]
Fixed, added a new oauth service user and linked in to the spreadsheet. Please test when you have bandwidth!! @WhyldWanderer @MoeNick

**Comment by CarlosQ96** [comment]
I exported 5 projects filtered by giveth succesfully in the spreadsheet. If you need the link to the spreadsheet dm me, but everyone was added.

**Comment by divine-comedian** [comment]
hey @CarlosQ96 can you clarify inside of admin bro what categories we should be able to export to csv?

I can right now I can only export the `project` category 

I click export and it says projects successfully exported but I am not prompted to download any export file..

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/184934595-fb72bf66-854e-48b2-8d81-b8099e7a321b.png">

**Comment by CarlosQ96** [comment]
It is not posible to download from the adminbro. I'll DM you the link. 
https://docs.google.com/spreadsheets/d/1uqw40RxtxhhsVBq5_QwnBJ1V40z6I8Pfe2q8nxdHejM/edit#gid=0
I don't see you in the list, what is your gmail to grand you access?

**Comment by MoeNick** [comment]
@CarlosQ96 I gave permission o the export sheet to @maryjaf for testing, appreciate if you can elaborate more about the testing scenario of this issue ./

**Comment by maryjaf** [comment]
I tested and the issue passed.
