### ISSUE TITLE
Allow projects to have just one recipient address

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#565]
@RamRamez  said we need to have it

**Comment by mohammadranjbarz** [comment]
@MoeNick  @RamRamez 
We deployed it on staging

**Comment by divine-comedian** [comment]
how can this issue be tested?

**Comment by RamRamez** [comment]
@divine-comedian you test multi recipient address after [this PR](https://github.com/Giveth/giveth-dapps-v2/issues/1135) is merged.

**Comment by MoeNick** [comment]
Moving it back to code review due to the depency.

**Comment by MoeNick** [comment]
The dependency merged, so it's now testable with the same scenario of #1150
