### ISSUE TITLE
Backend technical debts

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#571]

**Comment by divine-comedian** [comment]
@mohammadranjbarz @aminlatifi @CarlosQ96 

What's the progress on this epic? 

Is this part of the technical debts we would like to focus on resolving this quarter?

**Comment by aminlatifi** [comment]
@divine-comedian Let's plan these in our sprints. Some are closed, and some are left

**Comment by jainkrati** [comment]
@mohammadranjbarz pls share list of tech debts here so that I can help prioritize. Once i get the list we can assign each item to a different developer.
