### ISSUE TITLE
Update typeorm and  admin-bro dependencies

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#572]

**Comment by aminlatifi** [comment]
It seems the current version of typeorm doesn't support upsert. It's important now as we are implementing automatic cron jobs to insert to db. If any of them does a mistake and tries to insert an entity again one round of process would fail

**Comment by mohammadranjbarz** [comment]
@MohammadPCh  gave this: https://giveth-dapps-v2-git-staging-with-dev-serve-backend-givethio.vercel.app 

A frontend version that uses https://dev.serve.giveth.io as backend

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @CarlosQ96  
I deployed our PR on dev ENV.

@maryjaf  can you test our functionality, especially in admin panel, and if it's ok tell us to merge it to staging
https://giveth-dapps-v2-git-staging-with-dev-serve-backend-givethio.vercel.app/
admin panel: https://dev.serve.giveth.io/admin

**Comment by maryjaf** [comment]
by selecting **project** in admin I got 502  bad gateway, but for other menu like donation i didn't see this problem
@mohammadranjbarz 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/111529185/212095250-73614f71-fe39-4476-88d3-fff447512b2d.png">
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/111529185/212095409-0721bdb6-c8ab-4476-bde9-e0dd98dcd19f.png">

**Comment by mohammadranjbarz** [comment]
@maryjaf Can you test it again?
maybe you have had some internet problem, because it's working for me

https://dev.serve.giveth.io/admin/resources/Project/records/37/show
<img width="1433" alt="Screen Shot 1401-10-25 at 09 49 26" src="https://user-images.githubusercontent.com/9850545/212526092-a5fd3573-e040-47e9-988b-e8699b803f66.png">

**Comment by mohammadranjbarz** [comment]
https://github.com/Giveth/impact-graph/issues/813

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz  the problem related to edit project has been resolved
Plz check this scenario
the status of verification form of project is submitted
when the admin user change this status to verified
error message is shown as below pic but the status of verification form changed into verified correctly
<img width="958" alt="image" src="https://user-images.githubusercontent.com/111529185/213917235-3cc23686-b96d-4064-b7e8-853b78c955fa.png">

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz the problem related to edit project has been resolved Plz check this scenario the status of verification form of project is submitted when the admin user change this status to verified error message is shown as below pic but the status of verification form changed into verified correctly <img alt="image" width="958" src="https://user-images.githubusercontent.com/111529185/213917235-3cc23686-b96d-4064-b7e8-853b78c955fa.png">

Thanks @maryjaf 
It's resolved now, you can create new verification form and try to verify it

@aminlatifi  We can merge this to staging, please if you did it tell @maryjaf  then she can test the things on staging instead of `develop` ENV

**Comment by aminlatifi** [comment]
> > Thanks @mohammadranjbarz the problem related to edit project has been resolved Plz check this scenario the status of verification form of project is submitted when the admin user change this status to verified error message is shown as below pic but the status of verification form changed into verified correctly <img alt="image" width="958" src="https://user-images.githubusercontent.com/111529185/213917235-3cc23686-b96d-4064-b7e8-853b78c955fa.png">
> 
> Thanks @maryjaf It's resolved now, you can create new verification form and try to verify it
> 
> @aminlatifi We can merge this to staging, please if you did it tell @maryjaf then she can test the things on staging instead of `develop` ENV

Thanks @mohammadranjbarz, let's give @maryjaf another couple of days to test on dev env. I hope we be cool and merge it to staging

**Comment by maryjaf** [comment]
1-When I try to confirm my email in step of submit verification form, I got this error
 It is related to test env or this changes?
 
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/111529185/214097311-1124a8c2-fdfc-445a-809a-82db90370329.png">
@mohammadranjbarz

**Comment by maryjaf** [comment]
2-
https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new
By taping on create new on third party project import and complete field 
When click on save , this message is shown
<img width="1423" alt="image" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">

**Comment by mohammadranjbarz** [comment]
> 1-When I try to confirm my email in step of submit verification form, I got this error It is related to test env or this changes?
> 
> <img alt="image" width="1259" src="https://user-images.githubusercontent.com/111529185/214097311-1124a8c2-fdfc-445a-809a-82db90370329.png">
> 
> @mohammadranjbarz

It can be because of different ENVs,  because it returns to staging.giveth.io that is not correct, anyway please edit the forms from edit page of them , then test verify/reject, you can test submitting verification form in staging after merging that

<img width="1819" alt="Screen Shot 1401-11-04 at 10 14 08" src="https://user-images.githubusercontent.com/9850545/214228806-420ff1b3-51c9-4ee6-8046-4e7df31039f2.png">

**Comment by mohammadranjbarz** [comment]
> 2- https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new By taping on create new on third party project import and complete field When click on save , this message is shown <img alt="image" width="1423" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">

It's fixed now

**Comment by mohammadranjbarz** [comment]
@maryjaf  As we merged this PR to staging, from now on you can continue your tests for this issue on 
https://staging.giveth.io

**Comment by maryjaf** [comment]
> @maryjaf As we merged this PR to staging, from now on you can continue your tests for this issue on https://staging.giveth.io

Thanks @mohammadranjbarz I will check this tonight

**Comment by maryjaf** [comment]
> 2- https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new By taping on create new on third party project import and complete field When click on save , this message is shown <img alt="image" width="1423" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">

This problem also exists in the token menu
plz check this as well

**Comment by maryjaf** [comment]
Now when I set a new broadcast notification my user has received two notification
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/111529185/214334288-d5a90c3b-9922-43eb-b64f-fc0add705506.png">

**Comment by mohammadranjbarz** [comment]
> > 2- https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new By taping on create new on third party project import and complete field When click on save , this message is shown <img alt="image" width="1423" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">
> 
> This problem also exists in the token menu plz check this as well

I think you didn't reload your admin page, because it's ok for me, anyway please continue your tests in `Staging ENV`

**Comment by mohammadranjbarz** [comment]
> Now when I set a new broadcast notification my user has received two notification <img alt="image" width="1025" src="https://user-images.githubusercontent.com/111529185/214334288-d5a90c3b-9922-43eb-b64f-fc0add705506.png">

It's not related to this PR, we had it before and it's the reason:

<img width="1110" alt="Screen Shot 1401-11-05 at 10 08 46" src="https://user-images.githubusercontent.com/9850545/214497126-d25ddfe4-0447-4420-a8c0-a41a08cb876e.png">


We have two users with you wallet address, one of them is your using account another one is for admin panel, so you receive two notifications, it's a bug , you can create another issue about it but it's not related to this PR

**Comment by maryjaf** [comment]
> > 2- https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new By taping on create new on third party project import and complete field When click on save , this message is shown <img alt="image" width="1423" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">
> 
> This problem also exists in the token menu plz check this as well

Thanks @mohammadranjbarz I checked "token" menu and the problem has been fixed
I think we don't have any more problem on admin bro and all problem has been fixed .

**Comment by aminlatifi** [comment]
> > > 2- https://dev.serve.giveth.io/admin/resources/ThirdPartyProjectImport/actions/new By taping on create new on third party project import and complete field When click on save , this message is shown <img alt="image" width="1423" src="https://user-images.githubusercontent.com/111529185/214100637-559b446b-b84c-4fc2-bb7d-12cea7779a58.png">
> > 
> > 
> > This problem also exists in the token menu plz check this as well
> 
> Thanks @mohammadranjbarz I checked "token" menu and the problem has been fixed I think we don't have any more problem on admin bro and all problem has been fixed .

Thanks @maryjaf, it's a great relief. And thank you @mohammadranjbarz for all your efforts
