### ISSUE TITLE
create a step in back-end for social profiles

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#576]
When user clicks next on social profiles step, there is no checked badge for it.

![image](https://user-images.githubusercontent.com/73441857/181222378-cbf859ce-fe85-49de-b6d5-27b74701ba16.png)

**Comment by divine-comedian** [comment]
@RamRamez is this issue still relevant?

**Comment by RamRamez** [comment]
@divine-comedian Yes, it's related to the green check box next to the Social profiles menu. That's not much important though

**Comment by divine-comedian** [comment]
What's the next steps on this? @RamRamez @mohammadranjbarz  Is it done already?

**Comment by mohammadranjbarz** [comment]
> What's the next steps on this? @RamRamez @mohammadranjbarz Is it done already?

I think so, @RamRamez  can you confirm it?

**Comment by RamRamez** [comment]
@Reshzera could you please take it? (if not already resolved)

**Comment by Reshzera** [comment]
@RamRamez Yes, I'll take a look

**Comment by Reshzera** [comment]
@RamRamez This problem was already solved, but I found a bug on the green check box icon validation, so I fixed here

**Comment by Reshzera** [comment]
@maryjaf @LatifatAbdullahi This issue has already been resolved, but I found a bug with the green check icon on the social profile. Even after completing all the steps, the icon still shows a yellow warning icon. Could you please take a look?

**Comment by LatifatAbdullahi** [comment]
@Reshzera @RamRamez 

I just checked and confirmed the bug found by @Reshzera .

After completing all steps in the "Social profiles" section, the yellow icon still remains.


![sy](https://github.com/user-attachments/assets/87ef140f-07bb-449d-8621-96cac7b368a3)

Raised, a new ticket for this,

https://github.com/Giveth/impact-graph/issues/1727
