### ISSUE TITLE
Change projects query to support multiple filters and some improvement

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#579]
@mohammadranjbarz commented on [Wed Jul 27 2022](https://github.com/Giveth/GIVeconomy/issues/672)

---

@mohammadranjbarz commented on [Wed Jul 27 2022](https://github.com/Giveth/GIVeconomy/issues/672#issuecomment-1196813908)

![Screen_Shot_2022-07-27_at_3.39.30_PM.png](https://images.zenhubusercontent.com/5fa7ed7fb0994323d1a66034/bb25f52d-3733-4328-ae2a-a7036b5e77f6)

Now our sorting and filtering is not good because design made us do it in that way, but with new design we should change `projects` query, 
Now filters should be filter ( before it was like sorting) so if you filter by `Accept GIV` you should not get other projects, and you user can send multiple filters together , for instance, projects that are from givingBlock and are givback eligible, ....
other thing like pagination should be as before, filters can be used by mainCategory and category , ...

---

@mohammadranjbarz commented on [Wed Jul 27 2022](https://github.com/Giveth/GIVeconomy/issues/672#issuecomment-1196839940)

@CarlosQ96  JFYI , @alireza-sharifpour  is the one who is going to implement frontend side, so if you any specific question he can help

@MoeNick  I just mentioned you to stay in the loop

**Comment by CarlosQ96** [comment]
Pr ready for review @MoeNick @mohammadranjbarz 
Link: https://github.com/Giveth/impact-graph/pull/580

**Comment by CarlosQ96** [comment]
Filters are based off the image. Let me know if any other filter is required.

Btw Givback Elegible and Verified is exactly the same.

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  @MoeNick 
It's deployed on staging , @CarlosQ96  explained how you can call the query here
https://github.com/Giveth/impact-graph/pull/580#issuecomment-1199907827

`FilterField` can be : 
* **Verified**
* **Traceable**
* **AcceptGiv**
* **GivingBlock**

`SortingField` can be:
* **MostFunded**
* **MostLiked**
* **Newest**
* **Oldest**

Query sample
```
 query {
     allProjects(
      take: 10,
      skip: 0,
      sortingBy: Newest,
      filters: Traceable,
      searchTerm: "",
      category: "",
      mainCategory: "",
      connectedWalletUserId: 1,
    ) {
      projects {
        id
        title
        balance
        traceCampaignId
        image
        slug
        creationDate
        updatedAt
        admin
        description
        walletAddress
        impactLocation
        qualityScore
        verified
        traceCampaignId
        listed
        givingBlocksId
        status {
          id
          symbol
          name
          description
        }
        categories {
          name
          mainCategory {
            title
            slug
            banner
            description
          }
        }
        reaction {
          id
        }
        adminUser {
          id
          email
          firstName
          walletAddress
        }
        organization {
          name
          label
          supportCustomTokens
        }
        addresses {
          address
          isRecipient
          networkId
        }
        totalReactions
        totalDonations
        totalTraceDonations
      }
      totalCount
      categories {
        name
      }
    }

  }
```

**Comment by divine-comedian** [comment]
Where and how can this be tested?

**Comment by MoeNick** [comment]
Env: https://givfilter.vercel.app/
Test Scenarios: 
The same with front-end scenarios, all sorting/filtering should work fine and be checked with facts. all sorting scenarios, all filtering scenarios and both of the together when selected at the same time. 
Also on the load more, the filtered and sorted result should not change.

**Comment by divine-comedian** [comment]
testing on `https://givfilter.vercel.app/projects`
test on brave browser and firefox

I can test a combination of scenarios add a sorting and a combination of different filters. the project page updates and shows me the correct projects depending on the options I chose. 

I notice there are two strange bugs:

**The first**, sometimes on **firefox** when I log in while browsing projects I can hit the bottom of the list and there is still a load more button, clicking load more does not reveal any new projects and I know that I am at the bottom of the list according to my sorting/filter combination.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/67759413/183751409-3fe3d531-c70e-469f-a500-e6297efb5c7d.png">

I can fix this by refreshing page after I sign in, it no longer shows this erroneous load more button while filtering/sorting

---

**The second** issue is that while signed in on either firefox and brave. I am already signed in and if I try to  apply two filters when I click load more the button shows the loading animation but does nothing. 

I can apply just one filter and the load more button works

If I am signed out of my web wallet I can click load more with two filters and it works.

If I sign out, refresh the page, sign in and apply two filters it works. If I refresh the page after this scenarion then I arrive at the same problem with the load more button.

I make a loom video to try and show off the bug better. 
https://www.loom.com/share/dca68f63cb3f4fdc82e8e590a0b427d7

**Comment by CarlosQ96** [comment]
@alireza-sharifpour I think this might be a frontend issue? Or both, let me know and we can check.

**Comment by MoeNick** [comment]
According to @alireza-sharifpour it was the Front end and it's solved now, moving to Unit Test, @divine-comedian can you confirm the problem is solved or not?

**Comment by alireza-sharifpour** [comment]
This issue is fixed
You can check on:
https://givfilter.vercel.app/

**Comment by divine-comedian** [comment]
I can now sucessfully select two filets and the load more button works, I see also the new loading animation. I took this quick loom video to show how it all looks:
https://www.loom.com/share/51d3b968c9044ac7a390d3471490e54d

calling this done moving to unit test passed.
