### ISSUE TITLE
GIVpower boosting database schema

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#591]
These values should be saved in DB
- givpower allocation percentage per user and project
- Accumulated user power in the last two weeks
- ~~Total percentage of givpower allocated by user~~
- Total givPower allocated to each project

Note: I have searched about Postgres triggers. I think we can use this feature to keep data consistency (not more than 100% allocation per user) and update user total allocation percentages

**Comment by mohammadranjbarz** [comment]
* **Power boosting**

| name       | type    | required | validation     |
|------------|---------|----------|----------------|
| projectId  | integer | yes      |                |
| userId     | integer | yes      |                |
| percentage | integer | yes      | min=0, max-100 |

* **Power boosting snapshot**

| name       | type    | required | description                 |
|------------|---------|----------|-----------------------------|
| userId     | integer | yes      |                             |
| date       | Date    | yes      |                             |
| userPower  | integer | yes      | user power at specific time |

**Comment by aminlatifi** [comment]
> 

By new design (givpower of a user is used 100% or 0%), it doesn't make sense to have this _Total percentage of givpower allocated by user_

**Comment by MoeNick** [comment]
Ranking by the user service is still missing @mohammadranjbarz

**Comment by aminlatifi** [comment]
> Ranking by the user service is still missing @mohammadranjbarz

@mohammadranjbarz @MoeNick We have a view to mapping tuple of userId and projectId to power (corresponding percentage multiplied by user average power in last round)
This view is of materialized one and has appropriate indexes for filtering and sorting.

**Comment by aminlatifi** [comment]
The design of computing a project's givpower must be changed. Based on the new design, we should take snapshots of users' power balance, and the allocated percentages every 4 hours.
In order to implement project average allocated givpower we need to change the design and define new tables.

**Snapshot time and blocknumber**
| name       | type    | required | validation     | description |
|------------|---------|----------|----------------|----------------|
| id  | integer | yes      |                ||
| time     | Date | yes      |                |time of snapshot (every 4 hours). Will be filled by a job run by a cron job|
| blockNumber | integer |no     | | Will be filled later |
| roundNumber| integer| no|| The round snapshot belongs to. Can be filled later by app (not by db cron job)|

**User power balance at snapshot**
| name       | type    | required | validation     | description |
|------------|---------|----------|----------------|----------------|
|id| integer| yes|||
| userId| integer | true|||
|snapshotId| integer| true| | |
| balance| ineger| true| ||

**Percentage snapshot**
| name       | type    | required | validation     | description |
|------------|---------|----------|----------------|----------------|
|id| integer| yes|||
| userId| integer | true|||
|projectId| integer| true| | |
| percentage| float| true| ||
| snapshotId| integer| true|||

**Project Power**
| name       | type    | required | validation     | description |
|------------|---------|----------|----------------|----------------|
|id| integer| yes|||
|projectId| integer| true| | |
| totalPower| float| true| | average power allocated to a project in a round|
| roundNumber| integer| true|||

**Comment by aminlatifi** [comment]
> The design of computing a project's givpower must be changed. Based on the new design, we should take snapshots of users' power balance, and the allocated percentages every 4 hours. In order to implement project average allocated givpower we need to change the design and define new tables.
> 
> **Snapshot time and blocknumber**
> 
> name	type	required	validation	description
> id	integer	yes		
> time	Date	yes		time of snapshot (every 4 hours). Will be filled by a job run by a cron job
> blockNumber	integer	no		Will be filled later
> roundNumber	integer	yes		The round snapshot belongs to
> **User power balance at snapshot**
> 
> name	type	required	validation	description
> id	integer	yes		
> userId	integer	true		
> snapshotId	integer	true		
> balance	ineger	true		
> **Percentage snapshot**
> 
> name	type	required	validation	description
> id	integer	yes		
> userId	integer	true		
> projectId	integer	true		
> percentage	float	true		
> snapshotId	integer	true		
> **Project Power**
> 
> name	type	required	validation	description
> id	integer	yes		
> projectId	integer	true		
> totalPower	float	true		average power allocated to a project in a round
> roundNumber	integer	true

@CarlosQ96 @mohammadranjbarz I appreciate if you take a look and suggest any improvement or feedback about any issue you see

**Comment by mohammadranjbarz** [comment]
> The design of computing a project's givpower must be changed. Based on the new design, we should take snapshots of users' power balance, and the allocated percentages every 4 hours. In order to implement project average allocated givpower we need to change the design and define new tables.
> 
> **Snapshot time and blocknumber**
> 
> name	type	required	validation	description
> id	integer	yes		
> time	Date	yes		time of snapshot (every 4 hours). Will be filled by a job run by a cron job
> blockNumber	integer	no		Will be filled later
> roundNumber	integer	yes		The round snapshot belongs to
> **User power balance at snapshot**
> 
> name	type	required	validation	description
> id	integer	yes		
> userId	integer	true		
> blockNumber	integer	true		
> balance	ineger	true		
> **Percentage snapshot**
> 
> name	type	required	validation	description
> id	integer	yes		
> userId	integer	true		
> projectId	integer	true		
> percentage	float	true		
> time	Date	true		
> **Project Power**
> 
> name	type	required	validation	description
> id	integer	yes		
> projectId	integer	true		
> totalPower	float	true		average power allocated to a project in a round
> roundNumber	integer	true

Thanks @aminlatifi , it looks fine
