### ISSUE TITLE
Boosting api - set user-project allocation

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#593]
Set user-project boosting allocation percentage.

This API should accept an array of <projectId, percentages> tuples. So it should enable the user to set percentages of one or multiple projects(for dashboard use case) in one query

**Validations:**
Each user can allocate to a limited number of projects. Consider the limitation of 20 projects.
The allocation percentage precision is 0. (i.e. numbers like 12.1 are not accepted, only 12 or 13)

**Consistency:**
We should check the sum of the user allocation percentages is not more than 100%
We must update the user totalAllocatedGIVpower percentage after each update.
These can be implemented on DB layer by the user of triggers.

**Comment by aminlatifi** [comment]
@mohammadranjbarz and I concluded
1. We will have an API for setting single project boosting. In this scenario, the user sets boosting for a single project and the rest of the positive boosting adapt their values as the sum of all user boosting values becomes 100%
2. Another API for setting multiple boosting values. The sum of these values must be 99% to 100%. A successful full call to this API causes all other boosting values to become zero and only data passed be persisted as user boosting.

**Comment by maryjaf** [comment]
1-

Plz check this scenario @MohammadPCh 
Select the edit option
Change one of the percentages to 100 so that the total number of allocutions is above 100
The message is displayed correctly: You can’t exceed 100%
But when cancel or reset is selected, this message is still displayed
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/2121935b-2840-4063-9d12-cc830001086f)

**Comment by maryjaf** [comment]
2-

![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/bb84f888-928f-4ca4-85ce-b452ec5e091c)
@mohammadranjbarz 
In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.

**Comment by maryjaf** [comment]
> ![image.png](https://camo.githubusercontent.com/a680e9b8d33d45cff8543860a8b2670da6542e7eab21fff68b1c23f13956292e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623834663838382d393238662d346361342d383563652d623435326563356530393163) @mohammadranjbarz In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.

The same scenario is happened when edit percentage of allocation and set a number with a decimal
@mohammadranjbarz

**Comment by maryjaf** [comment]
3-

Some times when edit percentage of allocation and set a number with a decimal then tap on save changes nothing happens. 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/1a0bcd68-9f3c-4949-8dc5-2896a2005726)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/bd732b3b-d271-4a85-91f8-16044bd68555)
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> ![image.png](https://camo.githubusercontent.com/a680e9b8d33d45cff8543860a8b2670da6542e7eab21fff68b1c23f13956292e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623834663838382d393238662d346361342d383563652d623435326563356530393163) @mohammadranjbarz In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.



> ![image.png](https://camo.githubusercontent.com/a680e9b8d33d45cff8543860a8b2670da6542e7eab21fff68b1c23f13956292e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623834663838382d393238662d346361342d383563652d623435326563356530393163) @mohammadranjbarz In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.

@maryjaf  In this case backend returns **Number of boosted projects exceeds limit** error, @MohammadPCh  maybe frontend don't show error message correctly, can you check it?

**Comment by maryjaf** [comment]
> > ![image.png](https://camo.githubusercontent.com/a680e9b8d33d45cff8543860a8b2670da6542e7eab21fff68b1c23f13956292e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623834663838382d393238662d346361342d383563652d623435326563356530393163) @mohammadranjbarz In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.
> 
> > ![image.png](https://camo.githubusercontent.com/a680e9b8d33d45cff8543860a8b2670da6542e7eab21fff68b1c23f13956292e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f62623834663838382d393238662d346361342d383563652d623435326563356530393163) @mohammadranjbarz In the description, there is a limit of 20 boosted projects for the user, but when I select the 21st project, the appropriate error message is not displayed and the boosting operation remains loading.
> 
> @maryjaf In this case backend returns **Number of boosted projects exceeds limit** error, @MohammadPCh maybe frontend don't show error message correctly, can you check it?

yes backend error is shown in response 
<img width="1420" alt="image" src="https://user-images.githubusercontent.com/111529185/193445392-8b9b69b4-1079-4ba9-97f6-8950bfe5f72c.png">

**Comment by maryjaf** [comment]
All three cases are related to the front, right?@mohammadranjbarz @MohammadPCh

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for your great tests, I will fix them on front-end.

**Comment by maryjaf** [comment]
> @maryjaf Thanks for your great tests, I will fix them on front-end.

Thanks @MohammadPCh 
Is the fix for these cases finished? Shall we test again?

**Comment by maryjaf** [comment]
I didn't see changes in  above scenarios,I think changes have not been deployed on https://givpower.vercel.app/

**Comment by maryjaf** [comment]
Thanks @MohammadPCh 
Now item 1 & 3 are fixed on givpower.vercel.app.
Item 2 is tested on issue #1599
