### ISSUE TITLE
Rank projects by based on GIVpower boosting

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#596]

**Comment by aminlatifi** [comment]
@MoeNick

**Comment by laurenluz** [comment]
**GIVpower Ranking**
- Ranking only changes once every two weeks - at the start of the new GIVback round
- A project’s rank is dependent on the GIVpower that they received throughout the previous GIVbacks round
      - A snapshot of GIVpower should be taken every 4 hrs to see what GIVpower is on each project
      - At the end of the round, all those GIVpower snapshots should be averaged and the new rank should be determined
