### ISSUE TITLE
Migrate test network from Kovan/Ropsten to Goerli on backend

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#597]
Specially for features like

- [x]  All Donating flow, from fetching prices and saving right amounts
- [x]  Token list given chainID: 5 (Goerli)
     Test tokens can be:
     goerliDAI: 0xdc31Ee1784292379Fbb2964b3B9C4124D8F89C60
     DRGIV3: 0xA2470F25bb8b53Bd3924C7AC0C68d32BF2aBd5be
- [x]  (Fill here if I miss something)

@CarlosQ96 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
Thanks @mateodaza for creating this issue and add information to this, I'm working on it

**Comment by mohammadranjbarz** [comment]
@mateodaza  We merged the impact-graph on staging, can you check the frontend?
