### ISSUE TITLE
Add sorting to list of mainCategories and sub categories

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#612]
We should add field named `priority` to both `category` and `mainCategory` tables, and when returning list of them we should sort them by priority.
@MoeNick please put the priority values here, because we have to write migration files to fill them in both staging and production servers

**Comment by MoeNick** [comment]
Let's sort them Alphabetically. First in Main Categories then in Sub Categories.

**Comment by maryjaf** [comment]
> Let's sort them Alphabetically. First in Main Categories then in Sub Categories.

Sorting is only for the list of categories and sub-categories on the Create and Edit Project page
Or the list of categories be displayed in alphabetical order on the project details page?

<img width="1331" alt="image" src="https://user-images.githubusercontent.com/111529185/189060583-ca5e89d7-7b70-426c-8604-f21b2dac29d1.png">

**Comment by mohammadranjbarz** [comment]
> Let's sort them Alphabetically. First in Main Categories then in Sub Categories.

@CarlosQ96  I'm almost busy with power boosting, can you do this?
( when calling mainCategories and categories, we want sort everything alphabetically, for instance when mainCategories should be sorted and projects inside that should be sorted as well)

**Comment by CarlosQ96** [comment]
Ill take it @mohammadranjbarz

**Comment by CarlosQ96** [comment]
Leaving Pr here https://github.com/Giveth/impact-graph/pull/637

**Comment by mohammadranjbarz** [comment]
@MoeNick  @MohammadPCh  Merged and it will be on Staging in 15 minutes
