### ISSUE TITLE
Deploy powerboosting on develop( not staging) ENV

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#613]
We dont want to merge #600 for now, so we deploy it in develop ENV then frontend can use that until we get ready to merge it on staging

**Comment by aminlatifi** [comment]
@MoeNick I and @mohammadranjbarz decided to deploy Power Boosting feature on develop env impact-graph and don't make the staging env dirty.

The server will be accessible at https://dev.serve.giveth.io/

**Comment by mohammadranjbarz** [comment]
@MohammadPCh 

we deployed power boosting feature on develop ENV (https://dev.serve.giveth.io)

Now you can use below queries/mutaions 

* Set power boosting for single project
https://github.com/Giveth/impact-graph/blob/28725b924353e588eb5217ef8df1732f93223259/test/graphqlQueries.ts#L1365-L1379

* Set power boosting for multiple projects
https://github.com/Giveth/impact-graph/blob/28725b924353e588eb5217ef8df1732f93223259/test/graphqlQueries.ts#L1380-L1394

* Get list of power boosting of users and projects

https://github.com/Giveth/impact-graph/blob/28725b924353e588eb5217ef8df1732f93223259/test/graphqlQueries.ts#L1395-L1423


And for see how you can call them you can see our test cases to get more insights:
https://github.com/Giveth/impact-graph/blob/f_16_power_boosting/src/resolvers/powerBoostingResolver.test.ts
