### ISSUE TITLE
Update dockerfile to execute js files rather than ts

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#620]
After this https://github.com/Giveth/impact-graph/pull/619, we are able to compile typescript to javascript completely. 
In docker file we should apply these changes:
1. compile typescript files and have result js files in the `./build` directory
2. replace executing typescript files by executing js files

**Note:** We must be sure the server works correctly after this change

**Comment by aminlatifi** [comment]
@CarlosQ96 What's the latest update? are we stuck with admin-bro?

**Comment by CarlosQ96** [comment]
Yeah, I investigated a lot to fix adminbro compilations.
So I did:
1. Migrated the adminbro jsx components to tsx for they are compiled successfully by tsc.
2. Imported dom elements to the tsconfig so tsc compiled adminbro correctly.

However now that the build is done, adminbro js isn't resolving the components path correctly. So the admin runs, but custom components show as red squares:

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/92376054/190577506-33974170-2e6d-4c1e-af6b-326d1a83b746.png">

**Comment by CarlosQ96** [comment]
I found this article where someone encountered this issue and fixed it in a really.... weird way, but he explains adminbro is looking for the uncompiled tsx files by default.

Link: https://lightrun.com/answers/softwarebrothers-adminjs-nestjs-provide-a-more-explanatory-example-project

**Comment by CarlosQ96** [comment]
That's my last blocker, if I fix it, once the component loads, the build-dev scripts I wrote can be modified to each env (staging/de/prod) and called on docker to run the app.

https://github.com/Giveth/impact-graph/pull/643 this is the draft pr, not ready for review yet as I am fixing this last issue.

**Comment by CarlosQ96** [comment]
Ok I managed to fix it, but the only solution I found in forums, was copy the uncompiled tsx files to the build folder. 
That worked perfectly.
