### ISSUE TITLE
Rejecting/Verifying Project verification forms are not triggering email

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#624]
Reported by Nikola.

Revoking on the old buttons in the projects page work.

But the new verification flow it does not.

**Comment by CarlosQ96** [comment]
![image](https://user-images.githubusercontent.com/92376054/188912148-870908e1-0ff4-49ea-a46e-c5d031a39510.png)
![image](https://user-images.githubusercontent.com/92376054/188912174-4eb0039e-9d3e-4d12-817f-2713ee070fb1.png)
Both reject and verify are not sending the email

**Comment by mohammadranjbarz** [comment]
<img width="1699" alt="Screen Shot 1401-06-17 at 11 48 40" src="https://user-images.githubusercontent.com/9850545/189066465-e4e6dfe1-888b-491a-b8ed-72f956c8d84f.png">

<img width="1705" alt="Screen Shot 1401-06-17 at 11 48 48" src="https://user-images.githubusercontent.com/9850545/189066490-c1412f8a-7264-404a-9235-31bd4bd49475.png">

@CarlosQ96  As I checked the segment logs I saw we send events, but I checked the auto pilot and understood we don't have any journey for **Project rejected**  so it makes sense why we don't send email for this specific event, I would change the code to send  **Project unverified** event in this case

**Comment by mohammadranjbarz** [comment]
Can you guys test it? @NikolaCreatrix  @CarlosQ96 
It's on production now

**Comment by NikolaCreatrix** [comment]
Hi @CarlosQ96 and @mohammadranjbarz  and fyi @WhyldWanderer 

I just tested with google chrome these actions:
1) Rejecting from the list of projects - trigger email - works

![image](https://user-images.githubusercontent.com/100084867/189921195-16789401-2be7-411e-975c-931d76f13bd1.png)


2) Rejecting from the project card - triggers email - works
![image](https://user-images.githubusercontent.com/100084867/189922787-a1237b13-9403-47b5-81fe-6c480361c1f7.png)

3) Verify from the project card when previously Rejected - changes the status but doesn't trigger email (we need this change also to trigger email sometimes we do that action)

4) Verify from the project card when submitted - doesn't trigger the email, does change the status

![image](https://user-images.githubusercontent.com/100084867/189927335-894ab8f2-e346-419e-bf07-b7fbf43b6dea.png)

**Comment by mohammadranjbarz** [comment]
> Hi @CarlosQ96 and @mohammadranjbarz and fyi @WhyldWanderer
> 
> I just tested with google chrome these actions:
> 
> 1. Rejecting from the list of projects - trigger email - works
> 
> ![image](https://user-images.githubusercontent.com/100084867/189921195-16789401-2be7-411e-975c-931d76f13bd1.png)
> 
> 2. Rejecting from the project card - triggers email - works
>    ![image](https://user-images.githubusercontent.com/100084867/189922787-a1237b13-9403-47b5-81fe-6c480361c1f7.png)
> 3. Verify from the project card when previously Rejected - changes the status but doesn't trigger email (we need this change also to trigger email sometimes we do that action)
> 4. Verify from the project card when submitted - doesn't trigger the email, does change the status
> 
> ![image](https://user-images.githubusercontent.com/100084867/189927335-894ab8f2-e346-419e-bf07-b7fbf43b6dea.png)

Thanks @NikolaCreatrix  For your information, I would check it again

**Comment by NikolaCreatrix** [comment]
Still only 'verifying' doesn't trigger email. Tested again just now.

**Comment by mohammadranjbarz** [comment]
> Still only 'verifying' doesn't trigger email. Tested again just now.

I read the codes again, logic is correct, just tested it again and I received the email, I will coordinate with you in DM to check it together in a call to see what happens, maybe it goes to your spam,

<img width="1169" alt="Screen Shot 1401-06-29 at 10 16 10" src="https://user-images.githubusercontent.com/9850545/191176943-8dc9d9ca-c898-4677-a47c-946e34ba301f.png">



And below screenshot is the related segment event

<img width="1228" alt="Screen Shot 1401-06-29 at 10 19 56" src="https://user-images.githubusercontent.com/9850545/191177498-06807714-0245-486c-bafe-1894131188a4.png">

**Comment by MoeNick** [comment]
@mohammadranjbarz did you contact @NikolaCreatrix ?
Do you want me to ask @maryjaf to test it on production?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz did you contact @NikolaCreatrix ? Do you want me to ask @maryjaf to test it on production?

It would be good

**Comment by maryjaf** [comment]
Please create production access for me @MoeNick

**Comment by NikolaCreatrix** [comment]
Hi guys, according to last week triggering both email responses works okay now. Thank for your amazing detective work and support.
