### ISSUE TITLE
Users can register with the same email but different wallet

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#626]
We need to add uniqueness to emails, this is getting confusing for us debugging and the users when login in and not finding their project.
Assigning myself and Mohammad for now, whoever has time.

**Comment by CarlosQ96** [comment]
@MoeNick

**Comment by mohammadranjbarz** [comment]
As I remember it's something that should @MoeNick and @markoprljic decide, I agree that the non-uniqueness of emails makes some problems

**Comment by MoeNick** [comment]
On the business side it's required that we let the user create an account with a single email, 
so I don't know the reason you made this issue, do we use emails as a key in DB?
