### ISSUE TITLE
Boosting API - get project allocated power list

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#633]
Get the list of powers (user average power in the last round multiplied by allocated percentage) allocated to a project.
We have a corresponding materialized view (supports index) to fetch this information. An API needs to be created for exposing this information.

The API must support sorting and pagination.

**Comment by aminlatifi** [comment]
<img width="794" alt="image" src="https://user-images.githubusercontent.com/5684607/189642964-93dd06d7-d850-450c-9d9e-5bd54ec261d1.png">

**Comment by maryjaf** [comment]
The list of users who have boosted the project is in the order of Give Power amount correctly,but I could not test the pagination in this list.
And in  the list of user's boosted projects, the project is listed in the order of allocated amount and there was no pagination for 20 boosted projects on this page
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/da573f0d-acd6-4181-be60-48828b83ea16)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/464dd385-d1a7-4bd5-ada1-bbcec97925a1)

**Comment by maryjaf** [comment]
Plz check this:
When a project in the list of boosted projects is updated the sorting of list is messed up and is not displayed based on the allocated percentage.
But by refreshing page, sorting will be done.
after edit :
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e301a345-6283-4a9d-b2b5-94728095703b)
after refresh:
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/5f7be25b-b88a-41e6-861d-8fa0992359f7)
@mohammadranjbarz

**Comment by aminlatifi** [comment]
> Plz check this: When a project in the list of boosted projects is updated the sorting of list is messed up and is not displayed based on the allocated percentage. But by refreshing page, sorting will be done. after edit : ![image.png](https://camo.githubusercontent.com/48db862b7d33c3faaf5d1a3ffbba80fab46553f0eb30df68f9492182a47e8326/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65333031613334352d363238332d346139642d623262352d393437323830393537303362) after refresh: ![image.png](https://camo.githubusercontent.com/f6498b8519cfac05b24f6ea6a40407bc2d0163232c84b1105a74ac79299179c7/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f35663762653235622d623838612d343165362d383631642d386661303939323335396637) @mohammadranjbarz

It's a frontend issue @alireza-sharifpour @MohammadPCh

**Comment by MohammadPCh** [comment]
@aminlatifi @maryjaf FYI I show the projects that the back-end returns. I talked with @mohammadranjbarz and we decide to handle sorting for this part totally in the front-end, so I will fix it today.

**Comment by maryjaf** [comment]
Thanks, I check it and passed.
