### ISSUE TITLE
Adminbro Improvements and bug fixes

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#642]
Tasks:
- [x] Rejecting submitted application not changing (SOMETIMES) - Bug
- [x] Project Rejection should change also the project verification form rejection in Adminbro - Update
- [x] Add Operator permissions to edit comments - Update adminbro permissions 
- [ ] When adding or updating a project Update that should set listed to Null (which means waiting for review) - Bug/Update/Mistake on release
- [ ] Add the comments to the project rejection in Segment Info and edit autopilot email template  to show the comment - Update 
- [x] Add giveth.io project Link in the project verification form and project  page in adminbro - Update
- [x] Validate the Approved emails are working (Issue #624) - Bug

**Comment by CarlosQ96** [comment]
I think most of this was done, but some issues are related to other issues, we should move this to done with the current ones done. And then tackle the others in their respective issues.

**Comment by MoeNick** [comment]
Please let us know when the whole flow is ready to test! thanks

**Comment by maryjaf** [comment]
1- giveth.io project Link is not added in project update page 
2- these button should not be shown in all page, it seems buggy 
plz check @CarlosQ96

**Comment by CarlosQ96** [comment]
@maryjaf what buttons  do you refer in point 2?

**Comment by maryjaf** [comment]
> @maryjaf what buttons do you refer in point 2?

@CarlosQ96 The picture was not uploaded
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/111529185/233823188-84981637-e848-466f-8fa4-089c48d0ba51.png">

**Comment by MoeNick** [comment]
@CarlosQ96 the same!

**Comment by MoeNick** [comment]
pinging @WhyldWanderer here. 
@CarlosQ96 can we start testing again?

**Comment by divine-comedian** [comment]
@CarlosQ96  

Do we need to keep working on this for our technical debts?

**Comment by CarlosQ96** [comment]
The project update issue @divine-comedian was never finalized or planned so that is blocked indefinitely.
I don't think the comments one is priority right now. I think we can close this issue

**Comment by divine-comedian** [comment]
OK - Is that issue around project update severe? It says it was a bug/mistake

**Comment by divine-comedian** [comment]
A changed was proposed to make it so only the project update was set as unlisted instead of the entire project. 

This issue however was never drafted or prioritized..
