### ISSUE TITLE
Migration Scripts Limitation for Kubernetes

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/impact-graph#648]
There is a limitation regarding the migration scripts that we use whenever we run impact-graph, where the migration scripts can cause data duplication, this can cause a limitation for scalability in Kubernetes with data duplication once we deploy a new version of our apps running in a container. This is specifically important when we have more than one impact-graph container running and connected to the same database.

**Comment by mohammadranjbarz** [comment]
@mohammadranjbarz  @aminlatifi

**Comment by aminlatifi** [comment]
AFAIK, the footprint of running migration scripts is saved on the database and each migration is run once per DB. So, probably we won't have any issue if we create multiple dockers and connect them to a same DB.

**Comment by mhmdksh** [comment]
> AFAIK, the footprint of running migration scripts is saved on the database and each migration is run once per DB. So, probably we won't have any issue if we create multiple dockers and connect them to a same DB.

Thanks for your feedback Amin. My concern is just when we want to update our apps with new version, and do a new release (Canary or Blue/Green for example). We might need to update the Production DB that is running, and for that I want to make sure that if we have (5 replicas of impact-graph for example) and all f them are being updated while we are doing a canary release, the migration scripts are only run once, and the DB is only changed once.

A.I, not changed with every new replica container that is running.

A good example would be: 

Having a minimum of 2 replicas of impact graph running at all times, The first one is Master (Read/Write) Replica and the second one is Slave (Read Only) Replica, and the database update can be executed only on the master replica.

Do you think these kind of steps are needed??

**Comment by aminlatifi** [comment]
> > AFAIK, the footprint of running migration scripts is saved on the database and each migration is run once per DB. So, probably we won't have any issue if we create multiple dockers and connect them to a same DB.
> 
> Thanks for your feedback Amin. My concern is just when we want to update our apps with new version, and do a new release (Canary or Blue/Green for example). We might need to update the Production DB that is running, and for that I want to make sure that if we have (5 replicas of impact-graph for example) and all f them are being updated while we are doing a canary release, the migration scripts are only run once, and the DB is only changed once.
> 
> A.I, not changed with every new replica container that is running.
> 
> A good example would be:
> 
> Having a minimum of 2 replicas of impact graph running at all times, The first one is Master (Read/Write) Replica and the second one is Slave (Read Only) Replica, and the database update can be executed only on the master replica.
> 
> Do you think these kind of steps are needed??

Good point. If I understood correctly, you are concerned about two replicas running a migration at the same time. So, do you think only master replica must be responsible for running migrations?

**Comment by mhmdksh** [comment]
> > > AFAIK, the footprint of running migration scripts is saved on the database and each migration is run once per DB. So, probably we won't have any issue if we create multiple dockers and connect them to a same DB.
> > 
> > 
> > Thanks for your feedback Amin. My concern is just when we want to update our apps with new version, and do a new release (Canary or Blue/Green for example). We might need to update the Production DB that is running, and for that I want to make sure that if we have (5 replicas of impact-graph for example) and all f them are being updated while we are doing a canary release, the migration scripts are only run once, and the DB is only changed once.
> > A.I, not changed with every new replica container that is running.
> > A good example would be:
> > Having a minimum of 2 replicas of impact graph running at all times, The first one is Master (Read/Write) Replica and the second one is Slave (Read Only) Replica, and the database update can be executed only on the master replica.
> > Do you think these kind of steps are needed??
> 
> Good point. If I understood correctly, you are concerned about two replicas running a migration at the same time. So, do you think only master replica must be responsible for running migrations?

Yes exactly, this could be one of the solutions, if there was a duplication in the migration scripts, if there was no duplication, then I think it's ok. But we have to test to know for sure

**Comment by MoeNick** [comment]
How we can move this issue to QA or done?

**Comment by divine-comedian** [comment]
@mhmdksh 

Is this epic closed? I had understood we were halting the Kubernetes Integration - is this still important?

**Comment by mhmdksh** [comment]
@divine-comedian Exactly, we are halting it for now. Starting it's development again could be a long time from now. I think we have two options, either keep it in icebox, or close it. Feel free to choose.

> @mhmdksh
> 
> Is this epic closed? I had understood we were halting the Kubernetes Integration - is this still important?

**Comment by divine-comedian** [comment]
Icebox!
