### ISSUE TITLE
Can't query Users projects - INTERNAL ERROR

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#66]
I'm trying to query information on a user's projects on - 
https://mainnet.serve.giveth.io/graphql

and it's throwing an INTERNAL SERVER ERROR

![image](https://user-images.githubusercontent.com/67759413/117685690-276a2800-b184-11eb-9a18-2107f068e46e.png)

the user does exist and we can isolate the error specific to this if we remove `projects` from the query.

![image](https://user-images.githubusercontent.com/67759413/117686069-7f089380-b184-11eb-8f86-71113f9b1dfa.png)

**Comment by mohammadranjbarz** [comment]
@divine-comedian pls test this in this url https://serve.giveth.io/graphql
with this query

```
query{
  user(userId:1){
    firstName
    lastName
    projects{
      title
    }
  }
}
```
and if it was ok please tell @MoeNick  to move this to `Done`

**Comment by mateodaza** [comment]
> @divine-comedian pls test this in this url https://serve.giveth.io/graphql
> with this query
> 
> ```
> query{
>   user(userId:1){
>     firstName
>     lastName
>     projects{
>       title
>     }
>   }
> }
> ```
> 
> and if it was ok please tell @MoeNick to move this to `Done`

The problem is particularly on the production database, I'm checking what's wrong with those users and then improve that query

**Comment by mohammadranjbarz** [comment]
> > @divine-comedian pls test this in this url https://serve.giveth.io/graphql
> > with this query
> > ```
> > query{
> >   user(userId:1){
> >     firstName
> >     lastName
> >     projects{
> >       title
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and if it was ok please tell @MoeNick to move this to `Done`
> 
> The problem is particularly on the production database, I'm checking what's wrong with those users and then improve that query

@mateodaza  No it was in staging as well, after deploying PR it resolved, please see https://github.com/Giveth/impact-graph/pull/135#issue-737120234
(it existed even in my local system)

**Comment by divine-comedian** [comment]
user projects seem to be returning data now! 

![image](https://user-images.githubusercontent.com/67759413/134055485-fa736296-dc2e-40cc-b8e1-972a5bc4f739.png)

no errors, hopefully pushing this to productions will solve the problem

**Comment by divine-comedian** [comment]
@mohammadranjbarz  can you ping me when this has been merged to master so I can carry out the task I need to do with the  prod Database?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz  can you ping me when this has been merged to master so I can carry out the task I need to do with the  prod Database?

Sure mitch,
I dont know whats our release plans for now, but I'll let you know

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz can you ping me when this has been merged to master so I can carry out the task I need to do with the prod Database?

@divine-comedian 
It's in production now

<img width="1349" alt="Screen Shot 1400-07-04 at 12 23 38" src="https://user-images.githubusercontent.com/9850545/134800850-3b57d9d6-9534-4f17-85bc-cb15301d1edf.png">

**Comment by divine-comedian** [comment]
thank you man! thanks for pushing this out so quickly
