### ISSUE TITLE
Fetch user power balance for snapshots

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#660]
https://github.com/Giveth/impact-graph/issues/591#issuecomment-1250850647

We have filled PowerSnapshot and PowerBoostingSnapshot tables by DB cron job. Also, we have a cron job in js (impact-graph) that finds and fills the corresponding block number for each snapshot.
At this stage, we need to fill the power balance snapshot table with the help of the `getPowerBoostingSnapshotWithoutBalance` method. The query returns a list of <userId, snapshotId> which must be completed by user balance at snapshot corresponding block and finally be put in the powerBalanceSnapshot table.
The query which will be run to subgraph will look like this
```graphQL
query {
  unipoolBalances(
    first: 3
    where: { 
      unipool: "0xdaea66adc97833781139373df5b3bced3fdda5b1",
      user_in: ["0x05a1ff0a32bc24265bcb39499d0c5d9a6cb2011c", "0x00d18ca9782be1caef611017c2fbc1a39779a57c"]
    },
    block: {number: 24124422}
  ) {
    balance
    user {
      id
    }
  }
}
```
**Note:** `unipool` is address of givpower contract
**Note:** The `getPowerBoostingSnapshotWithoutBalance` returns result which may have various `snapshotId` values. So, we must aggregate (group by) items based on their `snapshotId` and aggregate them in a single query.

**Comment by divine-comedian** [comment]
@mohammadranjbarz @aminlatifi is this issue still relevant?

**Comment by aminlatifi** [comment]
> @mohammadranjbarz @aminlatifi is this issue still relevant?

No, we can close it.
