### ISSUE TITLE
Backend: Adding "Accept Funds on Gnosis" to filters

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#664]

**Comment by mohammadranjbarz** [comment]
@maryjaf  The backend is ready , you can test it now with postman, so I move this to unit test

@MohammadPCh when frontend implement it we can move to UAT

sample request data for postman
```
query {
  projects(
    take: 10,
    skip: 0,
    searchTerm: "",
    filterBy: {
        field: AcceptFundOnGnosis,
        value: true
        },
    orderBy: {
        field: CreationDate,
        direction: DESC
         }
  ) {
    totalCount
    projects {
      traceCampaignId
      id
      addresses {
        networkId
        isRecipient
        address
      }
      categories {
        id
        name
      }
      title
      slug
      qualityScore
      walletAddress
      creationDate
      adminUser{
        name
      }
      users {
          name
      }
      updatedAt
      totalReactions
      totalDonations
      totalTraceDonations
    }

  }
}

```

every project that we get with this payload would have a
```
  {
                            "networkId": 100,
                            "isRecipient": true,
                            "address": "walletAddress..."
                        }
```
in the addresses array, it means it have a recipient address in gnosis(xdai) 

PS: `netowrkId:100` is for gnosis chain

**Comment by mohammadranjbarz** [comment]
> @maryjaf The backend is ready , you can test it now with postman, so I move this to unit test
> 
> @MohammadPCh when frontend implement it we can move to UAT
> 
> sample request data for postman
> 
> ```
> query {
>   projects(
>     take: 10,
>     skip: 0,
>     searchTerm: "",
>     filterBy: {
>         field: AcceptFundOnGnosis,
>         value: true
>         },
>     orderBy: {
>         field: CreationDate,
>         direction: DESC
>          }
>   ) {
>     totalCount
>     projects {
>       traceCampaignId
>       id
>       addresses {
>         networkId
>         isRecipient
>         address
>       }
>       categories {
>         id
>         name
>       }
>       title
>       slug
>       qualityScore
>       walletAddress
>       creationDate
>       adminUser{
>         name
>       }
>       users {
>           name
>       }
>       updatedAt
>       totalReactions
>       totalDonations
>       totalTraceDonations
>     }
> 
>   }
> }
> ```
> 
> every project that we get with this payload would have a
> 
> ```
>   {
>                             "networkId": 100,
>                             "isRecipient": true,
>                             "address": "walletAddress..."
>                         }
> ```
> 
> in the addresses array, it means it have a recipient address in gnosis(xdai)
> 
> PS: `netowrkId:100` is for gnosis chain

@maryjaf  You can play with `take` and `skip` to see more projects and check there addresses

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I tested and it passed
@MoeNick Is a separate issue created for the front-end ?and move this issue to Done?

**Comment by alireza-sharifpour** [comment]
Thanks @mohammadranjbarz for implementing this.
It seems like you added this filter to projects service, we are calling allProjects for getting projects with filters and sorting.
Could you please add it to allProjects?

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour  Now it's on staging, you can send filters like this:
`  filters: ['AcceptFundOnGnosis']`
