### ISSUE TITLE
Revoke the first badge of the projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#665]
@MoeNick commented on [Mon Sep 12 2022](https://github.com/Giveth/Roadmap/issues/22)

---

@CarlosQ96 commented on [Mon Sep 26 2022](https://github.com/Giveth/Roadmap/issues/22#issuecomment-1258076500)

While I moved all to unit testing, and events arrive from my tests. Sometimes they don't
I talked to Mohammad about rewriting segment library to avoid using their inmemory queue and instead we do it with Bull.
I started on this.

**Comment by maryjaf** [comment]
Does this issue need to be tested? I did not understand @CarlosQ96

**Comment by CarlosQ96** [comment]
I'll post the test cases on another issue. This one is more technical.

**Comment by MoeNick** [comment]
@CarlosQ96 I commented on the other issue, let's test it. we need configurable cronjob timing and some test cases.
