### ISSUE TITLE
Review list of all of the projects and their categories

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#688]
As per @ahmadabugosh requests [in Discord](https://discord.com/channels/679428761438912522/861692942645067777/1029837452317302884) and based on this [Epic](https://github.com/Giveth/giveth-dapps-v2/issues/1557), we have to review all project's new categories and sort them all to make sure they are correct. 

Also, Yass had a requirement to have only one main category for each project, maybe we can fix the problem in this issue if we want to go through the project's categories one by one.

**Comment by mohammadranjbarz** [comment]
@MoeNick  I think we dont need this issue anymore

**Comment by MoeNick** [comment]
I think we still need it! 
But mostly on the comms side, shall we have a full list of active projects with their subcategories so we can review it with comms team?

**Comment by ahmadabugosh** [comment]
Yes, @mohammadranjbarz @MoeNick we can still do it, can you share a list of all the projects and categories and I'll work on it with the team?

**Comment by MoeNick** [comment]
@mohammadranjbarz can you share the list with @ahmadabugosh to review them again one by one?

**Comment by mohammadranjbarz** [comment]
Query:
```
SELECT CONCAT('https://giveth.io/project/',slug) as link, STRING_AGG(category.value, ', ') AS categories  FROM project
LEFT JOIN project_categories_category ON project.id = project_categories_category."projectId"
LEFT JOIN category ON category.id = project_categories_category."categoryId"
WHERE project."statusId"=5
GROUP BY slug
```

result
[project_joind_and_aggregated_with_categories.csv](https://github.com/Giveth/impact-graph/files/11016493/project_joind_and_aggregated_with_categories.csv)


@ahmadabugosh  @MoeNick
