### ISSUE TITLE
Add additional option for elastic-search logging in the impact-graph logger

### ISSUE THREAD

**Issue by mhmdksh** [Giveth/impact-graph#712]
Add additional option for elastic-search logging in the impact-graph logger where it can give an option to do external logging or not:

The reference on how to setup this can be found on this page: https://www.npmjs.com/package/bunyan-elasticsearch

1- Add the bunyan-elasticsearch logger option
2- Make it optional to do external logging with bunyan-elasticsearch
3- Make the HOST and PORT of elastic Search a variable that can be defined in the env file

**Comment by mhmdksh** [comment]
The work on this has been done and finished by @aminlatifi here: https://github.com/Giveth/impact-graph/commit/08d8c0d169a2fbae0a2402d39009f623b290b0d7

**Comment by mhmdksh** [comment]
I will reopen this since this is a different approach than what has been worked on here https://github.com/Giveth/impact-graph/commit/08d8c0d169a2fbae0a2402d39009f623b290b0d7

**Comment by aminlatifi** [comment]
The bunyan-elasticsearch package is inspiring but too dated. We can mimic the package short logic in our own source code.

**Comment by MoeNick** [comment]
put it back to product backlog because of not having any process.

**Comment by mhmdksh** [comment]
There will be no need to further proceed with this issue, as we will be following a different approach
Please check this: https://github.com/Giveth/impact-graph/issues/712
