### ISSUE TITLE
Send email when someone like your project

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#732]
- [ ] Send segment data by impact-graph
- [ ] Create autopilot journey for  **project liked** event

**Comment by mohammadranjbarz** [comment]
@MoeNick  I dont know who is in charge for autopilot journeys

**Comment by divine-comedian** [comment]
I'm not sure if we should send emails when a project receives a like - this can make lots of spam. Gonna icebox this one.

**Comment by MoeNick** [comment]
Yeah we disbled the email notifier for like on notification center
