### ISSUE TITLE
Document status changes effect on power boosting

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#740]
@laurenluz  requested to document edge cases ( For instance what happened if a project get deactivated and after a while get activated , ...)

**Comment by divine-comedian** [comment]
@mohammadranjbarz @laurenluz  is this issue still relevant?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz @laurenluz is this issue still relevant?

I think it's better to close it
