### ISSUE TITLE
Dont allow owner of project to donate to his/her own project

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#743]
Now we dont allow it in UI, but it's better to restrict it in backend as well

<img width="1369" alt="Screen Shot 1401-09-07 at 10 03 32" src="https://user-images.githubusercontent.com/9850545/204214825-7d31a1cb-b3a8-43ab-a902-ab4c6ab6a7e1.png">

**Comment by mohammadranjbarz** [comment]
@HrithikSampson Please implement this issue, it's a good task for start contributing
You need to change `createDonation` in `donationResolver.ts` and also please add appropriate test case in `donationResolver.test.ts`  to make sure your code works properly.
(For just running tests related to donation resolver you can use `test:donationResolver` instead of `npm run test` )

**Comment by HrithikSampson** [comment]
Hi @mohammadranjbarz ,I have made the changes in this pull request:
https://github.com/Giveth/impact-graph/pull/1756

**Comment by mohammadranjbarz** [comment]
@maryjaf It's ready for testing now ( If you had problem to how test it DM me please)

**Comment by maryjaf** [comment]
After confirming transaction in metamask I got this error 
I think before this step the error message should be shown, am I right?
@mohammadranjbarz 

<img width="707" alt="Screenshot 2024-08-12 at 2 02 58 PM" src="https://github.com/user-attachments/assets/42b8ac10-b63d-4fdf-87f3-7492b77980f2">


https://github.com/user-attachments/assets/e0705c2c-30a3-474f-afe7-9456b51b3d60

**Comment by mohammadranjbarz** [comment]
> After confirming transaction in metamask I got this error I think before this step the error message should be shown, am I right? @mohammadranjbarz
> 
> <img alt="Screenshot 2024-08-12 at 2 02 58 PM" width="707" src="https://private-user-images.githubusercontent.com/111529185/357014041-42b8ac10-b63d-4fdf-87f3-7492b77980f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1NDI0NTIsIm5iZiI6MTcyMzU0MjE1MiwicGF0aCI6Ii8xMTE1MjkxODUvMzU3MDE0MDQxLTQyYjhhYzEwLWI2M2QtNGZkZi04N2YzLTc0OTJiNzc5ODBmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwOTQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kYjljZTQ1MTY0ZjYxZDJkMzM0YTdiN2Q2ZDM0YTQxMzFmZmI1YWU5MTgzNzAyNTkzMDY1YjQyNGU5MWIzZDhiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UtD0JJuLBqM-SZhCEyotM-pydjFtGxaOmnJcwFuRdLo">
>  Screen.Recording.2024-08-12.at.2.02.29.PM.mov

Thanks @maryjaf  
@HrithikSampson You should do same restriction and write test cases for `createDraftDonation` as well

**Comment by HrithikSampson** [comment]
Hi @maryjaf ,
I have merged the branch to staging with the restrictions added for createDraftDonation

**Comment by maryjaf** [comment]
Thanks @HrithikSampson 

- [ ] 1- I think it would be good if this message in console log also be shown in UI instead of "transaction rejected"

![image](https://github.com/user-attachments/assets/313a5c4a-1a6e-4aff-8e6e-99e92be4856a)


- [ ] 2- This limitation doesn't exist in recurring donation and I could set a recurring donation for my project 

https://github.com/user-attachments/assets/e4ece612-6bd0-4ca5-a2fe-6b0d585d62fb

- [ ] 3- we will have a new  model for donation, donate with stellar ; this new logic also should be applied for stellar ?
cc: @MoeNick @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Thanks @HrithikSampson
> 
> * [ ]  1- I think it would be good if this message in console log also be shown in UI instead of "transaction rejected"
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/358890304-313a5c4a-1a6e-4aff-8e6e-99e92be4856a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDk1MTAsIm5iZiI6MTcyNDMwOTIxMCwicGF0aCI6Ii8xMTE1MjkxODUvMzU4ODkwMzA0LTMxM2E1YzRhLTFhNmUtNGFmZi04ZTZlLTk5ZTkyYmU0ODU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMlQwNjQ2NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NGM2YmE4NTljMjE2MDJhZTY2NTJlYjA3ZDE4YWI1YTBjYTdjZDk4NTdhNjRjMzE5N2IzNmVkZDU0Zjk0MWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8iEMUVsDr2Oh6mI3csfE92Sa8lmOV5NWjAurV8RyBI0)
> 
> * [ ]  2- This limitation doesn't exist in recurring donation and I could set a recurring donation for my project
> 
>  Screen.Recording.2024-08-18.at.10.45.57.AM.mov 
> * [ ]  3- we will have a new  model for donation, donate with stellar ; this new logic also should be applied for stellar ?
>   cc: @MoeNick @mohammadranjbarz

1. I think we can do it. @HrithikSampson please try to to fix it and if you had problem ask from some FE devs (@MohammadPCh  or @RamRamez )
2. @HrithikSampson Please add this restriction for recurring donations as well
3. @maryjaf I think it's better to add another issue in order to implemen it. @MoeNick WDYT?

**Comment by divine-comedian** [comment]
Hey guys! look like this hasn't passed QA - please let @maryjaf test this out and approve before moving it to Done @HrithikSampson 
 
We also have https://github.com/Giveth/giveth-dapps-v2/issues/4612 which is to prevent the user from attempting to make a donation directly from the donate page of the project (the back-end still rejects it but we need to handle it on the UI)

**Comment by HrithikSampson** [comment]
Sure @divine-comedian, @maryjaf I thought that Issue 4612(https://github.com/Giveth/giveth-dapps-v2/issues/4612) is the Frontend Version of this issue.

**Comment by maryjaf** [comment]
> Thanks @HrithikSampson
> 
> * [ ]  1- I think it would be good if this message in console log also be shown in UI instead of "transaction rejected"
> 
> ![image](https://private-user-images.githubusercontent.com/111529185/358890304-313a5c4a-1a6e-4aff-8e6e-99e92be4856a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUxNzMzMzMsIm5iZiI6MTcyNTE3MzAzMywicGF0aCI6Ii8xMTE1MjkxODUvMzU4ODkwMzA0LTMxM2E1YzRhLTFhNmUtNGFmZi04ZTZlLTk5ZTkyYmU0ODU2YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQwNjQzNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGU0YjE0MjczZGFjNzViYmM0ZDMwNWZjNTM1MzdlZGMxNDMxNjk4MzNlZTc0MTU3OTI3MjdiZTRlYzhmNGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cTCNdySroGVZf8fUpzv49jGypRyDRk8hM4nwD3-MMaY)
> 
> * [ ]  2- This limitation doesn't exist in recurring donation and I could set a recurring donation for my project
> 
>  Screen.Recording.2024-08-18.at.10.45.57.AM.mov 
> * [ ]  3- we will have a new  model for donation, donate with stellar ; this new logic also should be applied for stellar ?
>   cc: @MoeNick @mohammadranjbarz

I've tested this issue and reported these items 
when they are ready for retesting, please let me know

**Comment by divine-comedian** [comment]
@maryjaf check out the FE implementation of this change - read the issue and understand the proposed changes and we can follow UI changes there.  https://github.com/Giveth/giveth-dapps-v2/issues/4612

In terms of preventing it from the back-end it seems this issue is complete.

Have we also tested this for Solana and Stellar addresses?

**Comment by maryjaf** [comment]
> * [ ]  2- This limitation doesn't exist in recurring donation and I could set a recurring donation for my project

This item hasn't been fixed 
@divine-comedian @mohammadranjbarz

**Comment by MoeNick** [comment]
For Stellar please note that we only have the Stellar recipient address and the project owner does not have any Stellar address as a user-related address like Sol and Eth. 
So we can only avoid the recipient address as a source of donation in this case.

**Comment by maryjaf** [comment]
> Have we also tested this for Solana and Stellar addresses?

for stellar @MoeNick added some description above
and for solana I got an error when I try to donate, could you please take a look ? @HrithikSampson @mohammadranjbarz 


https://github.com/user-attachments/assets/4f27d8d9-f4a6-4a3c-9875-9dd346c37671

**Comment by maryjaf** [comment]
> Have we also tested this for Solana and Stellar addresses?

I've tested with SOL token and the correct error is shown on backend side

![image](https://github.com/user-attachments/assets/ad3c25ea-8aac-49bf-a47e-5f9ee44d4830)

**Comment by HrithikSampson** [comment]
https://github.com/Giveth/impact-graph/issues/743#issuecomment-2324300583

@maryjaf, I have tried to resolve it and merged it to staging.
