### ISSUE TITLE
Archive old power boosting related data

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#750]
Power Boosting Snapshot and Power Balance Snapshot tables can become too big after taking many snapshots. This impacts system performance and sometimes functionalities since the DB queries may take a long time.

For instance, today staging was not responding because the boosting-related queries used to take a very long time and blocked the DB!

As power boosting snapshot and power balance snapshot tables' data are indexed and queried a lot, one solution is to make them lighter. Technically, computing projects' rank and future rank needs only data related to 2 rounds ago. Therefore, we can move the rest to archived equivalent ones. In this way, we won't lose data for future analyses. 

The point is that only power boosting snapshot data is essential to be kept somewhere since the power balance snapshot data can be retrieved again by impact graph. BTW, we can store both so far till sometime we suffer from the huge amount of data in Db.

**Comment by aminlatifi** [comment]
So far, I deleted old data with
```sql
delete FROM public.power_boosting_snapshot
where "powerSnapshotId" in (
	select "snapshot"."id" from public.power_snapshot as "snapshot",
	public.power_round as "powerRound"
	where "snapshot"."roundNumber" < "powerRound"."round" - 3
);

delete FROM public.power_balance_snapshot
where "powerSnapshotId" in (
	select "snapshot"."id" from public.power_snapshot as "snapshot",
	public.power_round as "powerRound"
	where "snapshot"."roundNumber" < "powerRound"."round" - 3
);
```

**Comment by aminlatifi** [comment]
Maybe something like this may work
https://stackoverflow.com/questions/2974057/move-data-from-one-table-to-another-postgresql-edition/8095147#8095147

**Comment by aminlatifi** [comment]
Maybe the best way is to create another pg_cron job for archiving that runs once per round and inside of that run that query. Obviously, we must create a procedure call with all archiving logic and set it as the query is run by the cron job. @CarlosQ96 @mohammadranjbarz I like you guys once create a pg_cron job and see how is the procedure.

**Comment by CarlosQ96** [comment]
I think this might work after looking at the docs, so we can periodically run this query inside the cronjob and clean up the main table. 

On staging tho, we should add additional logic, because of testing queries I did. So we should delete stuff in the historic table eventually too in staging. 

Because Staging is the one that grows insanely fast compared to prod. (unless we are not gonna query this historic data, but if we are we should clean it in staging or we will crash the server again).

**Comment by aminlatifi** [comment]
@CarlosQ96 Let's go forward, 

- [x] Create archive tables (as a migration)
- [x] Defined procedure to archive records that belong to rounds older than 2 rounds ago. (again in a migration file)
- [x] Create pg_cron job to run it once per round at least

**Comment by aminlatifi** [comment]
@mohammadranjbarz You are the only one who can test it.

**Comment by aminlatifi** [comment]
@mohammadranjbarz Can you take the responsibility to test it and verify the system works correctly (ranking, projected ranking, etc.)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Can you take the responsibility to test it and verify the system works correctly (ranking, projected ranking, etc.)

Sure, I will do it
