### ISSUE TITLE
Backend - Project update feed

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#751]

**Comment by maryjaf** [comment]
I don't know anything about testing this @MoeNick

**Comment by MoeNick** [comment]
@CarlosQ96 can you please provide the name of the service so @MohammadPCh can QA it.

**Comment by CarlosQ96** [comment]
Linking. my current PR: https://github.com/Giveth/impact-graph/pull/752

I will modify it with what we talked in the meeting.

**Comment by CarlosQ96** [comment]
Summary: 
1. One card per project (even if they do many updates, only get latest update)
2. Join with the project for the slug and image.

**Comment by CarlosQ96** [comment]
Making the changes said in the meeting. Will deploy tomorrow early.
- Unique project card (1 update max in the list)
- Join project data.

**Comment by maryjaf** [comment]
https://github.com/Giveth/impact-graph/issues/856#issuecomment-1462015572
In latest updates the unlisted and deactivated projects are shown @CarlosQ96

**Comment by maryjaf** [comment]
Now we show the latest update of each project
That is, if a project has, for example, two updates in one day
In the list of latest updates, the second update replaces the first, is this ok? @MoeNick

**Comment by CarlosQ96** [comment]
I'll add the validations tomorrow.

**Comment by CarlosQ96** [comment]
Yeah I don't remember where, but I talked to Ashley and the latest update should replace the new one.

**Comment by CarlosQ96** [comment]
@WhyldWanderer can you confirm?

**Comment by maryjaf** [comment]
> [#856 (comment)](https://github.com/Giveth/impact-graph/issues/856#issuecomment-1462015572) In latest updates the unlisted and deactivated projects are shown @CarlosQ96

This problem has been resolved and now the unlisted and deactivated projects are not shown in latest updates list
