### ISSUE TITLE
Edit and remove project updates

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#76]
Allow users to edit and remove their project updates

**Comment by mateodaza** [comment]
blocked by [this issue](https://github.com/giveth/impact-graph/issues/76)

**Comment by divine-comedian** [comment]
edited update successfully!

![image](https://user-images.githubusercontent.com/67759413/124392666-083fd080-dcc5-11eb-9352-723b53211b46.png)

project deleted successfully!
![image](https://user-images.githubusercontent.com/67759413/124392956-2bb74b00-dcc6-11eb-85c0-a3d05198fc15.png)


YAY!
