### ISSUE TITLE
Get list of most funded projects (top 10) in 2022

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#763]
@MoeNick  Wanted this 
> I just want to ask if there is a way to determine the top 10 most funded projects in Giveth for 2022

**Comment by mohammadranjbarz** [comment]
### Query 
@CarlosQ96  Can you review my query to see wether it's correct or not?

```
select  "slug", COALESCE(SUM("valueUsd"),0) as total from donation
left join project on project.id = "projectId"
where "createdAt" >'2022-01-01 00:00:00'and status='verified'
group by "slug"
order by total DESC
limit 10
```

### Response
|slug                                                         |total  USD value  |
|-------------------------------------------------------------|---------|
|expedition-grundeinkommen                                    |480049.94|
|unchain-fund                                                 |146019.31|
|Colorado-Multiversity-0                                      |99722.02 |
|giveth-house                                                 |46855.215|
|diamante-bridge-collective-0                                 |38331.914|
|the-giveth-community-of-makers                               |28479.236|
|trusted-seed                                                 |22532.244|
|Bloom-Network-0                                              |18826.383|
|Giveth-Matching-Pool-0                                       |16268.163|
|Diamante-Luz-Center-for-Regenerative-Living-0                |15766.418|

**Comment by maryjaf** [comment]
@mohammadranjbarz Can you share the curl of this api with me?

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz Can you share the curl of this api with me?

We don't have any curl for this, I just get it directly from DB with above query, it's not an issue that needs to get tested
