### ISSUE TITLE
Why round number not get updated correctly in production?

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#764]
Currently we disabled the cronjob that update the projectRound ( with setting `UPDATE_POWER_ROUND_CRONJOB_EXPRESSION=0 0 0 0 0 11` in `.env`) in Production ENV and set roundNumber to `25` manually in DB

**Comment by mohammadranjbarz** [comment]
It was `FIRST_GIVBACK_ROUND_TIME_STAMP=1640718000` in config and it was **2021-12-28 22:30:00 GMT+03:30** but first givback round time should have be `FIRST_GIVBACK_ROUND_TIME_STAMP=1640707200` **2021-12-28 19:30:00 GMT+03:30** so there wasn't anything wrong in code in this wrong config caused miscalculation in three first hours of each round, I update the config but don't change `UPDATE_POWER_ROUND_CRONJOB_EXPRESSION` till @aminlatifi  approve that.

**Comment by aminlatifi** [comment]
> 1640718000

You are right Mohammad, it was my bad. When I was computing the first round start time, I converted my local time (GMT+3) to epoch! that's the reason in GMT the round change would happen 3 hours later!

**Comment by aminlatifi** [comment]
@mohammadranjbarz I applied the changes and restarted the server. Also, one of the snapshots' round number was wrong. I cleared its value then it became filled again with the correct value. Even a new snapshot created during my experiments with correct round number.

**Comment by aminlatifi** [comment]
@MoeNick @laurenluz The issue must be fixed, the round number must be increased by one at the edge of this round.

**Comment by laurenluz** [comment]
Are you on it @aminlatifi ?

**Comment by aminlatifi** [comment]
> Are you on it @aminlatifi ?

Yes, I enabled the set round cron job again and everything has been ok till now. We expect everything work fine at he edge of this round too. It means the ranks and values be updated 5 minutes after new round start time.
