### ISSUE TITLE
Create notification for when a project you own gets unverified

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#773]
This is for the project owner of a verified project. When their project gets unverified (loses status) It should say:

Your project {projectname} has lost its verified status. 

... do we have this one already? @CarlosQ96 @mohammadranjbarz 

close it if so, I didn't see it in the figma

**Comment by laurenluz** [comment]
Do we already have a notification for when a project gets verified?

**Comment by MoeNick** [comment]
@maryjaf please check it again.

**Comment by maryjaf** [comment]
1-When my project is unverified I receive this notification
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/da0d12d6-0f51-4d57-8622-0715c4eb79b4)
2-unverified project --> verified
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/36add91a-ac45-4418-afa6-830396d2f385)

**Comment by mohammadranjbarz** [comment]
> 1-When my project is unverified I receive this notification ![image.png](https://camo.githubusercontent.com/068f1abea6ef21ffd2b4b1fca953d2d39136951853203103b595db314f23a37e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64613064313264362d306635312d346435372d383632322d303731356334656237396234) 2-unverified project --> verified ![image.png](https://camo.githubusercontent.com/aa9236c29b67db326e0f2f4e6ea529bf4eea084798ee951d8736728ec6657af9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33366164643931612d616334352d343431382d616661362d383330333936643266333835)

Do you mean it's ok or not?
Do the **GIVbacks** and **GIVpower** links work well?

**Comment by maryjaf** [comment]
> > 1-When my project is unverified I receive this notification ![image.png](https://camo.githubusercontent.com/068f1abea6ef21ffd2b4b1fca953d2d39136951853203103b595db314f23a37e/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f64613064313264362d306635312d346435372d383632322d303731356334656237396234) 2-unverified project --> verified ![image.png](https://camo.githubusercontent.com/aa9236c29b67db326e0f2f4e6ea529bf4eea084798ee951d8736728ec6657af9/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f33366164643931612d616334352d343431382d616661362d383330333936643266333835)
> 
> Do you mean it's ok or not? Do the **GIVbacks** and **GIVpower** links work well?

Yeah , it is ok and I have moved it to the list of passed
Thanks
