### ISSUE TITLE
Create notification for when your verified project has a new rank

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#774]
This should consider only the current rank of the project and should send a notification if it changes when the GIVbacks round turns over. I would love to specify if it went up or down. Copy:

Your project {project name} has a new higher rank!

Your project {project name} has a new lower rank.

@CarlosQ96 @mohammadranjbarz

**Comment by MoeNick** [comment]
heads up not to miss this one guys!

**Comment by laurenluz** [comment]
Spreadsheet created to outline which notifications we have: https://docs.google.com/spreadsheets/d/1-YjL6O6GFcoLlWM0CcqoW3VztJcNlploHAWqRfT5uJA/edit#gid=0

Need @mohammadranjbarz or @CarlosQ96 to create new notifications.

Got feedback from @aminlatifi about how we know when a project gets a new rank.
Amin sent some guidelines in the group:
Actually, the transition to the next the next round and updating ranks doesn't happen in single step or in atomic way! 
- We update round number  on a regular basis
- We update ranks based on synced balances and round number again on a regular basis
So, when the round is changed, we don't have the ranks yet. And when the new ranks are changed we don't save what was the input (round number I mean).
We must add this feature if you like. It's possible but needs maybe a week of development and testing

**Comment by laurenluz** [comment]
@aminlatifi will think about how we can get info about when the project new rank is achieved, because it's not easily attained.

**Comment by mohammadranjbarz** [comment]
@MoeNick  @laurenluz 
Do we need show these notifications in notification setting page?(If it's yes, what would be text of that and should we show it in which notification category)
The default value for web notification should be `true` or `false`?

I mean this page content for this notification

<img width="1339" alt="Screen Shot 1402-01-27 at 12 59 21" src="https://user-images.githubusercontent.com/9850545/232289734-145d2bb8-a67b-4239-9c26-17ddcdd184cb.png">

**Comment by MoeNick** [comment]
Thanks, @mohammadranjbarz for the hint, and sorry we missed it. 
Yes, it should be there. 

Copy:
**New Rank**
Notify me when my project has a new rank. 

Web: Editale, default value on
Email: disabled, default value off

(Let's make the emails off until @ahmadabugosh makes sure about the autopilot template. )

**Comment by mohammadranjbarz** [comment]
@maryjaf  You can test it now on staging
each round duration is about `20 min` so you need to boost/unboost your project to change it's ranking in next round, then after next round begins admin will see a notification about that

I tested with https://staging.giveth.io/project/testnotif10000xd5db3f8b0a236176587460dc85f0fc5705d78477 so currently you would see a notification for the owner of that project that I guess you are the owner

And in notification setting you should see **Notify me when my project has a new rank.** item for both new users and old users 

<img width="1435" alt="Screen Shot 1402-02-05 at 14 25 15" src="https://user-images.githubusercontent.com/9850545/234256117-46b7d787-0549-40a1-b168-d0b059d0c29b.png">

**Comment by maryjaf** [comment]
I boosted one of my projects that had no Givepower and the expected rank changed to 16
But after the end of the round and the change of current rank to 16, I didn't receive a notification
Plz check @mohammadranjbarz 
https://staging.giveth.io/project/testremove

**Comment by mohammadranjbarz** [comment]
> I boosted one of my projects that had no Givepower and the expected rank changed to 16 But after the end of the round and the change of current rank to 16, I didn't receive a notification Plz check @mohammadranjbarz https://staging.giveth.io/project/testremove

@maryjaf 
If it didn't have rank before that you would not receive a notification, because you just get notification when change of rank, so for first time you get rank you will not recieve it

**Comment by maryjaf** [comment]
> > I boosted one of my projects that had no Givepower and the expected rank changed to 16 But after the end of the round and the change of current rank to 16, I didn't receive a notification Plz check @mohammadranjbarz https://staging.giveth.io/project/testremove
> 
> @maryjaf If it didn't have rank before that you would not receive a notification, because you just get notification when change of rank, so for first time you get rank you will not recieve it

I think it is better to inform the project owner for the projects that do not have Givpower and now their ranking has changed from zero, but Lauren and you know better @mohammadranjbarz @laurenluz

**Comment by maryjaf** [comment]
For the above project, the rank has changed from 17 to 24, but I have not received a notification
https://staging.giveth.io/project/testremove
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> For the above project, the rank has changed from 17 to 24, but I have not received a notification https://staging.giveth.io/project/testremove @mohammadranjbarz

@maryjaf 
Thanks for reporting, we had a bug there, I fixed it and deployed on staging, can you test it again?

**Comment by maryjaf** [comment]
Please check these  test results : @mohammadranjbarz 
1-
I reduced  GIVpower of "testremove" project with current rank 23 , its projected rank changed from 23 to 26 (pic 1)
Then I increase GIVpower and  its projected rank  from 23 to 16(pic 2)
When the round ended and the current rank changed to 16, I this notification: your project [testremove]has a new lower rank.
![image](https://user-images.githubusercontent.com/111529185/236874116-c34ec2fc-912f-43f3-8f0e-af159aa67ece.png)
![image](https://user-images.githubusercontent.com/111529185/236874185-6558c6ff-9ea8-49fc-8639-38bd6ce56ab9.png)
<img width="713" alt="image" src="https://user-images.githubusercontent.com/111529185/236875451-ea4e5d95-43fc-47eb-ab99-bc409686de04.png">

2-
I boosted the project which had no GIVpower and it's projected rank changed  from "--"to "21". When the round ended,and the current rank changed to 22,  I received this notification: your project has a new lower rank.
 
![image](https://user-images.githubusercontent.com/111529185/236876387-0e477271-df36-4dee-84a3-1cbc1827ef7b.png)
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/111529185/236876864-cf52d4c9-498f-4bb6-a96e-52b3d4bc59be.png">
<img width="728" alt="image" src="https://user-images.githubusercontent.com/111529185/236876971-231a0200-d0bd-49ce-8c2b-718612469713.png">

**Comment by mohammadranjbarz** [comment]
> Please check these test results : @mohammadranjbarz 1- I reduced GIVpower of "testremove" project with current rank 23 , its projected rank changed from 23 to 26 (pic 1) Then I increase GIVpower and its projected rank from 23 to 16(pic 2) When the round ended and the current rank changed to 16, I this notification: your project [testremove]has a new lower rank. ![image](https://user-images.githubusercontent.com/111529185/236874116-c34ec2fc-912f-43f3-8f0e-af159aa67ece.png) ![image](https://user-images.githubusercontent.com/111529185/236874185-6558c6ff-9ea8-49fc-8639-38bd6ce56ab9.png) <img alt="image" width="713" src="https://user-images.githubusercontent.com/111529185/236875451-ea4e5d95-43fc-47eb-ab99-bc409686de04.png">
> 
> 2- I boosted the project which had no GIVpower and it's projected rank changed from "--"to "21". When the round ended,and the current rank changed to 22, I received this notification: your project has a new lower rank.
> 
> ![image](https://user-images.githubusercontent.com/111529185/236876387-0e477271-df36-4dee-84a3-1cbc1827ef7b.png) <img alt="image" width="1357" src="https://user-images.githubusercontent.com/111529185/236876864-cf52d4c9-498f-4bb6-a96e-52b3d4bc59be.png"> <img alt="image" width="728" src="https://user-images.githubusercontent.com/111529185/236876971-231a0200-d0bd-49ce-8c2b-718612469713.png">

I think it's misunderstanding, I was thinking when rank reduced we say your project has lower rank, and otherwise we say project has higher rank, if I'm wrong I should change it, 

@MoeNick  @maryjaf  Which one is correct?

**Comment by MoeNick** [comment]
- When the project is new and has not had any rank yet, I guess we have to have a different copy like:
"Your project got a rank!" or if it's hard your project has a new rank is enough. 
- but the first case sounds ok to me, projected rank may be changed due to other boost happened during the round and it's ok

**Comment by laurenluz** [comment]
I think we should change the copy to make it more clear and more optimismtic. What do you think about this:

- When the project rank becomes a new, lower number we say: "Your project has risen in the ranks"
- When the project rank becomes a new, higher number we say: "Your project has a new rank"
- When the project gets a rank, and before didn't have one we say: "Your project got a rank"

**Comment by mohammadranjbarz** [comment]
> I think we should change the copy to make it more clear and more optimismtic. What do you think about this:
> 
> * When the project rank becomes a new, lower number we say: "Your project has risen in the ranks"
> * When the project rank becomes a new, higher number we say: "Your project has a new rank"
> * When the project gets a rank, and before didn't have one we say: "Your project got a rank"

@maryjaf Now you can test it on Staging

**Comment by maryjaf** [comment]
> * When the project gets a rank, and before didn't have one we say: "Your project got a rank"

I tested this case with https://staging.giveth.io/project/testprofilepic?tab=givpower, but I didn't receive any notification @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> > * When the project gets a rank, and before didn't have one we say: "Your project got a rank"
> 
> I tested this case with https://staging.giveth.io/project/testprofilepic?tab=givpower, but I didn't receive any notification @mohammadranjbarz

<img width="1920" alt="Screen Shot 1402-02-24 at 19 14 47 (2)" src="https://github.com/Giveth/impact-graph/assets/9850545/9a612e84-1fd4-49f8-8768-f084a799e8ad">

@maryjaf 
I guess it was a problem with updating DB views delay, I changed something and I tested it myself and got the notification, can you test it again?

**Comment by MoeNick** [comment]
@maryjaf can you test it again?

**Comment by maryjaf** [comment]
I think there is a problem @mohammadranjbarz 
I boosted this project, which did not have GّIVpower before this and it's rank changed from "--" to "27"
https://staging.giveth.io/project/testpfp010 after the end of the round, I did not receive a notification for this project

![image](https://github.com/Giveth/impact-graph/assets/111529185/a114af8d-5e50-4769-9805-9d50c97d4507)
<img width="1339" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/46c50f0a-a2c4-4e0d-8a31-08a9224befc3">

But in the list of notifications, this notification related to another project is displayed
Your project [maryamtestboring](https://staging.giveth.io/project/maryamtestboring) got a rank.
When I click on the name of the project, it has no givpowr and rank

<img width="1415" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/409a6955-70b3-4df4-822f-62b7c9de7346">
<img width="372" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/15e0646f-3ada-423d-82fc-147d7ef445ad">

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz this problem has been resolved and the test is passed

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz this problem has been resolved and the test is passed

@maryjaf 
Thanks for lots of testing you did on this issue, you found so many bugs that I couldn't fix it if you had not found them

**Comment by maryjaf** [comment]
I think it is better to display a different notification when a project loses its entire GIVPower and its rank changes from "20" to "--", for example.
@MoeNick  suggested this copy "Your project lost its rank."
Can we apply these changes? @mohammadranjbarz
