### ISSUE TITLE
Create notification for when someone boosts a project you own with GIVpower

### ISSUE THREAD

**Issue by laurenluz** [Giveth/impact-graph#775]
This notification is for verified project owners. When someone boosts their project, they should be notified. Copy:

Someone boosted your project {projectname}!

@CarlosQ96 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
@maryjaf 
It's on staging you can test it now

**Comment by mohammadranjbarz** [comment]
> @maryjaf It's on staging you can test it now

@maryjaf  We send notifications one per project-booster
it means when someone boost a project we send notificaiton to project owner, but if user remove the boosted and boost that project again we would not send another notification

**Comment by maryjaf** [comment]
> > @maryjaf It's on staging you can test it now
> 
> @maryjaf We send notifications one per project-booster it means when someone boost a project we send notificaiton to project owner, but if user remove the boosted and boost that project again we would not send another notification

I tested this scenario but i didn't receive notification

**Comment by mohammadranjbarz** [comment]
> > > @maryjaf It's on staging you can test it now
> > 
> > 
> > @maryjaf We send notifications one per project-booster it means when someone boost a project we send notificaiton to project owner, but if user remove the boosted and boost that project again we would not send another notification
> 
> I tested this scenario but i didn't receive notification

I had forgotten to merge notificaiton-center PR, now I did it, can you test again?

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz Now when some one boost my project i receive notification like below pic

<img width="774" alt="image" src="https://user-images.githubusercontent.com/111529185/210377497-e11935bf-fadc-4910-b577-5fddf0f63dea.png">
