### ISSUE TITLE
Broadcast from Adminbro notifications

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#780]
### Write a service in adminbro and notificationcenter that allows broadcasting the notifications to all users. 

This service should receive an action name (broadcastType): 'broadcast', 'broadcast to group' and send the notification according to the received content.
The loop AND SQL query for creating it the notification should be done in the notification center.

### STEPS

**_1. Notification Center:  /broadcast_**
Body: content, userIds?, broadcastType, title

Executes:
-   SQL QUERY that creates the notification in the db for all users or selected users in 1 query ONLY. (no loop here)
- LOOP for enqueuing segment events in a bullQueue and send them.

**_2. Adminbro Custom Page and entity: BroadcastNotification_**
This entity will allow creating broadcast messages for reusing anytime. The model should have:
_broadcastType, content, userIds (optional), title, createdAt, updatedAt._ 

And a custom button called **Send Broadcast** that will call the /broadcast endpoint in the notification center, sending the params of the model.

**_3. Broadcast history entity_**
To keep track of the broadcasts we sent, we should fill this table everytime the button **Send Broadcast** is pressed.

**Comment by CarlosQ96** [comment]
Caveats or issues: 
We can do it without filtering by users, this can be a future issue. Just make it so it broadcasts to everyone. 
I say this because making good UX user filterer in a custom form in adminbro is quite time consuming because of limitation.

@MoeNick @mohammadranjbarz @aminlatifi  let me know what you think.

**Comment by CarlosQ96** [comment]
Since we have the adminbro in the impact graph and the admin it's entity dependent, It's inevitable to create the Broadcast notification entity in the impactgraph.

It's somewhat redundant. but if you have a better idea, let me know.

**Comment by mohammadranjbarz** [comment]
Nice, thanks for clarifying this issue, I agree with what you have written, just it should be good that we implement this feature in admin-bro for specific roles, for instance `Operator` role should not have access to send broadcast to all users

**Comment by mohammadranjbarz** [comment]
@maryjaf 
Now this feature is on staging , you can send broadcast notification from 
[https:](https://serve.giveth.io/admin and see the notifications in 
https://notification-center-13.vercel.app/notifications

**PS** You need to know basic things about Markdown for sending notifications, if you needed any help, you can ask Me or @MohammadPCh

**Comment by maryjaf** [comment]
When I  created new broadcast notification I see the notification like below pic for a second and after it has been fixed and the correct time is shown
<img width="632" alt="image" src="https://user-images.githubusercontent.com/111529185/212083116-4f55a5f9-c041-4de1-af66-899a884dd256.png">
 
<img width="632" alt="image" src="https://user-images.githubusercontent.com/111529185/212083281-40bc3f02-c2f3-4ae3-abfd-fe02196cce87.png">
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> When I created new broadcast notification I see the notification like below pic for a second and after it has been fixed and the correct time is shown <img alt="image" width="632" src="https://user-images.githubusercontent.com/111529185/212083116-4f55a5f9-c041-4de1-af66-899a884dd256.png">
> 
> <img alt="image" width="632" src="https://user-images.githubusercontent.com/111529185/212083281-40bc3f02-c2f3-4ae3-abfd-fe02196cce87.png">
> 
> @mohammadranjbarz

@MohammadPCh 
How you calculate time, I think you should not show `-1 year ago` at all, WDYT?

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting this,
@mohammadranjbarz I use `notification.createdAt` for this calculation. The main reason for this issue is the client's computer time. we can use the epoch time for it ( we have it on our frontend), but why is the last notification time correct? oops :(
We need a call for it. because it has been shown properly to me:
![image](https://user-images.githubusercontent.com/17097576/212527507-02484288-209c-40ac-9b1f-b781d5ead5c2.png)

**Comment by maryjaf** [comment]
I tested again and this problem did not occur again @mohammadranjbarz @MohammadPCh

**Comment by mohammadranjbarz** [comment]
> I tested again and this problem did not occur again @mohammadranjbarz @MohammadPCh

So I think we can go through with ignoring that
@MohammadPCh  @maryjaf What do you think?

**Comment by maryjaf** [comment]
@MohammadPCh  guesses that it may be related to users's device time  and suggests that we handle it
