### ISSUE TITLE
Improving db querying by caching

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#781]
Currently, on each query, we execute a DB query. Some queries are complex and repeated too often, like the list of projects ordered by GIVpower. Since it always joined with userId which can be different parameter per query, we must investigate how we can improve query response time and utilize caching

**Comment by CarlosQ96** [comment]
To summarize the steps forward:
- Use typeorm table cache
- Separate count from main projects query
- Run them in parallel with promise.all
- Cache categories
- Separate reaction query from main query

**Comment by CarlosQ96** [comment]
Investigate why project TotalDonations 
```
UPDATE "project"
      SET "totalDonations" = (
        SELECT COALESCE(SUM(d."valueUsd"),$2)
        FROM "donation" as d
        WHERE d."projectId" = $1 AND d."status" = $3
      )
      WHERE "id" = $1
```

Is being called so much

**Comment by aminlatifi** [comment]
As I and @CarlosQ96 discussed,
It's better to use the caching feature of the typeorm. One point to consider is that our query parameters are objects, so we must map a query object to a short key. In order to achieve the key, we will do these steps:
- stringify query object in a reorder-proof manner. It seems [json-stable-stringify](https://www.npmjs.com/package/json-stable-stringify) library does it
- Hash the result string

All of the above steps must be implemented in a separate worker thread since they are CPU demanding and will block the main thread. https://snyk.io/blog/node-js-multithreading-with-worker-threads/

**Comment by CarlosQ96** [comment]
PR in progress, gonna get into implementing the worker threads and finish refactoring querys. (move them to project repository for easier reusability).

**Comment by aminlatifi** [comment]
@CarlosQ96 Do you think we can rely on the front-end to calculate the cache key?!!

**Comment by CarlosQ96** [comment]
That's a great idea, I think that can be certainly helpful. So we can save the cache easier and not put  server work into that. 

I did the implementation but it's not on a worker thread yet.
