### ISSUE TITLE
Adding price for CULT token in monoswap

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#784]
@mateodaza  We recently have added **CULT** to our eligible givback tokens, so we need to have price for this token can you check monoswap and see if we support CULT or not?
https://github.com/Giveth/giveth-dapps-v2/issues/1957#issuecomment-1361406987

JFYI @MoeNick

**Comment by MoeNick** [comment]
@mateodaza can you please take a look?

**Comment by mateodaza** [comment]
@mohammadranjbarz sorry for the delay. please upgrade to version 0.3.16 of the monoswap library and we'll have support to CULT

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz sorry for the delay. please upgrade to version 0.3.16 of the monoswap library and we'll have support to CULT

Mucho gracias @mateodaza

**Comment by MoeNick** [comment]
Can you help us to test the issue? is it merged on production?
