### ISSUE TITLE
Create user when a change project is integrated

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#786]
We need to create a user when a Change project is added to the platform.

It will be associated with the email address and Ethereum wallet address from the Change API..
This will allow for the project owner to receive emails through autopilot and maybe allow for them to make edits and add updates.

**Comment by CarlosQ96** [comment]
@MoeNick lets close this, CHANGE is removing support for crypto so no longer required. I don't think this integration will continue.
