### ISSUE TITLE
Remove smart contract condition in WalletAdressIsValid

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#790]
> This will allow us to avoid the issues around contracts... we can let contracts receive funds. The big question is if we allow them to only accept some currencies or not.

@CarlosQ96 we have to remove the "smart contract" condition in WalletAddressIsValid. 
![image](https://user-images.githubusercontent.com/80677512/210176605-6cfa0900-2638-4435-bf99-83e945ffccc1.png)

_Originally posted by @MoeNick in https://github.com/Giveth/giveth-dapps-v2/issues/106#issuecomment-1368471405_

**Comment by mohammadranjbarz** [comment]
@maryjaf  @MoeNick 
It's on staging and ready for test

**Comment by MoeNick** [comment]
Test Scenario:
user will be allowed to add a smart contract as a recipient address and won't see the previous error msg.

**Comment by maryjaf** [comment]
Thanks @MoeNick @mohammadranjbarz
I tested it and create new project with receiving fund address : Eth address 0xc011a73ee8576fb46f5e1c5751ca3b9fe0af2a6f is a smart contract, I did not get the previous error and it was recorded and I made a successful donation to this address
