### ISSUE TITLE
Allow anonymous fiat donations without an user with only e-mail

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#797]
This is a request for improving fiat donations going from Onramper

Sadly we can't have the KYC info from the ramper but @GriffGreen suggested we could ask for an e-mail beforehand to save this donation without requesting user authentication.

I know this could bring a mess to the current donations table as they are all related to an userId, but maybe there's a way to handle this as "orphan" donations and eventually connect those when an user adds certain email to their user

Let me know what you think guys!

**Comment by laurenluz** [comment]
@mateodaza - I guess we can close this since we aren't using onramper?
