### ISSUE TITLE
Sequence Diagram of Integration with Chainvine. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#803]
Link to Chainvine SDK API EVENTS TRACKING: https://docs.chainvine.xyz/technical/overview/events
Link to Chainvine SDK API Referral Links: https://docs.chainvine.xyz/technical/overview/referral-url

**Comment by CarlosQ96** [comment]
Posting the first version: 
![mermaid-diagram-2023-01-16-011134](https://user-images.githubusercontent.com/92376054/212610009-7f02016b-e47b-4b53-8b61-41a1ff6cbf29.png)

**Comment by CarlosQ96** [comment]
Basically the Referral Link Generation looking at the API seems to be our own custom logic. 
To redirect to the project with the wallet address of the referrer. 

Aside from that, the donation flow and cronjobs is the same that we have, but when a donation is verified with our cronjob.
We send the event for tracking in to their platform.

The givback calculations part is manual still. We could look into automating this. 
We could ask them to provide an endpoint to retrieve the list of successful referrals and populate our givbacks CSVs.

**Comment by MoeNick** [comment]
Wow thanks @CarlosQ96 
I love to invite other team-mates to take a look @mateodaza @aminlatifi @MohammadPCh @MohammadPCh

**Comment by aminlatifi** [comment]
@CarlosQ96 Thanks for preparing this. Does any user see the chainvine frontend/dashboard by this flow? It looks like we proxy everything.

**Comment by CarlosQ96** [comment]
Updated the diagram, they provide a frontend we must configure to allow users to enter and view their referrals and rewards. I am unclear of the configuration I'll ask or we should probably with @ahmadabugosh  begin configuring it.

**Comment by MohammadPCh** [comment]
@CarlosQ96 Thanks, can I have high resolution version of this diagram?

**Comment by ahmadabugosh** [comment]
Thanks @CarlosQ96! So for Frontend and Backend on the left of the diagram, is that our Frontend and Backend? Since I think the generating of the link is on the Chainvine platform. 

Let's have a call with them this week or early next week to go through the flow and user stories and make sure we understand it. 

Besides you, who wants to be on the call, @aminlatifi @MohammadPCh ?

**Comment by aminlatifi** [comment]
@ahmadabugosh I like

**Comment by CarlosQ96** [comment]
Updated Diagram @MohammadPCh @aminlatifi @ahmadabugosh @MoeNick 
IF not visible here is the link to PNG High res
https://mermaid.ink/img/pako:eNp1Vslu2zAQ_ZWBLm0B9wd0CBDbbWE0aIy4cS6-0NTIYkyRKklZcIP-e2eozbGVIAdJnOW9Nwv9lkibYZImHv_UaCQulTg4Ue4M0J-QwTp4whydQ3fzDXFnuo91sKYu971RJVxQUlXCBPjurAlostuTuZDHyYNFIZQ5KYO3Rz_UaSG0rLUIypqNdKoKt1bLeY-sBw9f7-4GKClsFTYeQoGdgdCwdpaZw4MwmTIHWIsDAj2D1EoePbxa1cXsw8SYA9YUHis0HmT_gbFiKOB5BTlJVntCESw4PCgf6JljH9CgEwFBK3NsoxtLr_aEo_Ap3OfscMAQGBnbzhj8GaQw4AvhkCPTF-Ugd4qw-Qn6XdFS2LCHb9-J-Zi7s5gi1r5vR15E65qNw0w5DD3xytlXlMFTAh-BVywpSeErlCpXsrfgQJk1pEMLY0h9VbWViSV7fnroSA_0GqE1hmsBLygsah9sya6es10j8NAorWGPoMpKY4mUMYP9-aKaTHDI9xLzgTJQO00BLXx-Wa2_3Ko4gl9Ggp7guZK8z5SRNDq0UuXaNq0FdfVEl3WjQqXj2rZikSU9iSAIhtR1bFqWx02J0gWIwZZziiNOhKXP2GIZ2C0paOu2nL9P_3jTpMNRy6tlEkEWJEI_htraCjZnIwtipf7ikNnDC6f-haGx7ggLOn61-9bpGvdcW3mMBaF6FiiPI34fRKj9hdtg-h7_4LBFR_XHbDoTK_RcZbFe2Uc5brT5OR3sogu5erFGwZEBFwxP1Gpg88lSkJwPNJvAyWsp0fu81hfFH2b-fr0ac0_0P52nFIWajjfRqeM-RhqdL10-pjdR_t-F8kD_jjYSJyFi7gwGm1FAoRtx7nLFvT817VMLvm_7xWbLnGsfh7GhrWlFBirEhHL08lOBx21Km_6kMirtMGIUVNuDMjM40cXQTZDQvttqjXD9Qp1eLkOiYXtwbVlCbxknSfApUCAqAOnANEphaiovN_3Ha_-RLmR6bTcsRphjKuqiQhBC7ouxE9qtLON0dMBngEH2YiezpEQaVJXRpf_G33YJeZa4S1J6zDAXtQ67ZGf-kWkdZ-BbpujOT9LgapwlfNfzJPfvrU33uyFJc5IN__0HebjaLA?type=png

**Comment by CarlosQ96** [comment]
Here is the mermaid link if you want to edit it: https://mermaid.live/edit#pako:eNp1Vslu2zAQ_ZWBLm0B9wd0CBDbbWE0aIy4cS6-0NTIYkyRKklZcIP-e2eozbGVIAdJnOW9Nwv9lkibYZImHv_UaCQulTg4Ue4M0J-QwTp4whydQ3fzDXFnuo91sKYu971RJVxQUlXCBPjurAlostuTuZDHyYNFIZQ5KYO3Rz_UaSG0rLUIypqNdKoKt1bLeY-sBw9f7-4GKClsFTYeQoGdgdCwdpaZw4MwmTIHWIsDAj2D1EoePbxa1cXsw8SYA9YUHis0HmT_gbFiKOB5BTlJVntCESw4PCgf6JljH9CgEwFBK3NsoxtLr_aEo_Ap3OfscMAQGBnbzhj8GaQw4AvhkCPTF-Ugd4qw-Qn6XdFS2LCHb9-J-Zi7s5gi1r5vR15E65qNw0w5DD3xytlXlMFTAh-BVywpSeErlCpXsrfgQJk1pEMLY0h9VbWViSV7fnroSA_0GqE1hmsBLygsah9sya6es10j8NAorWGPoMpKY4mUMYP9-aKaTHDI9xLzgTJQO00BLXx-Wa2_3Ko4gl9Ggp7guZK8z5SRNDq0UuXaNq0FdfVEl3WjQqXj2rZikSU9iSAIhtR1bFqWx02J0gWIwZZziiNOhKXP2GIZ2C0paOu2nL9P_3jTpMNRy6tlEkEWJEI_htraCjZnIwtipf7ikNnDC6f-haGx7ggLOn61-9bpGvdcW3mMBaF6FiiPI34fRKj9hdtg-h7_4LBFR_XHbDoTK_RcZbFe2Uc5brT5OR3sogu5erFGwZEBFwxP1Gpg88lSkJwPNJvAyWsp0fu81hfFH2b-fr0ac0_0P52nFIWajjfRqeM-RhqdL10-pjdR_t-F8kD_jjYSJyFi7gwGm1FAoRtx7nLFvT817VMLvm_7xWbLnGsfh7GhrWlFBirEhHL08lOBx21Km_6kMirtMGIUVNuDMjM40cXQTZDQvttqjXD9Qp1eLkOiYXtwbVlCbxknSfApUCAqAOnANEphaiovN_3Ha_-RLmR6bTcsRphjKuqiQhBC7ouxE9qtLON0dMBngEH2YiezpEQaVJXRpf_G33YJeZa4S1J6zDAXtQ67ZGf-kWkdZ-BbpujOT9LgapwlfNfzJPfvrU33uyFJc5IN__0HebjaLA

**Comment by CarlosQ96** [comment]
To summarize of tasks of the last meeting, about the implementation.
1. Configure chainvine admin to redirect to Giveth all projects page. (one general link for all referral links).
    Note: Chainvine devs will implement users to configure to the donate page of a specific project per link. (WIP)
2. Frontend/Design: Create a landing page or somewhere in giveth.io that invites user to REGISTER on our Chainvine Referal Program and in their ChainvineUI, generate the link to invite their friends to donate.
3. Frontend: Add a code snippet that detects and grabs the referrer wallet address from url when someone open giveth.io through a referral link.
4. Backend: Install their SDK and save the donation normally but if there is a Referrer wallet, include it in the DB.
5. Backend: Modify VerifyDonationsWithBlockchain cronjob to send data to chainvine through their API when a donation is verified as successful.
6. Backend: Implement a script to extract referrals/rewards/ from chainvine. (CSV available in their UI at first, Chainvine devs working on API)

**Comment by CarlosQ96** [comment]
@MoeNick @ahmadabugosh @aminlatifi I think those are the general tasks I could think of, feel free to edit and suggest.

**Comment by ahmadabugosh** [comment]
Thanks @CarlosQ96 !

For:
1. Did you already create the admin panel? Can you add us to it please (I think you can do it through our eth addresses)? 
2. For this, it's optional (we could launch without it), we could even put it in the Giveth docs to start, then when we have bandwidth @mosaeedi can make a section on our site too
3. You mean [this one](https://docs.chainvine.xyz/technical/overview/referral-url)? I think that's also optional (if we want to bypass their normal site flow)
4. Besides their SDK (to [track events](https://docs.chainvine.xyz/technical/overview/events)), why is it necessary to store the referrer wallet in our DB when Chainvine is tracking it? Is it so we have the data ourselves?  
5. Yes 
6. For this one, they said they'll work on it but it's not blocking the other steps

--------

For next steps, should we start putting these in the epic? @MoeNick

**Comment by aminlatifi** [comment]
> To summarize of tasks of the last meeting, about the implementation.
> 
> 1. Configure chainvine admin to redirect to Giveth all projects page. (one general link for all referral links).
>    Note: Chainvine devs will implement users to configure to the donate page of a specific project per link. (WIP)
> 2. Frontend/Design: Create a landing page or somewhere in giveth.io that invites user to REGISTER on our Chainvine Referal Program and in their ChainvineUI, generate the link to invite their friends to donate.
> 3. Frontend: Add a code snippet that detects and grabs the referrer wallet address from url when someone open giveth.io through a referral link.
> 4. Backend: Install their SDK and save the donation normally but if there is a Referrer wallet, include it in the DB.
> 5. Backend: Modify VerifyDonationsWithBlockchain cronjob to send data to chainvine through their API when a donation is verified as successful.
> 6. Backend: Implement a script to extract referrals/rewards/ from chainvine. (CSV available in their UI at first, Chainvine devs working on API)

5. Let's include the referrer address somewhere in the API call! A user may do two donations with different referral links, so close to each other. Sending referral link from our side will be more precise than their approach.
6. Why do we need to import data anymore? we have had it in front.

**Comment by CarlosQ96** [comment]
On your points Amin:
5. I agree, but we have to tell them to add the referrer address to the API call, it's not present. Somewhat weird they don't include it and I was having the same questions as you. (maybe they handle it on their side?)
6. This point I was debating with myself, if we have the donation data and the referrer we might not need to import data, so this last feature could be optional.

**Comment by MoeNick** [comment]
@aminlatifi for GIVbacks issue can you add it to this list?

**Comment by aminlatifi** [comment]
I reckon we are not blocked for implementing:
1. Updating API and db schema to store referrer wallet address alongside the donation information
2. Updating givback calculation script to include referrer information in calculating givback amounts

**Comment by MoeNick** [comment]
@MoeNick to split it down.

**Comment by MoeNick** [comment]
I splitted the tasks based on @CarlosQ96 list, if we still have some dark areas about our analysis, I think we have to have another meetings with them @ahmadabugosh @CarlosQ96 @aminlatifi

**Comment by MoeNick** [comment]
heads up for updating the doc if we had any changes.
