### ISSUE TITLE
Support clustering

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#805]
Till now, impact-graph was developed with a monolithic mindset, and all the APIs and services are running on a single process.
While this approach enabled us to deploy features fast and debug easier, doesn't scale. As we are migrating to k8s based platform, scaling a service is done normally by launching multiple instances of a service and doing load balancing in front.

Thus, the impact-graph must be refactored and changed in order to enable us to have multiple instances of it at the same time. One blocker is multiple periodic jobs (corn jobs) are run, and only one instance of impact-graph must do it. Tasks like filling power-boosting snapshot data, sending notifications on specific events, etc. To achieve that, these kinds of tasks must be configurable (enable/disable) with a single flag. On deployment, we will only have one instance with this flag true, and all other redundant instances of impact-graph will be launched with this flag false.

@CarlosQ96 @mohammadranjbarz WDYT? Also, please put here any idea you have regarding clustering

**Comment by mohammadranjbarz** [comment]
@aminlatifi I totally agree with you, we should do it as you said

**Comment by divine-comedian** [comment]
@aminlatifi is this issue still relevant?

**Comment by aminlatifi** [comment]
> @aminlatifi is this issue still relevant?

@jainkrati
