### ISSUE TITLE
Supported projects as subscribing 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#809]
Related to https://github.com/Giveth/giveth-dapps-v2/issues/2040 We need to notify users who like, boost, or donate to a project about changes in status and updates (subscribing) 

_On the notification settings side:_

New Section:
Title: Supported Project Activity
Subtext: Notifications related to projects you liked, donated to, or boosted.

**Related Events:**

1.  "Project updated" 
"Notify me when a project I supported has been
- [ ]  edited
- [x]  update has been published

2."Project status" 
Notify me when a project I supported has been
- [x] https://github.com/Giveth/impact-graph/issues/817
- [x] listed
- [x]  unlisted
- [x] canceled
- [x]  activated 
- [x] deactivated

3. "Verification"
Notify me when a project I supported get 
- [x] verified
- [x]  unverified 

PS: _on all notification page:_

**Comment by mohammadranjbarz** [comment]
> Related to [Giveth/giveth-dapps-v2#2040](https://github.com/Giveth/giveth-dapps-v2/issues/2040) We need to notify users who like, boost, or donate to a project about changes in status and updates (subscribing)
> 
> _On the notification settings side:_
> 
> New Section: Title: Supported Project Activity Subtext: Notifications related to projects you liked, donated to, or boosted.
> 
> **Related Events:**
> 
> 1. "Project updated"
>    "Notify me when a project I supported has been
> 
> * [ ]   edited
> * [x]   update has been published
> 
> 2."Project status" Notify me when a project I supported has been
> 
> * [x]  [Send notification for supporters when a project get listed #817](https://github.com/Giveth/impact-graph/issues/817)
> * [x]  listed
> * [x]   unlisted
> * [x]  canceled
> * [x]   activated
> * [x]  deactivated
> 
> 3. "Verification"
>    Notify me when a project I supported get
> 
> * [x]  verified
> * [x]   unverified
> 
> PS: _on all notification page:_

@MoeNick  Said we can skip `project edited` for now because we don't send any notifications for this event

**Comment by mohammadranjbarz** [comment]
@maryjaf  This is deployed on staging, you can test it

**Comment by maryjaf** [comment]
> @maryjaf This is deployed on staging, you can test it

> _On the notification settings side:_
> 
> New Section: Title: Supported Project Activity Subtext: Notifications related to projects you liked, donated to, or boosted.

I tested the notification issues on the https://notification-center-13.vercel.app branch
There is no option related to notification and notif setting on the stage
Maybe I did not understand correctly

**Comment by maryjaf** [comment]
> > @maryjaf This is deployed on staging, you can test it
> 
> > _On the notification settings side:_
> > New Section: Title: Supported Project Activity Subtext: Notifications related to projects you liked, donated to, or boosted.
> 
> I tested the notification issues on the https://notification-center-13.vercel.app branch There is no option related to notification and notif setting on the stage Maybe I did not understand correctly

I understood this

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I tested the above scenarios related to supported project and the correct notification is sent to the user that supported this projects

I noticed 2 item that I think it should be fixed, maybe it is better to register a new issues
plz check this
1- when I Listed a project that it's status already is listed , the notification is sent although the status isn't changed 
2- (it related to admin bro)
I search a project from the filter section
Project details are displayed
When I select another project name from the filter section and make a change on the project details, for example, listed/unlisted the changes is applied to both projects

**Comment by mohammadranjbarz** [comment]
> Thanks @mohammadranjbarz I tested the above scenarios related to supported project and the correct notification is sent to the user that supported this projects
> 
> I noticed 2 item that I think it should be fixed, maybe it is better to register a new issues plz check this 1- when I Listed a project that it's status already is listed , the notification is sent although the status isn't changed 2- (it related to admin bro) I search a project from the filter section Project details are displayed When I select another project name from the filter section and make a change on the project details, for example, listed/unlisted the changes is applied to both projects

Woow , nice catch, but as you said they are not related to this issue, and for first bug it should exists in vertify/unlisted/... as well, I appreciate if you create issue for them
