### ISSUE TITLE
new adminjs dashboard - donation create issue

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#813]
Seems the createDonation function is not working. I get this errors from the. UI (TESTS run but not from ui)
at /admin/resources/Donation/actions/new/Donation
<img width="1362" alt="image" src="https://user-images.githubusercontent.com/92376054/213368857-0e20e018-b9c4-4283-9eec-8beb55596a27.png">

**Comment by divine-comedian** [comment]
@aminlatifi is this issue still relevant?

**Comment by aminlatifi** [comment]
> @aminlatifi is this issue still relevant?

@jainkrati
