### ISSUE TITLE
Decrease get all projects request size

### ISSUE THREAD

**Issue by MohammadPCh** [Giveth/impact-graph#816]
each time we fetch the 15 projects to show on our projects page the response is about 2MB:
![image](https://user-images.githubusercontent.com/17097576/213704437-d96c2012-0b20-4996-b66d-e7a1571897dc.png)

the root cause of this huge size is the project's description, but we want to show this information in the project card:
![image](https://user-images.githubusercontent.com/17097576/213705012-ca124da4-04d2-4a11-bb56-3d2768e46f97.png)
as you can see we only need plain text (not HTML) and a maximum of 30 words.
if we remove the description from the response you will see the size decreases a lot:
![image](https://user-images.githubusercontent.com/17097576/213705813-4ef38bfb-cc0b-4ad6-ad76-3149cd416c94.png)
I suggest having a new attribute for our projects called summary. we can easily produce it in the backend with this package:
https://www.npmjs.com/package/html-to-text
@aminlatifi @MoeNick

**Comment by aminlatifi** [comment]
I like this typeorm listener https://typeorm.io/listeners-and-subscribers#beforeupdate
@mohammadranjbarz @CarlosQ96 Do you think we can rely on it?

**Comment by MohammadPCh** [comment]
@aminlatifi I think it's better to have a summarized plain text version for all our HTML entities since we also need it for project updates.

**Comment by aminlatifi** [comment]
> @aminlatifi I think it's better to have a summarized plain text version for all our HTML entities since we also need it for project updates.

@MohammadPCh Do you have any spec in your mind for the summary? the length I mean

**Comment by aminlatifi** [comment]
> @aminlatifi I think it's better to have a summarized plain text version for all our HTML entities since we also need it for project updates.

@MohammadPCh Do you have any spec in your mind for the summary? the length I mean

**Comment by MohammadPCh** [comment]
@aminlatifi In my opinion, about 40~50 words or 300 chars is suitable.

**Comment by aminlatifi** [comment]
`descriptionSummary` for projects and `contentSummary` for projectUpdates are ready, deployed to the staging env

**Comment by aminlatifi** [comment]
@MohammadPCh I am concerned about displaying summary contents in the UI!
As an example summary
```
"[data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNTAiIGhlaWdodD0iNTAiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgdmVyc2lvbj0iMS4xIi8+]

[https://next.giveth.io/_next/image?url=%2Fimages%2Fgiveth-logo-blue.svg&w=128&q=75]

Home [https://next.giveth.io/]

Projects [https://next.giveth.io/projects]

G..."
```

Is it okay for the frontend components?

**Comment by MohammadPCh** [comment]
@aminlatifi  hmmm... there is a problem here :cry:  . Can we remove them? we only need plain text. 
could you please send me the project link?

**Comment by aminlatifi** [comment]
It's the project https://staging.giveth.io/project/Ram-third-metamask-0

**Comment by MohammadPCh** [comment]
we gonna show that summary here:
![image](https://user-images.githubusercontent.com/17097576/219308763-1d6be4a1-9bf7-4942-bb40-ba3721f7103f.png)
Therefore, all elements except plain text should be removed. let me check it.

**Comment by aminlatifi** [comment]
@MohammadPCh One way around is ignoring imagges
<img width="749" alt="image" src="https://user-images.githubusercontent.com/5684607/219309144-3fce2f6e-b333-47ad-ac79-ab82c5c274aa.png">

**Comment by maryjaf** [comment]
Does this issue need to be tested by QA? @MohammadPCh @aminlatifi

**Comment by aminlatifi** [comment]
> Does this issue need to be tested by QA? @MohammadPCh @aminlatifi

I am not sure if the front end uses that field or not! @MohammadPCh can you confirm?

**Comment by MohammadPCh** [comment]
@maryjaf @aminlatifi We use it in all project cards and update cards.
