### ISSUE TITLE
Remove Admin Column that was Deprecated

### ISSUE THREAD

**Issue by CarlosQ96** [Giveth/impact-graph#825]
We had issues with admin column as it was a string, we couldn't fetch relationships effectively.

I deprecated for new endpoints this column, and created AdminUserId column with foreign keys so we can work better with relations.

However we can remove the old "Admin" column yet. Old tests and old code that hasn't been updated still use it.

Lets remove admin column!

**Comment by MoeNick** [comment]
tagging @WhyldWanderer here to prioritise

**Comment by RamRamez** [comment]
@maryjaf to test an verify
It's just a code refactor but for testing it's good to test general use cases related to Admin actions like the toast notifications for givback and verified projects on owner and non owner view, also actions like editing a project from project view that's related to admin actions

**Comment by maryjaf** [comment]
- [x] 1-
There is a problem in showing verification status in project page, "incomplete","submitted,"rejected " aren't shown correctly in project page, it seems there only two statuses , verified and not verified 

for example for "Incomplete" verification status in project owner view, the status should be shown"Incomplete" and "resume verification" button , please take a look

**Correct view on production**
![image](https://github.com/Giveth/impact-graph/assets/111529185/30c54e8f-a5f9-423d-b361-b6aa7e7e2921)

**Current View on STG** 
![image](https://github.com/Giveth/impact-graph/assets/111529185/0d8fe7d8-35f2-413b-b3e6-75138197def0)
![image](https://github.com/Giveth/impact-graph/assets/111529185/df539a58-2fe2-403c-be6a-3a7af901ebd3)

**Comment by maryjaf** [comment]
- [x] 2-
There is no reason for deactivating
![image](https://github.com/Giveth/impact-graph/assets/111529185/988ce9c3-12b7-4144-9d30-2734e0c0bdeb)

**Comment by maryjaf** [comment]
> It's just a code refactor but for testing it's good to test general use cases related to Admin actions like the toast notifications for givback and verified projects on owner and non owner view, also actions like editing a project from project view that's related to admin actions

-I haven't seen any problem in project edit flow from admin panel and toast box for givback eligible or not eligible tokens in donate page

**Comment by divine-comedian** [comment]
@maryjaf  - can we call this issue done then?

**Comment by RamRamez** [comment]
> * [x]  2-
>   There is no reason for deactivating
>   ![image](https://private-user-images.githubusercontent.com/111529185/331987738-988ce9c3-12b7-4144-9d30-2734e0c0bdeb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxOTc0NjIsIm5iZiI6MTcxNjE5NzE2MiwicGF0aCI6Ii8xMTE1MjkxODUvMzMxOTg3NzM4LTk4OGNlOWMzLTEyYjctNDE0NC05ZDMwLTI3MzRlMGMwYmRlYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQwOTI2MDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmY2ZjI0MDA1N2NiMzg5ZjYxYWE3MGZkZWY2OWM1Y2U2MmYzNmViY2I3NWU5NjYwMzU3NWRhOWM5MjYzZDg2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fuCx4geLLzc2EDljiPtaDvzX_j7MKQUtmnmxicxNrZ8)

I think it was a temporary problem, I tested and it was ok for me.

**Comment by RamRamez** [comment]
> * [x]  1-
>   There is a problem in showing verification status in project page, "incomplete","submitted,"rejected " aren't shown correctly in project page, it seems there only two statuses , verified and not verified
> 
> for example for "Incomplete" verification status in project owner view, the status should be shown"Incomplete" and "resume verification" button , please take a look
> 
> **Correct view on production** ![image](https://private-user-images.githubusercontent.com/111529185/331978878-30c54e8f-a5f9-423d-b361-b6aa7e7e2921.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg0MDMsIm5iZiI6MTcxNjIwODEwMywicGF0aCI6Ii8xMTE1MjkxODUvMzMxOTc4ODc4LTMwYzU0ZThmLWE1ZjktNDIzZC1iMzYxLWI2YWE3ZTdlMjkyMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjI4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZjMzMmMxYTQzZjgyY2VhYjljNTNlZDUzM2MxOWU2ODBkNWQ1NzUwYjUzNDQ0NTIzN2VkMWIzYTgwZDNkZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.k-e2_72eDz7LtWZt1PFplQ1scnweAAVVuPZNsrZUR58)
> 
> **Current View on STG** ![image](https://private-user-images.githubusercontent.com/111529185/331979656-0d8fe7d8-35f2-413b-b3e6-75138197def0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg0MDMsIm5iZiI6MTcxNjIwODEwMywicGF0aCI6Ii8xMTE1MjkxODUvMzMxOTc5NjU2LTBkOGZlN2Q4LTM1ZjItNDEzYi1iM2U2LTc1MTM4MTk3ZGVmMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjI4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00YjY0MmVlN2FjYzkxMjg4YzcyYWQyYjhhYTNlNWFmNWQwZmM2NGNjOTRmNmQxOWNhYWVlNzViYTkxMDRkMzQ5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iiVW_lS70kH9T5GTsI24mJQp4VrtWNksxP_nvME1m0Y) ![image](https://private-user-images.githubusercontent.com/111529185/331979859-df539a58-2fe2-403c-be6a-3a7af901ebd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDg0MDMsIm5iZiI6MTcxNjIwODEwMywicGF0aCI6Ii8xMTE1MjkxODUvMzMxOTc5ODU5LWRmNTM5YTU4LTJmZTItNDAzYy1iZTZhLTNhN2FmOTAxZWJkMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMjI4MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTg0ZGU0M2I0YmM0YWIwODY4MjhmOGEwYWRjMjMzMjEwNjk0NGFkYWRjZjQ0NWIyNWFiOWZjZjljNmRmMjZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6mhujxTVnGbo2ytXOwm1KQjEAuoEHhiOmakS7lfEGT8)

I fixed this problem. My PR just got approved and I merged it. @maryjaf you can test it after the build is completed (20 minutes from now)
