### ISSUE TITLE
Configure chainvine admin to redirect to Giveth all projects page.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#829]
Configure chainvine admin to redirect to Giveth all projects page. (one general link for all referral links).
Note: Chainvine devs will implement users to configure to the donate page of a specific project per link.

**Comment by CarlosQ96** [comment]
@MoeNick this is also working I configured the admin, but hmm ill report an issue.

I think we shouldn't allow users to change the redirect url, its bad ux and complex for them.

I don't see a way to disable it.

**Comment by CarlosQ96** [comment]
leaving in progress in the meantime
