### ISSUE TITLE
Huge number of queries to GPRC provider

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#833]
Our quiknode grpc provider plan is eaten up by impact-graph due to stuck queries!
![image](https://user-images.githubusercontent.com/5684607/215701717-ba9dd039-3a26-4d04-9a2b-abc011e2cbca.png)

@CarlosQ96 has investigated the issue and read the logs, there is massive amount of logs to comprehend the issue

A sample log 
```
{"name":"giveth-impact-graph","hostname":"08863b13b4fa","pid":52,"level":20,

"msg":"syncDonationStatusWithBlockchainNetwork() error {\n  error: Error: Invalid JSON RPC response: {\"size\":0,\"timeout\":0}\n      at Object.InvalidResponse (/usr/src/app/node_modules/web3-core-h
helpers/lib/errors.js:43:16)\n      at /usr/src/app/node_modules/web3-providers-http/lib/index.js:126:29\n      at runMicrotasks (<anonymous>)\n      at processTicksAndRejections (node:internal/process/task_queues:96:5),\n  donationId: 15673,\n  txHash: '0xe1e338134eea4ca2307b0b0a5407d2118da52e82442deeb88e49d92a71f24712'\n}","time":"2023-01-30T05:00:05.199Z","v":0}
```
Generally, we produce GRPC queries for two use case
1. Verifying the donations
2. Finding the closest gnosis-chain block (blocknumber) to a timestamp

**Comment by aminlatifi** [comment]
For the second usecase, we can rely on gnosisscan API 

https://docs.gnosisscan.io/api-endpoints/blocks#get-block-number-by-timestamp

**Comment by MoeNick** [comment]
shall I close this one?
