### ISSUE TITLE
Decide about status of pending donations

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#839]
We have some donations in our db that are `pending` for long time, we should do something about them
- [ ] Some of them are some custom tokens ( that means we don't have tokens in our db so we can't verify it so it can't be verified by network and also we always check them with same result
- [x] #842 

<img width="1006" alt="Screen Shot 1401-11-11 at 16 36 03" src="https://user-images.githubusercontent.com/9850545/215768599-930af155-f594-4c1e-bb34-e1d189267c50.png">

It can be one of the reasons that why we call quicknode Gnosis RPC too much

**Comment by MoeNick** [comment]
Maybe we can add a staus like verifiedErr after 5 attempts of verifying then we mark them with this staus and investigate manually.

**Comment by mohammadranjbarz** [comment]
> Maybe we can add a staus like verifiedErr after 5 attempts of verifying then we mark them with this staus and investigate manually.

It can't be a precise solution, imagine we get error from blockchain network node RPC for 10 hours, then all of our donations that has been made within that time has failed more than 5 times because of network errors

**Comment by aminlatifi** [comment]
> > Maybe we can add a staus like verifiedErr after 5 attempts of verifying then we mark them with this staus and investigate manually.
> 
> It can't be a precise solution, imagine we get error from blockchain network node RPC for 10 hours, then all of our donations that has been made within that time has failed more than 5 times because of network errors

We had an issue on rpc endpoint, reaching to subscription limit. Other than that, we didn't stop checking a donation. @mohammadranjbarz added a policy to not check pending donations status for ever. Am I right @mohammadranjbarz ?

**Comment by mohammadranjbarz** [comment]
> > > Maybe we can add a staus like verifiedErr after 5 attempts of verifying then we mark them with this staus and investigate manually.
> > 
> > 
> > It can't be a precise solution, imagine we get error from blockchain network node RPC for 10 hours, then all of our donations that has been made within that time has failed more than 5 times because of network errors
> 
> We had an issue on rpc endpoint, reaching to subscription limit. Other than that, we didn't stop checking a donation. 

@aminlatifi  You are right we fixed this issue through https://github.com/Giveth/impact-graph/issues/842

JFYI @MoeNick
