### ISSUE TITLE
Awesome updates :) 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#856]
As a user I want to see list of awesome project updates (which has been selected by Admin) with a related project card in the admin page. 

Related to : https://github.com/Giveth/giveth-dapps-v2/issues/1996

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  Can you take this?
I think @MohammadPCh  has comments on it

**Comment by CarlosQ96** [comment]
ill take it!

**Comment by MohammadPCh** [comment]
Thanks, @mohammadranjbarz 
Yes, this is how I build that section:
1. get N projects that have been updated/added their featured updates without that featured Update.
2. create the page.
3. when the user scrolls to that part of the page I fetch the featured update of that project and show it to the user.
so I want 2 queries:
1. fetch the latest projects with featured updates.
2. get a project's featured update by project id.
Thanks @CarlosQ96

**Comment by MoeNick** [comment]
Hey @CarlosQ96 a gentle reminder on this :)

**Comment by CarlosQ96** [comment]
I started on this, talked to Cherik on how will be implemented. Working on a issue in adminbro I have but I will push it today for Cherik to start testing it.

**Comment by CarlosQ96** [comment]
UX isnt that great for selecting the project update in the Adminbro but will push it for review

**Comment by maryjaf** [comment]
The awesome updates isn't shown on this branch https://giveth-dapps-v2-git-add-awsome-projects-update-givethio.vercel.app/

and the latest update is not work correctly and my last update is not shown in list

**Comment by MohammadPCh** [comment]
@maryjaf Thanks for reporting. we don't show the updates since they haven't the position and the backend doesn't return them to front-end, I fixed them and added the position and now you can see them.
and about the latest updates did you stay for 10 minutes?

**Comment by maryjaf** [comment]
Thanks @CarlosQ96  @MohammadPCh , Now the awesome updates are shown on stg based on  their's position on admin bro
But when I add a update on project update list from admin bro as featured update, it is'n shown in  featured update list on admin, plz check this

**Comment by CarlosQ96** [comment]
@maryjaf thats because the update was a default Update (all projects have an empty update)
You have to filter by isMain = false (No)
To get the non-default updates, you can add those.
Also there is a restriction you cannot add twice the same project as featured.
So make sure its not an update from the same one and its not the isMain=true update.

**Comment by maryjaf** [comment]
> @maryjaf Thanks for reporting. we don't show the updates since they haven't the position and the backend doesn't return them to front-end, I fixed them and added the position and now you can see them. and about the latest updates did you stay for 10 minutes?



> and about the latest updates did you stay for 10 minutes?

The latest update also shown in stg but we have 3 problem related that
Do we have a separate issue for latest update or should I register? To raise these problem there @MohammadPCh 
1- the updates of  deactivate or unlisted project is shown 
2- the color for projects is dark Blue even if the cover set for the project is a different color

**Comment by maryjaf** [comment]
> @maryjaf thats because the update was a default Update (all projects have an empty update) You have to filter by isMain = false (No) To get the non-default updates, you can add those. Also there is a restriction you cannot add twice the same project as featured. So make sure its not an update from the same one and its not the isMain=true update.

Thanks @CarlosQ96 I'll check it

**Comment by maryjaf** [comment]
> @maryjaf thats because the update was a default Update (all projects have an empty update) You have to filter by isMain = false (No) To get the non-default updates, you can add those. Also there is a restriction you cannot add twice the same project as featured. So make sure its not an update from the same one and its not the isMain=true update.

Yeah, that's right
Thanks @CarlosQ96 Now we don't have any problems with the awesome updates and it's ok

Just one question, if I click "see more " on an update as a project owner, I see the update page as below
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/111529185/223853758-745b94e7-2e66-4600-a084-68f99905f60a.png">

isn't it better to scroll and display the section related to this update? @MoeNick @MohammadPCh 
according to the picture
<img width="1293" alt="image" src="https://user-images.githubusercontent.com/111529185/223854210-4208906a-f5ad-4072-8155-de6ed3d90c7c.png">

**Comment by MohammadPCh** [comment]
@maryjaf Latest update issue: https://github.com/Giveth/giveth-dapps-v2/issues/2053

**Comment by maryjaf** [comment]
> > @maryjaf Thanks for reporting. we don't show the updates since they haven't the position and the backend doesn't return them to front-end, I fixed them and added the position and now you can see them. and about the latest updates did you stay for 10 minutes?
> 
> > and about the latest updates did you stay for 10 minutes?
> 
> The latest update also shown in stg but we have 3 problem related that Do we have a separate issue for latest update or should I register? To raise these problem there @MohammadPCh 1- the updates of deactivate or unlisted project is shown 2- the color for projects is dark Blue even if the cover set for the project is a different color 3- if I edited my project update this isn't shown in latest update

@mohammadranjbarz Plz check 1 & 3 ,seems these related to backend

**Comment by maryjaf** [comment]
> > @maryjaf Thanks for reporting. we don't show the updates since they haven't the position and the backend doesn't return them to front-end, I fixed them and added the position and now you can see them. and about the latest updates did you stay for 10 minutes?
> 
> 
> 
> 
> 
> 
> 
> > and about the latest updates did you stay for 10 minutes?
> 
> 
> 
> The latest update also shown in stg but we have 3 problem related that
> 
> Do we have a separate issue for latest update or should I register? To raise these problem there @MohammadPCh 
> 
> 1- the updates of  deactivate or unlisted project is shown 
> 
> 2- the color for projects is dark Blue even if the cover set for the project is a different color


@CarlosQ96 Plz check # 1  ,seems these related to backend

**Comment by mohammadranjbarz** [comment]
> > > @maryjaf Thanks for reporting. we don't show the updates since they haven't the position and the backend doesn't return them to front-end, I fixed them and added the position and now you can see them. and about the latest updates did you stay for 10 minutes?
> > 
> > 
> > > and about the latest updates did you stay for 10 minutes?
> > 
> > 
> > The latest update also shown in stg but we have 3 problem related that
> > Do we have a separate issue for latest update or should I register? To raise these problem there @MohammadPCh
> > 1- the updates of  deactivate or unlisted project is shown
> > 2- the color for projects is dark Blue even if the cover set for the project is a different color
> 
> @CarlosQ96 Plz check # 1 ,seems these related to backend

@aminlatifi fixed it, it's deploying on Staging now
