### ISSUE TITLE
Add origin header to jrpc queries

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#860]
https://github.com/Giveth/devops/issues/93

**Comment by aminlatifi** [comment]
@MoeNick someone from devops team can test this feature.

**Comment by MoeNick** [comment]
@mhmdksh can you QA this issue?

**Comment by mhmdksh** [comment]
Hey @MoeNick yes sure.
I tested this before and it is acting as it should be.
We have metrics monitored on our Endpoints by header. Showing the queries origin. I think we can close this

<img width="1195" alt="image" src="https://user-images.githubusercontent.com/52987806/230899067-fe7e7ec6-8d1f-43c4-9df7-c83c2bfc1c04.png">
