### ISSUE TITLE
Recently Updated Projects

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#862]
@MoeNick also we have no sort option to get recently updated projects.

_Originally posted by @MohammadPCh in https://github.com/Giveth/giveth-dapps-v2/issues/2019#issuecomment-1427754008_

**Comment by MoeNick** [comment]
@CarlosQ96 @mohammadranjbarz on the new menu design team places a recently updated projects link, when the user clicks on this option we should sort projects which have posted the newest update. 
I gues we had this sorting @CarlosQ96 can you remember?

**Comment by CarlosQ96** [comment]
yes we have a sort by newest (updatedAt) which will return in that order.

**Comment by MoeNick** [comment]
can u please share it with @MohammadPCh ?

**Comment by CarlosQ96** [comment]
@MohammadPCh same query for projects allProjects()
But the new sort is:
    sortingBy: 'RecentlyUpdated'

**Comment by CarlosQ96** [comment]
https://github.com/Giveth/impact-graph/pull/863 Related PR for review by @mohammadranjbarz  can merge instantly to staging after approving.

**Comment by mohammadranjbarz** [comment]
> #863 Related PR for review by @mohammadranjbarz can merge instantly to staging after approving.

Thanks @CarlosQ96  I merged it right now

**Comment by MohammadPCh** [comment]
Thanks @CarlosQ96 @mohammadranjbarz
