### ISSUE TITLE
New created projects have null adminUser

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#871]
@RamRamez  has reported it

![null adminUser](https://user-images.githubusercontent.com/9850545/219936551-28c41664-6dcc-4ccd-affa-85d7a839d8c6.png)

**Comment by mohammadranjbarz** [comment]
@maryjaf It's done and deployed on Staging

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz 
I tested and this issue has been resolved
