### ISSUE TITLE
Some donations are not anonymous but they dont have user

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#872]
![image.png](https://images.zenhubusercontent.com/604f242c2819d5da6426ad03/dcbd71c0-e26a-4386-a728-51af027fa7df)

https://media.discordapp.net/attachments/947760363854786600/1076821743349534780/image.png

**Comment by mohammadranjbarz** [comment]
@RamRamez 

![annonymous donation](https://user-images.githubusercontent.com/9850545/219944393-dc7d78c3-5480-4ee9-a23a-b6da4d5c40ac.png)

**Comment by mohammadranjbarz** [comment]
@MoeNick  @RamRamez  These users dont have name so when you want to to fetch their name you get nul, but please try getting `id` or `walletAddress` like this:
```
{
 ...
  user{
    name
    id
    walletAddress
  }
...
}
```
You would see you have user's info, @MoeNick  @mosaeedi  you should think what you should show when donor doesn't have name, for instance you can show beginning and end of wallet address instead, something likethis: `0x23...1fd3`

**Comment by RamRamez** [comment]
> @MoeNick @RamRamez These users dont have name so when you want to to fetch their name you get nul, but please try getting `id` or `walletAddress` like this:
> 
> ```
> {
>  ...
>   user{
>     name
>     id
>     walletAddress
>   }
> ...
> }
> ```
> 
> You would see you have user's info, @MoeNick @mosaeedi you should think what you should show when donor doesn't have name, for instance you can show beginning and end of wallet address instead, something likethis: `0x23...1fd3`

I fixed it in PR [#2387](https://github.com/Giveth/giveth-dapps-v2/pull/2387)

**Comment by MoeNick** [comment]
@maryjaf please test them very deeply.

**Comment by maryjaf** [comment]
Now, when the user has a profile and disable the check box of anonymous, after complete the the donation, the user's name will be displayed in the donations tab.
And when the user has or does not have a profile and enable the check box of anonymous, after complete the the donation, the  "anonymous" will be displayed in the donations tab.
And when the user does not have a profile and disable the check box of anonymous, the wallet address will be displayed in the list of donations.
Every thing is ok, Thanks @RamRamez @mohammadranjbarz 
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/111529185/229511013-08d1e9b6-8f0d-49b4-8b1b-5e4f81fe5166.png">
