### ISSUE TITLE
Adminbro filtering nullable values, project listed field

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#877]
After upgrading adminjs and typeorm, we encountered a nullable field filtering issue. The project entity listed field, can have three valid values true, false, and null (which means the project has not been reviewed yet). 
We had implemented a filter component to support all three fields and it had been working since the upgrade. Currently, adminjs doesn't recognize null in the filter query, and filtering by `Not Reviewed` doesn't work.

I raised [an issue](https://github.com/SoftwareBrothers/adminjs/issues/1425) on adminjs repo, hope they offer a solution.
Otherwise can change the field type to an enum as @CarlosQ96 suggested or find another solution

**Comment by maryjaf** [comment]
Thanks it seems has been resolved 
I filter the listed field: not reviewed and it work
