### ISSUE TITLE
AdminBro | The project list is not updated after applying changes through the list

### ISSUE THREAD

**Issue by maryjaf** [Giveth/impact-graph#884]
When I select a project through the check box list and make a change, the page must be updated to see the changes

**Comment by MoeNick** [comment]
Who can take this one? @mohammadranjbarz @CarlosQ96

**Comment by MoeNick** [comment]
tagging @WhyldWanderer to see and help us manage the AdminJS priorities.

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this up post your p0, p1 issues

**Comment by divine-comedian** [comment]
@CarlosQ96 what is the update on this issue?

**Comment by CarlosQ96** [comment]
@maryjaf can we retest this issue when posible? As it was hard to replicate at least for me.

**Comment by maryjaf** [comment]
> @maryjaf can we retest this issue when posible? As it was hard to replicate at least for me.


https://github.com/user-attachments/assets/6c03fe60-6944-4c05-9021-f3c24267fabe

**Comment by CarlosQ96** [comment]
Ok I found the issue, the redirect in each action is not reloading the route. I'll fix all routes and push a hotfix. Should make it coherent.

Basically use the http object functions, instead of writing the route manually.

**Comment by CarlosQ96** [comment]
@kkatusic https://github.com/Giveth/impact-graph/pull/1865 PR ready for review fixing the project view and adding function. 

(testing also Cursor editor with AI, so useful)

**Comment by CarlosQ96** [comment]
@LatifatAbdullahi  @maryjaf can retest this issue in staging

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 it has been fixed 


https://github.com/user-attachments/assets/0bf0ddcf-4692-4054-b4de-5444e159a19b
