### ISSUE TITLE
Change default status of My Project Activity Notifications

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#886]
- [x] Project published
Mail: checked, editable
DAPP: checked, editable

- [x] Your project update
Mail: unchecked, non-editable
DAPP: unchecked, editable

- [x] Project Likes: 
Mail: unchecked, not-editable
DAPP: checked, editable

- [x] Project boost status
Mail: unchecked, not-editable
DAPP: checked, editable

- [x] Your project status
Mail: checked, editable
DAPP: checked, editable

- [x] Donations
Mail: checked, editable
DAPP: checked, editable

- [x] Donation received
Mail: checked, editable
DAPP: checked, editable

**Comment by mohammadranjbarz** [comment]
@maryjaf  It's on staging, can you test this?

**Comment by maryjaf** [comment]
> @maryjaf It's on staging, can you test this?

Thanks @mohammadranjbarz I checked and it's OK
