### ISSUE TITLE
Adding Polygon Network

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#887]
* Write migration for adding tokens on the Polygon network
* Verify donations and transactions
* Get the price of the token when donating

**Comment by MoeNick** [comment]
list of tokens that we want to support on Polygan, the address, and the GIVback eligibility and decimals.

**Comment by aminlatifi** [comment]
We use monoswap to fetch tokens' price, currently, it doesn't support Polygon. Hopefully, uniswap is deployed on the Polygon network. As the monoswap is deployed based on the uniswap SDK, it would be possible to add Polygon support with little trouble.

**Comment by RamRamez** [comment]
@aminlatifi 
Coingecko doesn't have prices of some tokens in Gnosis chain, so we fetch those prices from Mainnet. For these tokens backend sends `mainnetAddress` for Gnosis tokens (I'm talking about `getProjectAcceptTokens`).
This should happen for Polygon tokens, too.

**Comment by RamRamez** [comment]
> @aminlatifi Coingecko doesn't have prices of some tokens in Gnosis chain, so we fetch those prices from Mainnet. For these tokens backend sends `mainnetAddress` for Gnosis tokens (I'm talking about `getProjectAcceptTokens`). This should happen for Polygon tokens, too.

Other solution is to fetch token prices of all chains from backend.
You know better which solution is better.

**Comment by aminlatifi** [comment]
@RamRamez The former solution would be better in my view. Querying backend for rates may cause vulnerabilities

**Comment by RamRamez** [comment]
@aminlatifi I need Polygon network to be allowed in `updateProjectVerificationForm` mutation for managing funds section in verification steps.

![image](https://user-images.githubusercontent.com/73441857/222965130-777c1cff-3ece-4142-9b81-6c1dc910b062.png)

**Comment by aminlatifi** [comment]
> @aminlatifi I need Polygon network to be allowed in `updateProjectVerificationForm` mutation for managing funds section in verification steps.
> 
> ![image](https://user-images.githubusercontent.com/73441857/222965130-777c1cff-3ece-4142-9b81-6c1dc910b062.png)

@mohammadranjbarz please be sure it will be addressed in #894

**Comment by mohammadranjbarz** [comment]
> @aminlatifi I need Polygon network to be allowed in `updateProjectVerificationForm` mutation for managing funds section in verification steps.
> 
> ![image](https://user-images.githubusercontent.com/73441857/222965130-777c1cff-3ece-4142-9b81-6c1dc910b062.png)

@RamRamez  Please use `development` environment as backend

https://dev.serve.giveth.io

**Comment by RamRamez** [comment]
@mohammadranjbarz In create project page I can't add more than two wallet addresses

![image](https://user-images.githubusercontent.com/73441857/223145066-d8e3f72a-3053-4cfe-9f2e-ee0824a9916a.png)


this is the request payload
![image](https://user-images.githubusercontent.com/73441857/223145504-e9716a23-a9ca-400a-a146-423b6a998707.png)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz In create project page I can't add more than two wallet addresses
> 
> ![image](https://user-images.githubusercontent.com/73441857/223145066-d8e3f72a-3053-4cfe-9f2e-ee0824a9916a.png)
> 
> this is the request payload ![image](https://user-images.githubusercontent.com/73441857/223145504-e9716a23-a9ca-400a-a146-423b6a998707.png)

@RamRamez  It's fixed and deployed on `develop` server

**Comment by RamRamez** [comment]
> @aminlatifi Coingecko doesn't have prices of some tokens in Gnosis chain, so we fetch those prices from Mainnet. For these tokens backend sends `mainnetAddress` for Gnosis tokens (I'm talking about `getProjectAcceptTokens`). This should happen for Polygon tokens, too.

@aminlatifi @mohammadranjbarz 
Coingecko doesn't have MATIC price in Polygon network. Please add MATIC ethereum mainnet contract address in `getProjectAcceptTokens` endpoint for this token.

For this token, the token.mainnetAddress should be `0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0`

**Comment by mohammadranjbarz** [comment]
> > @aminlatifi Coingecko doesn't have prices of some tokens in Gnosis chain, so we fetch those prices from Mainnet. For these tokens backend sends `mainnetAddress` for Gnosis tokens (I'm talking about `getProjectAcceptTokens`). This should happen for Polygon tokens, too.
> 
> @aminlatifi @mohammadranjbarz Coingecko doesn't have MATIC price in Polygon network. Please add MATIC ethereum mainnet contract address in `getProjectAcceptTokens` endpoint for this token.
> 
> For this token, the token.mainnetAddress should be `0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0`

Thanks @RamRamez  I added `0x7d1afa7b718fb893db30a3abc0cfc608aacfebb0` as `mainnetAddress` of **MACIT** token
