### ISSUE TITLE
Queries and Mutations Optimization

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#89]
Optimize database queries and possibly add indexes 

This would improve response time and general UX on the frontend as these are the most frequently used queries

**Comment by cquinterom096** [comment]
Currently the project seems to be setup to sync with the entities completely. This leads to migrations not being run and some being redundant. I am somewhat unsure how to proceed here.

Would like to ask for some insight on how the project is managing database changes.

**Comment by mateodaza** [comment]
I discussed with @cquinterom096 and there are a couple of things that still need optimization

- [ ]  Validation on queries and mutations, some flows are wrong. For example you can create project with empty fields that are important.

- [ ] Optimize response time on heavy queries, consider making previous calculations when is possible.

**Comment by mateodaza** [comment]
closing this one as we have a new issue on it

**Comment by MoeNick** [comment]
@mateodaza where are the related issues ? would u pls mention them. 
I know @mohammadranjbarz creates some under technical debt epic

**Comment by mohammadranjbarz** [comment]
> @mateodaza where are the related issues ? would u pls mention them. I know @mohammadranjbarz creates some under technical debt epic

I added these two issues, but we should add more by the time
Giveth/giveth-next#279
Giveth/giveth-next#278
