### ISSUE TITLE
Define list of tokens eligible to donate on the Polygon

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#891]

**Comment by mohammadranjbarz** [comment]
@divine-comedian  And we want the givback eligible token list on Polygon as well

**Comment by divine-comedian** [comment]
Here is a comprehensive list I will review and provide a first set of tokens we can use for our polygon deployment

https://www.npmjs.com/package/quickswap-default-token-list?activeTab=explore

EDIT: Okay I went through the list and proposed a set of tokens to be approved by the community for GIVbacks eligiblity 

https://forum.giveth.io/t/givbacks-token-list/253/21?u=mitch

**Comment by aminlatifi** [comment]
> Here is a comprehensive list I will review and provide a first set of tokens we can use for our polygon deployment
> 
> https://www.npmjs.com/package/quickswap-default-token-list?activeTab=explore
> 
> EDIT: Okay I went through the list and proposed a set of tokens to be approved by the community for GIVbacks eligiblity
> 
> https://forum.giveth.io/t/givbacks-token-list/253/21?u=mitch

Adding new token support needs these two steps:
1- Adding token information to the end of this list
https://github.com/Giveth/monoswap/blob/c862f54cda296d958167db97efac553abae61570/src/token/tokenLists.ts#L1055
2- Being sure <Token>-<Dest Token probably USDT> pair exists on uniswap v3 with 0.3% fee

**Comment by divine-comedian** [comment]
> > Here is a comprehensive list I will review and provide a first set of tokens we can use for our polygon deployment
> > https://www.npmjs.com/package/quickswap-default-token-list?activeTab=explore
> > EDIT: Okay I went through the list and proposed a set of tokens to be approved by the community for GIVbacks eligiblity
> > https://forum.giveth.io/t/givbacks-token-list/253/21?u=mitch
> 
> Adding new token support needs these two steps: 1- Adding token information to the end of this list https://github.com/Giveth/monoswap/blob/c862f54cda296d958167db97efac553abae61570/src/token/tokenLists.ts#L1055 2- Being sure - pair exists on uniswap v3 with 0.3% fee

What pair exactly do you mean? The token needs a pair with what? Why only uniswap?
