### ISSUE TITLE
wallet address standardization

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#903]
Since we save all of the addresses in lowercase in the database, can we also show these addresses in all lowercase?
When I am doing tasks in the adminbro, it is really tedious to change the letters to lowercase manually.

![image](https://user-images.githubusercontent.com/74267818/224870949-7fa21b72-97d9-4d01-8602-9cb49c96d973.png)

**Comment by MoeNick** [comment]
@maryjaf

**Comment by maryjaf** [comment]
Thanks @alireza-sharifpour  It has been changed to lowercase on production
