### ISSUE TITLE
Updating Monoswap toekn list for Polygon.

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#909]
@MoeNick commented on [Wed Mar 15 2023](https://github.com/Giveth/GIVeconomy/issues/862)

Related to 
https://github.com/Giveth/impact-graph/issues/890
https://github.com/Giveth/impact-graph/issues/891

According to @aminlatifi :
Adding new token support needs these two steps:
1- Adding token information to the end of this list
https://github.com/Giveth/monoswap/blob/c862f54cda296d958167db97efac553abae61570/src/token/tokenLists.ts#L1055
2- Being sure - pair exists on uniswap v3 with 0.3% fee

**Comment by mateodaza** [comment]
Working on [this PR](https://github.com/Giveth/monoswap/pull/3) to add the suggested tokens

**Comment by MoeNick** [comment]
@maryjaf it's on production but worth reviewing it to make sure about probable problems.
