### ISSUE TITLE
Organization not showing in admin bro (token page)

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#911]
We can't see related organiztion to tokens in admin bro , tokens page and it makes it vulnerable when updating tokens

<img width="1897" alt="Screen Shot 1401-12-25 at 14 23 51" src="https://user-images.githubusercontent.com/9850545/225629444-543d6d5e-019a-4868-8e11-ad035ca052ad.png">

**Comment by MoeNick** [comment]
@maryjaf pls test and approve

**Comment by maryjaf** [comment]
Thanks , Now the organization is shown in token list
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/c88034ed-9c6a-4534-b1dc-4531cf2bc5e0)
