### ISSUE TITLE
Add Optimistic network

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#915]
* Block Explorer URL: https://optimistic.etherscan.io
* chainId:  `10`
* Native token symbol: **OP**
* OP transfer tx sample: https://optimistic.etherscan.io/tx/0xf11be189d967831bb8a76656882eeeac944a799bd222acbd556f2156fdc02db4

**Comment by mohammadranjbarz** [comment]
@aminlatifi  @mhmdksh @geleeroyale 
I get error for optimistic infura, but in our panel it seems we enabled that, but  here is the error I get

https://github.com/Giveth/impact-graph/actions/runs/4481197466/jobs/7877561209
```
"message\":\"project ID does not have access to optimism l2\",\"data\":{\"see\":\"[https://infura.io/dashboard\](https://infura.io/dashboard/)"
```
<img width="1077" alt="Screen Shot 1402-01-01 at 19 45 24" src="https://user-images.githubusercontent.com/9850545/226672068-6e083078-4357-43da-b706-6d8028ceef8b.png">


Can you do something about it?

**Comment by geleeroyale** [comment]
Please try again - it had not yet been activated in the billing tab.

**Comment by mohammadranjbarz** [comment]
> Please try again - it had not yet been activated in the billing tab.

Yeah thanks, it seems we not get that error anymore

@aminlatifi we just another problem I think it's because of data of my test cases, I commented those two test cases about verifying optimistic donations and pushed to staging, we can check it together later to find out the problem

**Comment by maryjaf** [comment]
when I donate to a project on optimism network and op token,  by  confirming Metamask transaction, I receive this error.
but it is ok on Eth token(pic 2)
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/111529185/232333542-b85a2500-2cfc-427a-9fa0-f9e1c9a4a196.png">

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/111529185/232334248-868be9a0-3b3a-4a6c-9b6e-d7db022db8de.png">

plz check @mohammadranjbarz @MohammadPCh

**Comment by aminlatifi** [comment]
> * Block Explorer URL: https://optimistic.etherscan.io
> * chainId:  `10`
> * Native token symbol: **OP**
> * OP transfer tx sample: https://optimistic.etherscan.io/tx/0xf11be189d967831bb8a76656882eeeac944a799bd222acbd556f2156fdc02db4

There is a mistake here, Optimism native token is ETH not OP
That would have caused issues.

**Comment by aminlatifi** [comment]
> > Please try again - it had not yet been activated in the billing tab.
> 
> Yeah thanks, it seems we not get that error anymore
> 
> @aminlatifi we just another problem I think it's because of data of my test cases, I commented those two test cases about verifying optimistic donations and pushed to staging, we can check it together later to find out the problem

I am looking in this

**Comment by aminlatifi** [comment]
Pushed this, I hope this fix the problem
f116c8e30cc4f065a4391c35ec1c0ac829e06411

**Comment by maryjaf** [comment]
> Pushed this, I hope this fix the problem [f116c8e](https://github.com/Giveth/impact-graph/commit/f116c8e30cc4f065a4391c35ec1c0ac829e06411)

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/111529185/232471663-7448cbed-2103-4045-91dd-077948c6dcff.png">

https://optimistic.etherscan.io/tx/0x452696b99f6308ee7caa83ba4e24c927ba10ea6a7b7401308d4f0039227b5791

**Comment by maryjaf** [comment]
> when I donate to a project on optimism network and op token, by confirming Metamask transaction, I receive this error. but it is ok on Eth token(pic 2) <img alt="image" width="1146" src="https://user-images.githubusercontent.com/111529185/232333542-b85a2500-2cfc-427a-9fa0-f9e1c9a4a196.png">
> 
> <img alt="image" width="1020" src="https://user-images.githubusercontent.com/111529185/232334248-868be9a0-3b3a-4a6c-9b6e-d7db022db8de.png">
> 
> plz check @mohammadranjbarz @MohammadPCh

Now the result is as below: @aminlatifi 
optimism-- OP :
Donation failed

<img width="495" alt="image" src="https://user-images.githubusercontent.com/111529185/232475018-0771dd4f-4f33-4acf-b0a2-3e5bd9a52714.png">

optimism -- Eth: 
status is pending in donation list
<img width="1394" alt="image" src="https://user-images.githubusercontent.com/111529185/232474676-3cc334e5-7b68-4190-92c3-ff08d78197c0.png">

**Comment by maryjaf** [comment]
Are  these reported bug ready for testing? @aminlatifi

**Comment by aminlatifi** [comment]
> Are these reported bug ready for testing? @aminlatifi

@maryjaf Yes, please test it

**Comment by aminlatifi** [comment]
@MoeNick @maryjaf There is only one ETH transfer to that project and it's correctly shown in the donation tab
https://optimistic.etherscan.io/address/0x3d4ed3163db57359acd1a3eca09d75ccd4d0981e

**Comment by MoeNick** [comment]
@maryjaf please test it again here:
https://giveth-dapps-v2-git-add-opt-for-test-givethio.vercel.app/

**Comment by maryjaf** [comment]
ETH and OP donations are still pending @aminlatifi 
<img width="970" alt="image" src="https://user-images.githubusercontent.com/111529185/233824164-43365bb3-b8de-40cf-a783-61df049381fc.png">

**Comment by maryjaf** [comment]
OP:
txHash
0xa6f0bd3f8c63cadecabb0ac53ae080283310ea2776bc8fc18bdcb8cd9440b8f3
https://serve.giveth.io/admin/resources/Donation/records/16411/show
https://giveth-dapps-v2-git-add-opt-for-test-givethio.vercel.app/project/test-optimism10001

ETH:
txHash
0x68861df585a879dbe52d4111b82cf6fdbdf088e78d31fc2bea0bee347d61e847
https://serve.giveth.io/admin/resources/Donation/records/16409/show
https://giveth-dapps-v2-git-add-opt-for-test-givethio.vercel.app/project/test-optimism10001
@mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
This is the error we get when requesting to infura for verifying OP tokens

```
  status = 403, error= {"code": 32002,"message":"rejected due to project ID settings"}, url="https://optimism-mainnet.infura.io/v3/infuraKey
```

I searched and found this
https://docs.infura.io/infura/networks/ethereum/how-to/secure-a-project/use-an-allowlist

But I didn't  try to change anything in infura panel as I thought it's better to just one person be responsible for maintaining these kind of things to prevent further misunderstandings.


@MoeNick  @aminlatifi  @mhmdksh  @geleeroyale

**Comment by maryjaf** [comment]
> ETH and OP donations are still pending @aminlatifi <img alt="image" width="970" src="https://user-images.githubusercontent.com/111529185/233824164-43365bb3-b8de-40cf-a783-61df049381fc.png">

Thanks,
this problem has been resolved
