### ISSUE TITLE
Fix Polygon tokens

### ISSUE THREAD

**Issue by RamRamez** [Giveth/impact-graph#918]
@aminlatifi @mohammadranjbarz 

1. Cosmos (Atom) contract address for Polygon is wrong
2. Please remove mainnetAddress from Beefy.Finance (BIFI) token on Polygon chain, because coingecko doesn't have this token price on mainnet

![image](https://user-images.githubusercontent.com/73441857/226870456-2b95e5e6-9eca-4c9b-901f-67e57629c7b5.png)

**Comment by mohammadranjbarz** [comment]
> @aminlatifi @mohammadranjbarz
> 
> 1. Cosmos (Atom) contract address for Polygon is wrong
> 2. Please remove mainnetAddress from Beefy.Finance (BIFI) token on Polygon chain, because coingecko doesn't have this token price on mainnet
> 
> ![image](https://user-images.githubusercontent.com/73441857/226870456-2b95e5e6-9eca-4c9b-901f-67e57629c7b5.png)

Thanks for reporting, I did it, although you could have done it yourself by admin-bro as well
<img width="1316" alt="Screen Shot 1402-01-02 at 14 47 50" src="https://user-images.githubusercontent.com/9850545/226888705-e31072fa-57cd-4572-a5cc-cab002abaf31.png">

**Comment by maryjaf** [comment]
Does this issue  need to be tested by QA? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
I believe @RamRamez  can approve it.
but it would be good if you check this tokens in admin panel in production ENV
