### ISSUE TITLE
Ability to export csv on donation tab of Adminbro

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#919]
Can we get a button on the donation tab of the admin bro that allows us to pull a csv file of all donations made on the platform?
Thank yooou!! 💜 

![image](https://user-images.githubusercontent.com/74267818/227029770-9b872ac1-de60-4e0d-8a88-e932e81ed114.png)

**Comment by mohammadranjbarz** [comment]
@MoeNick please put this in backlog, @WhyldWanderer  needs it

**Comment by MoeNick** [comment]
@maryjaf it for you to test and approve

**Comment by maryjaf** [comment]
1-
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/447ba32e-f56e-41e5-ae8b-a820df401ffc)
 buttons are shown in donation page that are not related to this page, plz check? @CarlosQ96

**Comment by maryjaf** [comment]
2-
When I tapping on "Export Filter To Csv " nothing happens
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/111529185/233827927-1f8ebb60-5fcf-427b-9f79-161624b646e3.png">

plz when 1 &2 are fixed let me now to test again @CarlosQ96

**Comment by MoeNick** [comment]
Shal we bring it back to sprint planning @CarlosQ96 ?

**Comment by CarlosQ96** [comment]
Its a staging issue, ill update the environment vars to make it work on staging, but I had to pay for storage in google drive because nothing worked that used my acccount, like the test spreadsheets.

**Comment by MoeNick** [comment]
@maryjaf can u take a look again?

**Comment by maryjaf** [comment]
I tested It, showing of the button was fixed  
but when we set some filter, these filters are not applied in the Google Sheet file report 
I reported this to Carlos to fix it

**Comment by MoeNick** [comment]
This is an old issue in which QA did not approve the csv with the filtering 
@divine-comedian @laurenluz @WhyldWanderer 

If it's going to affect the QF operations, we should give it a priority.

**Comment by divine-comedian** [comment]
I just tested it out on prod - looks like nothing happens either - it shows a loading spinning wheel for a bit - I get a success message saying it was successfully exported but no download link appears or request from my browser to download a CSV, does it go somewhere else or is it broken?

**Comment by laurenluz** [comment]
this is such a cool issue!! I didnt even know this was a thing!!

@divine-comedian I imagine the data auto-populates a specific google sheet... this is how we do a similar thing w/ post-QF round data... but @WhyldWanderer will know better than me.

**Comment by WhyldWanderer** [comment]
> I just tested it out on prod - looks like nothing happens either - it shows a loading spinning wheel for a bit - I get a success message saying it was successfully exported but no download link appears or request from my browser to download a CSV, does it go somewhere else or is it broken?

It goes to a spreadsheet that @CarlosQ96  set up here: https://docs.google.com/spreadsheets/d/1uqw40RxtxhhsVBq5_QwnBJ1V40z6I8Pfe2q8nxdHejM/edit?usp=sharing

It adds a sheet each time you press the button... It looks like the ones you tried did go through. 
As far as I know, the issue wasn't that the csv wasnt being exported. The issue was that it was not exported according to the filter that was applied at the time of export.

**Comment by laurenluz** [comment]
just want to make sure this isn't forgotten, assigning krati & priority.

**Comment by jainkrati** [comment]
@CarlosQ96 pls take this once superfluid p0 and p1 issues are fixed

**Comment by WhyldWanderer** [comment]
Checking in on the status of this... is this still a thing? Would be really nice to have @CarlosQ96

**Comment by divine-comedian** [comment]
@RamRamez as you are the tech lead of the adminJS I am passing this one to you

**Comment by RamRamez** [comment]
> > I just tested it out on prod - looks like nothing happens either - it shows a loading spinning wheel for a bit - I get a success message saying it was successfully exported but no download link appears or request from my browser to download a CSV, does it go somewhere else or is it broken?
> 
> It goes to a spreadsheet that [@CarlosQ96](https://github.com/CarlosQ96) set up here: https://docs.google.com/spreadsheets/d/1uqw40RxtxhhsVBq5_QwnBJ1V40z6I8Pfe2q8nxdHejM/edit?usp=sharing
> 
> It adds a sheet each time you press the button... It looks like the ones you tried did go through. As far as I know, the issue wasn't that the csv wasnt being exported. The issue was that it was not exported according to the filter that was applied at the time of export.

Please give me access to this spreadsheet for testing!

**Comment by WhyldWanderer** [comment]
@RamRamez - sure! Can you DM me your email address or request acces so that I can approve it?

**Comment by RamRamez** [comment]
I filtered donations to only show the Giveth very first donation only (id = 1), 
![Image](https://github.com/user-attachments/assets/455c5230-8ee6-4401-9f2b-786cb1dc533b)

then exported the data, I see only one donation exported, seems it's ok
![Image](https://github.com/user-attachments/assets/3d87371f-9aea-4e8a-9f9f-025d35b4dc47)

@WhyldWanderer can you check please?
