### ISSUE TITLE
Adminbro update tab does not show the name of the project

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#920]
When reviewing project updates in the Adminbro, its very difficult to know what project added the update.
Sometimes we can tell from the text of the update but it isn't always clear.

![image](https://user-images.githubusercontent.com/74267818/227030605-08e91332-9eb4-4c5e-bbb4-da6b9c07335f.png)

Is it possible to add the project title or slug to this tab so that it is easy to reference which project it is making the update?

![image](https://user-images.githubusercontent.com/74267818/227030770-51f08b72-7fcd-47b6-a11c-4abb38af67ce.png)

Thank you for all that you do for us!!
Sincerely,
Adminbro team

**Comment by maryjaf** [comment]
Thanks @CarlosQ96 	Project Title has been added in project update table
