### ISSUE TITLE
Creating campaignManager role in admin-bro

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#929]
We should create another role in admin :
- [x] name of role should be `campaignManager`
- [x] campaignManager can see all the tabs , but just can create/edit  things in **Campaigns** tab

**Comment by mohammadranjbarz** [comment]
I wrote down this based on @WhyldWanderer  requirements

**Comment by mohammadranjbarz** [comment]
@CarlosQ96  please get branch from `master`, because we may need to release it as a hotfix as well

**Comment by WhyldWanderer** [comment]
Can someone ping me when this is complete?
Comms team is ready to role out! 🚀

**Comment by CarlosQ96** [comment]
@WhyldWanderer it will be finish tomorrow ill notify you when I push it.

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  @maryjaf 

@CarlosQ96  implemented it and we have it in both staging and production ENVs

<img width="1064" alt="Screen Shot 1402-01-22 at 09 51 46" src="https://user-images.githubusercontent.com/9850545/231073679-1c338ab9-93d4-4a7f-8077-6c9eb02011f1.png">
