### ISSUE TITLE
Add & automate update reminders to notification center & emails for verified project owners

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#932]
Some project owners either don't check their email accounts or have unsubscribed from Giveth emails.
The verification team thinks that it is important to remind verified project owners that they need to add an update so that they dont lose their verified status.

Two notifications to be added to the notification center - these would be sent to verified projects 

45 days without an update - friendly reminder: "Don't forget to add regular updates to your project to keep your verified status! - Learn more"

90 days without an update - "You have 14 days to add an update to avoid badge expiration - Learn more"

Something like that.

**Comment by MoeNick** [comment]
if @CarlosQ96 is busy this week you may like to take it @mohammadranjbarz , can you take a look?

**Comment by NikolaCreatrix** [comment]
Hey hi guys, I would love to check in here to see if there is any chance to estimate when this can be implemented, please. @MoeNick @CarlosQ96 or @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> Hey hi guys, I would love to check in here to see if there is any chance to estimate when this can be implemented, please. @MoeNick @CarlosQ96 or @mohammadranjbarz

Hey @NikolaCreatrix @MoeNick  I haven't looked over this issue, but as we need to modify something in notification-center and impact-graph I think it would last about 2-3 days( assuming copies are ready and there is no blocker)
@CarlosQ96  WDYT?

**Comment by MoeNick** [comment]
Let's plan for it next week.

**Comment by divine-comedian** [comment]
@MoeNick here is the template
Can you add in the link for the template for this
https://www.figma.com/file/hNqwpebu4JCy1XIed2c862/Giveth-Public?type=design&node-id=23-48916&mode=design&t=7GnTh1lZ7WYORXWj-4

**Comment by MoeNick** [comment]
I talked with @mohammadranjbarz and he will take care of web and email notification of this issue. FOR THIS WEEK

**Comment by mohammadranjbarz** [comment]
> Some project owners either don't check their email accounts or have unsubscribed from Giveth emails. The verification team thinks that it is important to remind verified project owners that they need to add an update so that they dont lose their verified status.
> 
> Two notifications to be added to the notification center - these would be sent to verified projects
> 
> 45 days without an update - friendly reminder: "Don't forget to add regular updates to your project to keep your verified status! - Learn more"
> 
> 90 days without an update - "You have 14 days to add an update to avoid badge expiration - Learn more"
> 
> Something like that.


@WhyldWanderer 
What is the link for **Learn More**, after clicking on that, we should redirect to what URL?

**Comment by mohammadranjbarz** [comment]
@MoeNick  @WhyldWanderer I guess also we need to pu project name in notification text that when use clicks on that redirect them to project's page like other notifications, so I think we should modify the notification texts

**Comment by WhyldWanderer** [comment]
> I guess also we need to pu project name in notification text that when use clicks on that redirect them to project's page like other notifications, so I think we should modify the notification texts

Maybe something like this:

- 45 days without an update - friendly reminder: "**[projectname]** has not been updated in a while. Remember to add regular updates to your project to keep your verified status!"

     In this notification, they can click the project name and it should take them to "giveth.io/project/**[projectslug]**?tab=updates" for whichever project of theirs needs the update? 

- 90 days without an update - "You have 14 days to add an update to **[projectname]** to avoid badge expiration - Learn more"

     In this notification, "Learn more" should link to "youtu.be/sRhp74CcGU8?si=UWLAMVjIAiT_rO5y"

wdyt?

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  @MoeNick 

I saw we already use notification center for sending reminder emails, if we want to exactly send notifications when we are sending email so might not be needed to change impact-graph, we just need to modify some notificationTypes with copies that you provided to make it work

https://github.com/Giveth/impact-graph/blob/staging/src/services/cronJobs/checkProjectVerificationStatus.ts#L107-L150

WDYT?

**Comment by WhyldWanderer** [comment]
Unfortunately no emails get sent due to Segment issues or something.. 
At this point we have no process for notifying the user that they need to add an update.

Does that change what you are suggesting?

**Comment by MoeNick** [comment]
> @WhyldWanderer @MoeNick
> 
> I saw we already use notification center for sending reminder emails, if we want to exactly send notifications when we are sending email so might not be needed to change impact-graph, we just need to modify some notificationTypes with copies that you provided to make it work
> 
> https://github.com/Giveth/impact-graph/blob/staging/src/services/cronJobs/checkProjectVerificationStatus.ts#L107-L150
> 
> WDYT?

Yeah I think they are the exact events, but they have email templates and we need some copies with markup, so pls don't replace them, just duplicate them.

**Comment by mohammadranjbarz** [comment]
> Unfortunately no emails get sent due to Segment issues or something.. At this point we have no process for notifying the user that they need to add an update.
> 
> Does that change what you are suggesting?

Woow I thought the email is working, let me investigate it I will keep you posted about it

**Comment by divine-comedian** [comment]
@mohammadranjbarz 

Maybe we want to try out using the autopilot API directly to trigger the journey?

https://autopilot.docs.apiary.io/#reference/api-methods/trigger-journey

**Comment by divine-comedian** [comment]
Yup I would call this passed!

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz
> 
> Maybe we want to try out using the autopilot API directly to trigger the journey?
> 
> https://autopilot.docs.apiary.io/#reference/api-methods/trigger-journey

Yeah it can be a good idea, if we was Segment makes too much trouble and email loss ( and it's not because of our code) we can try it out

**Comment by mohammadranjbarz** [comment]
@WhyldWanderer  @MoeNick  @divine-comedian 
The job that was supposed to check project updates and send emails for reminding project owners was disabled so it was the reason that we weren't send emails.

@CarlosQ96  Now I enabled that service with `PROJECT_REVOKE_SERVICE_ACTIVE=true` in `Production` ENV so we should wait to see what happens after that, I would appreciate if you can check what happens, we should create notifications and send emails ( send Segment events), if it wasn't it can be the bug in our code logic or related `notification_type` config in DB , ...

**Comment by MoeNick** [comment]
Do we have an autopilot template set for each event? @divine-comedian @WhyldWanderer

**Comment by WhyldWanderer** [comment]
yep!
![image](https://github.com/Giveth/impact-graph/assets/74267818/546dcccf-21bb-4b7e-842b-1d5c07a9e5e3)

**Comment by WhyldWanderer** [comment]
Can we make sure we arent actually revoking badges at this point though?

**Comment by mohammadranjbarz** [comment]
> Can we make sure we arent actually revoking badges at this point though?

Until now the job was deactivate, but from now on it should work

**Comment by WhyldWanderer** [comment]
> Until now the job was deactivate, but from now on it should work

But just for emails right? It wont actually change the status in the db?

Im scared to revoke too many badges right away... it would be nice for people to start receiving the emails so that they know they need to add an update..

And then activate the badge revoking later after the users have had a chance to get caught up on updates

**Comment by mohammadranjbarz** [comment]
> > Until now the job was deactivate, but from now on it should work
> 
> But just for emails right? It wont actually change the status in the db?
> 
> Im scared to revoke too many badges right away... it would be nice for people to start receiving the emails so that they know they need to add an update..
> 
> And then activate the badge revoking later after the users have had a chance to get caught up on updates

If we want not revoke badges we can change `PROJECT_UPDATES_VERIFIED_REVOKE_DAYS` to a big number for instance make it 1000 days, to make sure not revoke badges ( because whole checking are one package so we can't enable some of them)

**Comment by WhyldWanderer** [comment]
Okay.. that sounds good. Lets do that at first and then we can adjust later after people have had a chance to get reminded

Thanks Mohammad

**Comment by mohammadranjbarz** [comment]
> Okay.. that sounds good. Lets do that at first and then we can adjust later after people have had a chance to get reminded
> 
> Thanks Mohammad

Done.

**Comment by MoeNick** [comment]
what about DApp notification (web) @mohammadranjbarz did they get implemented?

**Comment by mohammadranjbarz** [comment]
@MoeNick 
The first problem is that the job doesn't work properly, so I should put more logs to can investigate now I'm kind od blid on understanding what should I do

**Comment by MoeNick** [comment]
ok keep the great job going @mohammadranjbarz

**Comment by MoeNick** [comment]
OMG look at how many sprints we planned for it and we could not make it since Aug

Can we prioritize it @divine-comedian ?

**Comment by divine-comedian** [comment]
I would love to BUT it depends on BE resources available (not looking good), maybe we add it to the email migration epic

**Comment by MoeNick** [comment]
A gentle reminder for this.

**Comment by divine-comedian** [comment]
I don't think we can prioritize it right now among the other BE projects being worked on

**Comment by divine-comedian** [comment]
@jainkrati 

Can we look at this one as part of the email service migration as well? 

The summary here is that we want to automate sending notifications/emails to projects who have not provided an update to their project in a while.. at intervals:

60 days - send them an email and notification with some reminder
90 days - send them an email and notification with some reminder 
104 - send email, notification and change the project verified status in db to `ready to revoke` 

the project review team does not want to automatically revoke verification - but know which projects are due so they can take action case by case. 

What I understood from @mohammadranjbarz is that we had difficulties working with Segment and now since we are in the process of phasing out segment it would be a good time to take this one up. 

Since this is a new feature and not an existing one that needs to be migrated I have marked it as p2.


@WhyldWanderer - does this summary seem correct?

**Comment by jainkrati** [comment]
Yes we can take it up! 

@RamRamez is all set to finish his current email migration tasks by this Friday. We can work on this monday / tuesday if all activities are created in Ortto for same. @divine-comedian would wait for you to confirm on the activity configuration for this.

**Comment by divine-comedian** [comment]
Speaking with @mohammadranjbarz about this one - looks to be a complex & deep bug in the impact-graph that prevented this from happening - it was not related to ortto or segment. 

He mentioned that himself and Carlos and probably you @jainkrati  will need to work on debugging this one since it requires deep knowledge of the impact-graph

**Comment by MoeNick** [comment]
Thanks @divine-comedian 
Shall I remove it from Ortto? 

Where else do you think it can be categorized? I mean in which feature the value is going to be delivered to the user? (Product Wise) 

Maybe we can convert it to an independent epic.

**Comment by divine-comedian** [comment]
> Thanks @divine-comedian Shall I remove it from Ortto?
> 
> Where else do you think it can be categorized? I mean in which feature the value is going to be delivered to the user? (Product Wise)
> 
> Maybe we can convert it to an independent epic.

Let's keep it in Ortto - please don't change anything on those epics. It is a p2 and we should work in it to fully complete the migration I think

**Comment by WhyldWanderer** [comment]
> @WhyldWanderer - does this summary seem correct?

Seems great to me! Thanks Mitch <3
It is exciting to see attention on this issue. Let me know if there's anything I can do to help dig up the deep bug.

**Comment by divine-comedian** [comment]
@RamRamez - I added two new activites to Ortto - **first update warning** & **second update warning**

here is the snippet of the call for your reference - these body fields should all be familiar to you 

## first update warning 

```
const https = require('https');

const data = `{
	"activities": [
		{
			"activity_id": "act:cm:first-update-warning",
			"attributes": {
				"str:cm:email": "example string value",
				"str:cm:projecttitle": "example string value",
				"str:cm:projectupdatelink": "example string value",
				"str:cm:userid": "example string value"
			},
			"fields": {
				"str::email": "contact@email.com"
			},
			"location": {
				"source_ip": "172.217.4.1",
				"custom": null,
				"address": null
			}
		}
	],
	"merge_by": [
		"str::email"
	]
}`;

const options = {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'X-Api-Key': '{{ APIKey }}',
        'Content-Length': data.length
    }
};

const req = https.request('https://api-us.ortto.app/v1/activities/create', options, res => {
    res.on('data', d => {
        process.stdout.write(d);
    });
});

req.on('error', error => {
    console.error(error);
});
req.write(data);
req.end();
```

## second update warning 

```
const https = require('https');

const data = `{
	"activities": [
		{
			"activity_id": "act:cm:second-update-warning",
			"attributes": {
				"str:cm:email": "example string value",
				"str:cm:projecttitle": "example string value",
				"str:cm:projectupdatelink": "example string value",
				"str:cm:userid": "example string value"
			},
			"fields": {
				"str::email": "contact@email.com"
			},
			"location": {
				"source_ip": "172.217.4.1",
				"custom": null,
				"address": null
			}
		}
	],
	"merge_by": [
		"str::email"
	]
}`;

const options = {
    method: 'POST',
    headers: {
        'Content-Type': 'application/json',
        'X-Api-Key': '{{ APIKey }}',
        'Content-Length': data.length
    }
};

const req = https.request('https://api-us.ortto.app/v1/activities/create', options, res => {
    res.on('data', d => {
        process.stdout.write(d);
    });
});

req.on('error', error => {
    console.error(error);
});
req.write(data);
req.end();
```

**Comment by MoeNick** [comment]
@maryjaf to test.

**Comment by RamRamez** [comment]
@maryjaf to test and verify

**Comment by maryjaf** [comment]
Thanks @RamRamez I've tested and everything is ok 

Warning email:
<img width="1099" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/9521963b-e332-4288-85a9-952a697fd1bd">

last chance:
<img width="1274" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/80f2c610-3e64-45f1-9f9a-bbdfe358fb92">

I need to check with @divine-comedian or @WhyldWanderer  to make sure that the current conditions are expected
-when the verification status is warning and I've received  an email for that 
-then I record an update for this project
-in this scenario I won't receive email second email  correctly but my verification status remains "Warning"
Is this expected  that the status won't be changed after adding update ?

**Comment by divine-comedian** [comment]
@maryjaf nice catch! When you provide an update to your project the status should be updated to the original state which is `null`

**Comment by maryjaf** [comment]
Thanks @RamRamez all of open problems have been resolved
