### ISSUE TITLE
Add giveth tag to subgraph queries

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#934]
In order to get a higher rate limit from subgraph, we can set giveth as source value in our requests

<img width="549" alt="image" src="https://user-images.githubusercontent.com/5684607/228548408-9d92f533-c70e-42f3-8a35-d19453c3ce2c.png">

**Comment by MoeNick** [comment]
I added this issue to performance epic, is it still valid?

**Comment by aminlatifi** [comment]
A FE stuff. Not applied yet, am I right @MohammadPCh ?

**Comment by jainkrati** [comment]
Is this still needed @MoeNick @MohammadPCh @aminlatifi

**Comment by aminlatifi** [comment]
The issue has not appeared for a while, but it's better to implement this feature for future proof.

**Comment by RamRamez** [comment]
@maryjaf to test and verify
The Subgraph endpoint has changed so please test related features (like GIV balance, staked balance, locked token balance, APR, and GIVpower balance)

**Comment by RamRamez** [comment]
@aminlatifi should I add this tag to MPETH_GRAPHQL_PRICES_URL and POIGN_ART_SUBGRAPH_URL as well? (in impact-graph env vars)

**Comment by aminlatifi** [comment]
> @aminlatifi should I add this tag to MPETH_GRAPHQL_PRICES_URL and POIGN_ART_SUBGRAPH_URL as well? (in impact-graph env vars)

I don't know how often they are called and whether we suffer from rate limiting there.

**Comment by maryjaf** [comment]
> @maryjaf to test and verify
> The Subgraph endpoint has changed so please test related features (like GIV balance, staked balance, locked token balance, APR, and GIVpower balance

I've tested stake,unstake,lock,harvest flows and there is no problem 
but the APR is shown 0, I haven't more data about calculating APR it seems there is a problem relate to this @RamRamez 
![image](https://github.com/Giveth/impact-graph/assets/111529185/44c5b70a-4398-4d23-8ae5-9197f8da0e4a)

**Comment by RamRamez** [comment]
> > @maryjaf to test and verify
> > The Subgraph endpoint has changed so please test related features (like GIV balance, staked balance, locked token balance, APR, and GIVpower balance
> 
> I've tested stake,unstake,lock,harvest flows and there is no problem but the APR is shown 0, I haven't more data about calculating APR it seems there is a problem relate to this @RamRamez ![image](https://private-user-images.githubusercontent.com/111529185/332021345-44c5b70a-4398-4d23-8ae5-9197f8da0e4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYyMDAwMzEsIm5iZiI6MTcxNjE5OTczMSwicGF0aCI6Ii8xMTE1MjkxODUvMzMyMDIxMzQ1LTQ0YzViNzBhLTQzOTgtNGQyMy04YWU1LTkxOTdmOGRhMGU0YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMFQxMDA4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MTQyMWEzN2E5ZjY4YmZmY2ExZjBhODZmOGJlZTVjZGRlMjA4YzNhYTRkNWNlM2ExMjQ0NDBjOGJhN2YyOTE4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ilLBFCud3afEKba7tKtwTb4fXvwQxJKQ1iwHXT0o6O0)

I think the APR problem is related to Subgraph on staging, because I used staging branch locally with production Subgraph endpoints and it was working fine.
