### ISSUE TITLE
fix track calls for project update - donor

### ISSUE THREAD

**Issue by divine-comedian** [Giveth/impact-graph#94]
currently there are two analytic.track calls being sent to segment for when a project makes an update on giveth.io  from the giveth impact-graph. The intention is to eventually send emails to donors letting them know a project they donated to has an update. 

one is for the project owner
and another for donors to the project. the problem is that a track call is being sent for every instance of donation made not for every unique address that made a donation. 

this is problematic in that if a user has made several donations to a single project and the project has an update they would receive one email for each donation they had made to the project. meaning for one project update a user could receive several redundant emails

from projectresolver.ts 

```
  const donations = await this.donationRepository.find({
      where: { project: { id: project.id } },
      relations: ['user']
    })

    donations.forEach(donation => {
      analytics.track(
        'Project updated - donor',
        `givethId-${donation.user.id}`,
        {
          project,
          update: title,
          donation
        },
        null
      )
```

**Comment by divine-comedian** [comment]
another loose end I'm hoping to tie up with assistance from @cquinterom096 in the future.

**Comment by cquinterom096** [comment]
Let me know if you need anything else. I think it can be tested now.

**Comment by divine-comedian** [comment]
testing this out on `next.giveth.io` 

I tried to make a bunch of updates to my projects and I get a very frequent error of 'cannot read property 'id' of null. 

However,  my  project updates goes through and it sends the info to segment. The problem is however that only the project owner track call is made and nothing is sent for the donors to segment. I think this is an edge case related to the property 'id' error since it only throws this error for certain projects..

here's an example you can check out:
https://next.giveth.io/project/THIS-IS-THE-FINAL-PROJECT-ABOUT-CRABS-JUST-KIDDING
![image](https://user-images.githubusercontent.com/67759413/131554368-d77ac493-f745-48ed-9fb3-1d156f33c3e2.png)


any insight @cquinterom096 ?

**Comment by divine-comedian** [comment]
I did however test this out on a project which did not throw me the 'id' property error and I simulated multiple donations - It did seem to show up okay on the impact-graph which have one unique donor call for each donor, not for every donation. 

https://next.giveth.io/project/change-my-project's-name

**Comment by MoeNick** [comment]
@divine-comedian so do you think we can approve it as done?

**Comment by mateodaza** [comment]
@divine-comedian confirm to close this please

**Comment by divine-comedian** [comment]
yes this is done
 
 I just retested it quickly
