### ISSUE TITLE
Notifications about cancelling projects shouldnt be public

### ISSUE THREAD

**Issue by WhyldWanderer** [Giveth/impact-graph#943]
This notification looks really bad. This is a project that was cancelled because it was fraudulent.
This notification makes it seem like peopledao violated t&c when it was someone who was impersonating them.

![image](https://user-images.githubusercontent.com/74267818/229980722-e21ea315-c195-48d6-bb9c-11777c51611a.png)

Maybe these notifications should not be public knowledge?

**Comment by WhyldWanderer** [comment]
@mohammadranjbarz 
Maybe we can delete this notification for now until we can remove this type of notification in the future?

**Comment by MoeNick** [comment]
@laurenluz can you suggest a new copy or we stop sending them? 
As an owner, I want to know my project is cancelled and what it mean for me. If its not violating, we can simply say cancelled by admin and you cant see it or manage it.

**Comment by WhyldWanderer** [comment]
I think I agree with you MoeNick... as a project owner, I would also want to know. 
I personally emailed this project owner letting them know that their project was flagged for fraud and that they had a week to submit evidence that proved otherwise. There were mutliple members of PeopleDAO who said they knew nothing of this project or the wallet address attached to the project.

They never responded to the email so it was cancelled.

After it was cancelled, the project owner also received this email in autopilot informing them that their projects was cancelled.
![image](https://user-images.githubusercontent.com/74267818/229996144-7a43e458-8e05-4394-87e0-49a6fd1cef16.png)


It just really looks bad on the actual PeopleDAO project when they had nothing to do with the fraudulent project.

**Comment by laurenluz** [comment]
- [ ] For starters, we should remove the notifications being sent to project *supporters* if a projec they supported was cancelled.

- [ ] I think we still should show a notification to the project owner, because this would only be seen by the owner of the wallet address. I'm not sure of the current copy on it, but it could be simplified to something like:
"Your project [project name] has been cancelled by an admin. More information can be found in our [terms of service]."

- [ ] We should change the copy in the email to include a case like when someone impersonates a real project, adds their email but uses a personal wallet address (which is what seems like happened here...). @WhyldWanderer - can you make an issue in comms there? I can suggest a rewrite if you tag me, and you can edit in autopilot.

**Comment by WhyldWanderer** [comment]
Here it is! https://github.com/Giveth/giveth-planning/issues/1314

**Comment by MoeNick** [comment]
> * [ ]  For starters, we should remove the notifications being sent to project _supporters_ if a projec they supported was cancelled.
> * [ ]  I think we still should show a notification to the project owner, because this would only be seen by the owner of the wallet address. I'm not sure of the current copy on it, but it could be simplified to something like:
>   "Your project [project name] has been cancelled by an admin. More information can be found in our [terms of service]."
> * [ ]  We should change the copy in the email to include a case like when someone impersonates a real project, adds their email but uses a personal wallet address (which is what seems like happened here...). @WhyldWanderer - can you make an issue in comms there? I can suggest a rewrite if you tag me, and you can edit in autopilot.

@mohammadranjbarz can you take this one?

1) Cancelled for supporters: make it false and un-editable
2) Cancelled for project owners: 
"Your project [project name] has been cancelled by an admin. More information can be found in our [terms of service]."
@WhyldWanderer are you happy with the copy here?

**Comment by mohammadranjbarz** [comment]
> > * [ ]   For starters, we should remove the notifications being sent to project _supporters_ if a projec they supported was cancelled.
> > * [ ]   I think we still should show a notification to the project owner, because this would only be seen by the owner of the wallet address. I'm not sure of the current copy on it, but it could be simplified to something like:
> >   "Your project [project name] has been cancelled by an admin. More information can be found in our [terms of service]."
> > * [ ]   We should change the copy in the email to include a case like when someone impersonates a real project, adds their email but uses a personal wallet address (which is what seems like happened here...). @WhyldWanderer - can you make an issue in comms there? I can suggest a rewrite if you tag me, and you can edit in autopilot.
> 
> @mohammadranjbarz can you take this one?
> 
> 1. Cancelled for supporters: make it false and un-editable
> 2. Cancelled for project owners:
>    "Your project [project name] has been cancelled by an admin. More information can be found in our [terms of service]."
>    @WhyldWanderer are you happy with the copy here?

Yeah I can take it, but if we want to disable it, I think we should either separate it from other status or add new item for that in notification setting, WDYT?
I'm talking about this:
<img width="1211" alt="Screen Shot 1402-01-20 at 13 49 03" src="https://user-images.githubusercontent.com/9850545/230767284-f583e97c-0343-4eae-834a-cd77722d69ac.png">

**Comment by MoeNick** [comment]
Sorry @laurenluz to avoid complexity on the dev side, let's make it simple with a copy change for web notif. In the case of canceling for **BOTH supporters and owners**:

Supporters: "[project name] which you supported, has been canceled by an admin."
Owner: "Your project [project name] has been canceled by an admin. More information can be found in our [terms of service]."

**Comment by mohammadranjbarz** [comment]
> Sorry @laurenluz to avoid complexity on the dev side, let's make it simple with a copy change for web notif. In the case of canceling for **BOTH supporters and owners**:
> 
> Supporters: "[project name] which you supported, has been canceled by an admin." Owner: "Your project [project name] has been canceled by an admin. More information can be found in our [terms of service]."

@maryjaf  It's on staging, you can test it now

**Comment by maryjaf** [comment]
Thanks @mohammadranjbarz I checked and it passed
Supporter :[testcelo0001](https://staging.giveth.io/project/testcelo0001) which you supported, has been canceled by an admin.
project owner: Your project [testcelo0001](https://staging.giveth.io/project/testcelo0001) has been canceled by an admin. More information can be found in our [terms of service](https://giveth.io/tos) .

**Comment by WhyldWanderer** [comment]
I think that is sufficient enough... thanks for making the adjustment
