### ISSUE TITLE
Define List of Tokens for Celo Network

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#955]
Here is the list:

https://forum.giveth.io/t/givbacks-token-list/253/22?u=moenick

**Comment by laurenluz** [comment]
For phase 1, we don't need the full list, we have 4 tokens already on there.

@aminlatifi to confirm that we have CELO, cUSD, cEUR, cREAL correct price

Amin says we fetched those prices from some Celo DEX contracts. (deployed by celo). Celo official wallet is using them to do the exchange.

**Comment by aminlatifi** [comment]
Those contracts are listed in CELO official doc https://docs.celo.org/contract-addresses
