### ISSUE TITLE
Define prices in Monoswap for CELO token list

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#956]
Token List:

https://forum.giveth.io/t/givbacks-token-list/253/25?u=moenick

**Comment by laurenluz** [comment]
We will also need to get accurate prices for the tokens we choose to launch with in phase 2. Not sure yet which tokens the will be so @aminlatifi stay tuned until we decide on the forum post which tokens we will include.

**Comment by MoeNick** [comment]
@aminlatifi can have a chat with @mateodaza to discuss it.

**Comment by laurenluz** [comment]
I asked @brichis to review the token list to see which ones have more that $10k + and - liquidity.

**Comment by MoeNick** [comment]
Here is the updated Token List
https://forum.giveth.io/t/givbacks-token-list/253/25?u=moenick

**Comment by mateodaza** [comment]
@laurenluz should we stop working on this ?

**Comment by laurenluz** [comment]
I think we can go forward with it... it's kind of annoying that we haven't been able to announce but I do believe they will pay us for our work... we're just waiting on a nuance in incentives for project owners to add their addresses @mateodaza

**Comment by MoeNick** [comment]
Can you retake it, please?

**Comment by MoeNick** [comment]
According to @mateodaza he's blocked and needs @aminlatifi help for complexity.

**Comment by MoeNick** [comment]
Hey @mateodaza @laurenluz @Cotabe 
I don;t know what to do with this issue, if you guys think it is not worth adding other tokens to the list lets close this. wdyt?
I was assuming it's needed for fund raise to cover more CELO users.

**Comment by mateodaza** [comment]
> Hey @mateodaza @laurenluz @Cotabe I don;t know what to do with this issue, if you guys think it is not worth adding other tokens to the list lets close this. wdyt? I was assuming it's needed for fund raise to cover more CELO users.

liquidity on other tokens is super low and the monoswap is giving wrong prices that I'm not able to solve right now, tried to add PLASTIK, ETHIX, and NCT but price is not very reliable - @laurenluz should I keep pushing or leave it as it is?

**Comment by laurenluz** [comment]
we discussed this in the strategy call, and decided that it's not worth it to keep pushing if we can't get good pricing without a lot of work. We didn't promise Celo anything about more tokens.

We can either revisit this later, or just close the issue. @MoeNick
