### ISSUE TITLE
Some donations are not being tracked because of a segmentUserId problem

### ISSUE THREAD

**Issue by mateodaza** [Giveth/impact-graph#96]
Donations are not being saved for some (mainly old) projects because of a segment problem

![image](https://user-images.githubusercontent.com/18689480/122231963-7e98a200-ce80-11eb-8e25-e7f977a3aa4c.png)
 
 @divine-comedian you have some idea?

btw this test was making a donation to Giveth's project

_Originally posted by @mateodaza in https://github.com/Giveth/giveth-next/issues/87#issuecomment-862401788_

**Comment by divine-comedian** [comment]
are there any projects in particular that we can test this issue on? @cquinterom096

**Comment by divine-comedian** [comment]
bumping comment for testing - @cquinterom096  @MoeNick

**Comment by MoeNick** [comment]
@mateodaza @cquinterom096 
are there any projects in particular that we can test this issue on?
Would u pls update mitch?

**Comment by cquinterom096** [comment]
@mateodaza has access to the projects in production and we would have to fix their slugs manually, there seem to be 1-3 approx.
However you could reproduce de issue following the other issues created. 
Create a new project -> edit the address -> try to search it by slug. (The issue shouldn't occur)
Staging has my changes, Mateo deployed them.

**Comment by MoeNick** [comment]
@divine-comedian can u pls test and approve it's done?

**Comment by divine-comedian** [comment]
Following my comment above from almost a month ago.. I still don't have any more information on how I can test this issue
