### ISSUE TITLE
cowswap fork <> Giveth

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#970]
@mateodaza Has been looking into their backend services

**Comment by MoeNick** [comment]
I put it back to spront backlog. will re-plan again.

**Comment by MoeNick** [comment]
@GriffGreen @SnakeGH 
https://giveth-cowswap.vercel.app/#/

So the next step is waiting for @markoprljic 's point of view ?

**Comment by maryjaf** [comment]
1-
When I tap on "change wallet" , it stays in connecting mode
<img width="1345" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/0de6d20c-c0c4-4599-a945-87a553eb301e">

**Comment by maryjaf** [comment]
2-
My wallet is not connected, but I see an "Insufficient liquidity for this trade.
" (cached from the previous transaction)
<img width="1435" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/53540b97-a53b-4e8f-9fc4-ef22bd5b1342">

**Comment by maryjaf** [comment]
> 2- My wallet is not connected, but I see an "Insufficient liquidity for this trade. " (cached from the previous transaction) <img alt="image" width="1435" src="https://user-images.githubusercontent.com/111529185/246034530-53540b97-a53b-4e8f-9fc4-ef22bd5b1342.png">

I checked again and this issue has been resolved. thanks @mateodaza 
but the item 1  still has a bug
<img width="583" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/e4f69f3a-2e49-43c3-ba7c-3fcf80d2b5a7">

**Comment by maryjaf** [comment]
3-
after confirming transactions on meta mask this modal is shown but  the second step is loading
![image](https://github.com/Giveth/impact-graph/assets/111529185/cbff674e-f163-412e-b7a2-f4d66c798da6)
4- New design has not been implemented

**Comment by mateodaza** [comment]
> 

These are bugs from the fork itself 😅  - I'll try to update the fork soon and maybe all those are gone

I added parts of the new design but still waiting for the icon

**Comment by maryjaf** [comment]
**5-when I check the box, the percentage should be changed to 0% in box**

![image](https://github.com/Giveth/impact-graph/assets/111529185/00754557-0764-48d0-a3d4-16e1600e69c1)

**6-My last transaction(2 Jul) has been pending yet** 

![image](https://github.com/Giveth/impact-graph/assets/111529185/44da860a-0137-47fb-a31c-c657ff94793c)


**7-Mobile view, chrome on Android, needs some minor fixing**

![image](https://github.com/Giveth/impact-graph/assets/111529185/c5450136-4728-4b18-b3e8-2ea7e8f75e17)


**8- when I manually input a percentage it always adds a 0 in front of it, see photo**

![image](https://github.com/Giveth/impact-graph/assets/111529185/ac4d1c6b-e275-441d-b646-8bc6330c5e4f)

**Comment by maryjaf** [comment]
> 3- after confirming transactions on meta mask this modal is shown but the second step is loading ![image](https://user-images.githubusercontent.com/111529185/250365694-cbff674e-f163-412e-b7a2-f4d66c798da6.png) 4- New design has not been implemented

The item 3 is still exists and I can't complete a transaction
<img width="982" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/98fac60c-8fe3-465c-a5e2-75ad8a085843">

**Comment by maryjaf** [comment]
> **8- when I manually input a percentage it always adds a 0 in front of it, see photo**

this item has not been resolved , plz check @mateodaza

**Comment by maryjaf** [comment]
9-
always 1% is shown even if I set another for example 0.001%
<img width="625" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/597044d0-de7c-4c61-af78-9ce56da8c51f">
<img width="688" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/e2a4a268-c67f-4a69-ac73-1f376623676a">

@mateodaza

**Comment by mateodaza** [comment]
Thanks @maryjaf will fix!

**Comment by maryjaf** [comment]
Thanks @mateodaza 
8 & 9 have been resolved.

**Comment by maryjaf** [comment]
> 1- When I tap on "change wallet" , it stays in connecting mode <img alt="image" width="1345" src="https://user-images.githubusercontent.com/111529185/246032543-0de6d20c-c0c4-4599-a945-87a553eb301e.png">

This problem still exists, is that ok and accepted? @mateodaza

**Comment by mateodaza** [comment]
> > 1- When I tap on "change wallet" , it stays in connecting mode <img alt="image" width="1345" src="https://user-images.githubusercontent.com/111529185/246032543-0de6d20c-c0c4-4599-a945-87a553eb301e.png">
> 
> 
> 
> This problem still exists, is that ok and accepted? @mateodaza 

I can report this error and try to solve it on their repo on it's own PR outside of this. @MoeNick what do you think?

**Comment by MoeNick** [comment]
Can we move it to done and close it?

**Comment by maryjaf** [comment]
> Can we move it to done and close it?

Yeah, just the last comment should be considered in the next phase
