### ISSUE TITLE
Return givbackFactor in projectInfo

### ISSUE THREAD

**Issue by mohammadranjbarz** [Giveth/impact-graph#978]
@alireza-sharifpour  needs to have `givbackFactor` for projects in `projectBySlug` response

**Comment by alireza-sharifpour** [comment]
> @alireza-sharifpour needs to have `givbackFactor` for projects in `projectBySlug` response

Thanks @mohammadranjbarz for implementing this, please let me know when it's ready 🙏.

**Comment by mohammadranjbarz** [comment]
@alireza-sharifpour 
I added `givbackFactor` to response, you can use it now
example: https://github.com/Giveth/impact-graph/blob/staging/test/graphqlQueries.ts#L718
