### ISSUE TITLE
Use a library to create multiple resolution versions of images on upload

### ISSUE THREAD

**Issue by geleeroyale** [Giveth/impact-graph#981]
Amin mentioned we are saving full image sizes and are retrieving those which poses a huge performance problem.

Research possible ways to go about this @Giveth/devops

**Comment by geleeroyale** [comment]
For the easiest implementation we could use a feature from Pinata API that is currently unused but part of our plan - we have 50.000 image resize requests per month available - see https://docs.pinata.cloud/gateways/image-optimization

**Comment by aminlatifi** [comment]
> For the easiest implementation we could use a feature from Pinata API that is currently unused but part of our plan - we have 50.000 image resize requests per month available - see https://docs.pinata.cloud/gateways/image-optimization

@MohammadPCh
