### ISSUE TITLE
Get list of projects by chain. 

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#982]
We need filtering projects by accepting funds on 

- Polygon
- Celo
- Optimism

It's good we can revise the Accepting funds on the Gnosis structure query.

**Comment by CarlosQ96** [comment]
Related Pr: https://github.com/Giveth/impact-graph/pull/983/files
Updated the query and added new filters

**Comment by MoeNick** [comment]
Thanks man! 🙏

**Comment by MoeNick** [comment]
@MohammadPCh 
@mohammadranjbarz  will provide the link of the service here.

**Comment by mohammadranjbarz** [comment]
> @MohammadPCh @mohammadranjbarz will provide the link of the service here.

@MohammadPCh  @MoeNick 

now we have these filters as well
```
  AcceptFundOnPolygon = 'acceptFundOnPolygon',
  AcceptFundOnCelo = 'acceptFundOnCelo',
  AcceptFundOnOptimism = 'acceptFundOnOptimism'
```

You can see 
https://github.com/Giveth/impact-graph/blob/staging/src/entities/project.ts#L69-L78

**Comment by MohammadPCh** [comment]
Thanks @mohammadranjbarz

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Please take a look at this comment: https://github.com/Giveth/giveth-dapps-v2/issues/2677#issuecomment-1556222978
We need to add a new filter for the mainnet.

**Comment by mohammadranjbarz** [comment]
> Member

Done bro
