### ISSUE TITLE
Wrap GitCoin scorer backend

### ISSUE THREAD

**Issue by aminlatifi** [Giveth/impact-graph#987]
GitCoin has an API to work with GitCoin scorer, like
- Submit passport profile against a Scorer (Giveth)
- Get a nonce to sign by the user and submit the profile
- Get the score of a single user
- Get the list of all users who submitted their Passport Profile
- Get a user passport stamps

https://api.scorer.gitcoin.co/docs#/

All above calls need an API-key which rationally we must protect (I am not sure, I asked Zakk on TG)
From above, two services of getting nonce and submitting passport profile are implemented on the SIWE micro service.
On impact-graph side, we must be able to
1. Return the score of any user
2. Returns a default cut-off value for score eligibility
4. Query all donors' scores at the end of the round.

**Comment by aminlatifi** [comment]
https://docs.passport.gitcoin.co/building-with-passport/scorer-api

**Comment by MoeNick** [comment]
Hey @CarlosQ96 can you take it please?

**Comment by mohammadranjbarz** [comment]
@CarlosQ96   please use adapter for passport APIs, because we need to use them in other part of codes

**Comment by CarlosQ96** [comment]
@mohammadranjbarz thanks man, I am following the adapter pattern we use for other integrations and for the mocks too

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz thanks man, I am following the adapter pattern we use for other integrations and for the mocks too

Thanks bro

**Comment by MoeNick** [comment]
Can you connect the pR?

**Comment by CarlosQ96** [comment]
Ill merge this PR to Mohammad's branch so we can have the gitcoin adapter available. So refer to the main branch https://github.com/Giveth/impact-graph/pull/986

**Comment by MoeNick** [comment]
@CarlosQ96 fyin
https://github.com/Giveth/giveth-dapps-v2/issues/2654#issuecomment-1567896359

**Comment by maryjaf** [comment]
Where do we set the minimum score for eligibility?  @aminlatifi @CarlosQ96
