### ISSUE TITLE
QF - filter Projects list by QF round

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#994]

**Comment by maryjaf** [comment]
this project is unverified but it is shown in list of project in QF round , plz check @mohammadranjbarz 
https://givqf.vercel.app/project/maryam-jafarymehr

**Comment by mohammadranjbarz** [comment]
> this project is unverified but it is shown in list of project in QF round , plz check @mohammadranjbarz https://givqf.vercel.app/project/maryam-jafarymehr

@MohammadPCh  @alireza-sharifpour 
Can you put a checking in single page to check `verified` and `listed` status before assuming it's part of qfRound?

**Comment by MohammadPCh** [comment]
@mohammadranjbarz Yes sir :)

**Comment by mohammadranjbarz** [comment]
@MohammadPCh 
When calling `allProjects` query for getting projects related to active qf round please add `Verfied` filter as well, it would resolve this issue, filters should be like:
**filters: ['ActiveQfRound', 'Verified']**

**Comment by laurenluz** [comment]
hey guys!! actually, for our MVP round, all projects will need to be verified... but we shouldn't make this mandatory in the filtering... we should just filter for projects that are part of "QF Round 1" for example... nonverified OR verified.

We should only show them if they are listed, it's true... but verification shouldn't be a requirement. In admin bro, I want to be able to manually curate which projects we want in the round and not in the round. @MohammadPCh @mohammadranjbarz @maryjaf - is that clear?

**Comment by mohammadranjbarz** [comment]
> hey guys!! actually, for our MVP round, all projects will need to be verified... but we shouldn't make this mandatory in the filtering... we should just filter for projects that are part of "QF Round 1" for example... nonverified OR verified.
> 
> We should only show them if they are listed, it's true... but verification shouldn't be a requirement. In admin bro, I want to be able to manually curate which projects we want in the round and not in the round. @MohammadPCh @mohammadranjbarz @maryjaf - is that clear?
@laurenluz  Got it.
@MohammadPCh  Sorry man, I think you should revert the change and not send **Verified** filter got get projects of a qfRound

**Comment by MohammadPCh** [comment]
OK ;)
