### ISSUE TITLE
QF - AdminJs: Adding / Removing a project from a QF round

### ISSUE THREAD

**Issue by MoeNick** [Giveth/impact-graph#998]

**Comment by mohammadranjbarz** [comment]
I take it, I might need help of @MohammadPCh for this

**Comment by MohammadPCh** [comment]
@mohammadranjbarz  I am happy to be at your service if you need any help.

**Comment by maryjaf** [comment]
If a project doesn't have one of the criteria for adding to QF such as verified status
when a admin user try to add this project to QF, he should got an error ?

Can the admin user remove some project from QF in middle of round ?
 @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> If a project doesn't have one of the criteria for adding to QF such as verified status when a admin user try to add this project to QF, he should got an error ?
> 
> Can the admin user remove some project from QF in middle of round ? @mohammadranjbarz

1. Now they can add afRound to unlisted or unverified projects, but we don't return them in list of qfRound's projects for frontend, but you can add it to qfRound and once they got verified/listed they would appear in qfround's projects
2. Yeah they can remove/add project from/to qfRound during the round

**Comment by maryjaf** [comment]
I know that this task is n't ready to test, I check with you to be sure @mohammadranjbarz 
Now on edit page we can't add the project to a QF round and this is possible only throw list of project, is this expected? @mohammadranjbarz

**Comment by mohammadranjbarz** [comment]
> I know that this task is n't ready to test, I check with you to be sure @mohammadranjbarz Now on edit page we can't add the project to a QF round and this is possible only throw list of project, is this expected? @mohammadranjbarz

I  couldn't get your point, can you attach some screenshot?

**Comment by maryjaf** [comment]
I couldn't login to admin bro to take a screen shot, I got 504 Gateway Time-out error
but in edit page like this address the QF round Is not shown 
https://dev.serve.giveth.io/admin/resources/Project/records/{{id}}/edit
<img width="1290" alt="image" src="https://github.com/Giveth/impact-graph/assets/111529185/47426628-0401-4605-9b23-e8aa3490aeed">

**Comment by maryjaf** [comment]
When I create a new QF round and the "is active" not checked , after taping on save in the list this round is shown activated @mohammadranjbarz 
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/e52c6946-64ad-404a-ab00-ffcc40cfcc60)
![image.png](https://images.zenhubusercontent.com/62fe7a8b57c1a1770575ea40/6cc7329b-cf35-4d33-82c4-ceeb2914980b)

**Comment by maryjaf** [comment]
me & @mohammadranjbarz  checked this scenario and we need to your opinion about implementing this logic @laurenluz @MoeNick 
Now after that  a round was ended and it's status was changed to deactivated  by job and and projects related to this round are shown in QF round history, the user of admin bro can edit the round and change the "end date" and "is active" in this scenario we have one round in QF round as a active round and in round history as a deactivated round 
I'm not sure if this scenario would be  happened in real or not ?

**Comment by maryjaf** [comment]
> When I create a new QF round and the "is active" not checked , after taping on save in the list this round is shown activated @mohammadranjbarz ![image.png](https://camo.githubusercontent.com/529dac5151271cbc9e98987472988ca181bd3f69b7dd70d0d6d10c7bb23b5d5f/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f65353263363934362d363461642d343034612d616230302d666663633430636663633630) ![image.png](https://camo.githubusercontent.com/020cefe2de45f7f144447697ff56ed1925827a06e54040f873b31734aafc0bed/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3632666537613862353763316131373730353735656134302f36636337333239622d636633352d346433332d383263342d636565623239313439383062)

Can you take a look? @CarlosQ96

**Comment by laurenluz** [comment]
> me & @mohammadranjbarz checked this scenario and we need to your opinion about implementing this logic @laurenluz @MoeNick Now after that a round was ended and it's status was changed to deactivated by job and and projects related to this round are shown in QF round history, the user of admin bro can edit the round and change the "end date" and "is active" in this scenario we have one round in QF round as a active round and in round history as a deactivated round I'm not sure if this scenario would be happened in real or not ?

I'm not sure I understand @maryjaf. What does "QF Round History" show?

I don't think it's too much of an issue to have a round be active, then not active, then set to active again... and have its information show up in both "QF Round" and "QF Round History". I think on our frontend, everything will be fine. Also it seems like an unlikely scenario that a round would pass its end date and become deactivated... and then admin bro user would have to manually reactivate.

Our QF rounds dates will be determined before we start, and it seems really unlikely that we would even change the dates after the round begins.

**Comment by mohammadranjbarz** [comment]
> > me & @mohammadranjbarz checked this scenario and we need to your opinion about implementing this logic @laurenluz @MoeNick Now after that a round was ended and it's status was changed to deactivated by job and and projects related to this round are shown in QF round history, the user of admin bro can edit the round and change the "end date" and "is active" in this scenario we have one round in QF round as a active round and in round history as a deactivated round I'm not sure if this scenario would be happened in real or not ?
> 
> I'm not sure I understand @maryjaf. What does "QF Round History" show?
> 
> I don't think it's too much of an issue to have a round be active, then not active, then set to active again... and have its information show up in both "QF Round" and "QF Round History". I think on our frontend, everything will be fine. Also it seems like an unlikely scenario that a round would pass its end date and become deactivated... and then admin bro user would have to manually reactivate.
> 
> Our QF rounds dates will be determined before we start, and it seems really unlikely that we would even change the dates after the round begins.

Ok Got it, so after qfRound ends, I dont allow admins to edit any field of `qfRound` if we needed an emergency edit, we can change it manually in DB, is it ok?

**Comment by laurenluz** [comment]
@mohammadranjbarz I think it's ok, just to check - what are the fields currently editable now in admin bro?
- Start date
- End date
- Projects in the round
- Minimum passport score
- Allocated Fund (is the amount of funds being allocated to the round? or is this something related to estiamated matching?)

**Comment by mohammadranjbarz** [comment]
> @mohammadranjbarz I think it's ok, just to check - what are the fields currently editable now in admin bro?
> 
> * Start date
> * End date
> * Projects in the round
> * Minimum passport score
> * Allocated Fund (is the amount of funds being allocated to the round? or is this something related to estiamated matching?)

Yeah exactly, all fields are editable when endDate is not passed, and one other thing, for adding adding projects to qfRound we should do it from project page, and it's not possible to show qfRound's projects in qfRound tab ( I made an issue for that, will work on that)
